Repository onflow/cadence, pull requests merged in 2020-07, with the labels that each got.

#200 Fix parsing of multiple statements on same line
  runtime/parser2/expression_test.go
  runtime/parser2/statement.go
  runtime/parser2/statement_test.go
Labels: Bugfix

#213 Change [Int] to [UInt8] where byte array semantics are wanted
  runtime/crypto_test.go
  runtime/deferral_test.go
  runtime/interpreter/value.go
  runtime/runtime_test.go
  runtime/sema/type.go
  runtime/stdlib/contracts/crypto.cdc
  runtime/stdlib/internal/contracts.gen.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/utils/utils.go
Labels: Breaking Change, Improvement

#184 Make type values storable
  runtime/interpreter/decode.go
  runtime/interpreter/encode.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/sema/type.go
  runtime/type_test.go
Labels: Improvement

#227 Fix borrowing of capability without type argument
  runtime/sema/type.go
  runtime/tests/checker/genericfunction_test.go
Labels: Bugfix

#217 Remove controller from storage interface
  runtime/deferral_test.go
  runtime/interface.go
  runtime/runtime_storage.go
  runtime/runtime_test.go
Labels: Breaking Change

#233 Accept member expressions without name
  runtime/parser2/expression.go
  runtime/parser2/expression_test.go
  runtime/sema/check_member_expression.go
  runtime/sema/errors.go
  runtime/tests/fuzz/crashers_test.go
Labels: Improvement

#232 Record occurrences of types
  runtime/sema/check_assignment.go
  runtime/sema/check_expression.go
  runtime/sema/check_function.go
  runtime/sema/check_invocation_expression.go
  runtime/sema/checker.go
  runtime/sema/occurrences.go
  runtime/tests/checker/composite_test.go
  runtime/tests/checker/occurrences_test.go
Labels: Improvement

#214 Don't report an error for a restriction with an invalid type
  runtime/sema/checker.go
Labels: Improvement

#231 Prevent a potential stack overflow when checking member storability
  runtime/sema/check_composite_declaration.go
  runtime/sema/type.go
  runtime/stdlib/flow.go
  runtime/tests/checker/storable_test.go
Labels: Bugfix

#239 Add Cadence Program Pragmas
  runtime/ast/pragma.go
  runtime/ast/program.go
  runtime/ast/visitor.go
  runtime/common/declarationkind.go
  runtime/interpreter/interpreter.go
  runtime/parser2/declaration.go
  runtime/parser2/lexer/state.go
  runtime/parser2/lexer/tokentype.go
  runtime/parser2/parser.go
  runtime/sema/check_pragma.go
  runtime/sema/errors.go
  runtime/tests/checker/access_test.go
  runtime/tests/checker/pragma_test.go
  runtime/tests/checker/transactions_test.go
  runtime/tests/checker/utils.go
  runtime/tests/parser/parser_test.go
Labels: Feature

#236 Prepend stored data with magic
  runtime/interpreter/decode.go
  runtime/interpreter/magic.go
  runtime/interpreter/magic_test.go
  runtime/runtime_storage.go
  runtime/storage_test.go
Labels: Breaking Change

#250 Improve equatability check
  runtime/sema/type.go
  runtime/stdlib/flow.go
Labels: Improvement

#252 adding a cadence minifier
  runtime/cmd/minifier/minifier.go
  runtime/cmd/minifier/minifier_test.go
Labels: Feature

#262 LSP: Initialize Flow integration with commands
  languageserver/integration/integration.go
Labels: Bugfix

#255 Parse docstrings for more declarations
  runtime/ast/composite.go
  runtime/ast/interface.go
  runtime/ast/variable_declaration.go
  runtime/parser2/declaration.go
  runtime/parser2/declaration_test.go
  runtime/parser2/statement.go
  runtime/parser2/transaction.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/type.go
Labels: Improvement

#271 Export more types
  runtime/convertTypes.go
  types.go
Labels: Improvement

#270 Document setup for compatiblity suite
  compat/setup.md
Labels: Documentation

#251 Require values passed to `load` and `store` to be storable
  runtime/sema/check_composite_declaration.go
  runtime/sema/type.go
  runtime/tests/checker/account_test.go
Labels: Breaking Change, Improvement

#276 Language Server: Include error notes as related information in diagnostic
  languageserver/server/server.go
Labels: Feature

#279 Regenerate docs
  docs/highlight-cadence.js
  docs/language.generated.md
  docs/language.html
  docs/language.md
  docs/language.pdf
Labels: Documentation
