Repository onflow/cadence, pull requests merged in 2020-08, with the labels that each got.

#280 Include available declarations in "not declared" error
  runtime/sema/check_import_declaration.go
  runtime/sema/errors.go
Labels: Improvement

#281 Fix the suggestion in the error when an interface is used as a type
  runtime/sema/checker.go
  runtime/sema/errors.go
  runtime/sema/type.go
  runtime/stdlib/flow.go
  runtime/tests/checker/interface_test.go
Labels: Bugfix

#284 Handle incomplete types in checker
  runtime/parser2/type_test.go
  runtime/sema/checker.go
  runtime/tests/checker/dictionary_test.go
  runtime/tests/checker/utils.go
Labels: Bugfix

#286 Add JSON serialization support for more AST elements
  runtime/ast/block.go
  runtime/ast/block_test.go
  runtime/ast/expression.go
  runtime/ast/expression_extractor.go
  runtime/ast/expression_test.go
  runtime/ast/import.go
  runtime/ast/statement.go
  runtime/ast/statement_test.go
  runtime/ast/transferoperation.go
  runtime/ast/transferoperation_test.go
  runtime/ast/variablekind.go
  runtime/ast/variablekind_test.go
  runtime/common/compositekind.go
  runtime/common/compositekind_test.go
  runtime/common/declarationkind.go
  runtime/common/declarationkind_test.go
  runtime/interpreter/interpreter.go
  runtime/parser2/expression.go
  runtime/parser2/expression_test.go
  runtime/sema/check_expression.go
  runtime/sema/check_interface_declaration.go
  runtime/tests/parser/parser_test.go
Labels: Improvement

#290 Don't return an error when a location type is not supported
  languageserver/server/server.go
Labels: Bugfix

#291 Ensure script return type is storable type
  runtime/errors.go
  runtime/runtime.go
  runtime/runtime_test.go
Labels: Breaking Change, Improvement

#304 Treat carriage returns as space
  runtime/parser2/lexer/lexer.go
  runtime/parser2/lexer/state.go
Labels: Improvement

#305 Reject non-storable transaction/script arguments
  runtime/errors.go
  runtime/runtime.go
  runtime/runtime_test.go
Labels: Breaking Change, Improvement

#306 Improve JSON marshalling for more AST elements
  runtime/ast/access_test.go
  runtime/ast/argument_test.go
  runtime/ast/block_test.go
  runtime/ast/composite.go
  runtime/ast/conditionkind_test.go
  runtime/ast/expression.go
  runtime/ast/expression_test.go
  runtime/ast/function_declaration.go
  runtime/ast/import.go
  runtime/ast/import_test.go
  runtime/ast/interface.go
  runtime/ast/members.go
  runtime/ast/operation_test.go
  runtime/ast/statement.go
  runtime/ast/statement_test.go
  runtime/ast/transfer_test.go
  runtime/ast/transferoperation_test.go
  runtime/ast/type.go
  runtime/ast/type_test.go
  runtime/ast/variable_declaration.go
  runtime/ast/variable_declaration_test.go
  runtime/ast/variablekind_test.go
  runtime/interpreter/interpreter.go
  runtime/parser2/declaration.go
  runtime/parser2/declaration_test.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_interface_declaration.go
  runtime/sema/check_transaction_declaration.go
  runtime/tests/parser/parser_test.go
Labels: Improvement

#310 Add view field to block type
  docs/language.md
  runtime/interface.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/stdlib/flow.go
Labels: Breaking Change, Feature

#309 Make reference types non-storable
  runtime/sema/type.go
  runtime/tests/checker/storable_test.go
Labels: Breaking Change

#316 Validate script argument count
  runtime/runtime.go
  runtime/runtime_test.go
Labels: Bugfix

#346 Suggest replacing number conversion function calls
  languageserver/server/server.go
  runtime/repl.go
  runtime/sema/check_invocation_expression.go
  runtime/sema/checker.go
  runtime/sema/hints.go
  runtime/sema/type.go
  runtime/tests/checker/conversion_test.go
Labels: Feature

#355 Copy values on return
  runtime/interpreter/interpreter.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Bugfix
