Repository onflow/cadence, pull requests merged in 2020-11, with the labels that each got.

#441 Properly handle unspecified variable kind
  languageserver/server/server.go
  runtime/ast/variablekind.go
Labels: Bugfix

#444 Document the current options for syntax highlighting
  docs/syntax-highlighting.md
Labels: Documentation

#447 Don't use the cache when deploying or updating account code
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/tests/utils/utils.go
Labels: Bugfix

#446 Don't use the cache when deploying or updating account code
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/tests/utils/utils.go
Labels: Bugfix

#455 Improving the error message when there is constructor arguments.
  runtime/runtime.go
Labels: Improvement

#457 Refactor address locations, make composite decoding backwards-compatible
  runtime/ast/import.go
  runtime/ast/import_test.go
  runtime/cmd/cmd.go
  runtime/contract_test.go
  runtime/interpreter/decode.go
  runtime/interpreter/encode.go
  runtime/interpreter/encoding_test.go
  runtime/locations.go
  runtime/parser2/declaration.go
  runtime/parser2/declaration_test.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/sema/check_import_declaration.go
  runtime/sema/type.go
  runtime/stdlib/flow.go
  runtime/storage_test.go
  runtime/tests/checker/import_test.go
  runtime/tests/interpreter/import_test.go
Labels: Improvement

#458 Fix optional value's type function
  values.go
  values_test.go
Labels: Bugfix

#468 Infer address location name from type ID for static types
  runtime/interpreter/decode.go
  runtime/interpreter/encoding_test.go
Labels: Bugfix

#465 Add support for coverage reports
  runtime/coverage.go
  runtime/coverage_test.go
  runtime/runtime.go
Labels: Feature

#469 Add a test for decoding a struct with an address location without name
  runtime/interpreter/encoding_test.go
Labels: Improvement

#475 Improve error messages for contract deployment name argument checks
  runtime/runtime.go
Labels: Improvement

#476 Update the diagram illustrating the architcture of the runtime
  runtime/runtime.monopic
  runtime/runtime.png
  runtime/runtime.svg
Labels: Documentation
