Repository onflow/cadence, pull requests merged in 2021-11, with the labels that each got.

#1206 Remove trailing comma in JSON cadence spec
  docs/json-cadence-spec.md
Labels: Documentation

#1209 Fix playground URL for this example
  docs/tutorial/08-voting.mdx
Labels: Documentation

#1210 doc(05-marketplace-setup.mdx): comment typo
  docs/tutorial/05-marketplace-setup.mdx
Labels: Documentation

#1207 Fix typo on marketplace design code sample
  docs/tutorial/06-marketplace-compose.mdx
Labels: Documentation

#1213 Temporary fix for Testnet
  runtime/sema/check_composite_declaration.go
  runtime/sema/errors.go
Labels: Bugfix

#1208 Fix integer conversion
  runtime/interpreter/value.go
  runtime/tests/interpreter/integers_test.go
Labels: Bugfix

#1186 Allow runtime types to be used as a dictionary key
  runtime/interpreter/hashablevalue.go
  runtime/interpreter/value.go
  runtime/sema/check_dictionary_expression.go
  runtime/tests/checker/dictionary_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Feature, Improvement

#1215 Add container mutation tests for inserting functions into dictionaries
  runtime/tests/interpreter/container_mutation_test.go
Labels: Testing

#1214 Zero-pad string representation of addresses
  runtime/common/address.go
  runtime/common/address_test.go
  runtime/common/addresslocation.go
  runtime/common/addresslocation_test.go
  runtime/format/address.go
  runtime/interpreter/errors_test.go
  runtime/interpreter/value_test.go
  runtime/runtime_test.go
  runtime/tests/interpreter/builtinfunctions_test.go
  values_test.go
Labels: Breaking Change, Improvement

#1185 Add smoke tests cadence values / storage operations
  runtime/tests/interpreter/values_test.go
Labels: Improvement, Testing

#1212 doc(06-marketplace-compose.mdx): update ownerVault access control keyword
  docs/tutorial/06-marketplace-compose.mdx
Labels: Documentation

#1195 Add constructor functions for run-time types
  docs/language/run-time-types.md
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/sema/checker.go
  runtime/sema/runtime_type_constructors.go
  runtime/sema/type.go
  runtime/tests/checker/runtimetype_test.go
  runtime/tests/interpreter/runtimetype_test.go
Labels: Feature

#1211 Add converter functions to produce path values from strings
  docs/language/accounts.mdx
  runtime/interpreter/interpreter.go
  runtime/interpreter/location.go
  runtime/interpreter/value.go
  runtime/literal.go
  runtime/sema/check_path_expression.go
  runtime/sema/errors.go
  runtime/sema/type.go
  runtime/tests/checker/path_test.go
  runtime/tests/interpreter/path_test.go
Labels: Feature

#1216 Add new syntax to bind for-in loop indices
  docs/language/control-flow.md
  runtime/ast/statement.go
  runtime/ast/statement_test.go
  runtime/interpreter/interpreter_statement.go
  runtime/parser2/statement.go
  runtime/parser2/statement_test.go
  runtime/sema/check_for.go
  runtime/tests/checker/for_test.go
  runtime/tests/interpreter/for_test.go
Labels: Feature, Improvement

#1202 Allow importing type and capability values
  encoding/json/decode.go
  encoding/json/encode.go
  encoding/json/encoding_test.go
  runtime/convertTypes.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/interpreter/dynamictype.go
  runtime/interpreter/function.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/statictype.go
  runtime/interpreter/value.go
  runtime/program_params_validation_test.go
  runtime/sema/type.go
  runtime/storage_test.go
  types.go
  types_test.go
  values.go
  values_test.go
Labels: Improvement

#1204 Clean up types in `cadence` package
  encoding/json/decode.go
  encoding/json/encode.go
  encoding/json/encoding_test.go
  runtime/convertTypes.go
  types.go
Labels: Improvement

#1224 add missing types and conversion functions to cadence package
  encoding/json/decode.go
  encoding/json/encode.go
  encoding/json/encoding_test.go
  runtime/convertTypes.go
  runtime/convertValues_test.go
  types.go
Labels: Improvement

#1231 Fix grammar issue in Hello World tutorial
  docs/tutorial/02-hello-world.mdx
Labels: Documentation

#1025 Find least common super-type
  runtime/sema/any_type.go
  runtime/sema/anyresource_type.go
  runtime/sema/anystruct_type.go
  runtime/sema/block.go
  runtime/sema/bool_type.go
  runtime/sema/character_type.go
  runtime/sema/deployed_contract.go
  runtime/sema/invalid_type.go
  runtime/sema/meta_type.go
  runtime/sema/never_type.go
  runtime/sema/path_type.go
  runtime/sema/simple_type.go
  runtime/sema/string_type.go
  runtime/sema/type.go
  runtime/sema/type_tags.go
  runtime/sema/type_test.go
  runtime/sema/void_type.go
Labels: Feature

#1235 Fix composite-typed argument passing
  runtime/common/location.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/statictype.go
Labels: Bugfix

#1236 Add BLS-specific crypto functions to cadence
  docs/language/crypto.mdx
  runtime/crypto_test.go
  runtime/interface.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/sema/type.go
  runtime/stdlib/builtin.go
  runtime/tests/checker/crypto_test.go
Labels: Feature

#1243 Add test for casting storage ref to an invalid type
  runtime/tests/interpreter/account_test.go
Labels: Testing

#1249 Gracefully handle invalid restrictions
  runtime/sema/checker.go
  runtime/tests/checker/restriction_test.go
Labels: Bugfix

#1073 Report an error when the parameter list is missing commas
  runtime/parser2/declaration_test.go
  runtime/parser2/function.go
Labels: Bugfix, Breaking Change

#1238 Updates Fungible Token tutorial to use a different structure and explainations
  docs/tutorial/02-hello-world.mdx
  docs/tutorial/03-fungible-tokens.mdx
  docs/tutorial/04-non-fungible-tokens.mdx
Labels: Documentation, Improvement, T-Documentation 📃

#1027 Use common super-type for expression type inferring
  runtime/sema/check_array_expression.go
  runtime/sema/check_casting_expression.go
  runtime/sema/check_conditional.go
  runtime/sema/check_dictionary_expression.go
  runtime/sema/check_for.go
  runtime/sema/check_unary_expression.go
  runtime/sema/check_variable_declaration.go
  runtime/sema/checker.go
  runtime/sema/type_tags.go
  runtime/sema/type_test.go
  runtime/tests/checker/arrays_dictionaries_test.go
  runtime/tests/checker/conditional_test.go
  runtime/tests/checker/conditions_test.go
  runtime/tests/checker/runtimetype_test.go
  runtime/tests/checker/string_test.go
  runtime/tests/checker/type_inference_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/metatype_test.go
  runtime/tests/interpreter/string_test.go
Labels: Breaking Change, Feature

#1054 Update type inference docs
  docs/language/type-inference.md
  docs/language/type-inference.mdx
Labels: Documentation

#1049 Infer static type from the value itself for imported arrays/dictionaries
  runtime/convertValues.go
  runtime/convertValues_test.go
Labels: Feature

#1229 Add a clone function to all values
  runtime/interpreter/function.go
  runtime/interpreter/simplecompositevalue.go
  runtime/interpreter/value.go
Labels: Feature

#1240 Allow scripts to access authorized accounts
  docs/language/accounts.mdx
  runtime/account_test.go
  runtime/runtime.go
Labels: Feature

#1266 Use updated APIs for atree in tests
  runtime/interpreter/deepcopyremove_test.go
  runtime/interpreter/encoding_test.go
  runtime/storage_test.go
Labels: Technical Debt

#1233 Language server: Add test for diagnostics
  languageserver/test/index.test.ts
Labels: Testing

#1271 Update and to are in 03-fungible-tokens.mdx
  docs/tutorial/03-fungible-tokens.mdx
Labels: Documentation

#1272 Re-apply "Remove receiver type from function type"
  runtime/interpreter/function.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_invocation.go
  runtime/interpreter/statictype.go
  runtime/sema/check_invocation_expression.go
  runtime/sema/check_member_expression.go
  runtime/sema/checker_test.go
  runtime/sema/elaboration.go
  runtime/sema/type.go
  runtime/tests/checker/member_test.go
  runtime/tests/interpreter/container_mutation_test.go
Labels: Improvement

#1032 Replace `IsSubType` check with `IsSameTypeKind` check where necessary
  runtime/literal.go
  runtime/sema/check_binary_expression.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_dictionary_expression.go
  runtime/sema/check_event_declaration.go
  runtime/sema/check_expression.go
  runtime/sema/check_transaction_declaration.go
  runtime/sema/check_unary_expression.go
  runtime/sema/check_while.go
  runtime/sema/checker.go
  runtime/sema/type.go
  runtime/tests/checker/never_test.go
  runtime/tests/checker/return_test.go
Labels: Bugfix

#1277 Update 06-marketplace-compose.mdx
  docs/tutorial/06-marketplace-compose.mdx
Labels: Documentation

#1254 add `typeAt` function for inspecting the type of objects in storage
  docs/language/accounts.mdx
  runtime/interpreter/account.go
  runtime/interpreter/interpreter.go
  runtime/sema/authaccount_type.go
  runtime/tests/checker/account_test.go
  runtime/tests/interpreter/account_test.go
Labels: Feature

#1072 Report a hint for casting an expression of type `T` to same type `T`
  runtime/sema/check_cast_visitor.go
  runtime/sema/check_casting_expression.go
  runtime/sema/check_expression.go
  runtime/sema/checker.go
  runtime/tests/checker/casting_test.go
  runtime/tests/checker/utils_test.go
Labels: Feature

#1278 update typo 0x03 to 0x02
  docs/tutorial/04-non-fungible-tokens.mdx
Labels: Documentation

#1275 Disable existing hints if linting is disabled
  runtime/sema/check_casting_expression.go
  runtime/sema/check_force_expression.go
  runtime/sema/type.go
  runtime/tests/checker/conversion_test.go
  runtime/tests/checker/dynamic_casting_test.go
  runtime/tests/checker/force_test.go
  runtime/tests/checker/utils_test.go
Labels: Improvement

#1024 Start development of a new pretty printer for Cadence programs
  go.mod
  go.sum
  runtime/ast/block.go
  runtime/ast/expression.go
  runtime/ast/expression_test.go
  runtime/ast/statement.go
  runtime/ast/statement_test.go
  runtime/ast/string.go
  runtime/ast/string_test.go
  runtime/ast/transfer.go
  runtime/ast/type.go
  runtime/ast/type_test.go
  runtime/ast/variable_declaration.go
  runtime/format/string.go
  runtime/parser2/declaration_test.go
  runtime/parser2/expression.go
  runtime/parser2/expression_test.go
  runtime/parser2/parser_test.go
  runtime/parser2/statement_test.go
  runtime/parser2/type_test.go
  tools/pretty/README.md
  tools/pretty/main.go
Labels: Feature

#1285 Remove redundant subtyping check
  runtime/interpreter/value.go
Labels: Improvement
