Repository onflow/cadence, pull requests merged in 2021-12, with the labels that each got.

#1248 Refactor account storage to use atree ordered maps
  runtime/cmd/decode-state-values/main.go
  runtime/contract_test.go
  runtime/interface.go
  runtime/interpreter/decode.go
  runtime/interpreter/encode.go
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/storage.go
  runtime/interpreter/storage_test.go
  runtime/interpreter/storagemap.go
  runtime/interpreter/value.go
  runtime/resourcedictionary_test.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/storage.go
  runtime/storage_test.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/metatype_test.go
Labels: Improvement

#1290 Tweak Cadence bench to be more stable
  .github/workflows/benchmark.yml
Labels: Improvement

#1163 Update LS dependencies
  languageserver/go.mod
  languageserver/go.sum
  languageserver/integration/initialization.go
  languageserver/integration/resolving.go
  languageserver/server/server.go
Labels: dependencies

#1280 Pretty print statements
  runtime/ast/block.go
  runtime/ast/expression.go
  runtime/ast/expression_test.go
  runtime/ast/statement.go
  runtime/ast/statement_test.go
  tools/pretty/main.go
Labels: Feature

#1281 Pretty print types
  runtime/ast/expression.go
  runtime/ast/expression_test.go
  runtime/ast/type.go
  runtime/ast/type_test.go
  runtime/ast/variable_declaration.go
Labels: Feature

#1292 Merge v0.20.x changes
  bump-version.sh
  go.mod
  go.sum
  npm-packages/cadence-docgen/package.json
  npm-packages/cadence-parser/package.json
  version.go
Labels: Chore

#1301 Updates NFT tutorial to use latest best practices
  docs/design-patterns.mdx
  docs/tutorial/03-fungible-tokens.mdx
  docs/tutorial/04-non-fungible-tokens.mdx
Labels: Documentation, Dev Portal Documentation, T-Documentation 📃

#1293 Fix npm packages
  npm-packages/cadence-docgen/src/go.js
  npm-packages/cadence-docgen/tests/index.test.ts
  npm-packages/cadence-parser/src/go.js
Labels: Chore

#1299 Optimize ByteSize functions for 7 Value types
  runtime/interpreter/encode.go
  runtime/interpreter/value.go
Labels: Performance

#1274 Update testify
  go.mod
  go.sum
Labels: Chore

#1296 Optimize HashInput functions to use scratch buffer provided by onflow/atree
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
Labels: Performance

#1295 Language Server updates
  languageserver/integration/commands.go
Labels: Improvement

#1289 Add optional resource owner change tracking callback
  runtime/cmd/decode-state-values/main.go
  runtime/convertValues.go
  runtime/interface.go
  runtime/interpreter/inspect_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/storage_test.go
  runtime/interpreter/value.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/storage_test.go
  runtime/tests/interpreter/enum_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/reference_test.go
  runtime/tests/interpreter/values_test.go
Labels: Feature

#1279 Start of a symbol/operator glossary
  docs/language/glossary.md
Labels: Documentation

#1306 Gracefully handle casts during arithmetic operations
  runtime/interpreter/errors.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/arithmetic_test.go
Labels: Bugfix
