Repository onflow/cadence, pull requests merged in 2021-07, with the labels that each got.

#1042 Finish storage format changes
  runtime/cmd/decode-state-values/main.go
  runtime/interpreter/decode.go
  runtime/interpreter/decode_v3.go
  runtime/interpreter/decode_v4.go
  runtime/interpreter/deferred_decoding_test.go
  runtime/interpreter/encode.go
  runtime/interpreter/encode_v4.go
  runtime/interpreter/encoding_benchmark_test.go
  runtime/interpreter/encoding_test.go
Labels: Bugfix, Improvement, Technical Debt, Testing

#1038 Infer array and dictionary static types from expected type during import
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/deployment_test.go
  runtime/interpreter/conversion.go
  runtime/interpreter/decode.go
  runtime/interpreter/primitivestatictype.go
  runtime/interpreter/statictype.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/runtime.go
Labels: Improvement

#1043 Include and consider static types of arrays and dictionaries
  runtime/interpreter/dynamictype.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/runtime.go
  runtime/tests/interpreter/dynamic_casting_test.go
Labels: Improvement

#1045 Add more tests for imported array/dictionary value type conformance
  runtime/convertValues_test.go
Labels: Testing

#1046 Add tests for decoding from old format and encoding in new format
  runtime/interpreter/deferred_decoding_test.go
  runtime/interpreter/encoding_test.go
Labels: Testing

#1048 Add static type sanity check for imported values
  runtime/convertValues_test.go
  runtime/runtime.go
Labels: Technical Debt, Testing

#990 Add presentation "Programming Language Implementation / Cadence Implementation"
  docs/Cadence Implementation.odp
  docs/Cadence Implementation.pdf
Labels: Documentation

#1053 Remove obsolete fields
  runtime/interpreter/decode.go
  runtime/interpreter/decode_v4.go
  runtime/interpreter/encode.go
  runtime/interpreter/encoding_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Improvement, Technical Debt

#1065 Fix get and revoke key functions
  runtime/account_keys_test.go
  runtime/runtime.go
Labels: Bugfix

#1064 Return a dedicated error when decoding fails due to an unsupported CBOR tag
  runtime/interpreter/decode.go
  runtime/interpreter/decode_v4.go
Labels: Improvement

#1056 Report a hint when casting to a same type as the expected type
  runtime/sema/check_casting_expression.go
  runtime/sema/hints.go
  runtime/tests/checker/casting_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Feature

#1067 Fix export of values
  encoding/json/decode.go
  encoding/json/encoding_test.go
  helpers.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/literal.go
  runtime/literal_test.go
  runtime/runtime.go
  runtime/runtime_test.go
  values.go
  values_test.go
Labels: Bugfix

#1068 Fix import of values
  encoding/json/decode.go
  encoding/json/encoding_test.go
  runtime/common/orderedmap/orderedmap.go
  runtime/common/orderedmap/orderedmap_string_interface.go
  runtime/common/orderedmap/orderedmap_string_string.go
  runtime/common/orderedmap/orderedmap_string_struct.go
  runtime/common/orderedmap/string_fruit_orderedmap_test.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/deployment_test.go
  runtime/interpreter/ordered_map_string_computedfield.go
  runtime/interpreter/ordered_map_string_value.go
  runtime/interpreter/ordered_map_string_variable.go
  runtime/program_params_validation_test.go
  runtime/runtime.go
  runtime/sema/ordered_map_interface_resourceinfo.go
  runtime/sema/ordered_map_interfacetype_struct.go
  runtime/sema/ordered_map_member_fielddeclaration.go
  runtime/sema/ordered_map_member_struct.go
  runtime/sema/ordered_map_position_resourceuse.go
  runtime/sema/ordered_map_resourceinvalidation_struct.go
  runtime/sema/ordered_map_string_importelement.go
  runtime/sema/ordered_map_string_member.go
  runtime/sema/ordered_map_string_type.go
  runtime/sema/ordered_map_string_valuedeclaration.go
  runtime/sema/ordered_map_string_variable.go
  runtime/sema/ordered_map_typeparameter_type.go
  values.go
  values_test.go
Labels: Bugfix

#1069 Fix map keys
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/interpreter/authaccount_contracts.go
  runtime/interpreter/block.go
  runtime/interpreter/deployed_contract.go
  runtime/interpreter/dynamictype.go
  runtime/interpreter/function.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_invocation.go
  runtime/interpreter/interpreter_transaction.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/interpreter/visitor.go
  runtime/runtime.go
  runtime/stdlib/functions.go
  runtime/tests/interpreter/enum_test.go
Labels: Bugfix

#1070 Gracefully handle errors during transaction and script argument validation
  runtime/runtime.go
  runtime/validation_test.go
Labels: Bugfix

#1071 Gracefully handle the optional-chaining invocation on non-optional member
  runtime/tests/checker/member_test.go
Labels: Testing

#1089 Add `names` field to auth account contracts
  docs/language/accounts.mdx
  runtime/account_test.go
  runtime/interface.go
  runtime/interpreter/authaccount_contracts.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/sema/authaccount_contracts.go
  runtime/tests/checker/account_test.go
Labels: Feature

#1080 Fix address conversion
  runtime/interpreter/value.go
  runtime/tests/interpreter/integers_test.go
Labels: Bugfix

#1081 Check resource construction
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/sema/type.go
  runtime/tests/checker/casting_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/import_test.go
Labels: Bugfix

#1082 Fix interpretation of optional binding with second value
  runtime/interpreter/interpreter_statement.go
  runtime/tests/checker/resources_test.go
  runtime/tests/interpreter/resources_test.go
Labels: Bugfix

#1083 Check run-time type of the argument of getCapability calls
  runtime/interpreter/value.go
  runtime/runtime_test.go
  runtime/sema/authaccount_type.go
  runtime/sema/publicaccount_type.go
Labels: Bugfix

#1096 Fix race condition in hash and sign algorithm values
  runtime/runtime.go
  runtime/stdlib/builtin.go
  runtime/tests/checker/crypto_test.go
Labels: Bugfix
