Repository onflow/cadence, pull requests merged in 2021-05, with the labels that each got.

#867 Fix function type members
  runtime/sema/type.go
  runtime/tests/checker/function_test.go
Labels: Bugfix

#865 Fix link function return value
  runtime/interpreter/interpreter.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/capability_test.go
Labels: Bugfix

#866 Test equal for nil value, in comparison and switch
  runtime/tests/interpreter/equality_test.go
  runtime/tests/interpreter/switch_test.go
Labels: Integration testing

#848 Optimize Address.Bytes() to inline fast path
  runtime/common/address.go
Labels: Improvement

#858 Pre-allocate and reuse value-path for encoding
  runtime/interpreter/encode.go
Labels: Improvement

#869 Pre-allocate and reuse value-path for decoding
  runtime/interpreter/decode.go
  runtime/interpreter/encode.go
Labels: Improvement

#877 Remove the high-level storage API
  runtime/interface.go
  runtime/runtime.go
  runtime/runtime_storage.go
  runtime/runtime_test.go
  runtime/storage_test.go
Labels: Breaking Change

#874 Update language server to latest Cadence and Go SDK
  languageserver/go.mod
  languageserver/go.sum
  languageserver/server/server.go
Labels: Improvement

#886 Handle case with no arguments
  languageserver/integration/codelenses.go
Labels: Bugfix

#885 Optimize decoding by using CBOR StreamDecoder
  go.mod
  go.sum
  runtime/interpreter/decode.go
  runtime/interpreter/encode.go
  runtime/interpreter/encoding_test.go
Labels: Improvement

#899 Measure and report code coverage
  .github/workflows/ci.yml
  Makefile
Labels: Testing

#901 Fix Codecov "file not found at ./coverage.txt"
  Makefile
Labels: Bug

#902 Enable more linters and lint
  .golangci.yml
  encoding/json/decode.go
  runtime/account_keys_test.go
  runtime/common/orderedmap/orderedmap_test.go
  runtime/compiler/wasm/blocktype.go
  runtime/compiler/wasm/functiontype.go
  runtime/compiler/wasm/gen/main.go
  runtime/compiler/wasm/opcode.go
  runtime/compiler/wasm/reader.go
  runtime/format/bytes_test.go
  runtime/format/capability.go
  runtime/format/composite.go
  runtime/format/dictionary.go
  runtime/format/fix.go
  runtime/format/nil.go
  runtime/format/pad.go
  runtime/format/void.go
  runtime/ft_test.go
  runtime/interpreter/decode.go
  runtime/interpreter/decode_v3.go
  runtime/interpreter/encode.go
  runtime/interpreter/encoding_benchmark_test.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/value.go
  runtime/parser2/declaration.go
  runtime/parser2/expression.go
  runtime/runtime.go
  runtime/sema/check_assignment.go
  runtime/sema/type.go
  runtime/tests/checker/storable_test.go
  runtime/tests/interpreter/arithmetic_test.go
  runtime/tests/interpreter/builtinfunctions_test.go
  runtime/tests/interpreter/transactions_test.go
  tools/golangci-lint/go.mod
  tools/golangci-lint/go.sum
  tools/maprangecheck/go.mod
  tools/maprangecheck/go.sum
Labels: Improvement

#878 Direct contract function invoke
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_import.go
  runtime/interpreter/value.go
  runtime/runtime.go
  runtime/runtime_test.go
Labels: Feature

#904 Fix CI linter failure
  runtime/interpreter/interpreter.go
  runtime/runtime.go
  runtime/runtime_test.go
Labels: Technical Debt

#896 Add deferred decoding support for composite values
  runtime/convertValues.go
  runtime/interpreter/authaccount_contracts.go
  runtime/interpreter/decode.go
  runtime/interpreter/deferred_decoding_test.go
  runtime/interpreter/encode.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_transaction.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/runtime.go
  runtime/stdlib/crypto.go
  runtime/tests/interpreter/composite_value_test.go
  runtime/tests/interpreter/enum_test.go
  runtime/tests/interpreter/import_test.go
  runtime/tests/interpreter/uuid_test.go
Labels: Feature

#906 Handle recursive values (due to references) in string function
  runtime/cmd/execute/repl.go
  runtime/contract_test.go
  runtime/deployment_test.go
  runtime/interpreter/block.go
  runtime/interpreter/deployed_contract.go
  runtime/interpreter/errors.go
  runtime/interpreter/function.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/stdlib/builtin.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/string_test.go
Labels: Bugfix

#893 Add extra test for deterministic JSON export
  runtime/convertValues_test.go
Labels: Testing

#913 Directly create int subtype value at interpreter
  runtime/interpreter/interpreter_expression.go
Labels: Improvement

#912 Add a reference to PublicKey in the crypto docs
  docs/language/crypto.md
Labels: Documentation

#903 PublicKeyValue stringer fix
  .gitignore
  runtime/interpreter/authaccount_contracts.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
Labels: Bugfix

#918 Make the interpreter location optional
  runtime/interpreter/interpreter.go
  runtime/storage_test.go
Labels: Improvement

#916 Add interpreter tests for common resource reference usages
  runtime/tests/interpreter/reference_test.go
Labels: Testing

#920 Implement `StaticType` for `StorageReferenceValue` and `EphemeralReferenceValue`
  runtime/interpreter/value.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/metatype_test.go
Labels: Bugfix

#926 Update language server to Cadence v0.16.0
  languageserver/go.mod
  languageserver/go.sum
  languageserver/server/server.go
Labels: Improvement

#881 Language Server: Suggest completion items for declaration ranges
  languageserver/server/server.go
Labels: Feature

#932 Add HexToAddress utility function, add tests for address functions
  runtime/common/address.go
  runtime/common/address_test.go
  runtime/storage_test.go
Labels: Feature, Testing

#944 Remove coverage of empty functions from report
  Makefile
Labels: Chore

#909 Rename all occurrences of a symbol in the document
  languageserver/protocol/methods.go
  languageserver/protocol/server.go
  languageserver/server/server.go
Labels: Feature

#947 [Optimization] Re-use converter functions across interpreters
  runtime/interpreter/interpreter.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Improvement, Performance

#927 Add Cadence documentation generator
  tools/docgen/gen/doc_generator.go
  tools/docgen/gen/templates/base-template
  tools/docgen/gen/templates/composite-full-template
  tools/docgen/gen/templates/composite-template
  tools/docgen/gen/templates/declarations-template
  tools/docgen/gen/templates/enum-case-template
  tools/docgen/gen/templates/enum-template
  tools/docgen/gen/templates/field-template
  tools/docgen/gen/templates/function-template
  tools/docgen/gen/templates/initializer-template
  tools/docgen/go.mod
  tools/docgen/go.sum
  tools/docgen/main.go
  tools/docgen/test/doc_gen_test.go
  tools/docgen/test/outputs/Color.md
  tools/docgen/test/outputs/Direction.md
  tools/docgen/test/outputs/NFT.md
  tools/docgen/test/outputs/NFT_Color.md
  tools/docgen/test/outputs/NFT_Direction.md
  tools/docgen/test/outputs/NFT_SomeStruct.md
  tools/docgen/test/outputs/NFT_SomeStruct_InnerStruct.md
  tools/docgen/test/outputs/SomeStruct.md
  tools/docgen/test/outputs/SomeStruct_InnerStruct.md
  tools/docgen/test/outputs/index.md
  tools/docgen/test/samples/sample1.cdc
  tools/docgen/test/samples/sample2.cdc
Labels: Feature

#938 Add function docs formatting support
  tools/docgen/gen/doc_generator.go
  tools/docgen/gen/templates/composite-full-template
  tools/docgen/gen/templates/composite-template
  tools/docgen/gen/templates/enum-template
  tools/docgen/gen/templates/function-template
  tools/docgen/gen/templates/initializer-template
  tools/docgen/test/doc_gen_test.go
  tools/docgen/test/outputs/Color.md
  tools/docgen/test/outputs/Direction.md
  tools/docgen/test/outputs/NFT.md
  tools/docgen/test/outputs/NFT_Color.md
  tools/docgen/test/outputs/NFT_Direction.md
  tools/docgen/test/outputs/NFT_SomeStruct.md
  tools/docgen/test/outputs/NFT_SomeStruct_InnerStruct.md
  tools/docgen/test/outputs/SomeStruct.md
  tools/docgen/test/outputs/SomeStruct_InnerStruct.md
  tools/docgen/test/outputs/index.md
  tools/docgen/test/outputs/sample3_output.md
  tools/docgen/test/samples/sample1.cdc
  tools/docgen/test/samples/sample2.cdc
  tools/docgen/test/samples/sample3.cdc
Labels: Feature

#949 Optimize `Type` function declaration
  runtime/interpreter/interpreter.go
Labels: Improvement, Performance

#948 Optimize qualified identifier creation
  runtime/sema/type.go
  runtime/sema/type_test.go
Labels: Improvement, Performance

#951 Always check arguments and record the argument types in the elaboration
  runtime/sema/check_invocation_expression.go
Labels: Improvement

#923 Provide documentation for range completion items
  languageserver/server/server.go
Labels: Feature
