Repository onflow/cadence, pull requests merged in 2021-09, with the labels that each got.

#1033 Add type inferring for func-args when there are no generics
  runtime/sema/check_invocation_expression.go
  runtime/tests/checker/type_inference_test.go
Labels: Improvement

#1087 Cointainer variances fixes
  runtime/interpreter/function.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_invocation.go
  runtime/interpreter/interpreter_transaction.go
  runtime/interpreter/statictype.go
  runtime/interpreter/value.go
  runtime/runtime_test.go
  runtime/tests/interpreter/invocation_test.go
  runtime/tests/interpreter/reference_test.go
Labels: Bugfix

#1135 Bump Cadence version
  npm-packages/cadence-docgen/package.json
  npm-packages/cadence-language-server/package.json
  npm-packages/cadence-parser/package.json
  version.go
Labels: Technical Debt

#1114 Remove obsolete script/transaction parameter check
  runtime/interpreter/interpreter.go
Labels: Improvement

#1139 Fix export errors by properly wrapping in runtime errors
  runtime/import_test.go
  runtime/runtime.go
Labels: Bugfix

#1138 Add limit on call stack depth
  runtime/errors.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/runtime.go
  runtime/runtime_test.go
Labels: Breaking Change

#1144 Add static type to host functions
  runtime/interpreter/function.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_transaction.go
  runtime/interpreter/value.go
  runtime/runtime.go
  runtime/sema/authaccount_contracts.go
  runtime/sema/authaccount_type.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/checker.go
  runtime/sema/publicaccount_type.go
  runtime/sema/string_type.go
  runtime/sema/type.go
  runtime/stdlib/builtin.go
  runtime/stdlib/flow.go
  runtime/stdlib/functions.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/condition_test.go
  runtime/tests/interpreter/container_mutation_test.go
  runtime/tests/interpreter/import_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/metatype_test.go
  runtime/tests/interpreter/transactions_test.go
Labels: Improvement

#1146 Fix array function member type creation
  runtime/interpreter/deferred_decoding_test.go
  runtime/interpreter/value.go
Labels: Bugfix

#1141 Add Path.toString() with tests and documentation.
  docs/language/accounts.mdx
  docs/language/values-and-types.mdx
  runtime/interpreter/value.go
  runtime/sema/type.go
  runtime/tests/checker/path_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Feature, enhancement

#1150 Add missing function type for Path.toString
  runtime/interpreter/value.go
Labels: Bugfix

#1154 Infer RHS of nil-coalescing operator to have non-optional type of LHS
  runtime/sema/check_binary_expression.go
  runtime/tests/interpreter/container_mutation_test.go
Labels: Improvement

#1110 Core events documentation
  docs/language/core-events.md
Labels: Documentation

#1155 Migrate remaining docs from docs site.
  docs/contract-upgrades.mdx
  docs/measuring-time.mdx
  docs/msg-sender.mdx
Labels: Documentation
