Repository onflow/cadence, pull requests merged in 2021-03, with the labels that each got.

#634 Fix code examples and improve documentation in language reference
  docs/language/composite-types.mdx
  docs/language/functions.mdx
  docs/language/restricted-types.md
Labels: Documentation

#637 Optimize encoding of positive bigints
  runtime/interpreter/encode.go
  runtime/interpreter/encoding_test.go
Labels: Improvement

#647 Make contract update validation optional and disable it by default
  runtime/contract_update_validation_test.go
  runtime/runtime.go
  runtime/runtime_test.go
Labels: Improvement

#636 Delay contract code and value updates to the end of execution
  runtime/deployment_test.go
  runtime/interface.go
  runtime/runtime.go
  runtime/runtime_storage.go
  runtime/runtime_test.go
Labels: Improvement

#646 Make contract update validation optional and disable it by default
  runtime/contract_update_validation_test.go
  runtime/runtime.go
Labels: Improvement

#630 Optimize checker construction
  runtime/interpreter/interpreter.go
  runtime/sema/basefunction.go
  runtime/sema/checker.go
  runtime/sema/import.go
  runtime/sema/type.go
  runtime/sema/variable_activations.go
Labels: Improvement

#649 Fix updating contracts with reference typed fields
  runtime/contract_update_validation.go
  runtime/contract_update_validation_test.go
  runtime/errors.go
Labels: Bugfix

#656 Add parser for pragma signers
  runtime/parser2/docstring.go
  runtime/parser2/docstring_test.go
Labels: Feature

#654 Improve type equality check in the contract update validation
  runtime/contract_update_validation.go
  runtime/contract_update_validation_test.go
Labels: Bugfix

#658 Cache qualified identifier and type ID for composite types and interface types
  runtime/sema/type.go
Labels: Improvement

#659 Improve naming: Rename nominal type to simple type
  runtime/sema/any_type.go
  runtime/sema/anyresource_type.go
  runtime/sema/anystruct_type.go
  runtime/sema/authaccount_contracts.go
  runtime/sema/authaccount_type.go
  runtime/sema/block.go
  runtime/sema/bool_type.go
  runtime/sema/character_type.go
  runtime/sema/deployed_contract.go
  runtime/sema/invalid_type.go
  runtime/sema/meta_type.go
  runtime/sema/never_type.go
  runtime/sema/path_type.go
  runtime/sema/publicaccount_type.go
  runtime/sema/simple_type.go
  runtime/sema/storable_type.go
  runtime/sema/string_type.go
  runtime/sema/type.go
  runtime/sema/void_type.go
Labels: Improvement

#664 Add computed fields to the composite value
  runtime/interpreter/gen.go
  runtime/interpreter/ordered_map_string_computedfield.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/composite_value_test.go
Labels: Improvement

#670 Revert "Cache qualified identifier and type ID for composite types and interface types"
  runtime/sema/type.go
Labels: Bugfix

#669 Add support for exporting enums
  runtime/convertTypes.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  types.go
  values.go
Labels: Bugfix

#672 Add support for importing enum values
  encoding/json/decode.go
  encoding/json/encode.go
  runtime/convertValues.go
  runtime/convertValues_test.go
Labels: Improvement

#680 Optimize interpreter: Refactor function invocations to return a value instead of a trampoline
  runtime/interpreter/function.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/runtime.go
  runtime/stdlib/builtin.go
  runtime/stdlib/crypto.go
  runtime/stdlib/flow.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/import_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/transactions_test.go
Labels: Improvement

#677 Optimize integer conversion
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/literal.go
Labels: Improvement

#690 Ensure code is long enough when extracting excerpt
  runtime/pretty/print.go
  runtime/pretty/print_test.go
Labels: Bugfix

#633 Introduce a new Account Key API
  encoding/json/decode.go
  encoding/json/encoding_test.go
  runtime/account_keys_test.go
  runtime/common/location.go
  runtime/crypto_test.go
  runtime/interface.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/primitivestatictype.go
  runtime/interpreter/value.go
  runtime/interpreter/visitor.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/sema/authaccount_type.go
  runtime/sema/crypto_algorithm_types.go
  runtime/sema/hashalgorithm_string.go
  runtime/sema/publicaccount_type.go
  runtime/sema/signaturealgorithm_string.go
  runtime/sema/type.go
  runtime/stdlib/builtin.go
  runtime/stdlib/contracts/crypto.cdc
  runtime/stdlib/crypto.go
  runtime/stdlib/internal/contracts.gen.go
  runtime/stdlib/value.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/transactions_test.go
  runtime/types.go
  types.go
Labels: Feature

#685 Optimize interpreter: Make invocation location ranges lazy
  runtime/convertValues.go
  runtime/interpreter/authaccount_contracts.go
  runtime/interpreter/block.go
  runtime/interpreter/deployed_contract.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/function.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_invocation.go
  runtime/interpreter/interpreter_statement.go
  runtime/interpreter/location.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/runtime.go
  runtime/stdlib/builtin.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Improvement

#663 Allow the Language Server to be debugged
  docs/development.md
  languageserver/run.sh
Labels: Feature

#635 Add documentation for the new account key API
  docs/language/accounts.mdx
  docs/language/crypto.md
Labels: Documentation

#697 Return nil when revoking a non-existing key
  runtime/account_keys_test.go
  runtime/runtime.go
Labels: Improvement

#701 Fix the syntax of the signature algorithm enum in docs
  docs/language/crypto.md
Labels: Documentation

#688 Report a hint when a dynamic cast is statically known to always succeed
  runtime/sema/check_casting_expression.go
  runtime/sema/hints.go
  runtime/tests/checker/dynamic_casting_test.go
  runtime/tests/checker/occurrences_test.go
Labels: Feature

#707 Make all path sub-types externally returnable
  runtime/runtime_test.go
  runtime/sema/path_type.go
Labels: Bugfix

#705 Revert the addition of the unsupported signing and hash algorithms
  docs/language/crypto.md
  runtime/account_keys_test.go
  runtime/sema/crypto_algorithm_types.go
  runtime/sema/hashalgorithm_string.go
  runtime/sema/signaturealgorithm_string.go
  runtime/types.go
Labels: Improvement

#709 Properly handle recursive types when checking validity of event parameter types
  runtime/sema/check_event_declaration.go
  runtime/sema/type.go
  runtime/tests/checker/events_test.go
  runtime/tests/checker/storable_test.go
Labels: Bugfix, P-High

#694 Fix cadence-parser NPM package, update versions
  npm-packages/cadence-language-server/package.json
  npm-packages/cadence-parser/package.json
  npm-packages/cadence-parser/tsconfig.json
  npm-packages/monaco-languageclient-cadence/package.json
Labels: Bugfix

#711 Ensure imported checkers/elaborations are reused in tests' import handlers
  runtime/tests/checker/access_test.go
  runtime/tests/checker/import_test.go
  runtime/tests/interpreter/import_test.go
Labels: Improvement

#714 Use require.ErrorAs
  runtime/deployment_test.go
  runtime/predeclaredvalues_test.go
  runtime/runtime_test.go
  runtime/tests/checker/predeclaredvalues_test.go
  runtime/tests/checker/utils.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/capability_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/fixedpoint_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/transactions_test.go
  runtime/tests/utils/utils.go
Labels: Technical Debt

#723 Use location ID as key for maps holding account codes
  runtime/contract_test.go
  runtime/contract_update_validation_test.go
  runtime/runtime_test.go
Labels: Technical Debt

#719 Fix error range when reporting a type error for an indexing reference expression
  runtime/sema/check_reference_expression.go
  runtime/tests/checker/reference_test.go
Labels: Bugfix

#725 Fix runtime representation of native HashAlgorithm/SignAlgorithm enums
  runtime/account_keys_test.go
  runtime/interpreter/value.go
  runtime/runtime.go
  runtime/sema/crypto_algorithm_types.go
  runtime/sema/hashalgorithm_string.go
  runtime/sema/signaturealgorithm_string.go
  runtime/sema/type.go
  runtime/stdlib/builtin.go
  runtime/stdlib/crypto.go
Labels: Bugfix

#737 Add documentation for the `getType()` builtin method
  docs/language/run-time-types.md
Labels: Documentation

#727 Add array appendAll function
  docs/language/values-and-types.mdx
  runtime/interpreter/value.go
  runtime/sema/type.go
  runtime/tests/checker/arrays_dictionaries_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Feature

#741 Handle field initialization using force-move assignment
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_statement.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Bugfix
