Repository onflow/cadence, pull requests merged in 2021-06, with the labels that each got.

#946 Provide code action to declare variable/constant
  languageserver/server/server.go
  runtime/sema/check_assignment.go
  runtime/sema/check_expression.go
  runtime/sema/check_invocation_expression.go
  runtime/sema/checker.go
  runtime/sema/errors.go
Labels: Feature

#963 [Optimization] Make dynamic types singleton for simple types
  runtime/interpreter/block.go
  runtime/interpreter/deployed_contract.go
  runtime/interpreter/function.go
  runtime/interpreter/value.go
Labels: Improvement, Performance

#968 Add test case for invalid utf8 string import
  encoding/json/encoding_test.go
  runtime/convertValues_test.go
Labels: Testing

#967 Update account docs to not to pass PublicKey as an argument
  docs/language/accounts.mdx
Labels: Documentation

#972 Validate UTF-8 compatibility in string value constructor
  encoding/json/encoding_test.go
  runtime/convertValues_test.go
  values.go
  values_test.go
Labels: Improvement

#971 Use actions/setup-go@v2 to speed up CI by ~10 secs and specify Go 1.15.x
  .github/workflows/ci.yml
Labels: Chore

#973 Allow native composite types to be passed as script arguments
  runtime/account_keys_test.go
  runtime/errors.go
  runtime/interpreter/value.go
  runtime/program_params_validation_test.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/sema/any_type.go
  runtime/sema/anyresource_type.go
  runtime/sema/anystruct_type.go
  runtime/sema/authaccount_contracts.go
  runtime/sema/authaccount_type.go
  runtime/sema/block.go
  runtime/sema/bool_type.go
  runtime/sema/character_type.go
  runtime/sema/crypto_algorithm_types.go
  runtime/sema/deployed_contract.go
  runtime/sema/invalid_type.go
  runtime/sema/meta_type.go
  runtime/sema/never_type.go
  runtime/sema/path_type.go
  runtime/sema/publicaccount_type.go
  runtime/sema/simple_type.go
  runtime/sema/storable_type.go
  runtime/sema/string_type.go
  runtime/sema/type.go
  runtime/sema/void_type.go
Labels: Improvement

#983 Check 'importability' instead of 'storability' for transaction arguments
  runtime/program_params_validation_test.go
  runtime/sema/check_transaction_declaration.go
  runtime/sema/errors.go
  runtime/tests/checker/transactions_test.go
Labels: Improvement

#985 [Doc-Gen Tool] Add documentation generation support for event declarations
  tools/docgen/gen/doc_generator.go
  tools/docgen/gen/templates/base-template
  tools/docgen/gen/templates/composite-members-template
  tools/docgen/gen/templates/event-template
  tools/docgen/gen/templates/function-template
  tools/docgen/test/outputs/NFT.md
  tools/docgen/test/outputs/index.md
  tools/docgen/test/samples/sample1.cdc
  tools/docgen/test/samples/sample2.cdc
Labels: Documentation, Improvement

#962 Update for changes in Flowkit API
  languageserver/go.mod
  languageserver/go.sum
  languageserver/integration/commands.go
Labels: dependencies

#998 Fix AST walk for transaction declaration
  runtime/ast/transaction_declaration.go
Labels: Bugfix

#992 Fix dictionary deferred owner
  runtime/interpreter/decode.go
  runtime/interpreter/value.go
Labels: Bugfix

#999 Update the Crypto contract
  docs/language/crypto.mdx
  runtime/crypto_test.go
  runtime/runtime.go
  runtime/stdlib/contracts/crypto.cdc
  runtime/stdlib/crypto.go
  runtime/stdlib/internal/contracts.gen.go
Labels: Breaking Change, Improvement

#1000 No need for checking resource loss when function definitely halted
  runtime/sema/check_function.go
  runtime/sema/function_activations.go
  runtime/tests/checker/resources_test.go
Labels: Improvement

#1001 Remove the result declaration kind
  runtime/common/declarationkind.go
  runtime/common/declarationkind_string.go
  runtime/sema/check_function.go
  runtime/sema/checker.go
Labels: Technical Debt

#995 Make `PublicKey` type importable
  runtime/account_keys_test.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/deployment_test.go
  runtime/interpreter/value.go
  runtime/program_params_validation_test.go
  runtime/runtime.go
  runtime/sema/type.go
Labels: Improvement

#1004 Embed markdown templates to docgen tool at compile time
  tools/docgen/gen/doc_generator.go
  tools/docgen/gen/templates/markdown-templates.go
  tools/docgen/gen/templates/markdown/base-template
  tools/docgen/gen/templates/markdown/composite-full-template
  tools/docgen/gen/templates/markdown/composite-members-template
  tools/docgen/gen/templates/markdown/composite-template
  tools/docgen/gen/templates/markdown/enum-case-template
  tools/docgen/gen/templates/markdown/enum-template
  tools/docgen/gen/templates/markdown/event-template
  tools/docgen/gen/templates/markdown/field-template
  tools/docgen/gen/templates/markdown/function-template
  tools/docgen/gen/templates/markdown/initializer-template
  tools/docgen/gen/templates/templates.go
  tools/docgen/go.mod
Labels: Improvement, Technical Debt

#1006 Language Server NPM package: Add support for Node environment, add tests
  npm-packages/cadence-language-server/jest.config.js
  npm-packages/cadence-language-server/package-lock.json
  npm-packages/cadence-language-server/package.json
  npm-packages/cadence-language-server/src/index.ts
  npm-packages/cadence-language-server/tests/index.test.ts
  npm-packages/cadence-language-server/tests/setup.js
  npm-packages/cadence-language-server/tsconfig.json
Labels: Improvement, Testing

#1005 Add wasm generation for docgen tool
  tools/docgen/cmd/main.go
  tools/docgen/cmd/main_wasm.go
  tools/docgen/doc_generator.go
  tools/docgen/templates/markdown-templates.go
  tools/docgen/templates/markdown/base-template
  tools/docgen/templates/markdown/composite-full-template
  tools/docgen/templates/markdown/composite-members-template
  tools/docgen/templates/markdown/composite-template
  tools/docgen/templates/markdown/enum-case-template
  tools/docgen/templates/markdown/enum-template
  tools/docgen/templates/markdown/event-template
  tools/docgen/templates/markdown/field-template
  tools/docgen/templates/markdown/function-template
  tools/docgen/templates/markdown/initializer-template
  tools/docgen/templates/templates.go
  tools/docgen/test/doc_gen_test.go
Labels: Feature

#1003 Add documentation for the Cadence documentation generator
  docs/language/syntax.md
  tools/docgen/README.md
Labels: Documentation

#1002 Add HashAlgorithm hash and hashWithTag functions
  docs/language/crypto.mdx
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/crypto_test.go
  runtime/deployment_test.go
  runtime/interface.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/runtime.go
  runtime/sema/crypto_algorithm_types.go
  runtime/sema/type.go
  runtime/stdlib/builtin.go
  runtime/stdlib/contracts/crypto.cdc
  runtime/stdlib/crypto.go
  runtime/stdlib/internal/contracts.gen.go
  runtime/tests/checker/crypto_test.go
Labels: Breaking Change, Feature

#1007 Add dynamic type importability check for arguments
  runtime/errors.go
  runtime/interpreter/dynamictype.go
  runtime/program_params_validation_test.go
  runtime/runtime.go
Labels: Bugfix, Improvement

#1008 Add npm package for the docgen-tool
  Makefile
  npm-packages/cadence-docgen/.gitignore
  npm-packages/cadence-docgen/README.md
  npm-packages/cadence-docgen/jest.config.js
  npm-packages/cadence-docgen/package-lock.json
  npm-packages/cadence-docgen/package.json
  npm-packages/cadence-docgen/src/go.js
  npm-packages/cadence-docgen/src/index.ts
  npm-packages/cadence-docgen/tests/index.test.ts
  npm-packages/cadence-docgen/tests/setup.js
  npm-packages/cadence-docgen/tsconfig.json
  tools/docgen/go.mod
  tools/docgen/go.sum
  tools/docgen/wasm/main.go
Labels: Feature

#1013 Don't check missing program
  languageserver/server/server.go
  runtime/ast/function_declaration.go
  runtime/ast/statement.go
Labels: Bugfix

#1011 Update NPM packages
  npm-packages/cadence-docgen/README.md
  npm-packages/cadence-docgen/package-lock.json
  npm-packages/cadence-docgen/package.json
  npm-packages/cadence-language-server/README.md
  npm-packages/cadence-language-server/package.json
  npm-packages/cadence-parser/README.md
  npm-packages/cadence-parser/package.json
  tools/docgen/go.mod
  tools/docgen/go.sum
Labels: Chore

#1015 Update the language server to the latest Cadence version
  languageserver/go.mod
  languageserver/go.sum
Labels: Improvement

#1017 Fix operator documentation
  docs/language/operators.md
Labels: Documentation

#980 Extend the source compatibility suite
  .github/workflows/compat.yaml
  compat/main.py
  compat/suite/flow-core-contracts.yaml
  compat/suite/flow-ft.yaml
  compat/suite/flow-nft.yaml
  compat/suite/index.yaml
  compat/suite/nba-smart-contracts.yaml
  runtime/cmd/check/main.go
  runtime/cmd/cmd.go
  runtime/cmd/compile/main.go
  runtime/sema/check_member_expression.go
  runtime/sema/checker.go
Labels: Improvement

#1019 Fix close-brace for struct definition docs in docgen tool
  tools/docgen/templates/markdown/composite-full-template
  tools/docgen/test/outputs/NFT.md
  tools/docgen/test/outputs/NFT_SomeStruct.md
  tools/docgen/test/outputs/NFT_SomeStruct_InnerStruct.md
  tools/docgen/test/outputs/SomeInterface.md
  tools/docgen/test/outputs/SomeStruct.md
  tools/docgen/test/outputs/SomeStruct_InnerStruct.md
Labels: Bugfix

#1018 Reuse base activation across all interpreters
  runtime/cmd/execute/execute.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_import.go
  runtime/runtime.go
Labels: Improvement

#1022 Directly declare base values in activation without interpreter
  runtime/interpreter/globalvariables.go
  runtime/interpreter/interpreter.go
Labels: Improvement

#1020 Improve the documentation for dictionaries and arrays
  docs/language/values-and-types.mdx
Labels: Documentation

#1023 Produce valid Cadence string literals when formatting strings
  runtime/format/string.go
  runtime/format/string_test.go
Labels: Improvement

#1028 FlowKit API Update
  languageserver/go.mod
  languageserver/go.sum
  languageserver/integration/commands.go
  languageserver/integration/initialization.go
  languageserver/integration/integration.go
  languageserver/integration/resolving.go
Labels: Improvement, dependencies

#1012 Remove Crypto contract status callouts
  docs/language/crypto.mdx
Labels: Documentation

#1026 Remove additional check for builtin values during import resolving
  runtime/interpreter/interpreter_import.go
Labels: Technical Debt

#1037 Add walker for values
  runtime/interpreter/block.go
  runtime/interpreter/deployed_contract.go
  runtime/interpreter/function.go
  runtime/interpreter/inspect.go
  runtime/interpreter/inspect_test.go
  runtime/interpreter/value.go
  runtime/interpreter/walk.go
Labels: Feature

#1034 Add static types to array values and dictionary values
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/interpreter/conversion.go
  runtime/interpreter/conversion_test.go
  runtime/interpreter/deferred_decoding_test.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/runtime.go
  runtime/sema/authaccount_contracts.go
  runtime/sema/authaccount_type.go
  runtime/sema/check_array_expression.go
  runtime/sema/crypto_algorithm_types.go
  runtime/sema/deployed_contract.go
  runtime/sema/elaboration.go
  runtime/sema/string_type.go
  runtime/sema/type.go
  runtime/stdlib/flow.go
  runtime/storage_test.go
  runtime/tests/checker/builtinfunctions_test.go
  runtime/tests/checker/string_test.go
  runtime/tests/interpreter/builtinfunctions_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/enum_test.go
  runtime/tests/interpreter/for_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/metatype_test.go
  runtime/tests/interpreter/string_test.go
  runtime/tests/interpreter/switch_test.go
  types.go
  values.go
Labels: Improvement

#1035 Add encoding/decoding for array value static type
  runtime/interpreter/decode.go
  runtime/interpreter/encode.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/value.go
Labels: Breaking Change, Feature
