Repository onflow/cadence, pull requests merged in 2021-04, with the labels that each got.

#750 Document run-time type identifiers
  docs/language/run-time-types.md
Labels: Documentation

#759 Improve state decoding tool
  go.mod
  go.sum
  runtime/cmd/decode-state-values/main.go
Labels: Improvement

#762 Add validation for enum cases during contract updates
  runtime/contract_update_validation.go
  runtime/contract_update_validation_test.go
  runtime/errors.go
Labels: Improvement

#768 Panic with a dedicated error when a member access results in no value
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Improvement

#788 Remove obsolete code in decode.go
  runtime/interpreter/decode.go
Labels: Improvement

#783 Benchmark CBOR encoding/decoding using mainnet data
  runtime/interpreter/encoding_benchmark_test.go
  runtime/interpreter/testdata/comp_v2_96d7e06eaf4b3fcf.cbor.gz
  runtime/interpreter/testdata/comp_v3_99dc360eee32dcec.cbor.gz
  runtime/interpreter/testdata/comp_v3_b52a33b7e56868f6.cbor.gz
  runtime/interpreter/testdata/comp_v3_d99d7e6b4dad41e1.cbor.gz
  runtime/interpreter/testdata/link_v3_2392f05c3b72f235.cbor.gz
  runtime/interpreter/testdata/link_v3_3a791fe1b8243e73.cbor.gz
Labels: Improvement

#789 Use force expresion's end position in force nil error
  runtime/interpreter/interpreter_expression.go
Labels: Improvement

#769 Clean up "storage removal" index expression
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_statement.go
  runtime/sema/check_swap.go
  runtime/sema/check_variable_declaration.go
  runtime/sema/elaboration.go
Labels: Technical Debt

#799 Cache capability type members
  runtime/sema/type.go
  runtime/tests/checker/typeargument_test.go
Labels: Improvement

#808 added balance fields on accounts
  .gitignore
  docs/language/accounts.mdx
  runtime/interface.go
  runtime/interpreter/value.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/sema/authaccount_type.go
  runtime/sema/publicaccount_type.go
  runtime/tests/checker/account_test.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/transactions_test.go
Labels: Feature

#798 Improve state decoding tool
  runtime/cmd/decode-state-values/main.go
Labels: Feature

#811 Remove unused storage key handler
  runtime/interpreter/interpreter.go
  runtime/runtime.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Technical Debt

#812 Add functions to read stored and linked values
  runtime/convertValues.go
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/runtime.go
  runtime/storage_test.go
Labels: Feature

#792 Deny removing contracts if contract update validation is enabled
  docs/contract-updatability.md
  runtime/contract_update_validation.go
  runtime/contract_update_validation_test.go
  runtime/errors.go
  runtime/runtime.go
Labels: Improvement

#817 Document saturation arithmetic and min/max fields
  docs/language/values-and-types.mdx
Labels: Documentation

#819 Remove encoding and decoding support for storage references
  runtime/interpreter/decode.go
  runtime/interpreter/decode_v3.go
  runtime/interpreter/encode.go
  runtime/interpreter/encoding_test.go
Labels: Technical Debt

#823 Include wrapped error in InvalidEntryPointArgumentError message
  runtime/errors.go
Labels: Improvement

#825 Tutorial typo fixes
  docs/tutorial/04-non-fungible-tokens.mdx
Labels: Documentation, T-Documentation 📃

#822 Rename signature algorithm ECDSA_Secp256k1 to ECDSA_secp256k1
  docs/language/crypto.md
  runtime/account_keys_test.go
  runtime/sema/crypto_algorithm_types.go
  runtime/sema/signaturealgorithm_string.go
  runtime/types.go
Labels: Breaking Change, Improvement

#826 Add test for TopShot moment batch transfer
  runtime/storage_test.go
Labels: Integration testing

#854 Only consider the program invalid if there are error diagnostics
  languageserver/server/server.go
Labels: Bugfix

#857 Remove call to Valid() during encoding to boost speed by about 13-18%
  go.mod
  go.sum
  runtime/interpreter/decode.go
  runtime/interpreter/encode.go
Labels: Improvement

#849 Test getCapability after unlink
  runtime/storage_test.go
Labels: Integration testing

#855 Language Server: Reuse existing checkers instead of re-parsing and re-checking imports
  languageserver/server/server.go
Labels: Bugfix

#856 Test storing capabilities
  runtime/storage_test.go
Labels: Integration testing
