Repository onflow/cadence, pull requests merged in 2021-02, with the labels that each got.

#568 Use correct CommandSubmitTransaction command in entrypoint code lens
  languageserver/integration/codelenses.go
Labels: Bugfix

#430 WebAssembly: Add support for start section
  runtime/compiler/wasm/errors.go
  runtime/compiler/wasm/module.go
  runtime/compiler/wasm/reader.go
  runtime/compiler/wasm/reader_test.go
  runtime/compiler/wasm/section.go
  runtime/compiler/wasm/writer.go
  runtime/compiler/wasm/writer_test.go
Labels: Feature

#579 Update language server to Cadence v0.12.6 and Go SDK v0.14.3
  languageserver/go.mod
  languageserver/go.sum
  languageserver/server/server.go
Labels: Improvement

#583 Return a dedicated error for encoding an unsupported value
  runtime/interpreter/encode.go
  runtime/interpreter/errors.go
Labels: Improvement

#587 Fix `String()` function of `DicitonaryValue` when values are deferred
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/runtime_storage.go
Labels: Bugfix

#577 Fix parsing 'from' keyword in imported-identifiers
  runtime/parser2/declaration.go
  runtime/parser2/declaration_test.go
Labels: Bugfix

#591 Add compilation to runtime diagram
  runtime/runtime.monopic
  runtime/runtime.png
  runtime/runtime.svg
Labels: Documentation

#594 Minor additions to the docs
  docs/language/composite-types.mdx
Labels: Documentation

#593 Validate contract updates
  runtime/ast/composite.go
  runtime/ast/declaration.go
  runtime/ast/function_declaration.go
  runtime/ast/import.go
  runtime/ast/interface.go
  runtime/ast/memberindices.go
  runtime/ast/members.go
  runtime/ast/pragma.go
  runtime/ast/transaction_declaration.go
  runtime/ast/type.go
  runtime/ast/variable_declaration.go
  runtime/contract_update_validation.go
  runtime/errors.go
  runtime/runtime.go
  runtime/runtime_test.go
Labels: Feature

#597 Improve error reporting in contract update validation
  runtime/contract_update_validation.go
  runtime/contract_update_validation_test.go
  runtime/errors.go
  runtime/runtime.go
  runtime/runtime_test.go
Labels: Improvement

#600 Make interface sets ordered and thread-safe
  runtime/sema/gen.go
  runtime/sema/interfaceset.go
  runtime/sema/ordered_map_interfacetype_struct.go
  runtime/sema/type.go
Labels: Improvement

#602 Make member set deterministic
  runtime/sema/gen.go
  runtime/sema/member_set.go
  runtime/sema/ordered_map_member_struct.go
Labels: Improvement

#601 Make activations deterministic
  runtime/activations/activations.go
  runtime/common/orderedmap/gen.go
  runtime/common/orderedmap/orderedmap_string_interface.go
Labels: Improvement

#605 Make elaboration globals deterministic
  runtime/interpreter/interpreter.go
  runtime/repl.go
  runtime/runtime.go
  runtime/sema/checker.go
  runtime/sema/elaboration.go
  runtime/sema/gen.go
  runtime/sema/import.go
  runtime/sema/ordered_map_string_variable.go
  runtime/stdlib/crypto.go
  runtime/tests/checker/account_test.go
  runtime/tests/checker/arrays_dictionaries_test.go
  runtime/tests/checker/boolean_test.go
  runtime/tests/checker/builtinfunctions_test.go
  runtime/tests/checker/capability_test.go
  runtime/tests/checker/casting_test.go
  runtime/tests/checker/character_test.go
  runtime/tests/checker/composite_test.go
  runtime/tests/checker/declaration_test.go
  runtime/tests/checker/dictionary_test.go
  runtime/tests/checker/fixedpoint_test.go
  runtime/tests/checker/force_test.go
  runtime/tests/checker/genericfunction_test.go
  runtime/tests/checker/integer_test.go
  runtime/tests/checker/interface_test.go
  runtime/tests/checker/member_test.go
  runtime/tests/checker/metatype_test.go
  runtime/tests/checker/nil_coalescing_test.go
  runtime/tests/checker/path_test.go
  runtime/tests/checker/reference_test.go
  runtime/tests/checker/restriction_test.go
  runtime/tests/checker/string_test.go
  runtime/tests/checker/typeargument_test.go
  runtime/tests/checker/utils.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Improvement

#610 Reuse enc mode and dec mode
  runtime/interpreter/decode.go
  runtime/interpreter/encode.go
  runtime/interpreter/encoding_test.go
Labels: Improvement

#611 Cache members of composite types and interface types
  runtime/sema/check_composite_declaration.go
  runtime/sema/type.go
Labels: Improvement

#607 Use ordered maps for imported values and types
  runtime/sema/check_import_declaration.go
  runtime/sema/gen.go
  runtime/sema/import.go
  runtime/sema/ordered_map_string_importelement.go
  runtime/tests/checker/import_test.go
  runtime/tests/interpreter/import_test.go
Labels: Improvement

#608 Use ordered maps for type parameters
  runtime/interpreter/function.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/sema/authaccount_contracts.go
  runtime/sema/block.go
  runtime/sema/check_invocation_expression.go
  runtime/sema/deployed_contract.go
  runtime/sema/elaboration.go
  runtime/sema/gen.go
  runtime/sema/nominal_type.go
  runtime/sema/ordered_map_typeparameter_type.go
  runtime/sema/type.go
  runtime/tests/checker/genericfunction_test.go
Labels: Improvement

#609 Use ordered map for field initialization check
  runtime/sema/check_assignment.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_expression.go
  runtime/sema/check_function.go
  runtime/sema/check_member_expression.go
  runtime/sema/check_transaction_declaration.go
  runtime/sema/gen.go
  runtime/sema/initialization_info.go
  runtime/sema/ordered_map_member_fielddeclaration.go
Labels: Improvement

#612 Add tests for KeyString function
  runtime/interpreter/value_test.go
Labels: Improvement

#613 Write cached items in deterministic order
  runtime/interpreter/encode.go
  runtime/interpreter/encoding_test.go
  runtime/runtime_storage.go
Labels: Improvement

#606 Improve resource info merging
  runtime/sema/resources.go
Labels: Improvement

#619 Fix AuthAccount nested types
  runtime/sema/type.go
  runtime/tests/checker/account_test.go
Labels: Bugfix

#621 Remove the prepare callback
  runtime/runtime_storage.go
Labels: Improvement

#622 Remove prepare and decode callbacks
  runtime/runtime_storage.go
Labels: Improvement

#626 Cache members for array and dictionary types
  runtime/sema/type.go
Labels: Improvement

#625 Refactor String, AuthAccount.Contracts, and DeployedContract type to singleton
  runtime/compiler/compiler.go
  runtime/convertTypes.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/primitivestatictype.go
  runtime/literal.go
  runtime/literal_test.go
  runtime/sema/authaccount_contracts.go
  runtime/sema/authaccount_type.go
  runtime/sema/check_conditions.go
  runtime/sema/check_dictionary_expression.go
  runtime/sema/check_event_declaration.go
  runtime/sema/check_expression.go
  runtime/sema/deployed_contract.go
  runtime/sema/meta_type.go
  runtime/sema/nominal_type.go
  runtime/sema/string_type.go
  runtime/sema/type.go
  runtime/sema/type_test.go
  runtime/stdlib/builtin.go
  runtime/stdlib/flow.go
  runtime/tests/checker/arrays_dictionaries_test.go
  runtime/tests/checker/builtinfunctions_test.go
  runtime/tests/checker/dynamic_casting_test.go
  runtime/tests/checker/events_test.go
  runtime/tests/checker/storable_test.go
  runtime/tests/checker/string_test.go
  runtime/tests/checker/typeargument_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Improvement
