Repository onflow/cadence, pull requests merged in 2021-08, with the labels that each got.

#1104 flow-go sync tweaks
  .github/workflows/sync-flow-go.yml
Labels: Improvement

#1084 Include receiver in function type and check it in invocations
  runtime/interpreter/errors.go
  runtime/interpreter/function.go
  runtime/interpreter/import.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_invocation.go
  runtime/interpreter/interpreter_transaction.go
  runtime/interpreter/value.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_invocation_expression.go
  runtime/sema/check_member_expression.go
  runtime/sema/check_transaction_declaration.go
  runtime/sema/checker_test.go
  runtime/sema/elaboration.go
  runtime/sema/type.go
  runtime/stdlib/builtin.go
  runtime/stdlib/functions.go
  runtime/tests/checker/member_test.go
  runtime/tests/checker/reference_test.go
  runtime/tests/checker/resources_test.go
  runtime/tests/interpreter/import_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/reference_test.go
Labels: Bugfix

#1122 Fix and improve documentation
  docs/FAQ.md
  docs/language/built-in-functions.md
  docs/language/contracts.md
Labels: Documentation

#1052 Infer static-type from imported array/dictionary values
  runtime/convertValues.go
  runtime/convertValues_test.go
Labels: Feature

#1103 Add container mutation check for arrays and dictionaries
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/interpreter/deferred_decoding_test.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/errors.go
  runtime/interpreter/inspect_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/runtime_test.go
  runtime/storage_test.go
  runtime/tests/checker/arrays_dictionaries_test.go
  runtime/tests/interpreter/container_mutation_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Improvement

#1130 Give Resources their own page.
  docs/language/composite-types.mdx
  docs/language/resources.mdx
Labels: Documentation
