Repository onflow/cadence, pull requests merged in 2022-02, with the labels that each got.

#1396 [v0.21] Allows adding new interface conformances during a contract update
  docs/language/contract-updatability.md
  runtime/contract_update_validation.go
  runtime/contract_update_validation_test.go
  runtime/errors.go
Labels: Improvement

#1360 Disallow arithmetic, comparison and bitwise operations on number supertypes
  runtime/sema/check_binary_expression.go
  runtime/sema/type.go
  runtime/tests/checker/integer_test.go
  runtime/tests/checker/operations_test.go
  runtime/tests/interpreter/arithmetic_test.go
  runtime/tests/interpreter/equality_test.go
Labels: Breaking Change

#1267 Limit mutation of container-typed fields to the scope of the composite
  docs/language/access-control.md
  docs/language/values-and-types.mdx
  runtime/account_test.go
  runtime/common/declarationkind.go
  runtime/resourcedictionary_test.go
  runtime/runtime_test.go
  runtime/sema/check_assignment.go
  runtime/sema/check_member_expression.go
  runtime/sema/errors.go
  runtime/sema/type.go
  runtime/tests/checker/external_mutation_test.go
  runtime/tests/interpreter/resources_test.go
Labels: Breaking Change

#1399 Panic when testRuntimeInterface methods need hooks but lack them
  runtime/runtime_test.go
Labels: Testing

#1403 Add example of a script to add a key to existing account
  docs/language/accounts.mdx
Labels: Documentation

#1273 Removed PublicKey.isValid and .Validated
  .gitignore
  docs/language/crypto.mdx
  runtime/account_test.go
  runtime/cmd/parse/main_wasm.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/crypto_test.go
  runtime/interface.go
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/program_params_validation_test.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/sema/type.go
  runtime/types.go
Labels: Breaking Change, Improvement

#1250 Improve API for BLS crypto functions
  docs/language/crypto.mdx
  runtime/crypto_test.go
  runtime/interface.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/sema/type.go
  runtime/stdlib/builtin.go
  runtime/tests/checker/crypto_test.go
Labels: Improvement

#1407 Require static types for all host function values
  .github/workflows/ci.yml
  runtime/cmd/decode-state-values/main.go
  runtime/interpreter/function.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_transaction.go
  runtime/sema/meta_type.go
  runtime/sema/type.go
  runtime/sema/variable_activations.go
  runtime/tests/checker/declaration_test.go
  runtime/tests/interpreter/condition_test.go
  runtime/tests/interpreter/declaration_test.go
  runtime/tests/interpreter/import_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/metatype_test.go
  semgrep.yaml
Labels: Bugfix

#1409 Fix EOF emission in lexer
  runtime/parser2/expression_test.go
  runtime/parser2/lexer/lexer.go
  runtime/parser2/lexer/lexer_test.go
  runtime/parser2/lexer/state.go
  runtime/parser2/parser_test.go
Labels: Bugfix

#1411 Consider halting when determining definite invalidation
  runtime/sema/check_function.go
  runtime/sema/check_invocation_expression.go
  runtime/sema/resources.go
  runtime/tests/checker/resources_test.go
Labels: Bugfix

#1410 Fix acceptance of buffered errors
  runtime/parser2/parser.go
  runtime/parser2/parser_test.go
Labels: Bugfix

#1418 Updating Fungible Token video to correct source
  docs/tutorial/03-fungible-tokens.mdx
Labels: Documentation

#1413 Port v0.21 changes to master
  .github/workflows/ci.yml
  npm-packages/cadence-docgen/package.json
  npm-packages/cadence-parser/package.json
  runtime/interpreter/function.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_test.go
  runtime/interpreter/interpreter_transaction.go
  runtime/parser2/expression_test.go
  runtime/parser2/lexer/lexer.go
  runtime/parser2/lexer/lexer_test.go
  runtime/parser2/lexer/state.go
  runtime/parser2/parser.go
  runtime/parser2/parser_test.go
  runtime/sema/check_function.go
  runtime/sema/check_invocation_expression.go
  runtime/sema/meta_type.go
  runtime/sema/resources.go
  runtime/sema/type.go
  runtime/sema/variable_activations.go
  runtime/tests/checker/declaration_test.go
  runtime/tests/checker/resources_test.go
  runtime/tests/interpreter/condition_test.go
  runtime/tests/interpreter/declaration_test.go
  runtime/tests/interpreter/import_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/metatype_test.go
  semgrep.yaml
  version.go
Labels: Bugfix

#1397 Adding RLP decoding utility methods to runtime stdlib
  docs/language/built-in-functions.md
  runtime/crypto_test.go
  runtime/stdlib/builtin.go
  runtime/stdlib/rlp.go
  runtime/stdlib/rlp/rlp.go
  runtime/stdlib/rlp/rlp_test.go
  runtime/stdlib/rlp_test.go
  runtime/tests/checker/rlp_test.go
Labels: Feature

#1420 Make error reporting in contract update validation deterministic
  runtime/contract_update_validation.go
  runtime/contract_update_validation_test.go
  runtime/errors.go
Labels: Bugfix

#1416 Add tests for linking to already linked paths
  runtime/tests/interpreter/account_test.go
Labels: Testing

#1404 Storagemap backport
  runtime/cmd/decode-state-values/main.go
  runtime/contract_test.go
  runtime/interface.go
  runtime/interpreter/decode.go
  runtime/interpreter/encode.go
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/storage.go
  runtime/interpreter/storage_test.go
  runtime/interpreter/storagemap.go
  runtime/interpreter/value.go
  runtime/resourcedictionary_test.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/storage.go
  runtime/storage_test.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/metatype_test.go
Labels: Improvement

#1424 Fix definite field initialization analysis
  runtime/sema/check_assignment.go
  runtime/sema/check_return_statement.go
  runtime/sema/check_while.go
  runtime/sema/checker.go
  runtime/sema/return_info.go
  runtime/tests/checker/initialization_test.go
Labels: Bugfix

#1427 [0.21] Backport #1420
  runtime/contract_update_validation.go
  runtime/contract_update_validation_test.go
  runtime/errors.go
Labels: Bugfix

#1428 [0.22] Backport #1420
  runtime/contract_update_validation.go
  runtime/contract_update_validation_test.go
  runtime/errors.go
Labels: Bugfix

#1417 Improve BLS API
  docs/language/crypto.mdx
  runtime/crypto_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/sema/string_type.go
  runtime/sema/type.go
  runtime/stdlib/bls.go
  runtime/stdlib/builtin.go
  runtime/tests/checker/crypto_test.go
  runtime/tests/checker/rlp_test.go
Labels: Improvement

#1439 Fix comments for StorageMap ReadValue and WriteValue
  runtime/interpreter/storagemap.go
Labels: Documentation

#1440 Improve bug report issue template
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: Chore

#1421 Update atree
  go.mod
  go.sum
  runtime/storage_test.go
Labels: Bugfix, Chore

#1422 Refactor type assertions of host function arguments
  runtime/compiler/codegen_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/runtime.go
Labels: Improvement

#1352 trying to add indexOf to array
  docs/language/values-and-types.mdx
  runtime/interpreter/value.go
  runtime/sema/type.go
  runtime/tests/checker/arrays_dictionaries_test.go
  runtime/tests/interpreter/interpreter_test.go
  semantics/fpl.k
Labels: Feature

#1445 Catch potential panics produced by resource owner changed callback
  runtime/runtime.go
Labels: Bugfix

#1412 Marketplace tutorial improvements
  docs/tutorial/05-marketplace-setup.mdx
  docs/tutorial/06-marketplace-compose.mdx
Labels: Documentation, Dev Portal Documentation, T-Documentation 📃, SC-Eng
