Repository onflow/cadence, pull requests merged in 2022-07, with the labels that each got.

#1783 Fail invalidated-resource use with a proper error
  runtime/interpreter/value.go
  runtime/tests/interpreter/resources_test.go
Labels: Bugfix

#1782 Collape benchstat results
  .github/workflows/benchmark.yml
Labels: Chore

#1718 Separate user errors from internal errors
  encoding/json/decode.go
  go.cap
  runtime/common/addresslocation.go
  runtime/common/identifierlocation.go
  runtime/common/location.go
  runtime/common/metering.go
  runtime/common/repllocation.go
  runtime/common/scriptlocation.go
  runtime/common/stringlocation.go
  runtime/common/transactionlocation.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/errors.go
  runtime/errors/errors.go
  runtime/interpreter/conversion.go
  runtime/interpreter/decode.go
  runtime/interpreter/encode.go
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_statement.go
  runtime/interpreter/storage.go
  runtime/interpreter/storagemap.go
  runtime/interpreter/value.go
  runtime/parser/errors.go
  runtime/parser/expression.go
  runtime/parser/expression_test.go
  runtime/parser/lexer/lexer.go
  runtime/parser/parser.go
  runtime/parser/parser_test.go
  runtime/parser/statement.go
  runtime/runtime.go
  runtime/runtime_memory_metering_test.go
  runtime/runtime_test.go
  runtime/sema/errors.go
  runtime/sema/type.go
  runtime/sema/type_tags.go
  runtime/sema/type_test.go
  runtime/stdlib/flow.go
  runtime/stdlib/functions.go
  runtime/stdlib/panic.go
  runtime/stdlib/rlp.go
  runtime/storage.go
  runtime/tests/errors_test.go
  values.go
Labels: Improvement, Technical Debt

#1746 Refactor parser errors
  runtime/literal.go
  runtime/parser/comment.go
  runtime/parser/declaration.go
  runtime/parser/declaration_test.go
  runtime/parser/errors.go
  runtime/parser/expression.go
  runtime/parser/function.go
  runtime/parser/parser.go
  runtime/parser/statement.go
  runtime/parser/transaction.go
  runtime/parser/type.go
Labels: Improvement, Technical Debt

#1788 Language server should no longer depend on Flow CLI
  languageserver/go.mod
  languageserver/go.sum
Labels: dependencies

#1776 update the docs for design pattern
  docs/msg-sender.mdx
Labels: Documentation

#1794 Panic on duplicate key for resource-typed dictionary literal
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Bugfix

#1793 [0.24] Panic on duplicate key for resource-typed dictionary literal
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Bugfix

#1791 [0.24] Fix json encoding for builtin composite types
  encoding/json/encode.go
  encoding/json/encoding_test.go
  runtime/convertValues_test.go
Labels: Bugfix

#1764 Refactor parser to always return syntax errors
  runtime/parser/declaration.go
  runtime/parser/declaration_test.go
  runtime/parser/expression.go
  runtime/parser/function.go
  runtime/parser/parser.go
  runtime/parser/parser_test.go
  runtime/parser/statement.go
  runtime/parser/transaction.go
  runtime/parser/type.go
Labels: Technical Debt

#1785 Fix documentation, add linter
  .github/workflows/ci.yml
  docs/anti-patterns.mdx
  docs/contract-upgrades.mdx
  docs/design-patterns.mdx
  docs/index.mdx
  docs/language/access-control.md
  docs/language/accounts.mdx
  docs/language/composite-types.mdx
  docs/language/contract-updatability.md
  docs/language/contracts.md
  docs/language/control-flow.md
  docs/language/core-events.md
  docs/language/functions.mdx
  docs/language/glossary.md
  docs/language/imports.mdx
  docs/language/operators.md
  docs/language/resources.mdx
  docs/language/values-and-types.mdx
  docs/lint.js
  docs/measuring-time.mdx
  docs/msg-sender.mdx
  docs/package-lock.json
  docs/package.json
  docs/tutorial/01-first-steps.mdx
  docs/tutorial/02-hello-world.mdx
  docs/tutorial/03-resources.mdx
  docs/tutorial/04-capabilities.mdx
  docs/tutorial/05-non-fungible-tokens-1.mdx
  docs/tutorial/05-non-fungible-tokens-2.mdx
  docs/tutorial/06-fungible-tokens.mdx
  docs/tutorial/07-marketplace-setup.mdx
  docs/tutorial/08-marketplace-compose.mdx
  docs/tutorial/09-voting.mdx
  docs/tutorial/10-resources-compose.mdx
Labels: Documentation

#1801 Update language server to use new linter for hints
  languageserver/Makefile
  languageserver/go.mod
  languageserver/go.sum
  languageserver/integration/contracts.go
  languageserver/integration/diagnostics.go
  languageserver/integration/entrypoint.go
  languageserver/server/linting_test.go
  languageserver/server/server.go
Labels: Improvement

#1804 Use generics for ordered map, lazily allocate inner map and list
  go.mod
  go.sum
  runtime/common/deps/gen.go
  runtime/common/deps/node_test.go
  runtime/common/deps/orderedmap.go
  runtime/common/deps/set.go
  runtime/common/orderedmap/orderedmap.go
  runtime/common/orderedmap/orderedmap_string_interface.go
  runtime/common/orderedmap/orderedmap_string_string.go
  runtime/common/orderedmap/orderedmap_string_struct.go
  runtime/common/orderedmap/orderedmap_test.go
  runtime/common/orderedmap/string_fruit_orderedmap_test.go
  runtime/convertTypes_test.go
  runtime/convertValues_test.go
  runtime/interpreter/value_test.go
  runtime/sema/authaccount_type.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_event_declaration_test.go
  runtime/sema/check_expression.go
  runtime/sema/check_import_declaration.go
  runtime/sema/check_interface_declaration.go
  runtime/sema/check_invocation_expression.go
  runtime/sema/check_member_expression.go
  runtime/sema/check_transaction_declaration.go
  runtime/sema/check_while.go
  runtime/sema/checker.go
  runtime/sema/elaboration.go
  runtime/sema/gen.go
  runtime/sema/import.go
  runtime/sema/initialization_info.go
  runtime/sema/interfaceset.go
  runtime/sema/member_set.go
  runtime/sema/orderdmaps.go
  runtime/sema/ordered_map_interface_resourceinfo.go
  runtime/sema/ordered_map_interfacetype_struct.go
  runtime/sema/ordered_map_member_fielddeclaration.go
  runtime/sema/ordered_map_member_struct.go
  runtime/sema/ordered_map_position_resourceuse.go
  runtime/sema/ordered_map_resourceinvalidation_struct.go
  runtime/sema/ordered_map_string_importelement.go
  runtime/sema/ordered_map_string_member.go
  runtime/sema/ordered_map_string_type.go
  runtime/sema/ordered_map_string_valuedeclaration.go
  runtime/sema/ordered_map_string_variable.go
  runtime/sema/ordered_map_typeparameter_type.go
  runtime/sema/publicaccount_type.go
  runtime/sema/resource_invalidations.go
  runtime/sema/resource_uses.go
  runtime/sema/resources.go
  runtime/sema/resources_test.go
  runtime/sema/type.go
  runtime/sema/type_test.go
  runtime/sema/variable_activations.go
  runtime/stdlib/flow.go
  runtime/tests/checker/import_test.go
  runtime/tests/interpreter/composite_value_test.go
  runtime/tests/interpreter/import_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/values_test.go
Labels: Improvement

#1807 Don't copy code string if there's no error
  runtime/context.go
  runtime/errors.go
  runtime/runtime.go
Labels: Improvement

#1808 Switch to generic list
  check-headers.sh
  runtime/common/list/list.go
  runtime/common/orderedmap/orderedmap.go
Labels: Improvement

#1820 Update 05-non-fungible-tokens-2.mdx
  docs/tutorial/05-non-fungible-tokens-2.mdx
Labels: Documentation

#1739 [LS] Use a hosted emulator from flowkit
  languageserver/integration/codelenses.go
  languageserver/integration/commands.go
  languageserver/integration/config.go
  languageserver/integration/initialization.go
  languageserver/integration/integration.go
  languageserver/test/flow.json
  languageserver/test/index.test.ts
  languageserver/test/script.cdc
Labels: Improvement, Language Server, Developer Tool Team

#1810 Fix typo in how to run docgen tool
  tools/docgen/README.md
Labels: Documentation, Bugfix

#1679 Expose runtime storage
  Makefile
  runtime/interpreter/storage_test.go
  runtime/interpreter/storagemap.go
  runtime/runtime.go
  runtime/storage_test.go
Labels: Feature

#1797 refactor ExecuteTransaction body into Executor object
  runtime/runtime.go
  runtime/transaction_executor.go
Labels: Improvement

#1800 refactor ExecuteScript body into Executor object
  runtime/runtime.go
  runtime/script_executor.go
Labels: Improvement

#1833 Refactor intervalst to be generic
  runtime/common/intervalst/intervalst.go
  runtime/common/intervalst/intervalst_test.go
  runtime/common/intervalst/node.go
  runtime/sema/function_invocations.go
  runtime/sema/member_accesses.go
  runtime/sema/occurrences.go
  runtime/sema/ranges.go
Labels: Improvement

#1824 Switch to OpenTelemetry tracing library
  go.cap
  go.mod
  go.sum
  runtime/interface.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_tracing.go
  runtime/interpreter/interpreter_tracing_test.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Breaking Change, Improvement, Performance

#1834 Fix typos and broken links on docs
  docs/anti-patterns.mdx
  docs/design-patterns.mdx
  docs/language/transactions.md
  docs/tutorial/02-hello-world.mdx
  docs/tutorial/04-capabilities.mdx
  docs/tutorial/05-non-fungible-tokens-2.mdx
  docs/tutorial/06-fungible-tokens.mdx
  docs/tutorial/08-marketplace-compose.mdx
  docs/tutorial/09-voting.mdx
Labels: Documentation, Improvement, Feedback, T-Documentation 📃, SC-Eng

#1841 Fix tutorial numerations
  docs/tutorial/07-marketplace-setup.mdx
  docs/tutorial/08-marketplace-compose.mdx
  docs/tutorial/09-voting.mdx
  docs/tutorial/10-resources-compose.mdx
Labels: Documentation, Improvement, T-Documentation 📃, SC-Eng

#1837 Revert argument labels fix
  runtime/sema/check_composite_declaration.go
  runtime/tests/checker/invocation_test.go
Labels: Chore

#1836 Revert reference improvements
  runtime/ast/expression.go
  runtime/ast/expression_test.go
  runtime/parser/expression.go
  runtime/parser/expression_test.go
  runtime/parser/statement_test.go
  runtime/sema/check_array_expression.go
  runtime/sema/check_dictionary_expression.go
  runtime/sema/check_reference_expression.go
  runtime/tests/checker/casting_test.go
  runtime/tests/checker/reference_test.go
Labels: Chore

#1842 Remove deprecated key management API
  docs/language/accounts.mdx
  runtime/account_test.go
  runtime/interpreter/account.go
  runtime/runtime.go
  runtime/sema/authaccount_type.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Breaking Change

#1811 Change Runtime.InvokeContractFunction signature
  runtime/contract_function_executor.go
  runtime/runtime.go
  runtime/runtime_test.go
Labels: Improvement

#1830 Robert/custom codec
  encoding/custom/sema_codec/codec_test.go
  encoding/custom/sema_codec/decode.go
  encoding/custom/sema_codec/encode.go
  runtime/sema/authaccount_contracts.go
  runtime/sema/authaccount_type.go
  runtime/sema/crypto_algorithm_types.go
  runtime/sema/public_account_contracts.go
  runtime/sema/publicaccount_type.go
  runtime/sema/simple_type.go
  runtime/sema/type.go
Labels: Feature
