Repository onflow/cadence, pull requests merged in 2022-12, with the labels that each got.

#2082 Type Checking for Attachment Declarations
  runtime/ast/memberindices.go
  runtime/ast/members.go
  runtime/ast/program.go
  runtime/ast/programindices.go
  runtime/ast/programindices_test.go
  runtime/ast/visitor.go
  runtime/common/compositekind.go
  runtime/common/compositekind_string.go
  runtime/common/declarationkind.go
  runtime/common/declarationkind_string.go
  runtime/compiler/compiler.go
  runtime/interpreter/interpreter.go
  runtime/parser/declaration_test.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_interface_declaration.go
  runtime/sema/checker.go
  runtime/sema/elaboration.go
  runtime/sema/errors.go
  runtime/sema/simple_type.go
  runtime/sema/type.go
  runtime/sema/typeannotationstate.go
  runtime/sema/typeannotationstate_string.go
  runtime/tests/checker/access_test.go
  runtime/tests/checker/attachments_test.go
  runtime/tests/checker/composite_test.go
  runtime/tests/checker/contract_test.go
  runtime/tests/checker/declaration_test.go
  runtime/tests/checker/enum_test.go
  runtime/tests/checker/events_test.go
  runtime/tests/checker/interface_test.go
  runtime/tests/checker/nesting_test.go
  runtime/tests/checker/operations_test.go
  runtime/tests/checker/optional_test.go
  runtime/tests/checker/overloading_test.go
  runtime/tests/checker/resources_test.go
  runtime/tests/checker/storable_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Feature

#2172 improve ConformanceError error message
  runtime/sema/errors.go
  runtime/tests/checker/conformance_test.go
Labels: Improvement

#2173 Suggest lexically closest member in cases of NotDeclaredMemberError
  go.cap
  go.mod
  go.sum
  runtime/sema/check_member_expression.go
  runtime/sema/config.go
  runtime/sema/errors.go
  runtime/tests/checker/member_test.go
Labels: Improvement

#2178 Optimize elaboration
  runtime/compiler/compiler.go
  runtime/convertValues_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_import.go
  runtime/interpreter/interpreter_statement.go
  runtime/interpreter/interpreter_transaction.go
  runtime/interpreter/storage_test.go
  runtime/interpreter/value_test.go
  runtime/repl.go
  runtime/sema/check_array_expression.go
  runtime/sema/check_assignment.go
  runtime/sema/check_binary_expression.go
  runtime/sema/check_casting_expression.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_dictionary_expression.go
  runtime/sema/check_emit_statement.go
  runtime/sema/check_expression.go
  runtime/sema/check_force_expression.go
  runtime/sema/check_function.go
  runtime/sema/check_import_declaration.go
  runtime/sema/check_interface_declaration.go
  runtime/sema/check_invocation_expression.go
  runtime/sema/check_member_expression.go
  runtime/sema/check_reference_expression.go
  runtime/sema/check_return_statement.go
  runtime/sema/check_swap.go
  runtime/sema/check_transaction_declaration.go
  runtime/sema/check_variable_declaration.go
  runtime/sema/checker.go
  runtime/sema/elaboration.go
  runtime/sema/entrypoint.go
  runtime/sema/import.go
  runtime/sema/type.go
  runtime/stdlib/account.go
  runtime/stdlib/crypto.go
  runtime/stdlib/test.go
  runtime/tests/checker/casting_test.go
  runtime/tests/checker/conditions_test.go
  runtime/tests/checker/dynamic_casting_test.go
  runtime/tests/checker/genericfunction_test.go
  runtime/tests/checker/range_test.go
  runtime/tests/checker/utils.go
  runtime/tests/interpreter/composite_value_test.go
  runtime/tests/interpreter/import_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/values_test.go
  tools/analysis/analysis_test.go
Labels: Performance

#2164 fix view parsing for expressions
  runtime/parser/expression.go
  runtime/parser/expression_test.go
Labels: Bugfix

#2183 Initialize the Crypto contract lazily
  runtime/cmd/cmd.go
  runtime/environment.go
  runtime/runtime_test.go
  runtime/stdlib/crypto.go
  runtime/stdlib/crypto_test.go
  runtime/stdlib/test.go
  tools/analysis/programs.go
Labels: Improvement, Performance

#2185 Pretty print interpreter errors
  runtime/error_test.go
  runtime/interpreter/errors.go
  runtime/interpreter/errors_test.go
Labels: Improvement

#2099 Type Checking for attachment uses
  docs/json-cadence-spec.md
  encoding/json/decode.go
  encoding/json/encode.go
  encoding/json/encoding_test.go
  runtime/ast/attachment.go
  runtime/ast/attachment_test.go
  runtime/ast/expression_extractor.go
  runtime/ast/visitor.go
  runtime/common/compositekind.go
  runtime/compiler/compiler.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_statement.go
  runtime/parser/expression.go
  runtime/parser/expression_test.go
  runtime/sema/anyattachment_types.go
  runtime/sema/check_assignment.go
  runtime/sema/check_attach_expression.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_expression.go
  runtime/sema/check_invocation_expression.go
  runtime/sema/check_remove_statement.go
  runtime/sema/errors.go
  runtime/sema/type.go
  runtime/sema/type_tags.go
  runtime/tests/checker/attachments_test.go
  runtime/tests/checker/composite_test.go
  runtime/tests/checker/operations_test.go
  runtime/tests/checker/reference_test.go
  runtime/tests/checker/resources_test.go
  types.go
Labels: Feature

#2191 Avoid unnecessary slice allocations
  runtime/interpreter/conversion.go
  runtime/interpreter/conversion_test.go
  runtime/interpreter/decode.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_invocation.go
  runtime/interpreter/statictype.go
  runtime/sema/check_array_expression.go
  runtime/sema/check_dictionary_expression.go
  runtime/sema/check_invocation_expression.go
  runtime/sema/check_transaction_declaration.go
  runtime/sema/checker.go
  runtime/sema/type.go
Labels: Performance

#2113 Interpreting for basic attachment operations
  runtime/attachments_test.go
  runtime/contract_function_executor.go
  runtime/interpreter/config.go
  runtime/interpreter/errors.go
  runtime/interpreter/function.go
  runtime/interpreter/function_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_invocation.go
  runtime/interpreter/interpreter_statement.go
  runtime/interpreter/invocation.go
  runtime/interpreter/sharedstate.go
  runtime/interpreter/simplecompositevalue.go
  runtime/interpreter/value.go
  runtime/interpreter/value_accountreference.go
  runtime/sema/accesscheckmode.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_expression.go
  runtime/sema/check_import_declaration.go
  runtime/sema/check_member_expression.go
  runtime/sema/check_remove_statement.go
  runtime/sema/checker.go
  runtime/sema/elaboration.go
  runtime/stdlib/account.go
  runtime/tests/interpreter/attachments_test.go
Labels: Feature

#2140 Implement FLIP #43 (fn type syntax change)
  docs/cadence.ebnf
  docs/json-cadence-spec.md
  docs/language/accounts.mdx
  docs/language/composite-types.mdx
  docs/language/functions.mdx
  docs/language/resources.mdx
  docs/language/type-inference.md
  docs/language/values-and-types.mdx
  docs/testing-framework.mdx
  encoding/json/encoding_test.go
  go.mod
  go.sum
  runtime/ast/type.go
  runtime/ast/type_test.go
  runtime/contract_update_validation_test.go
  runtime/convertValues_test.go
  runtime/parser/expression.go
  runtime/parser/expression_test.go
  runtime/parser/type.go
  runtime/parser/type_test.go
  runtime/program_params_validation_test.go
  runtime/runtime_test.go
  runtime/sema/authaccount_type.go
  runtime/sema/checker_test.go
  runtime/sema/type.go
  runtime/sema/type_test.go
  runtime/stdlib/account.go
  runtime/stdlib/contracts/test.cdc
  runtime/stdlib/test.go
  runtime/tests/checker/account_test.go
  runtime/tests/checker/casting_test.go
  runtime/tests/checker/composite_test.go
  runtime/tests/checker/function_test.go
  runtime/tests/checker/interface_test.go
  runtime/tests/checker/member_test.go
  runtime/tests/checker/purity_test.go
  runtime/tests/checker/range_test.go
  runtime/tests/checker/resources_test.go
  runtime/tests/checker/transactions_test.go
  runtime/tests/interpreter/container_mutation_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/equality_test.go
  runtime/tests/interpreter/for_test.go
  runtime/tests/interpreter/import_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/reference_test.go
  runtime/tests/interpreter/runtimetype_test.go
Labels: Breaking Change, Improvement

#2198 Add update tool
  tools/update/.eslintrc.cjs
  tools/update/README.md
  tools/update/config.schema.json
  tools/update/config.schema.ts
  tools/update/config.yaml
  tools/update/main.ts
  tools/update/package-lock.json
  tools/update/package.json
  tools/update/tsconfig.json
Labels: Chore

#2190 Adds some suggestions/improvements to sema error messages
  runtime/sema/errors.go
Labels: Improvement

#2195 Add test case for publishing and claiming private account capability
  runtime/account_test.go
Labels: Testing

#2202 Skip broken values during storage iteration
  docs/language/accounts.mdx
  runtime/interpreter/interpreter.go
  runtime/runtime.go
  runtime/storage_test.go
Labels: Improvement
