Repository onflow/cadence, pull requests merged in 2022-01, with the labels that each got.

#1319 Support recursive supertype inferring for containers
  runtime/convertValues_test.go
  runtime/sema/type_tags.go
  runtime/sema/type_test.go
  runtime/tests/checker/type_inference_test.go
Labels: Improvement

#1331 Add safety checks for go casts in the interpreter
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_statement.go
  runtime/interpreter/value.go
Labels: Improvement

#1332 Fix resource loss analysis and definite initialization analysis
  runtime/sema/check_assignment.go
  runtime/sema/check_block.go
  runtime/sema/check_function.go
  runtime/sema/check_return_statement.go
  runtime/sema/check_switch.go
  runtime/sema/check_while.go
  runtime/sema/checker.go
  runtime/sema/resources.go
  runtime/sema/return_info.go
  runtime/tests/checker/initialization_test.go
  runtime/tests/checker/resources_test.go
  runtime/tests/checker/switch_test.go
  runtime/tests/checker/while_test.go
Labels: Bugfix

#1333 Fix and simplify parser buffering
  runtime/parser2/lexer/lexer.go
  runtime/parser2/lexer/lexer_test.go
  runtime/parser2/lexer/token.go
  runtime/parser2/lexer/tokenstream.go
  runtime/parser2/parser.go
  runtime/parser2/parser_test.go
Labels: Bugfix

#1334 Fix type requirement checking
  runtime/sema/check_composite_declaration.go
  runtime/tests/checker/conformance_test.go
Labels: Bugfix

#1335 Fix IsContainerType for CompositeType and InterfaceType
  runtime/cmd/parse/main.go
  runtime/sema/checker.go
  runtime/sema/simple_type.go
  runtime/sema/type.go
  runtime/tests/checker/nesting_test.go
Labels: Bugfix

#1336 Fix checking of `create before(...)` in post condition
  runtime/ast/expression_extractor.go
  runtime/tests/checker/conditions_test.go
Labels: Bugfix

#1337 [v0.20] Fix and simplify parser buffering
  runtime/parser2/lexer/lexer.go
  runtime/parser2/lexer/lexer_test.go
  runtime/parser2/lexer/token.go
  runtime/parser2/lexer/tokenstream.go
  runtime/parser2/parser.go
  runtime/parser2/parser_test.go
Labels: Bugfix

#1340 [v0.20] Fix checking of `create before(...)` in post condition
  runtime/ast/expression_extractor.go
  runtime/tests/checker/conditions_test.go
Labels: Bugfix

#1342 [v0.20] Gracefully handle mismatching types during binary operations
  runtime/interpreter/errors.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/arithmetic_test.go
Labels: Bugfix

#1341 [v0.20] Gracefully handle casts during comparison operators
  runtime/interpreter/value.go
  runtime/tests/interpreter/equality_test.go
Labels: Bugfix

#1315 Add array slice function
  docs/language/values-and-types.mdx
  go.mod
  go.sum
  runtime/interpreter/errors.go
  runtime/interpreter/value.go
  runtime/sema/string_type.go
  runtime/sema/type.go
  runtime/tests/checker/arrays_dictionaries_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Feature

#1346 Move resource owner section to resources page
  docs/language/composite-types.mdx
  docs/language/resources.mdx
Labels: Documentation

#1345 Ignore dead code
  runtime/sema/check_block.go
  runtime/sema/function_activations.go
  runtime/tests/checker/switch_test.go
Labels: Improvement

#1344 Fix references to resource-kinded values
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/value.go
  runtime/storage_test.go
Labels: Bugfix

#1350 Fixes glossary page
  docs/language/glossary.md
Labels: Documentation

#1349 Always check address overflow
  runtime/cmd/decode-state-values/main.go
  runtime/common/address.go
  runtime/common/address_test.go
  runtime/common/addresslocation.go
  runtime/common/addresslocation_test.go
  runtime/contract_test.go
  runtime/contract_update_validation_test.go
  runtime/error_test.go
  runtime/ft_test.go
  runtime/interpreter/decode.go
  runtime/interpreter/encoding_benchmark_test.go
  runtime/interpreter/encoding_test.go
  runtime/parser2/declaration.go
  runtime/parser2/declaration_test.go
  runtime/predeclaredvalues_test.go
  runtime/resourcedictionary_test.go
  runtime/runtime_test.go
  runtime/sema/errors.go
  runtime/storage_test.go
  runtime/tests/checker/access_test.go
  runtime/tests/checker/import_test.go
  runtime/tests/checker/integer_test.go
  runtime/tests/checker/nft_test.go
  runtime/tests/checker/predeclaredvalues_test.go
  runtime/tests/interpreter/equality_test.go
  runtime/tests/interpreter/import_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/metatype_test.go
  runtime/tests/interpreter/values_test.go
  runtime/type_test.go
Labels: Bugfix

#1348 Fix parsing of 0_ integer literals
  runtime/parser2/expression_test.go
  runtime/parser2/lexer/lexer_test.go
  runtime/parser2/lexer/state.go
  runtime/parser2/type_test.go
Labels: Bugfix

#1359 fix: links in callouts, linting
  docs/tutorial/03-fungible-tokens.mdx
  docs/tutorial/04-non-fungible-tokens.mdx
Labels: Documentation

#1327 add Keccak256 hash to cadence
  docs/language/crypto.mdx
  runtime/convertValues_test.go
  runtime/resourcedictionary_test.go
  runtime/sema/crypto_algorithm_types.go
  runtime/sema/hashalgorithm_string.go
  runtime/types.go
Labels: Feature

#1361 Update to Go 1.16
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/compat.yaml
  .github/workflows/sync-flow-go.yml
  compat/setup.md
  go.mod
  runtime/convertValues_test.go
  runtime/stdlib/contracts/crypto.go
  runtime/stdlib/crypto.go
  runtime/stdlib/internal/contracts.gen.go
  runtime/test-export-json-deterministic.txt
  tools/maprangecheck/go.mod
  tools/maprangecheck/go.sum
Labels: Chore

#1362 Gracefully handle cadence crashes/panics
  runtime/runtime.go
  runtime/runtime_test.go
Labels: Improvement

#1343 Add safety checks for go casts in the parser
  runtime/parser2/expression.go
  runtime/parser2/function.go
  runtime/parser2/parser.go
Labels: Improvement

#1365 Update 02-hello-world.mdx
  docs/tutorial/02-hello-world.mdx
Labels: Documentation

#1372 fix bad links in doc
  docs/anti-patterns.mdx
  docs/language/accounts.mdx
  docs/language/built-in-functions.md
  docs/language/composite-types.mdx
  docs/language/constants-and-variables.md
  docs/language/contract-updatability.md
  docs/language/contracts.md
  docs/language/events.md
  docs/language/functions.mdx
  docs/language/interfaces.mdx
  docs/language/references.md
  docs/language/resources.mdx
  docs/language/restricted-types.md
  docs/language/transactions.md
  docs/language/type-annotations.md
  docs/language/values-and-types.mdx
  docs/msg-sender.mdx
Labels: Documentation

#1303 Taking a reference to an optional value now produces an optionally-typed reference
  runtime/interpreter/interpreter_expression.go
  runtime/missingmember_test.go
  runtime/nft_test.go
  runtime/sema/check_reference_expression.go
  runtime/sema/elaboration.go
  runtime/sema/errors.go
  runtime/tests/checker/nft_test.go
  runtime/tests/checker/reference_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Breaking Change

#1376 Backport #1327 to `v0.21` branch
  docs/language/crypto.mdx
  runtime/convertValues_test.go
  runtime/resourcedictionary_test.go
  runtime/sema/crypto_algorithm_types.go
  runtime/sema/hashalgorithm_string.go
  runtime/types.go
Labels: Feature

#1383 Backport #1320 to v0.21
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/value.go
  runtime/storage_test.go
Labels: Bugfix

#1381 Backport #1332 to v0.21
  runtime/sema/check_assignment.go
  runtime/sema/check_block.go
  runtime/sema/check_function.go
  runtime/sema/check_return_statement.go
  runtime/sema/check_switch.go
  runtime/sema/check_while.go
  runtime/sema/checker.go
  runtime/sema/resources.go
  runtime/sema/return_info.go
  runtime/tests/checker/initialization_test.go
  runtime/tests/checker/resources_test.go
  runtime/tests/checker/switch_test.go
  runtime/tests/checker/while_test.go
Labels: Bugfix

#1385 Backport #1208 to v0.21
  runtime/interpreter/value.go
  runtime/tests/interpreter/integers_test.go
Labels: Bugfix

#1384 Backport #1349 to v0.21
  runtime/cmd/decode-state-values/main.go
  runtime/common/address.go
  runtime/common/address_test.go
  runtime/common/addresslocation.go
  runtime/common/addresslocation_test.go
  runtime/contract_test.go
  runtime/contract_update_validation_test.go
  runtime/error_test.go
  runtime/ft_test.go
  runtime/interpreter/decode.go
  runtime/interpreter/encoding_benchmark_test.go
  runtime/interpreter/encoding_test.go
  runtime/parser2/declaration.go
  runtime/parser2/declaration_test.go
  runtime/predeclaredvalues_test.go
  runtime/resourcedictionary_test.go
  runtime/runtime_test.go
  runtime/sema/errors.go
  runtime/storage_test.go
  runtime/tests/checker/access_test.go
  runtime/tests/checker/import_test.go
  runtime/tests/checker/integer_test.go
  runtime/tests/checker/nft_test.go
  runtime/tests/checker/predeclaredvalues_test.go
  runtime/tests/interpreter/equality_test.go
  runtime/tests/interpreter/import_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/metatype_test.go
  runtime/type_test.go
Labels: Bugfix

#1357 Update 02-hello-world.mdx
  docs/tutorial/02-hello-world.mdx
Labels: Documentation

#1387 update tutorial links for new playground format
  docs/tutorial/03-fungible-tokens.mdx
  docs/tutorial/05-marketplace-setup.mdx
  docs/tutorial/06-marketplace-compose.mdx
  docs/tutorial/07-resources-compose.mdx
  docs/tutorial/08-voting.mdx
Labels: Documentation, T-Documentation 📃

#1368 Object player/1358 fix broken links in cadence document
  CHANGELOG.md
  encoding/README.md
Labels: Documentation

#1370 Update uniseg to latest commit
  go.mod
  go.sum
Labels: Bugfix

#1390 [docs] update resource name
  docs/language/values-and-types.mdx
Labels: Documentation

#1391 Change WriteValue and SetValue to take an atree.Value input
  runtime/interpreter/storagemap.go
Labels: Improvement
