Repository onflow/cadence, pull requests merged in 2022-10, with the labels that each got.

#2004 Make Void values constructible
  runtime/ast/elementtype.go
  runtime/ast/elementtype_string.go
  runtime/ast/expression.go
  runtime/ast/expression_extractor.go
  runtime/ast/visitor.go
  runtime/compiler/compiler.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/value_test.go
  runtime/parser/expression.go
  runtime/parser/expression_test.go
  runtime/sema/check_expression.go
  runtime/sema/void_type.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Feature, Improvement

#2022 Fix accounts not being returnable from scripts
  runtime/account_test.go
  runtime/sema/authaccount_type.go
  runtime/sema/publicaccount_type.go
Labels: Bugfix

#2020 Update 06-fungible-tokens.mdx
  docs/tutorial/06-fungible-tokens.mdx
Labels: Documentation

#1982 Add fromString method on numeric types
  runtime/interpreter/interpreter.go
  runtime/sema/type.go
  runtime/tests/interpreter/fixedpoint_test.go
  runtime/tests/interpreter/integers_test.go
Labels: Feature

#2025 Fix composite types documentation
  docs/language/composite-types.mdx
  docs/language/resources.mdx
Labels: Documentation

#2029 Introduce and use singleton for Void value
  runtime/cmd/execute/colors.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/interpreter/decode.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_statement.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/stdlib/account.go
  runtime/stdlib/assert.go
  runtime/stdlib/log.go
  runtime/stdlib/test.go
  runtime/tests/interpreter/condition_test.go
  runtime/tests/interpreter/container_mutation_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/values_test.go
Labels: Performance

#2030 Introduce and use singletons for bool values
  runtime/convertValues.go
  runtime/imported_values_memory_metering_test.go
  runtime/interpreter/decode.go
  runtime/interpreter/function_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/tests/interpreter/capability_test.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Performance

#2031 Introduce and use singleton value for nil
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/environment.go
  runtime/interpreter/decode.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_test.go
  runtime/interpreter/interpreter_tracing_test.go
  runtime/interpreter/storage_test.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/stdlib/account.go
  runtime/stdlib/block.go
  runtime/stdlib/test.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/capability_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/if_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/path_test.go
  runtime/tests/interpreter/reference_test.go
  runtime/tests/interpreter/runtimetype_test.go
  runtime/tests/interpreter/string_test.go
  runtime/tests/interpreter/switch_test.go
  runtime/tests/interpreter/values_test.go
Labels: Performance

#2033 Improve resource tracking
  runtime/common/deps/set.go
  runtime/common/orderedmap/orderedmap.go
  runtime/common/persistent/orderedset.go
  runtime/common/persistent/orderedset_test.go
  runtime/sema/check_assignment.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_conditional.go
  runtime/sema/check_destroy_expression.go
  runtime/sema/check_expression.go
  runtime/sema/check_for.go
  runtime/sema/check_function.go
  runtime/sema/check_invocation_expression.go
  runtime/sema/check_member_expression.go
  runtime/sema/check_return_statement.go
  runtime/sema/check_switch.go
  runtime/sema/check_while.go
  runtime/sema/checker.go
  runtime/sema/errors.go
  runtime/sema/function_activations.go
  runtime/sema/initialization_info.go
  runtime/sema/interfaceset.go
  runtime/sema/member_set.go
  runtime/sema/member_set_test.go
  runtime/sema/resource_invalidations.go
  runtime/sema/resource_invalidations_test.go
  runtime/sema/resource_uses.go
  runtime/sema/resource_uses_test.go
  runtime/sema/resourceinfo.go
  runtime/sema/resourceinvalidationkind.go
  runtime/sema/resourceinvalidationkind_string.go
  runtime/sema/resources.go
  runtime/sema/resources_test.go
  runtime/sema/return_info.go
  runtime/sema/type.go
  runtime/tests/checker/arrays_dictionaries_test.go
  runtime/tests/checker/resources_test.go
  runtime/tests/checker/return_test.go
  runtime/tests/checker/utils.go
  runtime/tests/interpreter/resources_test.go
Labels: Improvement

#2028 Catch interpreter panics in REPL
  runtime/repl.go
Labels: Bugfix, Improvement

#2021 Improve REPL
  runtime/cmd/execute/repl.go
  runtime/repl.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_for.go
  runtime/sema/check_interface_declaration.go
  runtime/sema/check_variable_declaration.go
  runtime/sema/variable_activations.go
Labels: Improvement

#1983 Publish and Claim: Inbox API for Capability Bootstrapping
  docs/language/accounts.mdx
  docs/language/core-events.md
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/inbox_test.go
  runtime/interpreter/account.go
  runtime/interpreter/accountcontracts.go
  runtime/interpreter/accountinbox.go
  runtime/interpreter/accountkeys.go
  runtime/interpreter/decode.go
  runtime/interpreter/encode.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/primitivestatictype.go
  runtime/interpreter/primitivestatictype_string.go
  runtime/interpreter/statictype_test.go
  runtime/interpreter/value.go
  runtime/interpreter/visitor.go
  runtime/sema/authaccount_type.go
  runtime/stdlib/account.go
  runtime/stdlib/flow.go
  runtime/tests/checker/account_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Feature

#2035 Update design pattern documentation to refer to the new Capability Bootstrapping API
  docs/design-patterns.mdx
  docs/msg-sender.mdx
  runtime/tests/checker/account_test.go
Labels: Documentation

#2044 Improve resource tracking for optional binding
  runtime/sema/check_casting_expression.go
  runtime/sema/check_conditional.go
  runtime/sema/check_variable_declaration.go
  runtime/tests/checker/resources_test.go
Labels: Bugfix, Breaking Change

#2047 Fixes dead link in unsaferandom documentation
  docs/language/built-in-functions.mdx
Labels: Documentation

#2053 Fix account inbox implementation
  runtime/common/metering.go
  runtime/convertValues.go
  runtime/interpreter/account.go
  runtime/interpreter/accountinbox.go
  runtime/interpreter/primitivestatictype.go
  runtime/interpreter/primitivestatictype_string.go
  runtime/interpreter/primitivestatictype_test.go
  runtime/interpreter/statictype_test.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Bugfix

#2042 Directly transfer published values
  runtime/interpreter/value.go
  runtime/stdlib/account.go
Labels: Improvement

#2067 Prevent keywords from being used as names in function declarations
  runtime/parser/statement.go
  runtime/parser/statement_test.go
Labels: Bugfix, Improvement

#2065 Make the interpreter globals map allocation lazy
  runtime/environment.go
  runtime/interpreter/globalvariables.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_import.go
  runtime/tests/interpreter/arithmetic_test.go
  runtime/tests/interpreter/bitwise_test.go
  runtime/tests/interpreter/builtinfunctions_test.go
  runtime/tests/interpreter/composite_value_test.go
  runtime/tests/interpreter/container_mutation_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/enum_test.go
  runtime/tests/interpreter/equality_test.go
  runtime/tests/interpreter/fixedpoint_test.go
  runtime/tests/interpreter/if_test.go
  runtime/tests/interpreter/import_test.go
  runtime/tests/interpreter/integers_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/metatype_test.go
  runtime/tests/interpreter/path_test.go
  runtime/tests/interpreter/reference_test.go
  runtime/tests/interpreter/runtimetype_test.go
  runtime/tests/interpreter/string_test.go
  runtime/tests/interpreter/transactions_test.go
Labels: Performance

#2068 Improve block comment parsing
  runtime/parser/comment.go
  runtime/parser/expression.go
  runtime/parser/expression_test.go
  runtime/parser/parser.go
  runtime/parser/parser_test.go
  runtime/parser/trampoline.go
Labels: Performance

#2071 cleanup docs-tutorial06
  docs/anti-patterns.mdx
  docs/tutorial/06-fungible-tokens.mdx
Labels: Documentation

#2064 Simplify parser
  runtime/parser/declaration.go
  runtime/parser/expression.go
  runtime/parser/function.go
  runtime/parser/parser.go
  runtime/parser/parser_test.go
  runtime/parser/statement.go
  runtime/parser/transaction.go
  runtime/parser/type.go
Labels: Improvement

#2043 Document setup() and tearDown() functions in test-framework
  docs/testing-framework.mdx
Labels: Documentation

#2074 Re-use interpreter for value decoding in test-framework
  runtime/stdlib/test-framework.go
  runtime/stdlib/test.go
Labels: Improvement

#2038 Add key iteration, count methods to AccountKeyProvider interface
  docs/language/accounts.mdx
  runtime/account_test.go
  runtime/environment.go
  runtime/interface.go
  runtime/interpreter/accountkeys.go
  runtime/runtime_test.go
  runtime/sema/authaccount_type.go
  runtime/sema/publicaccount_type.go
  runtime/stdlib/account.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Breaking Change, Feature

#2037 Detect invalidated references statically
  docs/language/references.mdx
  runtime/missingmember_test.go
  runtime/sema/check_assignment.go
  runtime/sema/check_expression.go
  runtime/sema/check_variable_declaration.go
  runtime/sema/checker.go
  runtime/sema/errors.go
  runtime/sema/variable.go
  runtime/storage_test.go
  runtime/tests/checker/reference_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/reference_test.go
  runtime/tests/interpreter/resources_test.go
Labels: Breaking Change, Improvement

#2080 Allow for-loops over strings
  runtime/interpreter/interpreter_statement.go
  runtime/interpreter/value.go
  runtime/sema/check_for.go
  runtime/tests/checker/for_test.go
  runtime/tests/interpreter/for_test.go
Labels: Feature

#2083 Add `String.fromCharacters`
  runtime/interpreter/interpreter.go
  runtime/interpreter/string.go
  runtime/sema/string_type.go
  runtime/sema/type.go
  runtime/tests/checker/string_test.go
  runtime/tests/interpreter/string_test.go
Labels: Feature

#2040 Update flow-docs.json to include "why cadence" section.
  docs/flow-docs.json
Labels: Dev Portal Documentation

#2055 Improve CI
  .github/workflows/benchmark.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/downstream.yml
  .github/workflows/sync-flow-go.yml.disabled
Labels: Chore

#2058 Use Value.Clone instead of custom deep copy function
  runtime/tests/interpreter/values_test.go
Labels: Improvement

#2087 Parallelize more tests, use checker errors helper
  encoding/json/encoding_test.go
  runtime/account_test.go
  runtime/ast/expression_test.go
  runtime/ast/memberindices_test.go
  runtime/ast/parameterlist_test.go
  runtime/ast/programindices_test.go
  runtime/ast/string_test.go
  runtime/ast/type_test.go
  runtime/cmd/minifier/minifier_test.go
  runtime/common/compositekind_test.go
  runtime/common/declarationkind_test.go
  runtime/common/location_test.go
  runtime/common/orderedmap/orderedmap_test.go
  runtime/contract_update_test.go
  runtime/convertValues_test.go
  runtime/crypto_test.go
  runtime/format/bytes_test.go
  runtime/interpreter/value_test.go
  runtime/literal_test.go
  runtime/missingmember_test.go
  runtime/parser/docstring_test.go
  runtime/parser/expression_test.go
  runtime/parser/parser_test.go
  runtime/program_params_validation_test.go
  runtime/stdlib/flow_test.go
  runtime/stdlib/rlp/rlp_test.go
  runtime/tests/checker/builtinfunctions_test.go
  runtime/tests/checker/import_test.go
  runtime/tests/checker/restriction_test.go
  runtime/tests/checker/type_inference_test.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/values_test.go
  values_test.go
Labels: Testing

#2073 Optimize resource tracking
  runtime/sema/check_conditional.go
  runtime/sema/checker.go
  runtime/sema/resources.go
Labels: Performance

#2072 Improve interpreter storage
  runtime/common/orderedmap/orderedmap.go
  runtime/storage.go
  runtime/storage_test.go
Labels: Improvement, Performance

#2079 Improve type inference for case expressions in switch statement
  runtime/sema/check_switch.go
  runtime/tests/checker/switch_test.go
Labels: Improvement

#2039 Add "why Cadence" section to Cadence docs
  docs/why-cadence.md
Labels: Documentation

#2089 Sync Stable Cadence feature branch
  .github/workflows/benchmark.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/downstream.yml
  .github/workflows/sync-flow-go.yml.disabled
  docs/flow-docs.json
  encoding/json/encoding_test.go
  runtime/account_test.go
  runtime/ast/expression_test.go
  runtime/ast/memberindices_test.go
  runtime/ast/parameterlist_test.go
  runtime/ast/programindices_test.go
  runtime/ast/string_test.go
  runtime/ast/type_test.go
  runtime/cmd/minifier/minifier_test.go
  runtime/common/compositekind_test.go
  runtime/common/declarationkind_test.go
  runtime/common/location_test.go
  runtime/common/orderedmap/orderedmap.go
  runtime/common/orderedmap/orderedmap_test.go
  runtime/contract_update_test.go
  runtime/convertValues_test.go
  runtime/crypto_test.go
  runtime/format/bytes_test.go
  runtime/interpreter/value_test.go
  runtime/literal_test.go
  runtime/missingmember_test.go
  runtime/parser/docstring_test.go
  runtime/parser/expression_test.go
  runtime/parser/parser_test.go
  runtime/program_params_validation_test.go
  runtime/sema/check_conditional.go
  runtime/sema/checker.go
  runtime/sema/resources.go
  runtime/stdlib/flow_test.go
  runtime/stdlib/rlp/rlp_test.go
  runtime/storage.go
  runtime/storage_test.go
  runtime/tests/checker/builtinfunctions_test.go
  runtime/tests/checker/import_test.go
  runtime/tests/checker/restriction_test.go
  runtime/tests/checker/type_inference_test.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/values_test.go
  values_test.go
Labels: Chore

#2086 Refactor reference tests
  runtime/tests/checker/reference_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Technical Debt

#1999 Invalidate resource references when the referenced resource is moved
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/reference_test.go
  runtime/tests/interpreter/resources_test.go
Labels: Breaking Change, Improvement

#2096 Add invalidation info to the invalid reference usage error
  runtime/sema/check_expression.go
  runtime/sema/errors.go
  runtime/tests/checker/reference_test.go
Labels: Improvement

#2093 refactor AccountKeysCount to expect an error too
  runtime/account_test.go
  runtime/environment.go
  runtime/interface.go
  runtime/interpreter/accountkeys.go
  runtime/runtime_test.go
  runtime/stdlib/account.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Bugfix, Chore

#2098 Sync Stable Cadence feature branch
  docs/flow-docs.json
  docs/why-cadence.md
  runtime/account_test.go
  runtime/environment.go
  runtime/interface.go
  runtime/interpreter/accountkeys.go
  runtime/runtime_test.go
  runtime/sema/check_switch.go
  runtime/stdlib/account.go
  runtime/tests/checker/switch_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Chore

#2097 Improve interpreter config
  runtime/account_test.go
  runtime/contract_function_executor.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/crypto_test.go
  runtime/deployment_test.go
  runtime/environment.go
  runtime/interface.go
  runtime/interpreter/config.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_import.go
  runtime/interpreter/interpreter_statement.go
  runtime/interpreter/interpreter_test.go
  runtime/interpreter/interpreter_tracing.go
  runtime/interpreter/sharedstate.go
  runtime/interpreter/storage_test.go
  runtime/interpreter/storagemap.go
  runtime/interpreter/value.go
  runtime/interpreter/value_publickey.go
  runtime/interpreter/value_test.go
  runtime/runtime.go
  runtime/script_executor.go
  runtime/sema/crypto_algorithm_types.go
  runtime/sema/crypto_algorithm_types_test.go
  runtime/stdlib/account.go
  runtime/stdlib/bls.go
  runtime/stdlib/builtin.go
  runtime/stdlib/crypto.go
  runtime/stdlib/hashalgorithm.go
  runtime/stdlib/publickey.go
  runtime/stdlib/test-framework.go
  runtime/stdlib/test.go
  runtime/tests/checker/crypto_test.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/transaction_executor.go
Labels: Improvement, Technical Debt

#2100 Allow embedders to reuse interpreter shared state
  runtime/environment.go
  runtime/ft_test.go
  runtime/interface.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_import.go
  runtime/interpreter/interpreter_invocation.go
  runtime/interpreter/interpreter_statement.go
  runtime/interpreter/interpreter_tracing.go
  runtime/interpreter/sharedstate.go
  runtime/interpreter/storagemap.go
  runtime/interpreter/value.go
  runtime/runtime_test.go
  runtime/sharedstate_test.go
  runtime/storage_test.go
Labels: Performance

#2052 Allow export of function values
  docs/json-cadence-spec.md
  encoding/json/encode.go
  encoding/json/encoding_test.go
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/format/function.go
  runtime/import_test.go
  runtime/interpreter/function.go
  runtime/runtime_test.go
  runtime/sema/type.go
  types.go
  values.go
Labels: Improvement

#2104 Improve JSON decoding error messages, add utility
  encoding/json/decode.go
  encoding/json/encoding_test.go
  go.mod
  go.sum
  runtime/cmd/json-cdc/main.go
Labels: Improvement, Technical Debt

#2108 Fix self declaration
  runtime/contract_function_executor.go
  runtime/interpreter/function.go
  runtime/interpreter/function_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_invocation.go
  runtime/interpreter/interpreter_transaction.go
  runtime/interpreter/invocation.go
  runtime/interpreter/value.go
  runtime/stdlib/publickey.go
  runtime/stdlib/test.go
  runtime/tests/interpreter/invocation_test.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Bugfix

#2103 Improve common supertype calculation
  runtime/sema/type_tags.go
  runtime/sema/type_test.go
  runtime/tests/checker/type_inference_test.go
Labels: Improvement

#2107 Improve JSON encoding test cases, add REPL command for exporting
  encoding/json/encoding_test.go
  go.mod
  go.sum
  runtime/cmd/execute/repl.go
  runtime/repl.go
Labels: Feature, Improvement, Testing
