Repository onflow/cadence, pull requests merged in 2022-08, with the labels that each got.

#1858 Append special prefix to all internal error string messages
  runtime/errors/errors.go
  runtime/interpreter/decode.go
  runtime/interpreter/errors.go
Labels: Technical Debt

#1855 [LS] Enable argument init for add contract
  languageserver/go.mod
  languageserver/go.sum
  languageserver/integration/commands.go
Labels: Improvement, Language Server

#1865 Fix minor typo: language docs - consts & vars
  docs/language/constants-and-variables.md
Labels: Good First Issue

#1813 Optimize standard library enums
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/interpreter/accountkey.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/simplecompositevalue.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/resourcedictionary_test.go
  runtime/runtime.go
  runtime/stdlib/bls.go
  runtime/stdlib/crypto.go
  runtime/stdlib/hashalgorithm.go
  runtime/stdlib/publickey.go
  runtime/stdlib/rlp.go
  runtime/stdlib/signaturealgorithm.go
  runtime/test-export-json-deterministic.txt
Labels: Improvement, Performance

#1844 Optimize elaboration
  runtime/compiler/compiler.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_statement.go
  runtime/sema/check_array_expression.go
  runtime/sema/check_assignment.go
  runtime/sema/check_binary_expression.go
  runtime/sema/check_casting_expression.go
  runtime/sema/check_dictionary_expression.go
  runtime/sema/check_expression.go
  runtime/sema/check_invocation_expression.go
  runtime/sema/check_return_statement.go
  runtime/sema/check_swap.go
  runtime/sema/check_variable_declaration.go
  runtime/sema/elaboration.go
  runtime/tests/checker/conditions_test.go
  runtime/tests/checker/genericfunction_test.go
Labels: Improvement, Performance

#1861 Fix batch scipt tool
  Makefile
  tools/batch-script/address_provider.go
  tools/docgen/Makefile
Labels: Technical Debt

#1827 [Test Framework] Start development of Cadence test framework
  runtime/contract_function_executor.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/deployment_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/test-framework.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/sema/authaccount_contracts.go
  runtime/sema/authaccount_type.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_interface_declaration.go
  runtime/sema/crypto_algorithm_types.go
  runtime/sema/public_account_contracts.go
  runtime/sema/publicaccount_type.go
  runtime/sema/type.go
  runtime/sema/type_test.go
  runtime/stdlib/contracts/test.cdc
  runtime/stdlib/contracts/test.go
  runtime/stdlib/test.go
  test-framework/README.md
  test-framework/emulator_backend.go
  test-framework/go.mod
  test-framework/go.sum
  test-framework/test_framework.go
  test-framework/test_framework_test.go
Labels: Feature

#1843 Add meeting notes for July 22, 2022
  meetings/2022-07-22.md
Labels: Documentation

#1832 [Test Framework] Add support for importing and initializing contracts
  runtime/interpreter/function.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/runtime.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_for.go
  runtime/sema/check_function.go
  runtime/sema/check_import_declaration.go
  runtime/sema/check_variable_declaration.go
  runtime/sema/checker.go
  runtime/sema/variable_activations.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  test-framework/errors.go
  test-framework/go.mod
  test-framework/go.sum
  test-framework/test_framework.go
  test-framework/test_framework_test.go
Labels: Feature

#1835 [Test Framework] Use FVM as the environment provider for test runner
  runtime/sema/check_composite_declaration.go
  runtime/test_framework_runtime.go
  test-framework/go.mod
  test-framework/go.sum
  test-framework/test_framework.go
  test-framework/test_framework_test.go
Labels: Feature

#1849 [Test Framework] Add transaction execution support
  runtime/interpreter/test-framework.go
  runtime/runtime.go
  runtime/stdlib/contracts/test.cdc
  runtime/stdlib/publickey.go
  runtime/stdlib/test.go
  runtime/types.go
  test-framework/emulator_backend.go
  test-framework/test_framework.go
  test-framework/test_framework_test.go
Labels: Feature

#1864 [Test Framework] Run setup/teardown before/after tests
  test-framework/test_framework.go
  test-framework/test_framework_test.go
Labels: Feature

#1869 [Test Framework] Add support for loading programs from local files
  runtime/interpreter/test-framework.go
  runtime/stdlib/test.go
  test-framework/emulator_backend.go
  test-framework/test_framework.go
  test-framework/test_framework_test.go
Labels: Feature

#1076 Interface default implementation support
  docs/language/interfaces.mdx
  runtime/ast/block.go
  runtime/interpreter/interpreter.go
  runtime/sema/check_assignment.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_interface_declaration.go
  runtime/sema/errors.go
  runtime/sema/type.go
  runtime/tests/checker/conformance_test.go
  runtime/tests/checker/interface_test.go
  runtime/tests/interpreter/interface_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Feature

#1845 Add path fields to `AuthAccount` and `PublicAccount`
  docs/language/accounts.mdx
  runtime/interpreter/account.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/storagemap.go
  runtime/sema/authaccount_type.go
  runtime/sema/publicaccount_type.go
  runtime/tests/checker/account_test.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Feature

#1880 Ignore Go workspace files
  .gitignore
Labels: Improvement

#1851 Storage Iteration functions for accounts
  docs/language/accounts.mdx
  runtime/interpreter/account.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/sema/authaccount_type.go
  runtime/sema/publicaccount_type.go
  runtime/tests/checker/account_test.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Feature

#1863 [Test Framework] Add initial support for Matchers
  runtime/interpreter/interpreter.go
  runtime/stdlib/contracts/test.cdc
  runtime/stdlib/test.go
  runtime/tests/interpreter/memory_metering_test.go
  test-framework/test_framework_test.go
Labels: Feature

#1882 Improve documentation for storage iteration
  docs/language/accounts.mdx
Labels: Documentation

#1886 [Test Framework] Remove test-framework field from interpreter
  runtime/interpreter/interpreter.go
  runtime/stdlib/test.go
  test-framework/test_framework.go
Labels: Improvement, Technical Debt

#1890 [LS] Contract deploy test fix
  languageserver/integration/commands.go
  languageserver/integration/commands_test.go
  languageserver/integration/flow.go
  languageserver/integration/mock_flow_test.go
Labels: Improvement, Language Server, Developer Tool Team

#1878 Preallocate ordered maps
  runtime/common/list/list.go
  runtime/common/orderedmap/orderedmap.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_transaction_declaration.go
Labels: Improvement, Performance

#1888 Optimize import of crypto enum cases
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/program_params_validation_test.go
  runtime/stdlib/crypto.go
  runtime/stdlib/hashalgorithm.go
  runtime/stdlib/signaturealgorithm.go
Labels: Improvement, Performance

#1901 Append special prefix to all internal error string messages
  runtime/errors/errors.go
  runtime/interpreter/decode.go
  runtime/interpreter/errors.go
Labels: Improvement, Technical Debt

#1892 Add panic after continuing storage iteration after a storage mutation
  docs/language/accounts.mdx
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/sharedstate.go
  runtime/tests/interpreter/account_test.go
Labels: Feature

#1904 Improve hex decoding errors
  runtime/interpreter/errors.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/string_test.go
Labels: Improvement

#1902 Move resource variables to shared state
  runtime/interpreter/interpreter.go
  runtime/interpreter/sharedstate.go
Labels: Improvement, Performance

#1899 Reduce allocations by refactoring simple composite computed fields from map to function
  runtime/convertValues.go
  runtime/interpreter/account.go
  runtime/interpreter/accountcontracts.go
  runtime/interpreter/simplecompositevalue.go
  runtime/tests/interpreter/composite_value_test.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Improvement, Performance

#1893 [Test Framework] Provide a way to specify addresses for the imports
  runtime/interpreter/test-framework.go
  runtime/stdlib/contracts/test.cdc
  runtime/stdlib/test.go
  test-framework/emulator_backend.go
  test-framework/test_framework_test.go
Labels: Feature

#1895 [Test Framework] Move matcher implementation to cadence
  runtime/stdlib/contracts/test.cdc
  runtime/stdlib/test.go
Labels: Improvement

#1906 Parse version file and use max version
  go.mod
  go.sum
  utils/version/main.go
Labels: Chore

#1897 [Test Framework] Refactor and cleanup the test-stdlib
  runtime/stdlib/contracts/test.cdc
  runtime/stdlib/test.go
  test-framework/test_framework_test.go
Labels: Improvement

#1877 [LS] General improvements
  languageserver/go.mod
  languageserver/go.sum
  languageserver/integration/commands.go
  languageserver/integration/commands_test.go
  languageserver/integration/contracts.go
  languageserver/integration/entrypoint.go
  languageserver/integration/entrypoint_test.go
  languageserver/integration/flow.go
  languageserver/integration/integration.go
  languageserver/integration/mock_flow_test.go
  languageserver/protocol/server.go
  languageserver/server/server.go
  languageserver/test/index.test.ts
  languageserver/test/transaction-none.cdc
Labels: Improvement, Language Server, Developer Tool Team

#1887 docs: add security best practices
  docs/security-best-practices.mdx
Labels: Documentation

#1914 Make missing casting expression a user error
  runtime/parser/expression.go
  runtime/parser/expression_test.go
  runtime/parser/parser_test.go
Labels: Bugfix

#1911 Make Paths equatable, add tests
  runtime/sema/path_type.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Feature

#1920 Add description to interpreter.Value
  runtime/interpreter/value.go
Labels: Documentation

#1907 Optimize and make visitor generic
  runtime/ast/block.go
  runtime/ast/composite.go
  runtime/ast/expression.go
  runtime/ast/expression_extractor.go
  runtime/ast/function_declaration.go
  runtime/ast/import.go
  runtime/ast/interface.go
  runtime/ast/pragma.go
  runtime/ast/program.go
  runtime/ast/statement.go
  runtime/ast/transaction_declaration.go
  runtime/ast/variable_declaration.go
  runtime/ast/visitor.go
  runtime/cmd/compile/main.go
  runtime/compiler/compiler.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_import.go
  runtime/interpreter/interpreter_statement.go
  runtime/interpreter/interpreter_transaction.go
  runtime/repl.go
  runtime/sema/check_array_expression.go
  runtime/sema/check_assignment.go
  runtime/sema/check_binary_expression.go
  runtime/sema/check_block.go
  runtime/sema/check_casting_expression.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_conditional.go
  runtime/sema/check_conditions.go
  runtime/sema/check_create_expression.go
  runtime/sema/check_destroy_expression.go
  runtime/sema/check_dictionary_expression.go
  runtime/sema/check_emit_statement.go
  runtime/sema/check_expression.go
  runtime/sema/check_for.go
  runtime/sema/check_force_expression.go
  runtime/sema/check_function.go
  runtime/sema/check_import_declaration.go
  runtime/sema/check_interface_declaration.go
  runtime/sema/check_invocation_expression.go
  runtime/sema/check_member_expression.go
  runtime/sema/check_path_expression.go
  runtime/sema/check_pragma.go
  runtime/sema/check_reference_expression.go
  runtime/sema/check_return_statement.go
  runtime/sema/check_swap.go
  runtime/sema/check_switch.go
  runtime/sema/check_transaction_declaration.go
  runtime/sema/check_unary_expression.go
  runtime/sema/check_variable_declaration.go
  runtime/sema/check_while.go
  runtime/sema/checker.go
Labels: Improvement, Performance

#1928 Add meeting notes for August 30, 2022
  meetings/2022-08-30.md
Labels: Documentation

#1927 Add String.fromUTF8 for conversion from [UInt8]
  runtime/interpreter/interpreter.go
  runtime/sema/string_type.go
  runtime/sema/type.go
  runtime/tests/interpreter/string_test.go
Labels: Feature, Feedback

#1917 Fix ToBigEndianBytes implementations for U?Int(128|256)
  runtime/interpreter/big.go
  runtime/interpreter/value.go
  runtime/sema/type.go
  runtime/tests/interpreter/builtinfunctions_test.go
  values.go
  values_test.go
Labels: Bugfix, Breaking Change
