Repository onflow/cadence, pull requests merged in 2022-06, with the labels that each got.

#1682 Update fxamacker/cbor and atree to latest versions
  go.mod
  go.sum
Labels: Improvement

#1621 Update to Go 1.18
  .github/workflows/benchmark.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/compat.yaml
  .github/workflows/sync-flow-go.yml.disabled
  go.mod
  go.sum
  languageserver/go.mod
  languageserver/go.sum
  runtime/interpreter/statictype_test.go
  runtime/interpreter/value_test.go
  tools/batch-script/go.mod
  tools/constructorcheck/go.mod
  tools/constructorcheck/go.sum
  tools/docgen/go.mod
  tools/golangci-lint/go.mod
  tools/golangci-lint/go.sum
  tools/maprangecheck/go.mod
  tools/maprangecheck/go.sum
Labels: Chore

#1685 Update call-refresh-workflow
  .github/workflows/call-refresh-doc.yml
Labels: Chore

#1688 update doc to provide clarity on initializers
  docs/language/contract-updatability.md
Labels: Documentation

#1689 Avoid type-checking of the old program during contract updates
  runtime/contract_update_test.go
  runtime/contract_update_validation_test.go
  runtime/runtime.go
Labels: Bugfix

#1699 Document new short address toString behaviour
  docs/language/values-and-types.mdx
Labels: Documentation

#1700 update documentation for optional references
  docs/language/references.md
Labels: Documentation

#1692 Avoid type-checking of the old program during contract updates
  runtime/contract_update_test.go
  runtime/contract_update_validation_test.go
  runtime/runtime.go
Labels: Bugfix

#1702 Document number supertype changes
  docs/language/operators.md
Labels: Documentation

#1705 Fix JSON encoding of type values with recursive type
  encoding/json/encode.go
  encoding/json/encoding_test.go
  runtime/convertTypes.go
  runtime/convertValues_test.go
  types.go
  types_test.go
Labels: Bugfix

#1694 Properly support super types in ConformsToStaticType implementations
  runtime/convertValues.go
  runtime/imported_values_memory_metering_test.go
  runtime/interpreter/function.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/simplecompositevalue.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/runtime.go
  runtime/runtime_test.go
Labels: Bugfix

#1706 Differentate invalidated resource use errors
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Improvement

#1698 [LS] Add stdlib builtin value declarations
  languageserver/server/server.go
Labels: Bugfix

#1707 [LS] Update to Secure Cadence
  languageserver/conversion/conversion.go
  languageserver/go.mod
  languageserver/go.sum
  languageserver/integration/contracts.go
  languageserver/integration/diagnostics.go
  languageserver/integration/entrypoint.go
  languageserver/server/server.go
Labels: Improvement, Developer Tool Team

#1696 [LS] Update types
  languageserver/conversion/conversion.go
  languageserver/integration/codelenses.go
  languageserver/integration/commands.go
  languageserver/integration/contracts.go
  languageserver/integration/diagnostics.go
  languageserver/integration/entrypoint.go
  languageserver/integration/integration.go
  languageserver/protocol/methods.go
  languageserver/protocol/server.go
  languageserver/protocol/types.go
  languageserver/scripts/README.md
  languageserver/scripts/package-lock.json
  languageserver/scripts/package.json
  languageserver/server/command.go
  languageserver/server/location.go
  languageserver/server/server.go
  languageserver/test/util.go
Labels: Improvement

#1697 [LS] Add inlay hints
  languageserver/protocol/methods.go
  languageserver/protocol/server.go
  languageserver/server/server.go
Labels: Feature

#1711 [0.24] Ignore missing comma in parameter list parse error for contract updates
  runtime/contract_update_validation_test.go
  runtime/parser2/declaration_test.go
  runtime/parser2/errors.go
  runtime/parser2/function.go
  runtime/runtime.go
Labels: Bugfix

#1712 Ignore missing comma in parameter list parse error for contract updates
  runtime/contract_update_validation_test.go
  runtime/parser2/declaration_test.go
  runtime/parser2/errors.go
  runtime/parser2/function.go
  runtime/runtime.go
Labels: Bugfix

#1716 Update Crypto docs
  docs/language/crypto.mdx
Labels: Documentation

#1717 Take argument labels into account when declaring members for nested declarations
  runtime/sema/check_composite_declaration.go
  runtime/tests/checker/invocation_test.go
Labels: Bugfix, Breaking Change

#1720 Fix decoding of repeated/recursive encoded types
  encoding/json/decode.go
  encoding/json/encode.go
  encoding/json/encoding_test.go
  types.go
Labels: Bugfix

#1725 Add documentation for type json encoding
  docs/json-cadence-spec.md
Labels: Documentation

#1726 Improve type json docs
  docs/json-cadence-spec.md
Labels: Documentation

#1587 [0.23] Add AST inspector which allows efficient element traversal
  runtime/ast/block.go
  runtime/ast/composite.go
  runtime/ast/elementtype.go
  runtime/ast/elementtype_string.go
  runtime/ast/expression.go
  runtime/ast/function_declaration.go
  runtime/ast/import.go
  runtime/ast/inspector.go
  runtime/ast/inspector_test.go
  runtime/ast/interface.go
  runtime/ast/pragma.go
  runtime/ast/program.go
  runtime/ast/statement.go
  runtime/ast/transaction_declaration.go
  runtime/ast/variable_declaration.go
  runtime/ast/visitor.go
  runtime/compiler/compiler.go
  runtime/interpreter/interpreter.go
  runtime/sema/check_function.go
Labels: Feature

#1730 Add AST inspector which allows efficient element traversal
  runtime/ast/block.go
  runtime/ast/composite.go
  runtime/ast/elementtype.go
  runtime/ast/elementtype_string.go
  runtime/ast/expression.go
  runtime/ast/function_declaration.go
  runtime/ast/import.go
  runtime/ast/inspector.go
  runtime/ast/inspector_test.go
  runtime/ast/interface.go
  runtime/ast/pragma.go
  runtime/ast/program.go
  runtime/ast/statement.go
  runtime/ast/transaction_declaration.go
  runtime/ast/variable_declaration.go
  runtime/ast/visitor.go
  runtime/compiler/compiler.go
  runtime/interpreter/interpreter.go
  runtime/sema/check_function.go
Labels: Feature

#1606 [0.23] Improve analysis package
  runtime/ast/statement.go
  runtime/cmd/cmd.go
  runtime/common/location.go
  runtime/pretty/print.go
  runtime/repl.go
  runtime/runtime.go
  runtime/sema/resolve.go
  runtime/stdlib/flow.go
  tools/analysis/analysis.go
  tools/analysis/analysis_test.go
  tools/analysis/analyzer.go
  tools/analysis/config.go
  tools/analysis/diagnostic.go
  tools/analysis/error.go
  tools/analysis/inspector.go
  tools/analysis/loadmode.go
  tools/analysis/pass.go
  tools/analysis/program.go
  tools/analysis/programs.go
  tools/contract-analyzer/README.md
  tools/contract-analyzer/analyzer.go
  tools/contract-analyzer/flag.go
  tools/contract-analyzer/go.mod
  tools/contract-analyzer/go.sum
  tools/contract-analyzer/main.go
Labels: Improvement

#1733 Allow decoding of types in pre-0.3.0 format (just type ID)
  encoding/json/decode.go
  encoding/json/encoding_test.go
  types.go
Labels: Improvement

#1734 Allow decoding of types in pre-0.3.0 format (just type ID)
  encoding/json/decode.go
  encoding/json/encoding_test.go
  types.go
Labels: Improvement

#1549 Show stack trace in runtime error
  runtime/cmd/cmd.go
  runtime/error_test.go
  runtime/errors/errors.go
  runtime/interpreter/errors.go
  runtime/interpreter/function.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_invocation.go
  runtime/interpreter/invocation.go
  runtime/pretty/print.go
  runtime/rlp_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Feature

#1614 Suggest optional chaining when member access is on optional type
  runtime/sema/errors.go
  runtime/tests/checker/composite_test.go
  runtime/tests/checker/utils.go
Labels: Improvement

#1619 Improve batch script / contract requesting tool
  tools/batch-script/address_provider.go
  tools/batch-script/batch.go
  tools/batch-script/cmd/get_contracts/main.go
Labels: Improvement

#1634 Add dependency resolution package
  runtime/common/deps/gen.go
  runtime/common/deps/node.go
  runtime/common/deps/node_test.go
  runtime/common/deps/orderedmap.go
  runtime/common/deps/set.go
Labels: Feature

#1737 Update design-patterns.mdx
  docs/design-patterns.mdx
Labels: Documentation

#1738 Fix example code from the docs section "design patterns/Script-Accessible report"
  docs/design-patterns.mdx
Labels: Documentation

#1728 Fix deadlock and simplify debugger
  runtime/interpreter/debugger.go
Labels: Bugfix

#1741 Fixes tutorial callout and removes screenshot
  docs/tutorial/02-hello-world.mdx
  docs/tutorial/04-capabilities.mdx
Labels: Documentation

#1742 Use location instead of location ID
  runtime/cmd/check/main.go
  runtime/cmd/cmd.go
  runtime/cmd/compile/main.go
  runtime/cmd/execute/repl.go
  runtime/cmd/parse/main.go
  runtime/common/location.go
  runtime/common/location_test.go
  runtime/context.go
  runtime/contract_test.go
  runtime/contract_update_test.go
  runtime/contract_update_validation_test.go
  runtime/error_test.go
  runtime/errors.go
  runtime/ft_test.go
  runtime/interpreter/encode.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/statictype.go
  runtime/interpreter/value.go
  runtime/missingmember_test.go
  runtime/parser2/errors.go
  runtime/pretty/print.go
  runtime/pretty/print_test.go
  runtime/repl.go
  runtime/runtime.go
  runtime/runtime_memory_metering_test.go
  runtime/runtime_test.go
  runtime/sema/errors.go
  runtime/stdlib/flow.go
  runtime/storage_test.go
  runtime/tests/checker/import_test.go
  runtime/tests/checker/utils.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Improvement

#1745 Fix capability check and borrow functions
  runtime/interpreter/interpreter.go
  runtime/tests/interpreter/capability_test.go
Labels: Bugfix

#1743 Move unnecessary force lint check to the contract analyzer
  fuzz.go
  runtime/cmd/cmd.go
  runtime/convertValues_test.go
  runtime/interpreter/storage_test.go
  runtime/interpreter/value_test.go
  runtime/repl.go
  runtime/runtime.go
  runtime/sema/check_force_expression.go
  runtime/sema/checker.go
  runtime/sema/elaboration.go
  runtime/sema/type_test.go
  runtime/stdlib/builtin_test.go
  runtime/stdlib/crypto.go
  runtime/tests/checker/conversion_test.go
  runtime/tests/checker/dynamic_casting_test.go
  runtime/tests/checker/force_test.go
  runtime/tests/checker/interface_test.go
  runtime/tests/checker/utils.go
  runtime/tests/checker/utils_test.go
  runtime/tests/interpreter/import_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/values_test.go
  tools/analysis/programs.go
  tools/contract-analyzer/analyzers/analyzers_test.go
  tools/contract-analyzer/analyzers/depreceated_functions_analyzer.go
  tools/contract-analyzer/analyzers/reference_operator_analyzer.go
  tools/contract-analyzer/analyzers/unnecessary_force_analyzer.go
  tools/contract-analyzer/go.mod
Labels: Feature

#1744 Resource destruction should also invalidate references
  runtime/interpreter/value.go
  runtime/tests/interpreter/resources_test.go
Labels: Bugfix

#1748 [0.24] Fix capability check and borrow functions
  runtime/interpreter/interpreter.go
  runtime/tests/interpreter/capability_test.go
Labels: Bugfix

#1749 [v0.24] Resource destruction should also invalidate references
  runtime/interpreter/value.go
  runtime/tests/interpreter/resources_test.go
Labels: Bugfix

#1760 Bump onflow/atree from 0.3.0 to 0.4.0
  go.mod
  go.sum
Labels: Improvement

#1758 Migrate casting lints to the new linter
  runtime/sema/check_casting_expression.go
  runtime/sema/elaboration.go
  runtime/sema/hints.go
  runtime/tests/checker/casting_test.go
  runtime/tests/checker/dynamic_casting_test.go
  tools/contract-analyzer/analyzers/analyzers_test.go
  tools/contract-analyzer/analyzers/casting_analysis.go
Labels: Feature

#1761 [0.24] Add defensive check for member accesses
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_test.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/member_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/reference_test.go
Labels: Feature

#1759 Add defensive check for member accesses
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_test.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/member_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/reference_test.go
Labels: Feature

#1766 Fix typo in nft-2 tutorial
  docs/tutorial/05-non-fungible-tokens-2.mdx
Labels: Documentation

#1763 Migrate number conversion hints to the contract analyzer
  runtime/repl.go
  runtime/sema/checker.go
  runtime/sema/elaboration.go
  runtime/sema/hints.go
  runtime/sema/type.go
  runtime/tests/checker/casting_test.go
  runtime/tests/checker/conversion_test.go
  tools/contract-analyzer/analyzers/analyzers_test.go
  tools/contract-analyzer/analyzers/number_function_argument_analyzer.go
  tools/contract-analyzer/go.mod
  tools/contract-analyzer/go.sum
Labels: Feature

#1736 Add support for adding breakpoints to the debugger
  go.mod
  go.sum
  runtime/debugger_test.go
  runtime/interpreter/debugger.go
Labels: Feature

#1769 Prepare contract analyzer to be moved to separate repo
  runtime/sema/check_casting_expression.go
  runtime/sema/check_force_expression.go
  runtime/sema/checker.go
  runtime/sema/elaboration.go
  runtime/sema/type.go
  tools/contract-analyzer/go.mod
  tools/contract-analyzer/go.sum
Labels: Improvement

#1762 Include static types when exporting arrays and dictionaries
  runtime/account_test.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/crypto_test.go
  runtime/rlp_test.go
  runtime/runtime_test.go
Labels: Breaking Change, Improvement

#1661 Improve reference expressions
  runtime/ast/expression.go
  runtime/ast/expression_test.go
  runtime/parser/expression.go
  runtime/parser/expression_test.go
  runtime/parser/statement_test.go
  runtime/sema/check_array_expression.go
  runtime/sema/check_dictionary_expression.go
  runtime/sema/check_reference_expression.go
  runtime/tests/checker/casting_test.go
  runtime/tests/checker/reference_test.go
Labels: Bugfix, Breaking Change, Improvement
