Repository onflow/cadence, pull requests merged in 2022-04, with the labels that each got.

#1547 Nil elements when reslicing
  runtime/activations/activations.go
  runtime/compiler/local_activations.go
  runtime/interpreter/variable_activations.go
  runtime/sema/function_activations.go
  runtime/sema/variable_activations.go
Labels: Bugfix

#1551 Remove release drafter GitHub action
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: Chore

#1550 [0.23] Fix overflow error in UInt to int conversion
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/runtime_test.go
Labels: Bugfix

#1542 Box optional-typed references to non-optional values
  runtime/interpreter/interpreter_expression.go
  runtime/tests/interpreter/reference_test.go
Labels: Bugfix

#1541 Add memory metering for AST declaration elements
  runtime/ast/argument.go
  runtime/ast/block.go
  runtime/ast/composite.go
  runtime/ast/function_declaration.go
  runtime/ast/import.go
  runtime/ast/interface.go
  runtime/ast/pragma.go
  runtime/ast/transaction_declaration.go
  runtime/ast/variable_declaration.go
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/interpreter/decode.go
  runtime/interpreter/interpreter_statement.go
  runtime/parser2/declaration.go
  runtime/parser2/expression.go
  runtime/parser2/function.go
  runtime/parser2/statement.go
  runtime/parser2/transaction.go
  runtime/sema/check_switch.go
  runtime/sema/checker.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Improvement

#1545 Add memory metering for statements
  runtime/ast/statement.go
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/interpreter/interpreter.go
  runtime/parser2/statement.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Improvement

#1554 Memory meter AST expressions
  runtime/ast/expression.go
  runtime/ast/function_declaration.go
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/parser2/expression.go
  runtime/parser2/statement.go
  runtime/parser2/type.go
  runtime/sema/before_extractor.go
  runtime/sema/type.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Improvement

#1553 Add codecov config
  codecov.yml
Labels: Chore

#1557 Reads of missing storage maps should not cause creation
  runtime/cmd/decode-state-values/main.go
  runtime/contract_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/storage.go
  runtime/interpreter/storage_test.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/storage.go
  runtime/storage_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/metatype_test.go
Labels: Bugfix

#1555 Memory meter AST types
  runtime/ast/block.go
  runtime/ast/composite_test.go
  runtime/ast/interface_test.go
  runtime/ast/memberindices_test.go
  runtime/ast/members.go
  runtime/ast/members_test.go
  runtime/ast/parameter.go
  runtime/ast/parameterlist.go
  runtime/ast/position.go
  runtime/ast/program.go
  runtime/ast/program_test.go
  runtime/ast/programindices_test.go
  runtime/ast/transfer.go
  runtime/ast/type.go
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/parser2/declaration.go
  runtime/parser2/declaration_test.go
  runtime/parser2/function.go
  runtime/parser2/parser.go
  runtime/parser2/statement.go
  runtime/parser2/transaction.go
  runtime/parser2/type.go
  runtime/repl.go
  runtime/sema/check_transaction_declaration.go
  runtime/sema/checker.go
  runtime/sema/type.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/values_test.go
Labels: Improvement

#1561 Handle missing member when checking mutability of member
  runtime/sema/check_assignment.go
  runtime/sema/check_member_expression.go
  runtime/tests/checker/indexing_test.go
Labels: Bugfix

#1560 add memory kind last
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
Labels: Feature

#1546 Improve metering of containers
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/imported_values_memory_metering_test.go
  runtime/interpreter/simplecompositevalue.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Feature

#1565 Transfer indexing expression
  runtime/interpreter/interpreter_expression.go
  runtime/sema/check_expression.go
  runtime/sema/elaboration.go
  runtime/storage_test.go
  runtime/tests/interpreter/indexing_test.go
Labels: Bugfix

#1548 Update the crypto doc
  docs/language/crypto.mdx
  runtime/sema/crypto_algorithm_types.go
  runtime/sema/type.go
Labels: Documentation

#1487 Add runtime subtype check using static types
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/interpreter/function.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_test.go
  runtime/interpreter/simplecompositevalue.go
  runtime/interpreter/statictype.go
  runtime/interpreter/storage_test.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/runtime.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Improvement, Performance

#1577 Remove dynamic types
  runtime/convertValues.go
  runtime/errors.go
  runtime/interpreter/account.go
  runtime/interpreter/accountcontracts.go
  runtime/interpreter/accountkey.go
  runtime/interpreter/accountkeys.go
  runtime/interpreter/block.go
  runtime/interpreter/deployedcontract.go
  runtime/interpreter/dynamictype.go
  runtime/interpreter/function.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_tracing.go
  runtime/interpreter/interpreter_transaction.go
  runtime/interpreter/simplecompositevalue.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/runtime.go
  runtime/stdlib/bls.go
  runtime/stdlib/rlp.go
Labels: Improvement

#1434 Add a package to run a script against all accounts
  tools/batch-script/.gitignore
  tools/batch-script/README.md
  tools/batch-script/address_provider.go
  tools/batch-script/batch.go
  tools/batch-script/cmd/get_contracts/main.go
  tools/batch-script/get_contracts.cdc
  tools/batch-script/go.mod
  tools/batch-script/go.sum
  tools/batch-script/use_cases.go
Labels: Feature

#1515 Remove addPublicKey and removePublicKey
  docs/language/accounts.mdx
  runtime/account_test.go
  runtime/interpreter/account.go
  runtime/runtime.go
  runtime/sema/authaccount_type.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Breaking Change

#1581 Add tests for casting references inside containers
  runtime/tests/interpreter/dynamic_casting_test.go
Labels: Testing

#1579 Meter additional container length as a function of original size
  runtime/common/metering.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Feature

#1532 Meter BigNumberValue.ToBigInt
  runtime/convertValues.go
  runtime/interpreter/conversion.go
  runtime/interpreter/conversion_test.go
  runtime/interpreter/decode.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/number.go
  runtime/interpreter/number_test.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/literal.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Improvement

#1559 Meter AST range
  runtime/ast/position.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/location.go
  runtime/parser2/declaration.go
  runtime/parser2/expression.go
  runtime/parser2/function.go
  runtime/parser2/lexer/lexer.go
  runtime/parser2/parser.go
  runtime/parser2/statement.go
  runtime/parser2/transaction.go
  runtime/parser2/type.go
  runtime/sema/check_block.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_event_declaration.go
  runtime/sema/check_force_expression.go
  runtime/sema/check_import_declaration.go
  runtime/sema/check_invocation_expression.go
  runtime/sema/check_member_expression.go
  runtime/sema/check_switch.go
  runtime/sema/check_unary_expression.go
  runtime/sema/checker.go
  runtime/sema/errors.go
  runtime/sema/occurrences.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Improvement

#1564 Meter AST dictionary entries
  runtime/ast/expression.go
  runtime/ast/expression_extractor.go
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/parser2/expression.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Improvement

#1582 Add test case for unparameterized type instantiation
  runtime/tests/checker/genericfunction_test.go
Labels: Testing

#1580 Merge master into memory metering
  docs/language/crypto.mdx
  runtime/convertTypes.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/errors.go
  runtime/interpreter/account.go
  runtime/interpreter/accountcontracts.go
  runtime/interpreter/accountkey.go
  runtime/interpreter/accountkeys.go
  runtime/interpreter/block.go
  runtime/interpreter/decode.go
  runtime/interpreter/deployedcontract.go
  runtime/interpreter/dynamictype.go
  runtime/interpreter/encode.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/function.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_test.go
  runtime/interpreter/interpreter_tracing.go
  runtime/interpreter/interpreter_transaction.go
  runtime/interpreter/simplecompositevalue.go
  runtime/interpreter/statictype.go
  runtime/interpreter/statictype_test.go
  runtime/interpreter/storage_test.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/runtime.go
  runtime/sema/crypto_algorithm_types.go
  runtime/sema/type.go
  runtime/stdlib/bls.go
  runtime/stdlib/rlp.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/metatype_test.go
  runtime/tests/interpreter/runtimetype_test.go
  runtime/tests/interpreter/values_test.go
Labels: Chore

#1589 Add fast-test option to makefile
  Makefile
Labels: Testing

#1538 Memory metering for primitive StaticType
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/convertTypes.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/interpreter/account.go
  runtime/interpreter/accountcontracts.go
  runtime/interpreter/deployedcontract.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/function.go
  runtime/interpreter/function_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/primitivestatictype.go
  runtime/interpreter/statictype.go
  runtime/interpreter/value.go
  runtime/runtime.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/reference_test.go
Labels: Improvement

#1588 Merge master into memory metering feature branch
  docs/language/accounts.mdx
  languageserver/Makefile
  languageserver/README.md
  languageserver/go.mod
  languageserver/go.sum
  languageserver/integration/commands.go
  languageserver/server/server.go
  languageserver/test/foo.cdc
  languageserver/test/index.test.ts
  runtime/account_test.go
  runtime/interpreter/account.go
  runtime/runtime.go
  runtime/sema/authaccount_type.go
  runtime/tests/checker/genericfunction_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/interpreter_test.go
  tools/batch-script/.gitignore
  tools/batch-script/README.md
  tools/batch-script/address_provider.go
  tools/batch-script/batch.go
  tools/batch-script/cmd/get_contracts/main.go
  tools/batch-script/get_contracts.cdc
  tools/batch-script/go.mod
  tools/batch-script/go.sum
  tools/batch-script/use_cases.go
Labels: Chore

#1563 Meter memory for more static types
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/convertTypes.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/interpreter/accountkey.go
  runtime/interpreter/block.go
  runtime/interpreter/decode.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_transaction.go
  runtime/interpreter/statictype.go
  runtime/interpreter/statictype_test.go
  runtime/interpreter/value.go
  runtime/runtime.go
  runtime/stdlib/rlp.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/metatype_test.go
Labels: Improvement

#1567 Meter the rest of the static types
  runtime/convertTypes.go
  runtime/imported_values_memory_metering_test.go
  runtime/interpreter/decode.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/statictype.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Improvement

#1568 Properly transfer indexing expression
  runtime/interpreter/interpreter_expression.go
  runtime/sema/check_expression.go
  runtime/sema/elaboration.go
  runtime/storage_test.go
  runtime/tests/interpreter/indexing_test.go
Labels: Bugfix

#1590 Adjust formulas for calculating memory usage of arithmetic operations on big integers
  runtime/common/metering.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Improvement

#1583 [LS] Update version
  npm-packages/cadence-language-server/package-lock.json
  npm-packages/cadence-language-server/package.json
Labels: Chore

#1593 fix double count memory
  runtime/interpreter/statictype.go
  runtime/interpreter/value.go
Labels: Bugfix

#1584 Elaboration metering
  fuzz.go
  runtime/cmd/cmd.go
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/convertValues_test.go
  runtime/interpreter/storage_test.go
  runtime/interpreter/value_test.go
  runtime/repl.go
  runtime/runtime.go
  runtime/runtime_memory_metering_test.go
  runtime/sema/checker.go
  runtime/sema/elaboration.go
  runtime/sema/type_test.go
  runtime/stdlib/builtin_test.go
  runtime/stdlib/crypto.go
  runtime/tests/checker/interface_test.go
  runtime/tests/checker/utils.go
  runtime/tests/interpreter/import_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/values_test.go
Labels: Feature

#1596 [0.23] Update to CBOR v2.4
  go.mod
  go.sum
Labels: Improvement

#1597 Don't report errors for invalid types
  runtime/sema/check_unary_expression.go
  runtime/sema/check_variable_declaration.go
  runtime/tests/checker/if_test.go
  runtime/tests/checker/operations_test.go
Labels: Improvement

#1605 Separate metering for simple composites
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/interpreter/simplecompositevalue.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Improvement
