Repository onflow/cadence, pull requests merged in 2022-09, with the labels that each got.

#1856 codec cadence.value cadence.type
  encoding/custom/common_codec/common.go
  encoding/custom/sema_codec/codec_test.go
  encoding/custom/sema_codec/decode.go
  encoding/custom/sema_codec/encode.go
  encoding/custom/value_codec/codec_test.go
  encoding/custom/value_codec/decode.go
  encoding/custom/value_codec/encode.go
  runtime/convertValues.go
  types.go
Labels: Performance

#1930 Remove values from tokens, make all code byte slices
  fuzz.go
  runtime/ast/expression.go
  runtime/ast/expression_test.go
  runtime/ast/inspector_test.go
  runtime/ast/string_test.go
  runtime/ast/type_test.go
  runtime/cmd/check/main.go
  runtime/cmd/cmd.go
  runtime/cmd/compile/main.go
  runtime/cmd/execute/repl.go
  runtime/cmd/parse/main.go
  runtime/cmd/parse/main_wasm.go
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/convertValues_test.go
  runtime/environment.go
  runtime/errors.go
  runtime/imported_values_memory_metering_test.go
  runtime/literal.go
  runtime/parser/benchmark_test.go
  runtime/parser/comment.go
  runtime/parser/declaration.go
  runtime/parser/declaration_test.go
  runtime/parser/errors.go
  runtime/parser/expression.go
  runtime/parser/expression_test.go
  runtime/parser/function.go
  runtime/parser/lexer/lexer.go
  runtime/parser/lexer/lexer_test.go
  runtime/parser/lexer/state.go
  runtime/parser/lexer/token.go
  runtime/parser/lexer/tokenstream.go
  runtime/parser/parser.go
  runtime/parser/parser_test.go
  runtime/parser/statement.go
  runtime/parser/statement_test.go
  runtime/parser/transaction.go
  runtime/parser/type.go
  runtime/parser/type_test.go
  runtime/pretty/print.go
  runtime/pretty/print_test.go
  runtime/repl.go
  runtime/runtime_memory_metering_test.go
  runtime/sema/before_extractor_test.go
  runtime/sema/errors.go
  runtime/sema/type_test.go
  runtime/stdlib/account.go
  runtime/stdlib/builtin_test.go
  runtime/stdlib/crypto.go
  runtime/tests/checker/import_test.go
  runtime/tests/checker/interface_test.go
  runtime/tests/checker/utils.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  tools/analysis/analysis_test.go
  tools/analysis/config.go
  tools/analysis/program.go
  tools/pretty/main.go
Labels: Improvement, Performance

#1944 Use WriteByte instead of WriteRune
  encoding/json/encode.go
  runtime/ast/expression.go
  runtime/format/array.go
  runtime/format/composite.go
  runtime/format/dictionary.go
  runtime/format/fix.go
  runtime/parser/parser.go
  runtime/sema/type.go
Labels: Improvement

#1910 Export environment checker and interpreter config to allow customization
  runtime/environment.go
Labels: Improvement

#1945 Refactor activations to be truly generic
  go.mod
  go.sum
  runtime/activations/activations.go
  runtime/activations/activations_test.go
  runtime/compiler/compiler.go
  runtime/compiler/gen.go
  runtime/compiler/local_activations.go
  runtime/environment.go
  runtime/interpreter/gen.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_invocation.go
  runtime/interpreter/variable_activations.go
  runtime/interpreter/variable_activations_extras.go
  runtime/stdlib/builtin_test.go
  runtime/tests/checker/utils.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/composite_value_test.go
  runtime/tests/interpreter/condition_test.go
  runtime/tests/interpreter/container_mutation_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/equality_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/metatype_test.go
  runtime/tests/interpreter/transfer_test.go
Labels: Improvement, Performance

#1953 Clarify that updating a contract does not change stored data
  docs/language/contracts.mdx
Labels: Documentation

#1955 [Test Framework] Update Cadence
  test-framework/go.mod
  test-framework/go.sum
  test-framework/test_runner.go
Labels: Improvement

#1957 Fixed result given by slice
  docs/language/values-and-types.mdx
Labels: Documentation

#1818 Add machinery for parsing and checking `view` functions
  encoding/json/decode.go
  encoding/json/encode.go
  encoding/json/encoding_test.go
  runtime/ast/expression.go
  runtime/ast/expression_test.go
  runtime/ast/function_declaration.go
  runtime/ast/function_declaration_test.go
  runtime/ast/position.go
  runtime/ast/type.go
  runtime/ast/type_test.go
  runtime/convertTypes.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/parser/declaration.go
  runtime/parser/declaration_test.go
  runtime/parser/expression.go
  runtime/parser/expression_test.go
  runtime/parser/function.go
  runtime/parser/keyword.go
  runtime/parser/statement.go
  runtime/parser/statement_test.go
  runtime/parser/transaction.go
  runtime/parser/type.go
  runtime/parser/type_test.go
  runtime/sema/authaccount_contracts.go
  runtime/sema/authaccount_type.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_function.go
  runtime/sema/check_interface_declaration.go
  runtime/sema/checker.go
  runtime/sema/crypto_algorithm_types.go
  runtime/sema/errors.go
  runtime/sema/meta_type.go
  runtime/sema/public_account_contracts.go
  runtime/sema/publicaccount_type.go
  runtime/sema/runtime_type_constructors.go
  runtime/sema/string_type.go
  runtime/sema/type.go
  runtime/sema/type_test.go
  runtime/stdlib/account.go
  runtime/stdlib/assert.go
  runtime/stdlib/block.go
  runtime/stdlib/bls.go
  runtime/stdlib/crypto.go
  runtime/stdlib/log.go
  runtime/stdlib/panic.go
  runtime/stdlib/publickey.go
  runtime/stdlib/rlp.go
  runtime/tests/checker/member_test.go
  runtime/tests/checker/purity_test.go
  runtime/tests/checker/storable_test.go
  runtime/tests/interpreter/interpreter_test.go
  types.go
Labels: Breaking Change

#1960 Move the `fail()` function to native implementation
  Makefile
  runtime/stdlib/contracts/test.cdc
  runtime/stdlib/test.go
  test-framework/Makefile
  test-framework/emulator_backend.go
  test-framework/go.mod
  test-framework/go.sum
  test-framework/test_framework_test.go
Labels: Improvement

#1950 [LS] Multiple language server bugfixes
  languageserver/protocol/mock_conn.go
  languageserver/server/server.go
Labels: Bugfix, Language Server

#1925 Add test case to check optional-chaining argument evaluation order
  runtime/tests/interpreter/interpreter_test.go
Labels: Testing

#1954 [Test Framework] Separate import resolver and file resolver
  test-framework/emulator_backend.go
  test-framework/errors.go
  test-framework/test_framework_test.go
  test-framework/test_runner.go
Labels: Improvement

#1932 Optimize type ID generation, remove location ID
  runtime/cmd/check/main.go
  runtime/cmd/cmd.go
  runtime/common/addresslocation.go
  runtime/common/addresslocation_test.go
  runtime/common/identifierlocation.go
  runtime/common/identifierlocation_test.go
  runtime/common/location.go
  runtime/common/repllocation.go
  runtime/common/repllocation_test.go
  runtime/common/scriptlocation.go
  runtime/common/scriptlocation_test.go
  runtime/common/stringlocation.go
  runtime/common/stringlocation_test.go
  runtime/common/transactionlocation.go
  runtime/common/transactionlocation_test.go
  runtime/contract_update_validation_test.go
  runtime/coverage.go
  runtime/imported_values_memory_metering_test.go
  runtime/resource_duplicate_test.go
  runtime/runtime_test.go
  runtime/sema/checker_test.go
  runtime/stdlib/flow.go
  runtime/stdlib/flow_test.go
  runtime/storage_test.go
  tools/analysis/analysis_test.go
Labels: Improvement, Performance

#1947 Update FAQ
  docs/FAQ.md
Labels: Documentation

#1924 Export functionality required by debugger
  runtime/cmd/cmd.go
  runtime/contract_function_executor.go
  runtime/interpreter/interpreter.go
  runtime/runtime.go
  runtime/script_executor.go
  runtime/transaction_executor.go
Labels: Improvement

#1965 DOCS: Fix line about storable fields in composite types
  docs/language/composite-types.mdx
Labels: Documentation, T-Documentation 📃

#1963 Remove test-framework module
  Makefile
  test-framework/Makefile
  test-framework/emulator_backend.go
  test-framework/errors.go
  test-framework/go.mod
  test-framework/go.sum
  test-framework/test_framework_test.go
  test-framework/test_runner.go
Labels: Technical Debt, Chore

#1967 Remove outdated prettier plugin
  tools/prettier-plugin-cadence/.gitignore
  tools/prettier-plugin-cadence/README.md
  tools/prettier-plugin-cadence/package-lock.json
  tools/prettier-plugin-cadence/package.json
  tools/prettier-plugin-cadence/src/index.ts
  tools/prettier-plugin-cadence/src/nodes.ts
  tools/prettier-plugin-cadence/src/parse.ts
  tools/prettier-plugin-cadence/src/print.ts
  tools/prettier-plugin-cadence/test.cdc
  tools/prettier-plugin-cadence/tsconfig.json
Labels: Chore

#1970 [LS] Update to Cadence v0.26.0
  languageserver/go.mod
  languageserver/go.sum
  languageserver/integration/contracts.go
  languageserver/integration/contracts_test.go
  languageserver/integration/entrypoint.go
  languageserver/integration/entrypoint_test.go
  languageserver/server/linting_test.go
  languageserver/server/server.go
  languageserver/server/stdlib.go
Labels: Improvement, Language Server

#1962 [LS] Release npm cadence-language-server v0.26.1
  npm-packages/cadence-language-server/package-lock.json
  npm-packages/cadence-language-server/package.json
Labels: Language Server

#1964 update playground tutorials
  docs/tutorial/02-hello-world.mdx
  docs/tutorial/03-resources.mdx
  docs/tutorial/04-capabilities.mdx
  docs/tutorial/05-non-fungible-tokens-1.mdx
  docs/tutorial/05-non-fungible-tokens-2.mdx
  docs/tutorial/06-fungible-tokens.mdx
  docs/tutorial/07-marketplace-setup.mdx
  docs/tutorial/08-marketplace-compose.mdx
  docs/tutorial/09-voting.mdx
  docs/tutorial/10-resources-compose.mdx
Labels: Documentation

#1980 Remove docgen module
  Makefile
  tools/docgen/Makefile
  tools/docgen/README.md
  tools/docgen/cmd/main.go
  tools/docgen/doc_generator.go
  tools/docgen/go.mod
  tools/docgen/go.sum
  tools/docgen/templates/markdown-templates.go
  tools/docgen/templates/markdown/base-template
  tools/docgen/templates/markdown/composite-full-template
  tools/docgen/templates/markdown/composite-members-template
  tools/docgen/templates/markdown/composite-template
  tools/docgen/templates/markdown/enum-case-template
  tools/docgen/templates/markdown/enum-template
  tools/docgen/templates/markdown/event-template
  tools/docgen/templates/markdown/field-template
  tools/docgen/templates/markdown/function-template
  tools/docgen/templates/markdown/initializer-template
  tools/docgen/templates/templates.go
  tools/docgen/test/doc_gen_test.go
  tools/docgen/test/outputs/Color.md
  tools/docgen/test/outputs/Direction.md
  tools/docgen/test/outputs/NFT.md
  tools/docgen/test/outputs/NFT_Color.md
  tools/docgen/test/outputs/NFT_Direction.md
  tools/docgen/test/outputs/NFT_SomeStruct.md
  tools/docgen/test/outputs/NFT_SomeStruct_InnerStruct.md
  tools/docgen/test/outputs/SomeInterface.md
  tools/docgen/test/outputs/SomeStruct.md
  tools/docgen/test/outputs/SomeStruct_InnerStruct.md
  tools/docgen/test/outputs/index.md
  tools/docgen/test/outputs/sample3_output.md
  tools/docgen/test/samples/sample1.cdc
  tools/docgen/test/samples/sample2.cdc
  tools/docgen/test/samples/sample3.cdc
  tools/docgen/wasm/main.go
Labels: Chore

#1984 Fix unnecessarily specific cast in storage iteration
  runtime/interpreter/interpreter.go
  runtime/tests/interpreter/account_test.go
Labels: Bugfix

#1988 [0.26] Fix unnecessarily specific cast in storage iteration
  runtime/interpreter/interpreter.go
  runtime/tests/interpreter/account_test.go
Labels: Bugfix

#1989 Add meeting notes for extensions meeting
  meetings/2022-09-20-Extensions.md
Labels: Documentation

#1987 Don't print large integers in error messages
  values.go
Labels: Bugfix

#1979 Track potential jumps, ignore resource invalidations which are only potential
  runtime/sema/check_while.go
  runtime/sema/checker.go
  runtime/sema/function_activations.go
  runtime/sema/resources.go
  runtime/sema/return_info.go
  runtime/tests/checker/resources_test.go
Labels: Bugfix

#1871 Enforce `view` in function conditions
  docs/language/composite-types.mdx
  docs/language/functions.mdx
  runtime/missingmember_test.go
  runtime/nft_test.go
  runtime/sema/check_function.go
  runtime/tests/checker/conditions_test.go
  runtime/tests/checker/nft_test.go
  runtime/tests/checker/purity_test.go
  runtime/tests/checker/resources_test.go
  runtime/tests/interpreter/condition_test.go
  runtime/tests/interpreter/resources_test.go
Labels: Breaking Change

#1991 Add method to get function value's sema function type
  runtime/interpreter/function.go
  runtime/stdlib/test.go
Labels: Improvement

#1976 Interface Default Functions status
  docs/language/interfaces.mdx
Labels: Documentation

#1998 Improve linting errors on CI
  Makefile
Labels: Chore

#1996 Fix batch script
  tools/batch-script/address_provider.go
  tools/batch-script/cmd/get_contracts/main.go
Labels: Bugfix

#1997 Define standard library values in analysis
  runtime/environment.go
  runtime/stdlib/builtin.go
  tools/analysis/analysis_test.go
  tools/analysis/programs.go
Labels: Bugfix

#1994 Improve type information in interpreter errors
  runtime/account_test.go
  runtime/contract_test.go
  runtime/contract_update_validation_test.go
  runtime/deployment_test.go
  runtime/import_test.go
  runtime/interpreter/encode.go
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/simplecompositevalue.go
  runtime/interpreter/value.go
  runtime/literal_test.go
  runtime/program_params_validation_test.go
  runtime/resource_duplicate_test.go
  runtime/rlp_test.go
  runtime/runtime_memory_metering_test.go
  runtime/runtime_test.go
  runtime/sema/errors.go
  runtime/stdlib/test.go
  runtime/storage_test.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/capability_test.go
  runtime/tests/interpreter/composite_value_test.go
  runtime/tests/interpreter/condition_test.go
  runtime/tests/interpreter/container_mutation_test.go
  runtime/tests/interpreter/contract_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/equality_test.go
  runtime/tests/interpreter/fixedpoint_test.go
  runtime/tests/interpreter/import_test.go
  runtime/tests/interpreter/integers_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/invocation_test.go
  runtime/tests/interpreter/member_test.go
  runtime/tests/interpreter/reference_test.go
  runtime/tests/interpreter/resources_test.go
  runtime/tests/interpreter/string_test.go
  runtime/tests/interpreter/transactions_test.go
  runtime/tests/interpreter/transfer_test.go
  runtime/validation_test.go
Labels: Improvement

#1900 [Test Framework] Add documentation for testing framework
  docs/testing-framework.mdx
Labels: Documentation

#2000 Add status callout for the test framework docs
  docs/flow-docs.json
  docs/testing-framework.mdx
Labels: Documentation

#2002 Remove npm-packages for the languageserver and docgen tool
  Makefile
  npm-packages/cadence-docgen/.gitignore
  npm-packages/cadence-docgen/README.md
  npm-packages/cadence-docgen/jest.config.js
  npm-packages/cadence-docgen/package-lock.json
  npm-packages/cadence-docgen/package.json
  npm-packages/cadence-docgen/src/go.js
  npm-packages/cadence-docgen/src/index.ts
  npm-packages/cadence-docgen/tests/index.test.ts
  npm-packages/cadence-docgen/tests/setup.js
  npm-packages/cadence-docgen/tsconfig.json
  npm-packages/cadence-language-server-demo/.gitignore
  npm-packages/cadence-language-server-demo/README.md
  npm-packages/cadence-language-server-demo/package-lock.json
  npm-packages/cadence-language-server-demo/package.json
  npm-packages/cadence-language-server-demo/src/cadence.ts
  npm-packages/cadence-language-server-demo/src/index.html
  npm-packages/cadence-language-server-demo/src/index.ts
  npm-packages/cadence-language-server-demo/tsconfig.json
  npm-packages/cadence-language-server-demo/webpack.config.js
  npm-packages/cadence-language-server/.gitignore
  npm-packages/cadence-language-server/README.md
  npm-packages/cadence-language-server/jest.config.js
  npm-packages/cadence-language-server/package-lock.json
  npm-packages/cadence-language-server/package.json
  npm-packages/cadence-language-server/src/go.js
  npm-packages/cadence-language-server/src/index.ts
  npm-packages/cadence-language-server/tests/index.test.ts
  npm-packages/cadence-language-server/tests/setup.js
  npm-packages/cadence-language-server/tsconfig.json
Labels: Chore

#1992 add key iteration method on dictionaries
  docs/language/control-flow.md
  docs/language/values-and-types.mdx
  runtime/interpreter/value.go
  runtime/sema/type.go
  runtime/tests/checker/resources_test.go
  runtime/tests/interpreter/array_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Feature

#2010 Improve reference expressions
  docs/language/references.md
  runtime/account_test.go
  runtime/ast/expression.go
  runtime/ast/expression_test.go
  runtime/literal.go
  runtime/parser/errors.go
  runtime/parser/expression.go
  runtime/parser/expression_test.go
  runtime/parser/statement_test.go
  runtime/parser/type.go
  runtime/sema/check_array_expression.go
  runtime/sema/check_dictionary_expression.go
  runtime/sema/check_reference_expression.go
  runtime/tests/checker/casting_test.go
  runtime/tests/checker/reference_test.go
Labels: Breaking Change

#2015 Make argument names in test-stdlib compatible with stable cadence
  docs/testing-framework.mdx
  runtime/stdlib/contracts/test.cdc
Labels: Technical Debt

#2016 Improve parser function naming, remove dead code
  runtime/parser/parser.go
  runtime/parser/parser_test.go
  runtime/parser/statement.go
  runtime/parser/transaction.go
Labels: Improvement

#2013 Take argument labels into account when declaring members for nested declarations
  runtime/sema/check_composite_declaration.go
  runtime/tests/checker/invocation_test.go
Labels: Breaking Change

#2012 Add language clarifying the type parameter's type in the private and public path iteration functions
  docs/language/accounts.mdx
Labels: Documentation

#2017 Refactor tests a bit, add FlowLocation to codec
  encoding/cbf/common_codec/common_test.go
  encoding/cbf/common_codec/location.go
Labels: Bugfix, Feature
