Repository onflow/cadence, pull requests merged in 2022-11, with the labels that each got.

#2090 Improve the definite return analysis
  runtime/sema/check_function.go
  runtime/sema/check_invocation_expression.go
  runtime/sema/check_return_statement.go
  runtime/sema/return_info.go
  runtime/tests/checker/resources_test.go
Labels: Breaking Change, Improvement

#2102 rename why-cadence.md to why.md to fix broken link
  docs/why.md
Labels: Documentation

#2109 Fix "log" crashing the REPL
  runtime/cmd/cmd.go
  runtime/repl.go
Labels: Bugfix, Improvement

#2105 Add documentation for String.fromUTF8, numeric types' fromString
  docs/language/values-and-types.mdx
Labels: Documentation

#2117 Improve view modifier parsing and printing
  runtime/ast/expression.go
  runtime/ast/expression_test.go
  runtime/ast/function_declaration.go
  runtime/ast/function_declaration_test.go
  runtime/ast/type.go
  runtime/ast/type_test.go
  runtime/parser/declaration.go
  runtime/parser/declaration_test.go
  runtime/parser/keyword.go
  types.go
Labels: Improvement

#2118 Add JSON language annotations to expected JSON encodings in AST tests
  runtime/ast/argument_test.go
  runtime/ast/block_test.go
  runtime/ast/expression_test.go
  runtime/ast/import_test.go
  runtime/ast/interface_test.go
  runtime/ast/members_test.go
  runtime/ast/pragma_test.go
  runtime/ast/program_test.go
  runtime/ast/statement_test.go
  runtime/ast/transaction_declaration_test.go
  runtime/ast/transfer_test.go
  runtime/ast/type_test.go
  runtime/ast/variable_declaration_test.go
Labels: Testing

#2123 Note in docs that inbox api is not yet released on mainnet
  docs/language/accounts.mdx
Labels: Documentation

#2121 Make view a soft keyword
  runtime/parser/declaration.go
  runtime/parser/expression.go
  runtime/parser/expression_test.go
  runtime/parser/keyword.go
  runtime/parser/statement.go
  runtime/parser/statement_test.go
Labels: Improvement

#2122 Fix documentation
  docs/flow-docs.json
Labels: Documentation

#2124 Sync Stable Cadence
  docs/cadence.ebnf
  docs/flow-docs.json
  docs/language/accounts.mdx
  docs/language/values-and-types.mdx
  docs/why.md
  encoding/json/encoding_test.go
  go.mod
  go.sum
  runtime/ast/argument_test.go
  runtime/ast/block_test.go
  runtime/ast/expression_test.go
  runtime/ast/import_test.go
  runtime/ast/interface_test.go
  runtime/ast/members_test.go
  runtime/ast/pragma_test.go
  runtime/ast/program_test.go
  runtime/ast/statement_test.go
  runtime/ast/transaction_declaration_test.go
  runtime/ast/transfer_test.go
  runtime/ast/type_test.go
  runtime/ast/variable_declaration_test.go
  runtime/cmd/cmd.go
  runtime/cmd/execute/repl.go
  runtime/repl.go
Labels: Chore

#2125 Add more purity annotations to built-in and standard library function types
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/sema/authaccount_contracts.go
  runtime/sema/authaccount_type.go
  runtime/sema/checker.go
  runtime/sema/publicaccount_type.go
  runtime/sema/runtime_type_constructors.go
  runtime/sema/type.go
  runtime/stdlib/account.go
  runtime/stdlib/block.go
  runtime/stdlib/random.go
  runtime/stdlib/test.go
Labels: Improvement

#2126 Clean up function types and type annotations
  runtime/convertValues_test.go
  runtime/interpreter/function_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/sema/anystruct_type.go
  runtime/sema/authaccount_contracts.go
  runtime/sema/authaccount_type.go
  runtime/sema/block.go
  runtime/sema/bool_type.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/checker.go
  runtime/sema/checker_test.go
  runtime/sema/crypto_algorithm_types.go
  runtime/sema/deployed_contract.go
  runtime/sema/meta_type.go
  runtime/sema/never_type.go
  runtime/sema/path_type.go
  runtime/sema/public_account_contracts.go
  runtime/sema/publicaccount_type.go
  runtime/sema/runtime_type_constructors.go
  runtime/sema/string_type.go
  runtime/sema/type.go
  runtime/sema/type_test.go
  runtime/sema/void_type.go
  runtime/stdlib/account.go
  runtime/stdlib/assert.go
  runtime/stdlib/block.go
  runtime/stdlib/bls.go
  runtime/stdlib/crypto.go
  runtime/stdlib/flow.go
  runtime/stdlib/log.go
  runtime/stdlib/panic.go
  runtime/stdlib/publickey.go
  runtime/stdlib/random.go
  runtime/stdlib/rlp.go
  runtime/stdlib/test.go
  runtime/tests/checker/casting_test.go
  runtime/tests/checker/entrypoint_test.go
  runtime/tests/checker/genericfunction_test.go
  runtime/tests/checker/import_test.go
  runtime/tests/checker/member_test.go
  runtime/tests/checker/storable_test.go
  runtime/tests/checker/type_inference_test.go
  runtime/tests/interpreter/condition_test.go
  runtime/tests/interpreter/import_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/invocation_test.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Technical Debt

#2129 Move test framework tests to Cadence
  runtime/stdlib/builtin_test.go
  runtime/stdlib/test.go
  runtime/stdlib/test_test.go
Labels: Testing, Technical Debt

#2130 Fix test matcher
  runtime/stdlib/builtin_test.go
  runtime/stdlib/test.go
  runtime/stdlib/test_test.go
Labels: Bugfix

#2131 Export all keywords
  runtime/parser/declaration.go
  runtime/parser/expression.go
  runtime/parser/function.go
  runtime/parser/keyword.go
  runtime/parser/statement.go
  runtime/parser/transaction.go
  runtime/parser/type.go
Labels: Improvement

#2128 Update CI jobs
  .github/workflows/benchmark.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/compat.yaml.disabled
  .github/workflows/downstream.yml
Labels: Chore

#2115 Fix whitespace parsing between expressions
  runtime/parser/expression.go
  runtime/parser/expression_test.go
  runtime/parser/parser.go
  runtime/parser/parser_test.go
  runtime/parser/statement_test.go
  runtime/parser/type.go
  tools/astexplorer/README.md
  tools/astexplorer/main.go
  tools/astexplorer/package-lock.json
  tools/astexplorer/package.json
  tools/astexplorer/src/cadence.ts
  tools/astexplorer/src/index.html
  tools/astexplorer/src/index.tsx
  tools/astexplorer/src/tree.tsx
  tools/astexplorer/webpack.config.js
  tools/pretty/README.md
  tools/pretty/main.go
Labels: Bugfix, Breaking Change

#2132 Remove outdated callout from the testing-framework docs
  docs/testing-framework.mdx
Labels: Documentation

#2135 Type fixes and improvements
  runtime/sema/any_type.go
  runtime/sema/anyresource_type.go
  runtime/sema/anystruct_type.go
  runtime/sema/block.go
  runtime/sema/bool_type.go
  runtime/sema/character_type.go
  runtime/sema/deployed_contract.go
  runtime/sema/invalid_type.go
  runtime/sema/meta_type.go
  runtime/sema/never_type.go
  runtime/sema/path_type.go
  runtime/sema/simple_type.go
  runtime/sema/storable_type.go
  runtime/sema/string_type.go
  runtime/sema/void_type.go
Labels: Improvement

#2134 Report invalid identifier preceding a member or nested declaration
  runtime/parser/declaration.go
  runtime/parser/declaration_test.go
Labels: Bugfix

#2119 Add static and native modifiers for fields and functions
  fuzz.go
  runtime/ast/composite.go
  runtime/ast/composite_test.go
  runtime/ast/expression.go
  runtime/ast/function_declaration.go
  runtime/ast/function_declaration_test.go
  runtime/ast/inspector_test.go
  runtime/ast/position.go
  runtime/ast/string_test.go
  runtime/cmd/cmd.go
  runtime/cmd/parse/main.go
  runtime/cmd/parse/main_wasm.go
  runtime/common/intervalst/node.go
  runtime/convertValues_test.go
  runtime/environment.go
  runtime/literal.go
  runtime/parser/benchmark_test.go
  runtime/parser/declaration.go
  runtime/parser/declaration_test.go
  runtime/parser/expression_test.go
  runtime/parser/function.go
  runtime/parser/keyword.go
  runtime/parser/parser.go
  runtime/parser/parser_test.go
  runtime/parser/statement.go
  runtime/parser/transaction.go
  runtime/repl.go
  runtime/sema/before_extractor_test.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_function.go
  runtime/sema/check_interface_declaration.go
  runtime/sema/checker.go
  runtime/sema/config.go
  runtime/sema/errors.go
  runtime/sema/type_test.go
  runtime/stdlib/account.go
  runtime/stdlib/builtin_test.go
  runtime/stdlib/crypto.go
  runtime/stdlib/test.go
  runtime/stdlib/test_test.go
  runtime/tests/checker/composite_test.go
  runtime/tests/checker/function_test.go
  runtime/tests/checker/import_test.go
  runtime/tests/checker/interface_test.go
  runtime/tests/checker/utils.go
  runtime/tests/interpreter/interpreter_test.go
  tools/analysis/programs.go
  tools/astexplorer/main.go
  tools/pretty/main.go
Labels: Feature

#2136 Fix parsing of array and dictionary expressions
  runtime/parser/expression.go
  runtime/parser/expression_test.go
  tools/compare-parsing/main.go
Labels: Bugfix

#2138 Improve error messages for values/types that cannot be imported or exported
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/errors.go
  runtime/runtime_test.go
  runtime/script_executor.go
  runtime/sema/any_type.go
  runtime/sema/anyresource_type.go
  runtime/sema/anystruct_type.go
  runtime/sema/block.go
  runtime/sema/bool_type.go
  runtime/sema/character_type.go
  runtime/sema/deployed_contract.go
  runtime/sema/invalid_type.go
  runtime/sema/meta_type.go
  runtime/sema/never_type.go
  runtime/sema/path_type.go
  runtime/sema/simple_type.go
  runtime/sema/storable_type.go
  runtime/sema/string_type.go
  runtime/sema/type.go
  runtime/sema/void_type.go
Labels: Improvement

#2144 Add meeting notes for interface inheritance meeting
  meetings/2022-11-16-Interface-Inheritance.md
Labels: Documentation

#2146 Update design-patterns.mdx
  docs/design-patterns.mdx
Labels: Documentation

#2110 Meter big int allocations in parser, improve over-estimation
  runtime/common/bigint.go
  runtime/common/bigint_test.go
  runtime/common/integerliteralkind.go
  runtime/common/integerliteralkind_string.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/parser/errors.go
  runtime/parser/expression.go
  runtime/parser/expression_test.go
  runtime/parser/type_test.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Improvement

#1934 Implement FLIP #1071: borrow contract
  runtime/account_test.go
  runtime/interpreter/accountcontracts.go
  runtime/sema/account_contracts.go
  runtime/sema/authaccount_contracts.go
  runtime/sema/public_account_contracts.go
  runtime/stdlib/account.go
  runtime/tests/checker/account_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Feature

#2143 Improve parameter AST node
  runtime/ast/expression_test.go
  runtime/ast/function_declaration_test.go
  runtime/ast/parameter.go
  runtime/parser/declaration_test.go
  runtime/parser/function.go
  runtime/parser/type_test.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Improvement

#2149 Add link to style guide
  docs/flow-docs.json
Labels: Documentation, Dev Portal Documentation

#2150 Sync Stable Cadence branch
  .github/workflows/ci.yml
  docs/design-patterns.mdx
  docs/flow-docs.json
  docs/syntax-highlighting.md
  meetings/2022-11-16-Interface-Inheritance.md
  runtime/account_test.go
  runtime/ast/expression_test.go
  runtime/ast/function_declaration_test.go
  runtime/ast/parameter.go
  runtime/common/bigint.go
  runtime/common/bigint_test.go
  runtime/common/integerliteralkind.go
  runtime/common/integerliteralkind_string.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/errors.go
  runtime/interpreter/accountcontracts.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/parser/declaration_test.go
  runtime/parser/errors.go
  runtime/parser/expression.go
  runtime/parser/expression_test.go
  runtime/parser/function.go
  runtime/parser/type_test.go
  runtime/runtime_test.go
  runtime/script_executor.go
  runtime/sema/account_contracts.go
  runtime/sema/any_type.go
  runtime/sema/anyresource_type.go
  runtime/sema/anystruct_type.go
  runtime/sema/authaccount_contracts.go
  runtime/sema/block.go
  runtime/sema/bool_type.go
  runtime/sema/character_type.go
  runtime/sema/deployed_contract.go
  runtime/sema/invalid_type.go
  runtime/sema/meta_type.go
  runtime/sema/never_type.go
  runtime/sema/path_type.go
  runtime/sema/public_account_contracts.go
  runtime/sema/simple_type.go
  runtime/sema/storable_type.go
  runtime/sema/string_type.go
  runtime/sema/type.go
  runtime/sema/void_type.go
  runtime/stdlib/account.go
  runtime/tests/checker/account_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  tools/compare-parsing/main.go
Labels: Chore

#2152 Clean up metering
  runtime/ast/expression.go
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/imported_values_memory_metering_test.go
  runtime/interpreter/decode.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Technical Debt

#2127 Improve allocations in checker
  runtime/interpreter/function_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/statictype.go
  runtime/interpreter/value_test.go
  runtime/runtime.go
  runtime/sema/account_contracts.go
  runtime/sema/authaccount_contracts.go
  runtime/sema/authaccount_type.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_event_declaration.go
  runtime/sema/check_function.go
  runtime/sema/check_transaction_declaration.go
  runtime/sema/checker.go
  runtime/sema/checker_test.go
  runtime/sema/crypto_algorithm_types.go
  runtime/sema/entrypoint.go
  runtime/sema/errors.go
  runtime/sema/function_activations.go
  runtime/sema/meta_type.go
  runtime/sema/positioninfo.go
  runtime/sema/publicaccount_type.go
  runtime/sema/runtime_type_constructors.go
  runtime/sema/string_type.go
  runtime/sema/type.go
  runtime/sema/type_test.go
  runtime/stdlib/account.go
  runtime/stdlib/assert.go
  runtime/stdlib/block.go
  runtime/stdlib/bls.go
  runtime/stdlib/crypto.go
  runtime/stdlib/flow.go
  runtime/stdlib/log.go
  runtime/stdlib/panic.go
  runtime/stdlib/publickey.go
  runtime/stdlib/rlp.go
  runtime/stdlib/test.go
  runtime/tests/checker/casting_test.go
  runtime/tests/checker/entrypoint_test.go
  runtime/tests/checker/genericfunction_test.go
  runtime/tests/checker/interface_test.go
  runtime/tests/checker/invocation_test.go
  runtime/tests/checker/member_test.go
  runtime/tests/checker/predeclaredvalues_test.go
  runtime/tests/checker/type_inference_test.go
  runtime/tests/interpreter/condition_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/runtimetype_test.go
Labels: Technical Debt, Performance

#1931 Parsing for attachments and related operations
  runtime/ast/attachment.go
  runtime/ast/attachment_test.go
  runtime/ast/elementtype.go
  runtime/ast/elementtype_string.go
  runtime/ast/precedence.go
  runtime/common/declarationkind.go
  runtime/common/declarationkind_string.go
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/parser/declaration.go
  runtime/parser/declaration_test.go
  runtime/parser/expression.go
  runtime/parser/expression_test.go
  runtime/parser/keyword.go
  runtime/parser/statement.go
  runtime/parser/statement_test.go
Labels: Feature

#2155 Address some tech debt
  runtime/environment.go
  runtime/interpreter/account.go
  runtime/sema/checker.go
  runtime/sema/type.go
Labels: Improvement, Technical Debt

#2156 Improve reference static type
  runtime/interpreter/statictype.go
Labels: Improvement, Technical Debt

#2024 Change for-loop variables from per-loop to per-iteration
  runtime/interpreter/interpreter_statement.go
  runtime/tests/interpreter/for_test.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Breaking Change, Improvement

#2158 Update Stable Cadence feature branches in downstream dependencies
  .github/workflows/downstream.yml
Labels: Chore

#2142 Fix links in documentation
  docs/design-patterns.mdx
  docs/language/imports.mdx
  docs/measuring-time.mdx
  docs/security-best-practices.mdx
  docs/tutorial/01-first-steps.mdx
  docs/tutorial/02-hello-world.mdx
  docs/tutorial/03-resources.mdx
  docs/tutorial/04-capabilities.mdx
  docs/tutorial/05-non-fungible-tokens-1.mdx
  docs/tutorial/05-non-fungible-tokens-2.mdx
  docs/tutorial/06-fungible-tokens.mdx
  docs/tutorial/08-marketplace-compose.mdx
Labels: Documentation

#2161 Improve type mismatch errors
  runtime/deployment_test.go
  runtime/errors.go
  runtime/inbox_test.go
  runtime/interpreter/errors.go
  runtime/runtime_test.go
  runtime/sema/errors.go
  runtime/sema/errors_test.go
  runtime/stdlib/account.go
Labels: Improvement

#2166 Improve sema
  runtime/convertValues.go
  runtime/interpreter/account.go
  runtime/interpreter/accountinbox.go
  runtime/interpreter/accountkey.go
  runtime/interpreter/accountkeys.go
  runtime/interpreter/value.go
  runtime/interpreter/value_publickey.go
  runtime/sema/authaccount_type.go
  runtime/sema/publicaccount_type.go
  runtime/sema/simple_type.go
  runtime/sema/type.go
  runtime/stdlib/account.go
  runtime/stdlib/publickey.go
  runtime/stdlib/test.go
Labels: Improvement

#2162 Optimize sema
  runtime/interpreter/primitivestatictype.go
  runtime/interpreter/value.go
  runtime/literal_test.go
  runtime/runtime_test.go
  runtime/sema/authaccount_type.go
  runtime/sema/check_expression.go
  runtime/sema/checker.go
  runtime/sema/deployed_contract.go
  runtime/sema/publicaccount_type.go
  runtime/sema/runtime_type_constructors.go
  runtime/sema/simple_type.go
  runtime/sema/type.go
  runtime/sema/type_tags.go
  runtime/sema/type_test.go
  runtime/stdlib/account.go
  runtime/stdlib/flow.go
  runtime/tests/checker/builtinfunctions_test.go
  runtime/tests/checker/capability_test.go
  runtime/tests/checker/dynamic_casting_test.go
  runtime/tests/checker/events_test.go
  runtime/tests/checker/integer_test.go
  runtime/tests/checker/storable_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Improvement, Performance

#2171 Transaction pre-conditions must also be `view`
  runtime/sema/check_conditions.go
  runtime/sema/check_function.go
  runtime/tests/checker/transactions_test.go
  version.go
Labels: Bugfix

#2159 Use invocation's interpreter
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
Labels: Improvement
