Repository onflow/cadence, pull requests merged in 2022-03, with the labels that each got.

#1460 Fix resource checking
  runtime/sema/check_conditional.go
  runtime/sema/check_unary_expression.go
  runtime/sema/checker.go
  runtime/sema/errors.go
  runtime/tests/checker/resources_test.go
Labels: Bugfix

#1461 Check transfer and use of transfered or destroyed resources at runtime
  runtime/cmd/decode-state-values/main.go
  runtime/compiler/wasm/writer_test.go
  runtime/convertValues.go
  runtime/interface.go
  runtime/interpreter/inspect_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_statement.go
  runtime/interpreter/interpreter_test.go
  runtime/interpreter/storage_test.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/storage_test.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/enum_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/resources_test.go
  runtime/tests/interpreter/values_test.go
Labels: Feature

#1441 use feature branch for cadence->flow-go sync PRs
  .github/workflows/sync-flow-go.yml
Labels: Chore

#1465 Fix CI typo feature-secure-cadence
  .github/workflows/sync-flow-go.yml
Labels: Bugfix

#1448 [0.23] Add tracing (backport #1179)
  go.mod
  go.sum
  runtime/interface.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_import.go
  runtime/interpreter/interpreter_tracing.go
  runtime/interpreter/value.go
  runtime/runtime.go
  runtime/runtime_test.go
Labels: Feature

#1452 [0.23] Add index to for loop (backport #1216)
  docs/language/control-flow.md
  runtime/ast/statement.go
  runtime/ast/statement_test.go
  runtime/interpreter/interpreter_statement.go
  runtime/parser2/statement.go
  runtime/parser2/statement_test.go
  runtime/sema/check_for.go
  runtime/tests/checker/for_test.go
  runtime/tests/interpreter/for_test.go
Labels: Feature

#1454 [0.23] Remove PublicKey.isValid and .Validated (backport #1273)
  .gitignore
Labels: Feature, Improvement

#1456 [0.23] Add RLP decoding utility methods (backport #1397)
  docs/language/built-in-functions.md
  runtime/crypto_test.go
  runtime/stdlib/builtin.go
  runtime/stdlib/rlp.go
  runtime/stdlib/rlp/rlp.go
  runtime/stdlib/rlp/rlp_test.go
  runtime/stdlib/rlp_test.go
  runtime/tests/checker/rlp_test.go
Labels: Feature

#1457 [0.23] Improve BLS API (backport #1417)
  runtime/cmd/parse/main.go
  runtime/interpreter/interpreter.go
Labels: Improvement

#1459 Fix resource field nesting check for enum raw value field
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_interface_declaration.go
  runtime/sema/checker.go
  runtime/sema/type.go
  runtime/tests/checker/resources_test.go
Labels: Bugfix

#1462 [0.21] Fix resource field nesting check for enum raw value field (backport #1460)
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_interface_declaration.go
  runtime/sema/checker.go
  runtime/sema/type.go
  runtime/tests/checker/resources_test.go
Labels: Bugfix

#1463 [0.21] Fix resource checking (backport #1460)
  runtime/sema/check_conditional.go
  runtime/sema/check_unary_expression.go
  runtime/sema/checker.go
  runtime/sema/errors.go
  runtime/tests/checker/resources_test.go
Labels: Bugfix

#1464 Check use of invalidated resources at runtime
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_statement.go
  runtime/tests/interpreter/resources_test.go
Labels: Improvement

#1450 Expand interpreter tracing for composite, array and dictionary types
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_import.go
  runtime/interpreter/interpreter_tracing.go
  runtime/interpreter/interpreter_tracing_test.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Improvement

#1468 [0.23] Expand interpreter tracing for composite, array and dictionary types (backport #1450)
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_import.go
  runtime/interpreter/interpreter_tracing.go
  runtime/interpreter/interpreter_tracing_test.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Improvement

#1466 [0.23] Update to atree 82a5e53e8248 (backport #1421)
  go.mod
  go.sum
  runtime/storage_test.go
Labels: Bugfix

#1470 Bump onflow/atree to v0.2.0
  go.mod
  go.sum
Labels: Improvement, Performance

#1432 Add test for CharacterValue.HashInput
  runtime/interpreter/value_test.go
Labels: Testing

#1472 Add container memory metering
  runtime/convertValues_test.go
  runtime/interface.go
  runtime/interpreter/account.go
  runtime/interpreter/accountcontracts.go
  runtime/interpreter/accountkey.go
  runtime/interpreter/accountkeys.go
  runtime/interpreter/block.go
  runtime/interpreter/deployedcontract.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_transaction.go
  runtime/interpreter/simplecompositevalue.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/stdlib/bls.go
  runtime/stdlib/rlp.go
  runtime/tests/checker/utils.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/container_mutation_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/reference_test.go
  runtime/tests/interpreter/transactions_test.go
Labels: Feature

#1425 Various regression tests
  runtime/convertValues_test.go
  runtime/parser2/parser_test.go
  runtime/tests/checker/casting_test.go
  runtime/tests/checker/contract_test.go
  runtime/tests/checker/declaration_test.go
  runtime/tests/checker/interface_test.go
  runtime/tests/checker/nesting_test.go
  runtime/tests/checker/resources_test.go
Labels: Testing

#1474 Add memory metering for interpreted functions
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/interpreter/function.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Feature

#1475 Add memory metering for host functions
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/interpreter/account.go
  runtime/interpreter/function.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/runtime.go
  runtime/stdlib/bls.go
  runtime/stdlib/functions.go
  runtime/stdlib/hashalgorithm.go
  runtime/stdlib/rlp.go
  runtime/tests/interpreter/condition_test.go
  runtime/tests/interpreter/import_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/metatype_test.go
Labels: Feature

#1477 Add bound functions memory metering
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/interpreter/function.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Feature

#1473 do not wrap conditional in ${{}}
  .github/workflows/sync-flow-go.yml
Labels: Bugfix

#1478 Improve string metering
  runtime/common/metering.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/interpreter/decode.go
  runtime/interpreter/deepcopyremove_test.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_tracing_test.go
  runtime/interpreter/number.go
  runtime/interpreter/number_test.go
  runtime/interpreter/storage_test.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/parser2/lexer/state.go
  runtime/runtime.go
  runtime/stdlib/builtin_test.go
  runtime/tests/interpreter/composite_value_test.go
  runtime/tests/interpreter/condition_test.go
  runtime/tests/interpreter/import_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/metatype_test.go
  runtime/tests/interpreter/metering_test.go
  runtime/tests/interpreter/uuid_test.go
  runtime/tests/interpreter/values_test.go
Labels: Improvement

#1482 Add test-cases for container value iteration metering
  runtime/interpreter/storage.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Testing

#1483 Add memory metering for optional values
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/imported_values_memory_metering_test.go
  runtime/interpreter/deepcopyremove_test.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/inspect_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_test.go
  runtime/interpreter/storage_test.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/runtime.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/container_mutation_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/if_test.go
  runtime/tests/interpreter/integers_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/reference_test.go
  runtime/tests/interpreter/resources_test.go
  runtime/tests/interpreter/switch_test.go
  runtime/tests/interpreter/values_test.go
Labels: Feature

#1480 Fix value transfer type check
  runtime/sema/type.go
  runtime/tests/checker/restriction_test.go
  runtime/tests/interpreter/transfer_test.go
Labels: Bugfix

#1486 Extend subtyping rule for restricted type
  runtime/sema/type.go
  runtime/tests/checker/restriction_test.go
  runtime/tests/interpreter/transfer_test.go
Labels: Bugfix, Improvement

#1485 String metering is length + 1 to account for empty strings
  runtime/common/metering.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Bugfix

#1492 Bump codecov-action from v1 to v2 in ci.yml
  .github/workflows/ci.yml
Labels: Testing, Chore

#1490 Meter memory for IntValue and UIntValue creation, addition, multiplication, and negation
  go.mod
  go.sum
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/deployment_test.go
  runtime/ft_test.go
  runtime/interpreter/conversion_test.go
  runtime/interpreter/decode.go
  runtime/interpreter/div_mod_test.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_statement.go
  runtime/interpreter/interpreter_tracing_test.go
  runtime/interpreter/minus_test.go
  runtime/interpreter/mul_test.go
  runtime/interpreter/negate_test.go
  runtime/interpreter/number_test.go
  runtime/interpreter/plus_test.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/literal.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/arithmetic_test.go
  runtime/tests/interpreter/bitwise_test.go
  runtime/tests/interpreter/capability_test.go
  runtime/tests/interpreter/condition_test.go
  runtime/tests/interpreter/declaration_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/for_test.go
  runtime/tests/interpreter/if_test.go
  runtime/tests/interpreter/import_test.go
  runtime/tests/interpreter/integers_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/metatype_test.go
  runtime/tests/interpreter/switch_test.go
  runtime/tests/interpreter/transactions_test.go
  runtime/tests/interpreter/values_test.go
  runtime/tests/interpreter/while_test.go
  vm/vm.go
Labels: Improvement

#1469 Moving computation metering and limit enforcement responsibility to the environment
  runtime/common/computationkind.go
  runtime/common/computationkind_string.go
  runtime/errors.go
  runtime/interface.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_statement.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/stdlib/rlp.go
Labels: Improvement

#1493 Finish memory metering for Int and UInt operations
  runtime/common/metering.go
  runtime/interpreter/div_mod_test.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/minus_test.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Improvement

#1494 Add memory metering for `Int8`, `Int16`, `Int32` and `Int64` Values
  runtime/common/metering.go
  runtime/convertValues.go
  runtime/imported_values_memory_metering_test.go
  runtime/interpreter/decode.go
  runtime/interpreter/div_mod_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/minus_test.go
  runtime/interpreter/mul_test.go
  runtime/interpreter/plus_test.go
  runtime/interpreter/value.go
  runtime/literal.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Improvement

#1498 Meter bitwise operations of fixed-sized int values
  runtime/interpreter/value.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Improvement

#1495 Meter fixed-size UInt* values
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/imported_values_memory_metering_test.go
  runtime/interpreter/account.go
  runtime/interpreter/conversion.go
  runtime/interpreter/conversion_test.go
  runtime/interpreter/decode.go
  runtime/interpreter/div_mod_test.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/minus_test.go
  runtime/interpreter/mul_test.go
  runtime/interpreter/plus_test.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/literal.go
  runtime/runtime.go
  runtime/stdlib/flow.go
  runtime/stdlib/hashalgorithm.go
  runtime/stdlib/signaturealgorithm.go
  runtime/storage_test.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/arithmetic_test.go
  runtime/tests/interpreter/bitwise_test.go
  runtime/tests/interpreter/builtinfunctions_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/enum_test.go
  runtime/tests/interpreter/import_test.go
  runtime/tests/interpreter/integers_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/string_test.go
  runtime/tests/interpreter/uuid_test.go
  runtime/tests/interpreter/values_test.go
Labels: Improvement

#1501 Use unmetered constructor for `Int*` values in all places
  runtime/convertValues_test.go
  runtime/interpreter/div_mod_test.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/negate_test.go
  runtime/interpreter/value_test.go
  runtime/tests/interpreter/arithmetic_test.go
  runtime/tests/interpreter/bitwise_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/enum_test.go
  runtime/tests/interpreter/integers_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/values_test.go
Labels: Improvement, Technical Debt

#1499 Add memory metering for word* values
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/imported_values_memory_metering_test.go
  runtime/interpreter/decode.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/tests/interpreter/arithmetic_test.go
  runtime/tests/interpreter/bitwise_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/integers_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/values_test.go
Labels: Improvement

#1488 Meter calls to `Transfer`
  runtime/interpreter/value.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Feature

#1508 Bump onflow/atree from 0.2.0 to 0.3.0
  go.mod
  go.sum
Labels: Improvement

#1507 Remove block memory kind
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
Labels: Feature

#1442 Memory metering for small types
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/imported_values_memory_metering_test.go
  runtime/interpreter/decode.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/errors_test.go
  runtime/interpreter/function.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_statement.go
  runtime/interpreter/simplecompositevalue.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/capability_test.go
  runtime/tests/interpreter/container_mutation_test.go
  runtime/tests/interpreter/equality_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/values_test.go
Labels: Improvement

#1512 Robert/metering small types 2
  runtime/interpreter/decode.go
  runtime/interpreter/interpreter.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Improvement

#1514 atree string value metering
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/convertValues.go
  runtime/imported_values_memory_metering_test.go
  runtime/interpreter/decode.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/stringatreevalue.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Feature

#1471 Best Practices and Anti-Patterns Updates
  docs/anti-patterns.mdx
  docs/design-patterns.mdx
  docs/measuring-time.mdx
  docs/msg-sender.mdx
Labels: Documentation, Improvement, Dev Portal Documentation, T-Documentation 📃

#1522 Check address length before decoding
  runtime/interpreter/decode.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/value.go
Labels: Improvement

#1524 Fix field initialization: nested intersection should not override outer set
  runtime/sema/check_conditional.go
  runtime/sema/member_set.go
  runtime/sema/member_set_test.go
  runtime/tests/checker/initialization_test.go
Labels: Bugfix

#1527 Forbid reinitialization of variable, resource-kinded fields
  runtime/sema/check_assignment.go
  runtime/sema/errors.go
  runtime/tests/checker/initialization_test.go
Labels: Bugfix

#1525 Commit storage before getting account storage capacity
  runtime/interpreter/account.go
  runtime/runtime.go
  runtime/tests/interpreter/account_test.go
Labels: Bugfix

#1531 Memory metering for variables
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/imported_values_memory_metering_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/variable.go
  runtime/stdlib/crypto.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Feature

#1521 Add memory metering for fixed-size numbers
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/ft_test.go
  runtime/imported_values_memory_metering_test.go
  runtime/interpreter/decode.go
  runtime/interpreter/div_mod_test.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/runtime.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/arithmetic_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/fixedpoint_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/values_test.go
Labels: Improvement

#1431 Added test to partially ensure HashableValue does not regress
  runtime/interpreter/encode.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/hashablevalue.go
  runtime/interpreter/hashablevalue_test.go
  runtime/interpreter/primitivestatictype.go
  runtime/interpreter/primitivestatictype_string.go
  runtime/interpreter/statictype_test.go
Labels: Testing

#1526 Meter results of logical operations on number values
  runtime/ft_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Improvement

#1519 Capability-based Access Control Document Improvements
  docs/language/capability-based-access-control.md
Labels: Documentation

#1533 Add memory metering for tokens
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/imported_values_memory_metering_test.go
  runtime/parser2/benchmark_test.go
  runtime/parser2/lexer/lexer.go
  runtime/parser2/lexer/memory_usage.go
  runtime/parser2/lexer/state.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Improvement

#1535 Add metering for locations
  encoding/json/decode.go
  encoding/json/encoding_test.go
  runtime/account_test.go
  runtime/cmd/check/main.go
  runtime/cmd/cmd.go
  runtime/cmd/compile/main.go
  runtime/cmd/parse/main.go
  runtime/common/addresslocation.go
  runtime/common/addresslocation_test.go
  runtime/common/identifierlocation.go
  runtime/common/identifierlocation_test.go
  runtime/common/location.go
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/common/repllocation.go
  runtime/common/scriptlocation.go
  runtime/common/scriptlocation_test.go
  runtime/common/stringlocation.go
  runtime/common/stringlocation_test.go
  runtime/common/transactionlocation.go
  runtime/common/transactionlocation_test.go
  runtime/convertValues_test.go
  runtime/crypto_test.go
  runtime/ft_test.go
  runtime/imported_values_memory_metering_test.go
  runtime/interpreter/decode.go
  runtime/interpreter/interpreter.go
  runtime/missingmember_test.go
  runtime/parser2/declaration.go
  runtime/program_params_validation_test.go
  runtime/rlp_test.go
  runtime/runtime.go
  runtime/runtime_memory_metering_test.go
  runtime/runtime_test.go
  runtime/stdlib/flow.go
  runtime/storage_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/validation_test.go
Labels: Feature
