Repository onflow/cadence, pull requests merged in 2022-05, with the labels that each got.

#1591 Meter Atree DataSlab and MetaDataSlab directly
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/interpreter/primitivestatictype.go
  runtime/interpreter/simplecompositevalue.go
  runtime/interpreter/statictype.go
  runtime/interpreter/storage.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Improvement

#1616 Meter variable activation
  runtime/activations/activations.go
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/compiler/local_activations.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/variable_activations.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Improvement

#1624 Add element overhead to atree array metering
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Improvement

#1623 Meter memory for pre-allocated elements in atree map
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Improvement

#1625 Fix erroneous report of resource invalidation when executing a pre-condition
  runtime/interpreter/interpreter.go
  runtime/missingmember_test.go
  runtime/tests/interpreter/resources_test.go
Labels: Bugfix

#1632 Sync memory-metering branch with master branch
  languageserver/go.mod
  languageserver/go.sum
  languageserver/jsonrpc2/server.go
  languageserver/server/server.go
  runtime/sema/check_unary_expression.go
  runtime/sema/check_variable_declaration.go
  runtime/tests/checker/if_test.go
  runtime/tests/checker/operations_test.go
Labels: Chore

#1601 [LS] Debugging documentation and utility functions
  languageserver/README.md
  languageserver/run.sh
  languageserver/test/util.go
Labels: Improvement

#1637 Sync memory metering branch with master
  languageserver/README.md
  languageserver/run.sh
  languageserver/server/server.go
  languageserver/test/util.go
  runtime/interpreter/interpreter.go
  runtime/missingmember_test.go
  runtime/tests/interpreter/resources_test.go
Labels: Chore

#1630 Track inner values of resource-kinded optionals
  runtime/interpreter/interpreter_expression.go
  runtime/missingmember_test.go
  runtime/tests/interpreter/resources_test.go
Labels: Bugfix

#1635 adjust big int metering minor errors
  runtime/common/metering.go
Labels: Bugfix, Improvement

#1631 Memory meter static-type to sema-type conversion
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/statictype.go
  runtime/sema/type.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Improvement

#1643 [0.23] Reads of missing storage maps should not cause creation
  runtime/cmd/decode-state-values/main.go
  runtime/contract_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/storage.go
  runtime/interpreter/storage_test.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/storage.go
  runtime/storage_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/metatype_test.go
Labels: Bugfix

#1644 Fix issue with programs cache on contract update
  runtime/contract_update_validation_test.go
  runtime/interface.go
  runtime/runtime.go
Labels: Bugfix

#1646 Merge master into memory metering branch
  .github/workflows/sync-flow-go.yml.disabled
  runtime/cmd/execute/repl.go
  runtime/contract_update_validation_test.go
  runtime/interface.go
  runtime/interpreter/interpreter_expression.go
  runtime/missingmember_test.go
  runtime/runtime.go
  runtime/tests/interpreter/resources_test.go
Labels: Chore

#1627 Language reference docs improvement
  docs/language/accounts.mdx
  docs/language/interfaces.mdx
Labels: Documentation, Improvement, T-Documentation 📃

#1610 Pool lexers to reduce allocations and improve performance
  .github/workflows/benchmark.yml
  runtime/parser2/lexer/lexer.go
  runtime/parser2/lexer/tokenstream.go
  runtime/parser2/parser.go
Labels: Performance

#1647 Improve memory metering
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/convertValues.go
  runtime/interpreter/decode.go
  runtime/interpreter/encode.go
  runtime/interpreter/function.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_invocation.go
  runtime/interpreter/storage.go
  runtime/interpreter/storagemap.go
  runtime/interpreter/value.go
  runtime/runtime.go
  runtime/storage.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/values_test.go
Labels: Improvement

#1622 Fix parsing of reference expressions
  runtime/parser2/expression.go
  runtime/parser2/expression_test.go
  runtime/tests/checker/reference_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Bugfix

#1620 Limit number of tokens which can be replayed (reparsed)
  runtime/parser2/expression_test.go
  runtime/parser2/parser.go
Labels: Improvement

#1613 Improve constant-sized type parsing
  runtime/parser2/lexer/tokentype.go
  runtime/parser2/type.go
  runtime/parser2/type_test.go
  runtime/tests/checker/arrays_dictionaries_test.go
Labels: Improvement

#1626 Meter location ID generation
  encoding/json/encode.go
  runtime/common/addresslocation.go
  runtime/common/identifierlocation.go
  runtime/common/location.go
  runtime/common/repllocation.go
  runtime/common/scriptlocation.go
  runtime/common/stringlocation.go
  runtime/common/transactionlocation.go
  runtime/imported_values_memory_metering_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/statictype.go
  runtime/interpreter/value.go
  runtime/runtime_memory_metering_test.go
  runtime/runtime_test.go
  runtime/sema/type.go
  runtime/stdlib/flow.go
  runtime/tests/interpreter/memory_metering_test.go
  types.go
Labels: Improvement

#1662 Memory meter committing storage deltas
  go.cap
  go.mod
  go.sum
  runtime/common/location.go
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/convertValues.go
  runtime/imported_values_memory_metering_test.go
  runtime/interpreter/statictype.go
  runtime/parser2/declaration.go
  runtime/runtime_memory_metering_test.go
  runtime/storage.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Improvement

#1660 Wrap memory error in FatalError and check for it when parsing
  runtime/common/metering.go
  runtime/imported_values_memory_metering_test.go
  runtime/parser2/expression.go
  runtime/parser2/expression_test.go
  runtime/parser2/lexer/lexer.go
  runtime/parser2/parser.go
  runtime/parser2/parser_test.go
Labels: Bugfix

#1666 Merge memory metering branch to master
  runtime/common/metering.go
  runtime/imported_values_memory_metering_test.go
  runtime/parser2/expression.go
  runtime/parser2/expression_test.go
  runtime/parser2/lexer/lexer.go
  runtime/parser2/parser.go
  runtime/parser2/parser_test.go
Labels: Chore

#1657 Meter byte array conversion
  runtime/interpreter/conversion.go
  runtime/interpreter/interpreter.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Improvement

#1667 Refactor memory kinds and memory usages
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/imported_values_memory_metering_test.go
  runtime/interpreter/decode.go
  runtime/interpreter/function.go
  runtime/interpreter/primitivestatictype.go
  runtime/interpreter/simplecompositevalue.go
  runtime/interpreter/statictype.go
  runtime/interpreter/value.go
  runtime/runtime_memory_metering_test.go
  runtime/tests/interpreter/memory_metering_test.go
  types.go
  values.go
Labels: Improvement, Technical Debt

#1664 Limit depth of expressions and types
  runtime/parser2/errors.go
  runtime/parser2/expression.go
  runtime/parser2/expression_test.go
  runtime/parser2/parser.go
  runtime/parser2/parser_test.go
  runtime/parser2/type.go
Labels: Improvement

#1655 Memory meter type value creation
  runtime/common/metering.go
  runtime/convertValues.go
  runtime/interpreter/decode.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/memory_metering_test.go
  types.go
Labels: Improvement

#1656 Improve memory metering for String.toLower
  runtime/interpreter/value.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Improvement

#1668 Add token limit
  runtime/parser2/lexer/lexer.go
  runtime/parser2/lexer/lexer_test.go
Labels: Improvement

#1663 Fix local token replay limit, add global replay limit
  runtime/parser2/expression.go
  runtime/parser2/expression_test.go
  runtime/parser2/parser.go
  runtime/parser2/parser_test.go
Labels: Improvement

#1562 Add a checker option to short-circuit error reporting
  codecov.yml
  runtime/sema/check_casting_expression.go
  runtime/sema/check_force_expression.go
  runtime/sema/checker.go
  runtime/sema/type.go
  runtime/tests/checker/errors_test.go
Labels: Feature

#1609 Meter static types string conversion
  runtime/common/metering.go
  runtime/interpreter/function.go
  runtime/interpreter/primitivestatictype.go
  runtime/interpreter/statictype.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Improvement

#1676 Add `type` function to list of functions in `AuthAccount` documentation
  docs/language/accounts.mdx
Labels: Documentation

#1678 Handle and wrap non-error type panics in interpreterRuntime
  runtime/runtime.go
  runtime/runtime_test.go
Labels: Improvement
