Repository onflow/cadence, pull requests merged in 2023-01, with the labels that each got.

#2205 Correct definition of block view
  docs/language/environment-information.md
Labels: Documentation

#2203 Add equal method for cadence external types
  runtime/sema/type.go
  types.go
  types_test.go
Labels: Improvement

#2213 Fix function activations
  runtime/sema/checker.go
  runtime/sema/function_activations.go
  runtime/tests/checker/return_test.go
Labels: Bugfix

#2194 improve wording and classification of some interpreter errors
  runtime/convertValues.go
  runtime/interpreter/errors.go
  runtime/interpreter/errors_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_statement.go
  runtime/interpreter/value.go
  runtime/interpreter/value_accountreference.go
  runtime/tests/interpreter/contract_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Improvement

#2218 Revert "don't ignore invalid identifier" / PR
  runtime/parser/declaration.go
  runtime/parser/declaration_test.go
Labels: Bugfix

#2216 Add documentation for contracts.borrow
  docs/language/accounts.mdx
  docs/language/contracts.mdx
Labels: Documentation

#2220 Also update flow-go's new insecure package
  tools/update/config.yaml
Labels: Improvement

#2230 Sync Stable Cadence
  docs/language/accounts.mdx
  docs/language/contracts.mdx
  runtime/parser/declaration.go
  runtime/parser/declaration_test.go
Labels: Chore

#2229 Refactor the existing issue templates to forms
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/feature-request.yaml
Labels: Chore

#2209 Correct example code link
  docs/design-patterns.mdx
Labels: Documentation, Improvement, Dev Portal Documentation

#2231 Report preceding identifier in member declaration
  runtime/contract_update_test.go
  runtime/parser/declaration.go
  runtime/parser/declaration_test.go
  runtime/parser/parser.go
  runtime/stdlib/account.go
Labels: Breaking Change

#2227 Allow exporting attachment values and types from scripts
  runtime/attachments_test.go
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/convertTypes.go
  runtime/convertValues.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/attachments_test.go
  types.go
  values.go
Labels: Bugfix

#2206 Use dedicated type parameters for test-stdlib functions
  runtime/stdlib/test.go
Labels: Technical Debt

#2241 [v0.31] Ensure SetProgram is called after GetProgram, even if there is an error
  runtime/environment.go
  runtime/storage_test.go
Labels: Bugfix

#2245 Ensure SetProgram is called after GetProgram, even if there is an error
  npm-packages/cadence-parser/package.json
  runtime/environment.go
  runtime/storage_test.go
  version.go
Labels: Bugfix

#2246 Remove old diagrams
  runtime/sema/resources.monopic
  runtime/sema/resources.png
  runtime/sema/resources.svg
  runtime/sema/resources.txt
Labels: Documentation

#2207 Fix Capability example in JSON-Cadence Data Interchange Format specs
  docs/json-cadence-spec.md
Labels: Documentation

#2248 Remove support for importing/exporting and JSON encoding/decoding path links and cadence type
  encoding/json/decode.go
  encoding/json/encode.go
  encoding/json/encoding_test.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  values.go
  values_test.go
Labels: Technical Debt

#2253 Add documentation on the release process
  docs/images/compatibility_check_action_params.png
  docs/images/compatibility_check_action_trigger.png
  docs/images/release_action.png
  docs/releasing.md
Labels: Documentation

#2197 Allow errors to pretty-print excerpts over multiple lines
  runtime/pretty/print.go
  runtime/runtime_test.go
Labels: Improvement

#2255 Fix loop variables being captured in closures
  runtime/program_params_validation_test.go
Labels: Bugfix

#2222 Add additional metering methods to the interface
  runtime/interface.go
  runtime/runtime_test.go
Labels: Improvement

#2234 Parse transaction role declarations
  runtime/ast/block.go
  runtime/ast/elementtype.go
  runtime/ast/elementtype_string.go
  runtime/ast/transaction_declaration.go
  runtime/ast/transaction_declaration_test.go
  runtime/common/declarationkind.go
  runtime/common/declarationkind_string.go
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/parser/declaration_test.go
  runtime/parser/keyword.go
  runtime/parser/transaction.go
Labels: Feature

#2249 Ensure GetProgram calls before SetProgram
  runtime/account_test.go
  runtime/contract_update_validation_test.go
  runtime/convertValues_test.go
  runtime/coverage_test.go
  runtime/crypto_test.go
  runtime/deployment_test.go
  runtime/environment.go
  runtime/import_test.go
  runtime/imported_values_memory_metering_test.go
  runtime/program_params_validation_test.go
  runtime/rlp_test.go
  runtime/runtime.go
  runtime/runtime_memory_metering_test.go
  runtime/runtime_test.go
  runtime/stdlib/account.go
  runtime/storage_test.go
  runtime/test-export-json-deterministic.txt
  runtime/validation_test.go
Labels: Improvement, Technical Debt

#2254 Replace interface GetProgram and SetProgram with GetAndSetProgram
  runtime/context.go
  runtime/contract_update_test.go
  runtime/contract_update_validation_test.go
  runtime/deployment_test.go
  runtime/environment.go
  runtime/interface.go
  runtime/runtime_test.go
  runtime/storage_test.go
Labels: Improvement

#2265 Update docs to reflect Account inbox live after MN21 spork
  docs/language/accounts.mdx
Labels: Documentation

#2242 Add publicTypes method to DeployedContract for introspection
  docs/language/accounts.mdx
  runtime/deployedcontract_test.go
  runtime/interpreter/deployedcontract.go
  runtime/sema/deployed_contract.go
  runtime/tests/checker/account_test.go
Labels: Feature

#2257 Type check transaction role declarations
  runtime/ast/visitor.go
  runtime/common/declarationkind.go
  runtime/compiler/compiler.go
  runtime/interpreter/interpreter_transaction.go
  runtime/parser/declaration_test.go
  runtime/parser/transaction.go
  runtime/sema/check_array_expression.go
  runtime/sema/check_assignment.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_create_expression.go
  runtime/sema/check_dictionary_expression.go
  runtime/sema/check_interface_declaration.go
  runtime/sema/check_invocation_expression.go
  runtime/sema/check_member_expression.go
  runtime/sema/check_return_statement.go
  runtime/sema/check_transaction_declaration.go
  runtime/sema/check_variable_declaration.go
  runtime/sema/checker.go
  runtime/sema/elaboration.go
  runtime/sema/errors.go
  runtime/sema/type.go
  runtime/sema/type_tags.go
  runtime/tests/checker/transactions_test.go
Labels: Feature

#2270 Avoid unnecessary use of any and casts, parse function is generic now
  runtime/parser/declaration_test.go
  runtime/parser/parser.go
  runtime/parser/parser_test.go
Labels: Technical Debt

#2274 Downgrade benchstat version to bring back html output
  .github/workflows/benchmark.yml
Labels: Chore

#2145 Parse type parameter lists for function declarations
  runtime/ast/expression.go
  runtime/ast/function_declaration.go
  runtime/ast/function_declaration_test.go
  runtime/ast/typeparameter.go
  runtime/ast/typeparameterlist.go
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/parser/declaration.go
  runtime/parser/declaration_test.go
  runtime/parser/function.go
  runtime/parser/parser.go
  runtime/parser/statement.go
  runtime/parser/transaction.go
  runtime/tests/utils/utils.go
Labels: Feature

#2256 Replace empty common.Address{} with singleton
  runtime/common/address.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/environment.go
  runtime/interpreter/conversion.go
  runtime/interpreter/conversion_test.go
  runtime/interpreter/deepcopyremove_test.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/inspect_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_tracing_test.go
  runtime/interpreter/storage_test.go
  runtime/interpreter/value.go
  runtime/interpreter/value_publickey.go
  runtime/interpreter/value_test.go
  runtime/stdlib/account.go
  runtime/stdlib/block.go
  runtime/stdlib/rlp.go
  runtime/stdlib/test.go
  runtime/tests/interpreter/builtinfunctions_test.go
  runtime/tests/interpreter/container_mutation_test.go
  runtime/tests/interpreter/enum_test.go
  runtime/tests/interpreter/for_test.go
  runtime/tests/interpreter/import_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/string_test.go
  runtime/tests/interpreter/values_test.go
  runtime/validation_test.go
Labels: Improvement

#2277 Clear warnings by removing unnecessary type arguments in tests
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/composite_value_test.go
  runtime/tests/interpreter/condition_test.go
  runtime/tests/interpreter/container_mutation_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/equality_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/invocation_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/metatype_test.go
  runtime/tests/interpreter/transfer_test.go
Labels: Technical Debt

#2269 Fix confusion of return type of checker's visitExpression methods
  runtime/sema/check_reference_expression.go
  runtime/sema/checker.go
Labels: Technical Debt

#2261 Improve update tool and documentation
  tools/update/README.md
  tools/update/main.ts
Labels: Documentation, Improvement

#2239 Automate the release process
  .github/workflows/release.yml
  Makefile
  bump-version.sh
Labels: Chore

#2259 Interpret transaction role declarations
  runtime/activations/activations.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_transaction.go
  runtime/tests/interpreter/transactions_test.go
Labels: Feature

#2262 Add support for resource-kinded fields in transaction roles
  runtime/ast/transaction_declaration.go
  runtime/interpreter/errors.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_member_expression.go
  runtime/sema/check_transaction_declaration.go
  runtime/sema/checker.go
  runtime/sema/errors.go
  runtime/sema/resources.go
  runtime/tests/checker/transactions_test.go
  runtime/tests/checker/utils.go
  types.go
Labels: Feature

#2268 Forbid taking references of transaction roles
  runtime/sema/check_reference_expression.go
  runtime/sema/checker.go
  runtime/sema/errors.go
  runtime/tests/checker/reference_test.go
Labels: Improvement

#2271 Allow equality tests on arrays if their inner types support it
  docs/language/operators.md
  runtime/sema/type.go
  runtime/tests/checker/arrays_dictionaries_test.go
  runtime/tests/checker/resources_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Improvement
