Repository onflow/cadence, pull requests merged in 2023-12, with the labels that each got.

#2960 Add test for container mutation while iterating
  runtime/tests/interpreter/container_mutation_test.go
Labels: Testing

#2958 Improve resource-reference tracking
  runtime/environment.go
  runtime/interpreter/config.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/sharedstate.go
  runtime/interpreter/value.go
  runtime/interpreter/value_function.go
  runtime/interpreter/value_function_test.go
  runtime/interpreter/value_test.go
  runtime/storage_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/member_test.go
  runtime/tests/interpreter/resources_test.go
Labels: Improvement

#2965 throw error on the creation of a nested reference
  runtime/contract_function_executor.go
  runtime/environment.go
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_invocation.go
  runtime/interpreter/interpreter_statement.go
  runtime/interpreter/interpreter_transaction.go
  runtime/interpreter/value.go
  runtime/interpreter/value_accountcapabilitycontroller.go
  runtime/interpreter/value_storagecapabilitycontroller.go
  runtime/interpreter/value_test.go
  runtime/stdlib/account.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/container_mutation_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/member_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/reference_test.go
  runtime/tests/interpreter/transactions_test.go
  runtime/transaction_executor.go
Labels: Language Breaking Change

#2923 Add account type migration
  migrations/account_storage.go
  migrations/account_type/dummy_static_type.go
  migrations/account_type/migration.go
  migrations/account_type/migration_test.go
  migrations/address_iterator.go
  migrations/migrate_value.go
  migrations/migration_reporter.go
Labels: Feature

#2937 Add String normalizing migration
  migrations/string_normalization/migration.go
  migrations/string_normalization/migration_test.go
Labels: Feature

#2966 Remove unsafeRandom
  runtime/runtime_test.go
  runtime/stdlib/builtin.go
  runtime/stdlib/random.go
Labels: Technical Debt

#2921 New Behavior for Attachments and Entitlements
  runtime/ast/attachment.go
  runtime/ast/attachment_test.go
  runtime/contract_update_validation_test.go
  runtime/entitlements_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_statement.go
  runtime/interpreter/value.go
  runtime/parser/declaration.go
  runtime/parser/declaration_test.go
  runtime/parser/expression.go
  runtime/parser/expression_test.go
  runtime/parser/keyword.go
  runtime/sema/access.go
  runtime/sema/check_attach_expression.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_interface_declaration.go
  runtime/sema/check_member_expression.go
  runtime/sema/check_transaction_declaration.go
  runtime/sema/checker.go
  runtime/sema/errors.go
  runtime/sema/type.go
  runtime/sema/type_test.go
  runtime/stdlib/contract_update_validation.go
  runtime/tests/checker/attachments_test.go
  runtime/tests/checker/entitlements_test.go
  runtime/tests/checker/events_test.go
  runtime/tests/interpreter/attachments_test.go
  runtime/tests/interpreter/entitlements_test.go
Labels: Language Breaking Change

#2968 Sync stable-cadence branch with master
  runtime/attachments_test.go
  runtime/convertValues_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/sharedstate.go
  runtime/interpreter/value.go
  runtime/interpreter/value_function.go
  runtime/interpreter/value_function_test.go
  runtime/interpreter/value_test.go
  runtime/runtime_test.go
  runtime/storage_test.go
  runtime/tests/checker/resources_test.go
  runtime/tests/interpreter/attachments_test.go
  runtime/tests/interpreter/container_mutation_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/member_test.go
  runtime/tests/interpreter/reference_test.go
  runtime/tests/interpreter/resources_test.go
Labels: Technical Debt

#2973 Improve Account type migration
  migrations/account_type/migration.go
  migrations/account_type/migration_test.go
Labels: Improvement

#2915 Make checkParameterizedTypeIsInstantiated recursive
  runtime/sema/checker.go
  runtime/sema/simple_type.go
  runtime/sema/type.go
  runtime/tests/checker/range_value_test.go
  runtime/tests/checker/typeargument_test.go
Labels: Technical Debt

#2976 Update interface of `revertibleRandom`
  encoding/ccf/ccf_test.go
  encoding/ccf/simpletype.go
  encoding/ccf/simpletype_string.go
  encoding/ccf/traverse_value.go
  runtime/convertTypes.go
  runtime/convertValues_test.go
  runtime/imported_values_memory_metering_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/primitivestatictype.go
  runtime/interpreter/primitivestatictype_string.go
  runtime/interpreter/statictype_test.go
  runtime/interpreter/value_test.go
  runtime/literal.go
  runtime/runtime_test.go
  runtime/sema/checker_test.go
  runtime/sema/type.go
  runtime/sema/type_names.go
  runtime/sema/type_tags.go
  runtime/sema/type_test.go
  runtime/stdlib/random.go
  runtime/tests/checker/builtinfunctions_test.go
  runtime/tests/checker/casting_test.go
  runtime/tests/checker/integer_test.go
  runtime/tests/checker/operations_test.go
  runtime/tests/interpreter/arithmetic_test.go
  runtime/tests/interpreter/bitwise_test.go
  runtime/tests/interpreter/builtinfunctions_test.go
  runtime/tests/interpreter/equality_test.go
  runtime/tests/interpreter/integers_test.go
  runtime/tests/interpreter/interpreter_test.go
  types.go
  values_test.go
Labels: Language Breaking Change, Improvement

#2972 Make entitlement set access incomparable
  runtime/common/incomparable.go
  runtime/sema/access.go
Labels: Improvement

#2977 Fix GetNativeCompositeValueComputedFields
  runtime/account_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
Labels: Bugfix

#2970 Static check to prevent nested references
  runtime/sema/check_reference_expression.go
  runtime/sema/errors.go
  runtime/tests/checker/reference_test.go
  runtime/tests/interpreter/reference_test.go
Labels: Language Breaking Change

#2980 Use IsPrimitiveType to check default destructor params
  runtime/sema/check_composite_declaration.go
Labels: Improvement

#2979 Various improvements
  migrations/account_type/migration.go
  migrations/account_type/migration_test.go
  runtime/interpreter/statictype.go
  runtime/tests/runtime_utils/testinterface.go
Labels: Improvement

#2984 Remove deprecated domain separation tag from Crypto contract
  runtime/crypto_test.go
  runtime/stdlib/contracts/crypto.cdc
  runtime/stdlib/contracts/crypto_test.cdc
Labels: Language Breaking Change, Improvement

#2967 Test type order insignificance
  runtime/storage_test.go
Labels: Testing

#2974 Add state migration for removing all values from private domain
  migrations/account_storage.go
  migrations/account_type/migration.go
  migrations/account_type/migration_test.go
  migrations/capcons/capabilitymigration.go
  migrations/capcons/linkmigration.go
  migrations/capcons/migration_test.go
  migrations/capcons/privatemigration.go
  migrations/migration.go
  migrations/migration_test.go
  migrations/string_normalization/migration.go
  migrations/string_normalization/migration_test.go
Labels: Feature

#2985 Report bespoke error for restricted types parsed as type arguments
  runtime/parser/errors.go
  runtime/parser/expression.go
  runtime/parser/expression_test.go
  runtime/parser/parser_test.go
  runtime/parser/type.go
  runtime/parser/type_test.go
Labels: Improvement

#2987 Use old hash/ID generation to remove keys
  migrations/legacy_intersection_type.go
  migrations/migration.go
  migrations/type_value/migration_test.go
Labels: Improvement

#2981 State migration for type values with two or more interfaces
  migrations/account_type/migration_test.go
  migrations/legacy_intersection_type.go
  migrations/migration.go
  migrations/migration_test.go
  migrations/string_normalization/migration_test.go
  migrations/type_value/migration.go
  migrations/type_value/migration_test.go
  runtime/interpreter/value.go
Labels: Feature
