Repository onflow/cadence, pull requests merged in 2023-11, with the labels that each got.

#2856 Update tests for `Crypto` contract to the latest testing framework API
  .github/workflows/ci.yml
  runtime/stdlib/contracts/crypto_test.cdc
  runtime/stdlib/contracts/flow.json
  runtime/stdlib/contracts/scripts/crypto_get_key_from_list.cdc
  runtime/stdlib/contracts/scripts/crypto_hash.cdc
  runtime/stdlib/contracts/scripts/crypto_hash_with_tag.cdc
  runtime/stdlib/contracts/scripts/crypto_key_list_add.cdc
  runtime/stdlib/contracts/scripts/crypto_key_list_verify.cdc
  runtime/stdlib/contracts/scripts/crypto_key_list_verify_duplicate_signature.cdc
  runtime/stdlib/contracts/scripts/crypto_key_list_verify_insufficient_weights.cdc
  runtime/stdlib/contracts/scripts/crypto_key_list_verify_invalid_signature.cdc
  runtime/stdlib/contracts/scripts/crypto_key_list_verify_missing_signature.cdc
  runtime/stdlib/contracts/scripts/crypto_key_list_verify_revoked.cdc
  runtime/stdlib/contracts/scripts/crypto_revoke_key_from_list.cdc
Labels: Technical Debt

#2927 Remove `StandardLibraryHandler` method from `TestFramework` interface
  runtime/stdlib/test-framework.go
  runtime/stdlib/test_test.go
Labels: Technical Debt

#2928 Merge destructor removal into stable cadence
  encoding/ccf/ccf_test.go
  encoding/json/encoding_test.go
  runtime/ast/composite.go
  runtime/ast/expression_test.go
  runtime/ast/function_declaration_test.go
  runtime/ast/memberindices.go
  runtime/ast/memberindices_test.go
  runtime/ast/members.go
  runtime/ast/parameter.go
  runtime/ast/parameterlist.go
  runtime/common/declarationkind.go
  runtime/common/declarationkind_string.go
  runtime/convertValues_test.go
  runtime/environment.go
  runtime/ft_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_statement.go
  runtime/interpreter/value.go
  runtime/nft_test.go
  runtime/parser/declaration.go
  runtime/parser/declaration_test.go
  runtime/parser/errors.go
  runtime/parser/function.go
  runtime/parser/transaction.go
  runtime/predeclaredvalues_test.go
  runtime/resource_duplicate_test.go
  runtime/resourcedictionary_test.go
  runtime/runtime_test.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_emit_statement.go
  runtime/sema/check_interface_declaration.go
  runtime/sema/elaboration.go
  runtime/sema/errors.go
  runtime/sema/type.go
  runtime/stdlib/builtin.go
  runtime/stdlib/publickey.go
  runtime/stdlib/test_contract.go
  runtime/storage_test.go
  runtime/tests/checker/access_test.go
  runtime/tests/checker/attachments_test.go
  runtime/tests/checker/composite_test.go
  runtime/tests/checker/conditions_test.go
  runtime/tests/checker/events_test.go
  runtime/tests/checker/initialization_test.go
  runtime/tests/checker/nft_test.go
  runtime/tests/checker/overloading_test.go
  runtime/tests/checker/reference_test.go
  runtime/tests/checker/resources_test.go
  runtime/tests/checker/storable_test.go
  runtime/tests/checker/swap_test.go
  runtime/tests/interpreter/attachments_test.go
  runtime/tests/interpreter/condition_test.go
  runtime/tests/interpreter/entitlements_test.go
  runtime/tests/interpreter/import_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/member_test.go
  runtime/tests/interpreter/reference_test.go
  runtime/tests/interpreter/resources_test.go
Labels: Language Breaking Change

#2892 Allow `InclusiveRange<T>` in a for-in loop
  runtime/interpreter/interpreter_statement.go
  runtime/interpreter/value.go
  runtime/interpreter/value_range.go
  runtime/sema/check_for.go
  runtime/tests/checker/for_test.go
  runtime/tests/interpreter/for_test.go
Labels: Feature

#2924 Add types to parsed array and dictionary literals
  runtime/literal.go
  runtime/literal_test.go
Labels: Improvement

#2930 [v0.42] Fix nested resource moves
  runtime/interpreter/value.go
  runtime/runtime_test.go
  runtime/sema/check_variable_declaration.go
  runtime/tests/interpreter/resources_test.go
Labels: Bugfix

#2932 [v0.42] Fix AuthAccount creation
  runtime/runtime_test.go
  runtime/stdlib/account.go
Labels: Bugfix

#2931 Fix nested resource moves
  runtime/interpreter/value.go
  runtime/runtime_test.go
  runtime/sema/check_variable_declaration.go
  runtime/tests/interpreter/resources_test.go
Labels: Bugfix

#2933 Fix AuthAccount creation
  runtime/runtime_test.go
  runtime/stdlib/account.go
Labels: Bugfix

#2938 Fix transaction resource-typed field move
  runtime/interpreter/simplecompositevalue.go
  runtime/runtime_test.go
Labels: Bugfix

#2939 Fix Semgrep
  .github/workflows/ci.yml
Labels: Chore

#2940 Merge v0.42 into master
  npm-packages/cadence-parser/package.json
  runtime/interpreter/simplecompositevalue.go
  runtime/runtime_test.go
  version.go
Labels: Chore

#2944 Add meeting notes for 2023-11-15
  meetings/2023-11-15.md
Labels: Documentation

#2946 Include interface conformances when computing the supported entitlements of an interface
  runtime/sema/type.go
  runtime/tests/checker/entitlements_test.go
Labels: Bugfix

#2949 AST improvements
  runtime/ast/block.go
  runtime/ast/position.go
Labels: Improvement
