Repository onflow/cadence, pull requests merged in 2023-06, with the labels that each got.

#2511 Return a text message instead of NaN
  runtime/coverage.go
  runtime/coverage_test.go
Labels: Improvement

#2425 Add mapping function for types
  runtime/sema/simple_type.go
  runtime/sema/type.go
  runtime/sema/type_test.go
Labels: Improvement

#2528 Fix `publicKey` to have matching static and runtime types
  runtime/account_test.go
  runtime/stdlib/account.go
  runtime/stdlib/flow.go
  runtime/stdlib/flow_test.go
Labels: Bugfix

#2529 Fix `codeHash` types to match (static and runtime)
  runtime/interpreter/conversion.go
  runtime/interpreter/conversion_test.go
  runtime/stdlib/account.go
Labels: Bugfix

#2532 Check code hash value's type is correct
  runtime/deployment_test.go
Labels: Testing

#2539 Update configuration of update tool
  tools/update/config.yaml
Labels: Chore

#2543 Update config of update tool
  tools/update/config.yaml
Labels: Chore

#2542 Add function type to function wrapper host functions
  runtime/interpreter/interpreter.go
  runtime/runtime_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Bugfix

#2544 Port internal fix 119
  runtime/interpreter/conversion.go
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/sharedstate.go
  runtime/interpreter/value.go
  runtime/resource_duplicate_test.go
  runtime/stdlib/account.go
Labels: Bugfix

#2545 Port internal fix 120
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/sharedstate.go
  runtime/interpreter/value.go
  runtime/runtime_test.go
  runtime/tests/interpreter/resources_test.go
Labels: Bugfix

#2547 Fix test: Pass interpreter when iterating over arrays
  runtime/stdlib/test.go
  runtime/stdlib/test_emulatorbackend.go
Labels: Bugfix

#2551 Bring back type IDs in JSON encoding of funtion types and restricted types
  encoding/json/encode.go
  encoding/json/encoding_test.go
  runtime/runtime_test.go
Labels: Bugfix

#2555 Improve function type decoding
  encoding/json/decode.go
  encoding/json/encoding_test.go
Labels: Bugfix

#2554 fetch event fields by name
  types.go
  values.go
  values_test.go
Labels: Feature

#2556 Fix race conditions in test
  runtime/convertValues_test.go
Labels: Bugfix

#2421 Runtime behavior for entitlements
  encoding/ccf/ccf_test.go
  encoding/ccf/decode_type.go
  encoding/ccf/encode_type.go
  go.mod
  go.sum
  runtime/contract_function_executor.go
  runtime/convertTypes.go
  runtime/convertValues_test.go
  runtime/entitlements_test.go
  runtime/imported_values_memory_metering_test.go
  runtime/interpreter/decode.go
  runtime/interpreter/encode.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/function.go
  runtime/interpreter/function_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_invocation.go
  runtime/interpreter/interpreter_statement.go
  runtime/interpreter/invocation.go
  runtime/interpreter/sharedstate.go
  runtime/interpreter/statictype.go
  runtime/interpreter/statictype_test.go
  runtime/interpreter/value.go
  runtime/interpreter/value_accountreference.go
  runtime/interpreter/value_test.go
  runtime/missingmember_test.go
  runtime/nft_test.go
  runtime/runtime_test.go
  runtime/sema/access.go
  runtime/sema/check_attach_expression.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_function.go
  runtime/sema/check_interface_declaration.go
  runtime/sema/checker.go
  runtime/sema/elaboration.go
  runtime/sema/gen/testdata/fields.golden.go
  runtime/sema/gen/testdata/functions.golden.go
  runtime/sema/orderdmaps.go
  runtime/sema/runtime_type_constructors.go
  runtime/sema/type.go
  runtime/stdlib/account.go
  runtime/storage_test.go
  runtime/tests/checker/entitlements_test.go
  runtime/tests/checker/runtimetype_test.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/capability_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/entitlements_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/metatype_test.go
  runtime/tests/interpreter/runtimetype_test.go
  runtime/tests/interpreter/values_test.go
Labels: Language Breaking Change, Feature

#2440 Attachment Iteration
  runtime/interpreter/value.go
  runtime/sema/checker.go
  runtime/sema/type.go
  runtime/tests/checker/attachments_test.go
  runtime/tests/interpreter/attachments_test.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Feature

#2559 Add support for CCF encoding/decoding modes and options
  encoding/ccf/ccf_test.go
  encoding/ccf/decode.go
  encoding/ccf/decode_type.go
  encoding/ccf/decode_typedef.go
  encoding/ccf/encode.go
  encoding/ccf/encode_type.go
  encoding/ccf/encode_typedef.go
  encoding/ccf/service_events_test.go
Labels: Bugfix, Feature

#2565 Add utility to decode fields into struct based on field tags
  types.go
  types_test.go
Labels: Feature

#2568 Fix resource tracking
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
Labels: Bugfix

#2569 Add tests for resource tracking in bound function invocations
  runtime/tests/interpreter/reference_test.go
Labels: Testing

#2570 Add tests for resource tracking in bound function invocations
  runtime/tests/interpreter/reference_test.go
Labels: Testing

#2574 [v0.31] Port internal fixes 119 and 120
  runtime/interpreter/conversion.go
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/sharedstate.go
  runtime/interpreter/value.go
  runtime/resource_duplicate_test.go
  runtime/runtime_test.go
  runtime/stdlib/account.go
  runtime/tests/interpreter/resources_test.go
Labels: Bugfix

#2575 [v0.31] Port internal fixes 123 and 125
  runtime/interpreter/function.go
  runtime/interpreter/interpreter_expression.go
  runtime/runtime_test.go
  runtime/tests/interpreter/resources_test.go
Labels: Bugfix

#2578 Fix resource tracking
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
Labels: Bugfix

#2571 Introduce the `Test.assertEqual` function
  runtime/stdlib/test_contract.go
  runtime/stdlib/test_test.go
Labels: Feature

#2572 decode complex fields into more primitive types
  types.go
  types_test.go
Labels: Feature

#2564 Add tests for entitlement inheritance between interfaces
  runtime/tests/checker/entitlements_test.go
  runtime/tests/checker/interface_test.go
Labels: Testing

#2580 Add support for running downstream dependencies workflow for PRs from forks
  .github/workflows/downstream.yml
Labels: Chore

#2579 Add meeting notes for LDMs May 4th, 2023 and June 15th, 2023
  meetings/2023-05-04.md
  meetings/2023-06-15.md
Labels: Chore

#2584 Fix panic in `DecodeFields` on bad inputs
  types.go
  types_test.go
Labels: Bugfix

#2590 Port internal fix 126
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/sharedstate.go
  runtime/runtime_test.go
  runtime/tests/interpreter/resources_test.go
Labels: Bugfix

#2592 Fix crash on entitlement mappings with empty outputs
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/invocation.go
  runtime/interpreter/sharedstate.go
  runtime/interpreter/value_function.go
  runtime/tests/interpreter/entitlements_test.go
Labels: Bugfix

#2567 Convert generic container types on upcast
  runtime/entitlements_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/entitlements_test.go
Labels: Feature

#2597 Improve formatting of access modifiers
  runtime/ast/attachment.go
  runtime/ast/attachment_test.go
  runtime/ast/block_test.go
  runtime/ast/composite.go
  runtime/ast/composite_test.go
  runtime/ast/entitlement_declaration.go
  runtime/ast/entitlement_declaration_test.go
  runtime/ast/expression.go
  runtime/ast/function_declaration_test.go
  runtime/ast/interface_test.go
  runtime/ast/transaction_declaration_test.go
  runtime/ast/variable_declaration.go
  runtime/ast/variable_declaration_test.go
Labels: Improvement

#2601 Improve update tool config
  tools/update/config.yaml
Labels: Improvement

#2607 Populate `Message`, `LocationRange` fields for `AssertionError` on `Test.expect` function
  runtime/stdlib/test_contract.go
  runtime/stdlib/test_test.go
Labels: Bugfix

#2606 [v0.31] Port internal fix 126
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/sharedstate.go
  runtime/runtime_test.go
  runtime/tests/interpreter/resources_test.go
Labels: Bugfix

#2609 Add utility function `ccf.HasMsgPrefix`
  encoding/ccf/ccf_test.go
  encoding/ccf/decode.go
Labels: Feature

#2612 Add support for forks to compatibility check
  .github/workflows/compatibility-check-template.yml
  .github/workflows/compatibility-check.yml
Labels: Chore

#2613 Set permissions in backward compatibility check
  .github/workflows/compatibility-check-template.yml
  .github/workflows/compatibility-check.yml
Labels: Chore

#2615 Update integration tests for built-in `Crypto` contract
  runtime/stdlib/contracts/crypto_test.cdc
  runtime/stdlib/contracts/scripts/crypto_get_key_from_list.cdc
  runtime/stdlib/contracts/scripts/crypto_hash.cdc
  runtime/stdlib/contracts/scripts/crypto_hash_with_tag.cdc
  runtime/stdlib/contracts/scripts/crypto_key_list_add.cdc
  runtime/stdlib/contracts/scripts/crypto_key_list_verify.cdc
  runtime/stdlib/contracts/scripts/crypto_key_list_verify_duplicate_signature.cdc
  runtime/stdlib/contracts/scripts/crypto_key_list_verify_insufficient_weights.cdc
  runtime/stdlib/contracts/scripts/crypto_key_list_verify_invalid_signature.cdc
  runtime/stdlib/contracts/scripts/crypto_key_list_verify_missing_signature.cdc
  runtime/stdlib/contracts/scripts/crypto_key_list_verify_revoked.cdc
  runtime/stdlib/contracts/scripts/crypto_revoke_key_from_list.cdc
Labels: Improvement

#2616 Don't skip benchmark for forks
  .github/workflows/benchmark.yml
Labels: Chore

#2618 Use atree orderd map's Has function to test for existence
  runtime/interpreter/storagemap.go
  runtime/interpreter/value.go
Labels: Improvement

#2617 Introduce Character.utf8
  runtime/interpreter/value.go
  runtime/sema/character.cdc
  runtime/sema/character.gen.go
  runtime/tests/checker/character_test.go
  runtime/tests/interpreter/character_test.go
Labels: Feature
