Repository onflow/cadence, pull requests merged in 2023-05, with the labels that each got.

#2475 Add support for restricted types to Go code generator
  runtime/sema/gen/main.go
  runtime/sema/gen/testdata/fields.cdc
  runtime/sema/gen/testdata/fields.golden.go
Labels: Feature

#2486 Don't truncate error message stack early in case of multiline errors
  runtime/error_test.go
  runtime/pretty/print.go
Labels: Bugfix

#2488 Handle wrapped errors during storage iteration
  runtime/interpreter/interpreter.go
  runtime/storage_test.go
Labels: Improvement

#2468 Introduce the `Test.expectFailure` function
  runtime/stdlib/test_contract.go
  runtime/stdlib/test_test.go
Labels: Feature

#2489 Improve code generation for members
  runtime/sema/authaccount.gen.go
  runtime/sema/block.gen.go
  runtime/sema/character.gen.go
  runtime/sema/deployedcontract.gen.go
  runtime/sema/gen/main.go
  runtime/sema/gen/testdata/docstrings.golden.go
  runtime/sema/gen/testdata/fields.cdc
  runtime/sema/gen/testdata/fields.golden.go
  runtime/sema/gen/testdata/functions.golden.go
  runtime/sema/gen/testdata/nested.cdc
  runtime/sema/gen/testdata/nested.golden.go
  runtime/sema/publicaccount.gen.go
  runtime/sema/publicaccount.go
  runtime/sema/type.go
Labels: Improvement

#2491 Implement Address.fromString
  docs/language/values-and-types.mdx
  runtime/common/address.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/sema/type.go
  runtime/tests/checker/builtinfunctions_test.go
  runtime/tests/interpreter/builtinfunctions_test.go
Labels: Feature

#2485 Add integration tests (in Cadence) for `Crypto` contract and generate code coverage
  runtime/stdlib/contracts/crypto_test.cdc
  runtime/stdlib/contracts/flow.json
  runtime/stdlib/contracts/scripts/crypto_get_key_from_list.cdc
  runtime/stdlib/contracts/scripts/crypto_hash.cdc
  runtime/stdlib/contracts/scripts/crypto_hash_with_tag.cdc
  runtime/stdlib/contracts/scripts/crypto_key_list_add.cdc
  runtime/stdlib/contracts/scripts/crypto_key_list_verify.cdc
  runtime/stdlib/contracts/scripts/crypto_key_list_verify_duplicate_signature.cdc
  runtime/stdlib/contracts/scripts/crypto_key_list_verify_insufficient_weights.cdc
  runtime/stdlib/contracts/scripts/crypto_key_list_verify_invalid_signature.cdc
  runtime/stdlib/contracts/scripts/crypto_key_list_verify_missing_signature.cdc
  runtime/stdlib/contracts/scripts/crypto_key_list_verify_revoked.cdc
  runtime/stdlib/contracts/scripts/crypto_revoke_key_from_list.cdc
Labels: Testing

#2474 Introduce a `LocationFilter` field on `CoverageReport` type
  runtime/coverage.go
  runtime/coverage_test.go
Labels: Feature

#2487 replace docs with links
  docs/anti-patterns.mdx
  docs/contract-upgrades.mdx
  docs/design-patterns.mdx
  docs/index.mdx
  docs/json-cadence-spec.md
  docs/language/access-control.md
  docs/language/accounts.mdx
  docs/language/attachments.md
  docs/language/built-in-functions.mdx
  docs/language/capability-based-access-control.md
  docs/language/composite-types.mdx
  docs/language/constants-and-variables.md
  docs/language/contract-updatability.md
  docs/language/contracts.mdx
  docs/language/control-flow.md
  docs/language/core-events.md
  docs/language/crypto.mdx
  docs/language/enumerations.md
  docs/language/environment-information.md
  docs/language/events.md
  docs/language/functions.mdx
  docs/language/glossary.md
  docs/language/imports.mdx
  docs/language/index.md
  docs/language/interfaces.mdx
  docs/language/operators.md
  docs/language/references.md
  docs/language/resources.mdx
  docs/language/restricted-types.md
  docs/language/run-time-types.md
  docs/language/scope.md
  docs/language/syntax.md
  docs/language/transactions.md
  docs/language/type-annotations.md
  docs/language/type-hierarchy.md
  docs/language/type-inference.md
  docs/language/type-safety.md
  docs/language/values-and-types.mdx
  docs/measuring-time.mdx
  docs/security-best-practices.mdx
  docs/solidity-to-cadence.mdx
  docs/testing-framework.mdx
  docs/tutorial/01-first-steps.mdx
  docs/tutorial/02-hello-world.mdx
  docs/tutorial/03-resources.mdx
  docs/tutorial/04-capabilities.mdx
  docs/tutorial/05-non-fungible-tokens-1.mdx
  docs/tutorial/05-non-fungible-tokens-2.mdx
  docs/tutorial/06-fungible-tokens.mdx
  docs/tutorial/07-marketplace-setup.mdx
  docs/tutorial/08-marketplace-compose.mdx
  docs/tutorial/09-voting.mdx
  docs/tutorial/10-resources-compose.mdx
  docs/why.md
Labels: Documentation

#2454 Implement Auth/PublicAccount.Capabilities functions
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/interpreter/value_accountreference.go
  runtime/sema/authaccount.go
  runtime/sema/type.go
  runtime/stdlib/account.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Feature

#2462 Implement AuthAccount.StorageCapabilities.getControllers and forEachController
  examples/quicksort.cdc
  runtime/capabilitycontrollers_test.go
  runtime/examples/importing/import.cdc
  runtime/examples/importing/imported.cdc
  runtime/examples/vault.cdc
  runtime/interpreter/value.go
  runtime/sema/authaccount.cdc
  runtime/sema/authaccount.gen.go
  runtime/stdlib/account.go
  runtime/tests/checker/account_test.go
Labels: Feature

#2472 Start implementation of account capability controller
  runtime/capabilitycontrollers_test.go
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/interpreter/decode.go
  runtime/interpreter/encode.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/value_accountcapabilitycontroller.go
  runtime/interpreter/value_accountcapabilitycontroller_test.go
  runtime/interpreter/value_storagecapabilitycontroller.go
  runtime/interpreter/value_storagecapabilitycontroller_test.go
  runtime/interpreter/visitor.go
  runtime/stdlib/account.go
Labels: Feature

#2476 Continue implementation of Cap Cons
  encoding/json/decode.go
  encoding/json/encode.go
  encoding/json/encoding_test.go
  runtime/capabilitycontrollers_test.go
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/convertTypes.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/environment.go
  runtime/format/capability.go
  runtime/imported_values_memory_metering_test.go
  runtime/interpreter/config.go
  runtime/interpreter/decode.go
  runtime/interpreter/encode.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/simplecompositevalue.go
  runtime/interpreter/value.go
  runtime/interpreter/value_account.go
  runtime/interpreter/value_accountcapabilitycontroller.go
  runtime/interpreter/value_accountreference.go
  runtime/interpreter/value_function.go
  runtime/interpreter/value_storagecapabilitycontroller.go
  runtime/interpreter/value_test.go
  runtime/interpreter/visitor.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/sema/type.go
  runtime/stdlib/account.go
  runtime/storage_test.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/equality_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/values_test.go
  values.go
  values_test.go
Labels: Feature

#2498 Fix userPanicToError to handle wrapped user error.
  runtime/runtime.go
  runtime/runtime_test.go
Labels: Bugfix

#2478 Continue implementation of Cap Cons
  runtime/capabilitycontrollers_test.go
  runtime/interpreter/value_accountcapabilitycontroller.go
  runtime/interpreter/value_accountreference.go
  runtime/sema/authaccount.cdc
  runtime/sema/authaccount.gen.go
  runtime/stdlib/account.go
Labels: Feature

#2479 Continue implementation of Cap Cons
  encoding/ccf/ccf_test.go
  encoding/ccf/decode.go
  encoding/ccf/encode.go
  runtime/account_test.go
  runtime/capabilitycontrollers_test.go
  runtime/coverage_test.go
  runtime/debugger_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value_accountcapabilitycontroller.go
  runtime/interpreter/value_accountreference.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/stdlib/account.go
  runtime/storage_test.go
Labels: Feature

#2483 Continue implementation of Cap Cons
  runtime/capabilitycontrollers_test.go
  runtime/config.go
  runtime/environment.go
  runtime/interpreter/value_account.go
  runtime/interpreter/value_accountcapabilitycontroller.go
  runtime/interpreter/value_storagecapabilitycontroller.go
  runtime/runtime_test.go
  runtime/sema/checker.go
  runtime/sema/config.go
  runtime/stdlib/account.go
  runtime/tests/checker/account_test.go
Labels: Feature

#2112 Add interface inheritance
  runtime/ast/attachment.go
  runtime/ast/composite.go
  runtime/ast/interface.go
  runtime/ast/interface_test.go
  runtime/interpreter/interpreter.go
  runtime/parser/declaration.go
  runtime/sema/check_casting_expression.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_interface_declaration.go
  runtime/sema/checker.go
  runtime/sema/errors.go
  runtime/sema/type.go
  runtime/sema/type_tags.go
  runtime/sema/type_test.go
  runtime/tests/checker/attachments_test.go
  runtime/tests/checker/interface_test.go
  runtime/tests/checker/resources_test.go
  runtime/tests/checker/type_inference_test.go
  runtime/tests/interpreter/interface_test.go
Labels: Feature

#2363 Parsing for Entitlements
  runtime/ast/access.go
  runtime/ast/access_string.go
  runtime/ast/access_test.go
  runtime/ast/attachment.go
  runtime/ast/attachment_test.go
  runtime/ast/composite_test.go
  runtime/ast/elementtype.go
  runtime/ast/elementtype_string.go
  runtime/ast/entitlement_declaration.go
  runtime/ast/entitlement_declaration_test.go
  runtime/ast/interface_test.go
  runtime/ast/members.go
  runtime/ast/primitiveaccess_string.go
  runtime/ast/transaction_declaration_test.go
  runtime/ast/type.go
  runtime/ast/type_test.go
  runtime/ast/variable_declaration.go
  runtime/common/declarationkind.go
  runtime/common/declarationkind_string.go
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/parser/declaration.go
  runtime/parser/declaration_test.go
  runtime/parser/expression.go
  runtime/parser/expression_test.go
  runtime/parser/keyword.go
  runtime/parser/lexer/lexer_test.go
  runtime/parser/lexer/state.go
  runtime/parser/lexer/tokentype.go
  runtime/parser/parser.go
  runtime/parser/statement_test.go
  runtime/parser/type.go
  runtime/parser/type_test.go
  runtime/sema/check_for.go
  runtime/sema/checker.go
Labels: Language Breaking Change, Feature

#2490 Add tag field to capability controllers
  runtime/capabilitycontrollers_test.go
  runtime/interpreter/value.go
  runtime/interpreter/value_accountcapabilitycontroller.go
  runtime/interpreter/value_storagecapabilitycontroller.go
  runtime/interpreter/value_string.go
  runtime/sema/account_capability_controller.cdc
  runtime/sema/account_capability_controller.gen.go
  runtime/sema/storage_capability_controller.cdc
  runtime/sema/storage_capability_controller.gen.go
  runtime/stdlib/account.go
  runtime/tests/checker/capability_controller_test.go
Labels: Feature

#2494 Continue implementation of Cap Cons: Backward compatibility
  runtime/capabilitycontrollers_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value_account_capabilities.go
  runtime/sema/authaccount.cdc
  runtime/sema/authaccount.gen.go
  runtime/stdlib/account.go
  runtime/tests/checker/account_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Feature

#2441 Type checking for entitlement and entitlement mapping declarations
  runtime/ast/access.go
  runtime/ast/entitlement_declaration.go
  runtime/ast/memberindices.go
  runtime/ast/members.go
  runtime/ast/program.go
  runtime/ast/programindices.go
  runtime/ast/type_test.go
  runtime/ast/visitor.go
  runtime/common/declarationkind.go
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/common/orderedmap/orderedmap.go
  runtime/compiler/compiler.go
  runtime/contract_update_validation_test.go
  runtime/convertTypes_test.go
  runtime/interpreter/interpreter_statement.go
  runtime/parser/declaration_test.go
  runtime/parser/type_test.go
  runtime/sema/access.go
  runtime/sema/accesscheckmode.go
  runtime/sema/check_assignment.go
  runtime/sema/check_attach_expression.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_for.go
  runtime/sema/check_function.go
  runtime/sema/check_import_declaration.go
  runtime/sema/check_interface_declaration.go
  runtime/sema/check_member_expression.go
  runtime/sema/check_variable_declaration.go
  runtime/sema/checker.go
  runtime/sema/elaboration.go
  runtime/sema/errors.go
  runtime/sema/gen/main.go
  runtime/sema/import.go
  runtime/sema/orderdmaps.go
  runtime/sema/type.go
  runtime/sema/typeannotationstate.go
  runtime/sema/typeannotationstate_string.go
  runtime/sema/variable.go
  runtime/sema/variable_activations.go
  runtime/stdlib/contract_update_validation.go
  runtime/tests/checker/entitlements_test.go
  runtime/tests/checker/import_test.go
  runtime/tests/interpreter/import_test.go
Labels: Language Breaking Change, Feature

#2502 Improve errors
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_transaction_declaration.go
  runtime/tests/checker/attachments_test.go
  tools/analysis/programs.go
Labels: Improvement

#2499 Add attachment keywords to keyword lists
  runtime/parser/declaration_test.go
  runtime/parser/keyword.go
  runtime/parser/statement_test.go
Labels: Bugfix

#2496 Add `fromBigEndianBytes` conversion function to `Number` types
  runtime/interpreter/big.go
  runtime/interpreter/interpreter.go
  runtime/sema/type.go
  runtime/tests/checker/builtinfunctions_test.go
  runtime/tests/interpreter/builtinfunctions_test.go
Labels: Feature

#2497 Introduce `Word128` integer type
  encoding/ccf/ccf_test.go
  encoding/ccf/decode.go
  encoding/ccf/decode_type.go
  encoding/ccf/encode.go
  encoding/ccf/simple_type_utils.go
  encoding/ccf/traverse_value.go
  encoding/json/decode.go
  encoding/json/encode.go
  encoding/json/encoding_test.go
  runtime/convertTypes.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/imported_values_memory_metering_test.go
  runtime/interpreter/decode.go
  runtime/interpreter/encode.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/hashablevalue.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/primitivestatictype.go
  runtime/interpreter/primitivestatictype_string.go
  runtime/interpreter/statictype_test.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/interpreter/visitor.go
  runtime/literal.go
  runtime/sema/type.go
  runtime/sema/type_names.go
  runtime/sema/type_tags.go
  runtime/sema/type_test.go
  runtime/tests/interpreter/arithmetic_test.go
  runtime/tests/interpreter/bitwise_test.go
  runtime/tests/interpreter/builtinfunctions_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/equality_test.go
  runtime/tests/interpreter/fixedpoint_test.go
  runtime/tests/interpreter/integers_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/values_test.go
  types.go
  types_test.go
  values.go
  values_test.go
Labels: Feature

#2510 Introduce Word256 integer type
  encoding/ccf/ccf_test.go
  encoding/ccf/decode.go
  encoding/ccf/decode_type.go
  encoding/ccf/encode.go
  encoding/ccf/simple_type_utils.go
  encoding/ccf/traverse_value.go
  encoding/json/decode.go
  encoding/json/encode.go
  encoding/json/encoding_test.go
  runtime/convertTypes.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/imported_values_memory_metering_test.go
  runtime/interpreter/decode.go
  runtime/interpreter/encode.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/hashablevalue.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/primitivestatictype.go
  runtime/interpreter/primitivestatictype_string.go
  runtime/interpreter/statictype_test.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/interpreter/visitor.go
  runtime/literal.go
  runtime/sema/type.go
  runtime/sema/type_names.go
  runtime/sema/type_tags.go
  runtime/tests/interpreter/arithmetic_test.go
  runtime/tests/interpreter/bitwise_test.go
  runtime/tests/interpreter/builtinfunctions_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/equality_test.go
  runtime/tests/interpreter/fixedpoint_test.go
  runtime/tests/interpreter/integers_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/values_test.go
  types.go
  types_test.go
  values.go
  values_test.go
Labels: Feature

#2492 Implement `check` functionality in AuthAccount
  runtime/interpreter/interpreter.go
  runtime/interpreter/value_account.go
  runtime/sema/authaccount.cdc
  runtime/sema/authaccount.gen.go
  runtime/tests/interpreter/account_test.go
Labels: Feature

#2514 Add tests for test framework blockchain
  runtime/stdlib/test_emulatorbackend.go
  runtime/stdlib/test_test.go
Labels: Bugfix, Improvement

#2516 Support 2 new attachment types in CCF codec
  encoding/ccf/ccf_test.go
  encoding/ccf/decode_type.go
  encoding/ccf/simple_type_utils.go
Labels: Feature

#2512 Improve linting
  .golangci.yml
  runtime/cmd/check/main.go
  runtime/cmd/parse/main.go
  runtime/stdlib/rlp/rlp.go
Labels: Chore

#2517 Improve export and encoding
  encoding/json/encode.go
  runtime/attachments_test.go
  runtime/convertValues_test.go
  runtime/runtime_test.go
Labels: Improvement

#2508 Add rule to clean linter
  Makefile
Labels: Chore

#2521 Support cyclic reference value in CCF codec
  encoding/ccf/ccf_test.go
  encoding/ccf/decode.go
  encoding/ccf/encode.go
  encoding/ccf/traverse_value.go
Labels: Feature
