Repository onflow/cadence, pull requests merged in 2023-07, with the labels that each got.

#2628 Add mailmap
  .mailmap
Labels: Chore

#2629 Add cyclic imports tests
  runtime/contract_test.go
  runtime/error_test.go
  runtime/import_test.go
  runtime/runtime_test.go
  runtime/sharedstate_test.go
Labels: Testing

#2624 Fix data race in sema/type_test.go
  runtime/sema/type.go
  runtime/sema/type_test.go
Labels: Bugfix

#2632 Improve cyclic import handling
  runtime/import_test.go
  runtime/sema/check_import_declaration.go
Labels: Improvement

#2621 Delegate Cadence composite `Storable()` to Atree
  runtime/interpreter/value.go
Labels: Improvement

#2622 Delegate storage address to Atree
  runtime/interpreter/value.go
Labels: Improvement

#2586 Introduce built-in mutability entitlements
  runtime/interpreter/interpreter.go
  runtime/sema/entitlements.cdc
  runtime/sema/entitlements.gen.go
  runtime/sema/entitlements.go
  runtime/sema/gen/main.go
  runtime/sema/gen/main_test.go
  runtime/sema/gen/testdata/entitlement.cdc
  runtime/sema/gen/testdata/entitlement.golden.go
  runtime/sema/type.go
  runtime/sema/type_test.go
  runtime/tests/checker/entitlements_test.go
  runtime/tests/interpreter/entitlements_test.go
Labels: Feature

#2587 Allow entitlement mappings to be used in container-typed composite-fields
  runtime/interpreter/interpreter_expression.go
  runtime/sema/check_expression.go
  runtime/sema/check_member_expression.go
  runtime/sema/checker.go
  runtime/sema/elaboration.go
  runtime/tests/checker/entitlements_test.go
  runtime/tests/checker/member_test.go
  runtime/tests/interpreter/member_test.go
Labels: Feature

#2588 Add identity entitlement mapping
  runtime/interpreter/interpreter.go
  runtime/sema/access.go
  runtime/sema/type.go
  runtime/sema/type_test.go
  runtime/tests/checker/entitlements_test.go
  runtime/tests/interpreter/entitlements_test.go
Labels: Feature

#2598 Add builtin entitlements to array/dictionary functions
  runtime/convertValues_test.go
  runtime/resource_duplicate_test.go
  runtime/runtime_test.go
  runtime/sema/checker.go
  runtime/sema/type.go
  runtime/tests/checker/arrays_dictionaries_test.go
  runtime/tests/checker/attachments_test.go
  runtime/tests/checker/entitlements_test.go
  runtime/tests/checker/external_mutation_test.go
  runtime/tests/checker/reference_test.go
  runtime/tests/interpreter/array_test.go
  runtime/tests/interpreter/dictionary_test.go
  runtime/tests/interpreter/reference_test.go
  runtime/tests/interpreter/resources_test.go
Labels: Language Breaking Change, Feature

#2636 Use diff command to generate diff
  .github/workflows/compatibility-check-template.yml
  tools/compatibility-check/cmd/check_diff/main.go
  tools/compatibility-check/go.mod
  tools/compatibility-check/go.sum
Labels: Chore

#2620 Update to new Atree API
  go.mod
  go.sum
  runtime/interpreter/deepcopyremove_test.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/storagemap.go
  runtime/interpreter/value.go
Labels: Improvement

#2644 Sync Atree register inlining branch with master
  .github/workflows/compatibility-check-template.yml
  runtime/ast/access.go
  runtime/common/concat.go
  runtime/interpreter/value.go
  runtime/literal_test.go
  runtime/sema/type.go
  runtime/sema/type_test.go
  runtime/tests/checker/builtinfunctions_test.go
  runtime/tests/checker/events_test.go
  runtime/tests/checker/integer_test.go
  runtime/tests/checker/operations_test.go
  runtime/tests/interpreter/arithmetic_test.go
  tools/compatibility-check/cmd/check_diff/main.go
  tools/compatibility-check/go.mod
  tools/compatibility-check/go.sum
Labels: Chore

#2634 Sync Stable Cadence
  .github/workflows/benchmark.yml
  .github/workflows/compatibility-check-template.yml
  .github/workflows/compatibility-check.yml
  .mailmap
  encoding/ccf/ccf_test.go
  encoding/ccf/decode.go
  runtime/ast/access.go
  runtime/common/concat.go
  runtime/interpreter/storagemap.go
  runtime/interpreter/value.go
  runtime/literal_test.go
  runtime/sema/character.cdc
  runtime/sema/character.gen.go
  runtime/sema/type.go
  runtime/sema/type_test.go
  runtime/stdlib/contracts/crypto_test.cdc
  runtime/stdlib/contracts/scripts/crypto_get_key_from_list.cdc
  runtime/stdlib/contracts/scripts/crypto_hash.cdc
  runtime/stdlib/contracts/scripts/crypto_hash_with_tag.cdc
  runtime/stdlib/contracts/scripts/crypto_key_list_add.cdc
  runtime/stdlib/contracts/scripts/crypto_key_list_verify.cdc
  runtime/stdlib/contracts/scripts/crypto_key_list_verify_duplicate_signature.cdc
  runtime/stdlib/contracts/scripts/crypto_key_list_verify_insufficient_weights.cdc
  runtime/stdlib/contracts/scripts/crypto_key_list_verify_invalid_signature.cdc
  runtime/stdlib/contracts/scripts/crypto_key_list_verify_missing_signature.cdc
  runtime/stdlib/contracts/scripts/crypto_key_list_verify_revoked.cdc
  runtime/stdlib/contracts/scripts/crypto_revoke_key_from_list.cdc
  runtime/stdlib/test_contract.go
  runtime/stdlib/test_test.go
  runtime/tests/checker/builtinfunctions_test.go
  runtime/tests/checker/character_test.go
  runtime/tests/checker/events_test.go
  runtime/tests/checker/integer_test.go
  runtime/tests/checker/operations_test.go
  runtime/tests/interpreter/arithmetic_test.go
  runtime/tests/interpreter/character_test.go
  tools/update/config.yaml
Labels: Chore

#2589 Allow emit statements in conditions
  runtime/ast/block.go
  runtime/ast/block_test.go
  runtime/ast/expression_test.go
  runtime/ast/transaction_declaration_test.go
  runtime/coverage.go
  runtime/interpreter/interpreter.go
  runtime/parser/declaration_test.go
  runtime/parser/statement.go
  runtime/parser/transaction.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_conditions.go
  runtime/sema/check_interface_declaration.go
  runtime/sema/checker.go
  runtime/sema/errors.go
  runtime/tests/checker/conditions_test.go
  runtime/tests/checker/purity_test.go
  runtime/tests/interpreter/condition_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Bugfix, Feature

#2645 Use new Atree API
  go.mod
  go.sum
  runtime/cmd/decode-state-values/main.go
  runtime/interface.go
  runtime/interpreter/decode.go
  runtime/interpreter/deepcopyremove_test.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/sharedstate.go
  runtime/interpreter/storage.go
  runtime/interpreter/storage_test.go
  runtime/interpreter/storagemap.go
  runtime/interpreter/value.go
  runtime/runtime_test.go
  runtime/storage.go
  runtime/storage_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/values_test.go
Labels: Improvement

#2651 [v0.39] Remove spurious resource loss errors (internal #130)
  runtime/sema/check_return_statement.go
  runtime/sema/variable_activations.go
  runtime/tests/checker/function_test.go
  runtime/tests/checker/resources_test.go
Labels: Bugfix

#2656 Add support for max parameter count (internal #128)
  runtime/account_test.go
  runtime/interpreter/interpreter.go
  runtime/sema/authaccount.go
  runtime/sema/check_invocation_expression.go
  runtime/sema/errors.go
  runtime/sema/type.go
  runtime/stdlib/assert.go
  runtime/stdlib/builtin_test.go
  runtime/stdlib/test_contract.go
  runtime/tests/checker/arrays_dictionaries_test.go
  runtime/tests/checker/builtinfunctions_test.go
  runtime/tests/checker/casting_test.go
  runtime/tests/checker/conditions_test.go
  runtime/tests/checker/genericfunction_test.go
  runtime/tests/checker/integer_test.go
  runtime/tests/checker/invocation_test.go
  runtime/tests/checker/metatype_test.go
  runtime/tests/checker/runtimetype_test.go
  runtime/tests/checker/type_inference_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Bugfix

#2657 Remove spurious resource loss errors (internal #130)
  runtime/sema/check_return_statement.go
  runtime/sema/variable_activations.go
  runtime/tests/checker/function_test.go
  runtime/tests/checker/resources_test.go
Labels: Bugfix

#2658 Fix checking of reference expressions involving optionals (internal #129)
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/value.go
  runtime/runtime_test.go
  runtime/sema/check_reference_expression.go
  runtime/tests/checker/reference_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/reference_test.go
Labels: Bugfix

#2659 Prevent recursive transfers (internal #133)
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_invocation.go
  runtime/interpreter/interpreter_statement.go
  runtime/interpreter/simplecompositevalue.go
  runtime/interpreter/value.go
  runtime/interpreter/value_accountcapabilitycontroller.go
  runtime/interpreter/value_accountreference.go
  runtime/interpreter/value_function.go
  runtime/interpreter/value_publickey.go
  runtime/interpreter/value_storagecapabilitycontroller.go
  runtime/interpreter/value_test.go
  runtime/runtime_test.go
  runtime/stdlib/account.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/reference_test.go
  runtime/tests/interpreter/resources_test.go
  runtime/tests/interpreter/values_test.go
Labels: Bugfix

#2619 Provide suggested fixes for argument label errors
  runtime/parser/declaration_test.go
  runtime/parser/expression.go
  runtime/parser/expression_test.go
  runtime/parser/parser_test.go
  runtime/sema/errors.go
  tools/analysis/diagnostic.go
Labels: Feature

#2625 Suggest optional chaining
  runtime/sema/errors.go
Labels: Feature

#2661 Handle destroyed optional references
  runtime/interpreter/location.go
  runtime/interpreter/location_test.go
  runtime/interpreter/value.go
  runtime/runtime_test.go
  runtime/script_executor.go
  runtime/tests/interpreter/reference_test.go
Labels: Bugfix

#2637 Return a reference with all entitlements, when access through owned values
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/sema/check_member_expression.go
  runtime/tests/checker/entitlements_test.go
  runtime/tests/interpreter/entitlements_test.go
Labels: Feature

#2666 Make more `AuthAccount` functions `view`
  runtime/sema/authaccount.cdc
  runtime/sema/authaccount.gen.go
  runtime/tests/checker/purity_test.go
Labels: Bugfix

#2665 Fix positioning of default function conflict errors
  runtime/error_test.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/errors.go
Labels: Bugfix

#2668 Fix entitlement memory metering
  runtime/ast/entitlement_declaration.go
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
Labels: Technical Debt

#2674 Fix interface inheritance for nested interfaces
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_interface_declaration.go
  runtime/sema/checker.go
  runtime/tests/checker/interface_test.go
  runtime/tests/interpreter/interface_test.go
Labels: Bugfix

#2680 Update reference invalidation check to consider optional resources
  runtime/interpreter/interpreter.go
  runtime/runtime_test.go
Labels: Bugfix
