Repository onflow/cadence, pull requests merged in 2023-08, with the labels that each got.

#2683 Wrap host env errors with external errors
  go.cap
  runtime/environment.go
  runtime/events.go
  runtime/interpreter/errors.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/stdlib/account.go
  runtime/stdlib/block.go
  runtime/stdlib/hashalgorithm.go
  runtime/stdlib/log.go
  runtime/stdlib/publickey.go
  runtime/stdlib/random.go
  runtime/storage.go
Labels: Bugfix

#2686 Fix interface member inheritance
  runtime/sema/type.go
  runtime/tests/checker/interface_test.go
  runtime/tests/interpreter/interface_test.go
Labels: Bugfix

#2664 Make indexing assignment entitled
  runtime/account_test.go
  runtime/capabilitycontrollers_test.go
  runtime/resource_duplicate_test.go
  runtime/runtime_test.go
  runtime/sema/check_assignment.go
  runtime/sema/check_member_expression.go
  runtime/sema/check_variable_declaration.go
  runtime/sema/errors.go
  runtime/sema/type.go
  runtime/tests/checker/arrays_dictionaries_test.go
  runtime/tests/checker/entitlements_test.go
  runtime/tests/checker/external_mutation_test.go
  runtime/tests/checker/member_test.go
  runtime/tests/checker/reference_test.go
  runtime/tests/interpreter/container_mutation_test.go
  runtime/tests/interpreter/member_test.go
  runtime/tests/interpreter/reference_test.go
  runtime/tests/interpreter/string_test.go
Labels: Language Breaking Change, Feature

#2687 Fix error on reference creation with invalid type
  runtime/sema/check_reference_expression.go
  runtime/tests/checker/reference_test.go
Labels: Bugfix

#2673 Temporarily remove deprecations for existing capability API
  runtime/sema/authaccount.cdc
  runtime/sema/authaccount.gen.go
  runtime/sema/publicaccount.cdc
  runtime/sema/publicaccount.gen.go
Labels: Technical Debt

#2690 Rename mutability entitlements
  runtime/account_test.go
  runtime/capabilitycontrollers_test.go
  runtime/convertValues_test.go
  runtime/resource_duplicate_test.go
  runtime/runtime_test.go
  runtime/sema/check_assignment.go
  runtime/sema/entitlements.cdc
  runtime/sema/entitlements.gen.go
  runtime/sema/type.go
  runtime/tests/checker/arrays_dictionaries_test.go
  runtime/tests/checker/attachments_test.go
  runtime/tests/checker/entitlements_test.go
  runtime/tests/checker/reference_test.go
  runtime/tests/interpreter/array_test.go
  runtime/tests/interpreter/container_mutation_test.go
  runtime/tests/interpreter/dictionary_test.go
  runtime/tests/interpreter/entitlements_test.go
  runtime/tests/interpreter/member_test.go
  runtime/tests/interpreter/reference_test.go
  runtime/tests/interpreter/resources_test.go
  runtime/tests/interpreter/string_test.go
Labels: Chore

#2692 Cleanup
  runtime/interpreter/location.go
  runtime/interpreter/value.go
  runtime/literal.go
  runtime/parser/errors.go
  runtime/parser/expression.go
  runtime/parser/type.go
  runtime/tests/utils/utils.go
Labels: Improvement

#2694 Update to Go 1.20, improve random value generation
  .github/workflows/benchmark.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/compatibility-check-template.yml
  .github/workflows/compatibility-check.yml
  .github/workflows/downstream.yml
  .github/workflows/release.yml
  go.mod
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/values_test.go
  tools/batch-script/go.mod
  tools/compatibility-check/go.mod
  tools/constructorcheck/go.mod
  tools/golangci-lint/go.mod
  tools/maprange/go.mod
  tools/unkeyed/go.mod
Labels: Chore

#2697 Allow default functions to co-exist with conditions in interface conformance
  runtime/ast/block.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_interface_declaration.go
  runtime/sema/type.go
  runtime/tests/checker/interface_test.go
Labels: Language Breaking Change, Improvement

#2699 Improve view annotations for account type functions
  runtime/sema/authaccount.cdc
  runtime/sema/authaccount.gen.go
  runtime/sema/publicaccount.cdc
  runtime/sema/publicaccount.gen.go
  runtime/tests/checker/purity_test.go
Labels: Improvement

#2702 Update storage iteration value check and related tests
  runtime/interpreter/interpreter.go
  runtime/storage_test.go
Labels: Technical Debt

#2696 Cadence testing framework improvements
  runtime/stdlib/contracts/test.cdc
  runtime/stdlib/test-framework.go
  runtime/stdlib/test_emulatorbackend.go
  runtime/stdlib/test_test.go
Labels: Improvement

#2701 Sync Stable Cadence branch with master
  .github/workflows/benchmark.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/compatibility-check-template.yml
  .github/workflows/compatibility-check.yml
  .github/workflows/downstream.yml
  .github/workflows/release.yml
  go.cap
  go.mod
  npm-packages/cadence-parser/package.json
  runtime/environment.go
  runtime/events.go
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/location.go
  runtime/interpreter/value.go
  runtime/literal.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/sema/check_reference_expression.go
  runtime/stdlib/account.go
  runtime/stdlib/block.go
  runtime/stdlib/hashalgorithm.go
  runtime/stdlib/log.go
  runtime/stdlib/publickey.go
  runtime/stdlib/random.go
  runtime/storage.go
  runtime/storage_test.go
  runtime/tests/checker/reference_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/values_test.go
  runtime/tests/utils/utils.go
  tools/batch-script/go.mod
  tools/compatibility-check/go.mod
  tools/constructorcheck/go.mod
  tools/golangci-lint/go.mod
  tools/maprange/go.mod
  tools/unkeyed/go.mod
  version.go
Labels: Chore

#2460 Invalidate references to nested resources upon the move of the outer resource
  go.mod
  go.sum
  runtime/cmd/decode-state-values/main.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/interpreter/value_function.go
  runtime/runtime_test.go
  runtime/tests/interpreter/reference_test.go
  runtime/tests/interpreter/resources_test.go
Labels: Bugfix

#2704 Hex encode user input in error to avoid invalid UTF-8
  encoding/json/decode.go
  encoding/json/encoding_test.go
Labels: Bugfix

#2678 Introduce `filter` in Fixed/Variable sized Array types
  runtime/interpreter/value.go
  runtime/sema/type.go
  runtime/tests/checker/arrays_dictionaries_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Feature

#2716 Use thread safe data structures for entitlement maps
  runtime/convertTypes.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/statictype.go
  runtime/sema/access.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_function.go
  runtime/sema/check_member_expression.go
  runtime/sema/checker.go
  runtime/sema/checker_test.go
  runtime/sema/errors.go
  runtime/sema/type.go
Labels: Bugfix

#2706 Update randomness runtime interface method
  runtime/environment.go
  runtime/interface.go
  runtime/runtime_test.go
  runtime/stdlib/random.go
Labels: Feature, Go API Breaking Change

#2722 Add test for borrowing as inherited interface
  runtime/capabilitycontrollers_test.go
Labels: Testing

#2723 Properly meter the creation of entitlement static types
  runtime/convertTypes.go
  runtime/convertValues_test.go
  runtime/interpreter/decode.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/statictype.go
  runtime/tests/interpreter/entitlements_test.go
  runtime/tests/interpreter/metatype_test.go
  runtime/tests/interpreter/reference_test.go
  runtime/tests/interpreter/runtimetype_test.go
Labels: Bugfix

#2728 Add purity/view annotations
  go.mod
  runtime/cmd/info/README.md
  runtime/cmd/info/main.go
  runtime/sema/character.cdc
  runtime/sema/character.gen.go
  runtime/sema/deployedcontract.cdc
  runtime/sema/deployedcontract.gen.go
  runtime/sema/string_type.go
  runtime/sema/type.go
  runtime/tests/checker/utils.go
Labels: Improvement

#2730 Entitlements error improvements
  runtime/sema/check_member_expression.go
  runtime/sema/errors.go
  runtime/tests/checker/attachments_test.go
  runtime/tests/checker/entitlements_test.go
Labels: Improvement

#2724 Add capability field to capabilitity controllers
  runtime/capabilitycontrollers_test.go
  runtime/interpreter/value_accountcapabilitycontroller.go
  runtime/interpreter/value_storagecapabilitycontroller.go
  runtime/sema/account_capability_controller.cdc
  runtime/sema/account_capability_controller.gen.go
  runtime/sema/storage_capability_controller.cdc
  runtime/sema/storage_capability_controller.gen.go
  runtime/stdlib/account.go
  runtime/tests/checker/capability_controller_test.go
Labels: Feature

#2732 Add test for attachment on built-in composite
  runtime/tests/interpreter/attachments_test.go
Labels: Testing

#2734 Allow `moveTime` function to accept negative time deltas for going backwards in time
  runtime/stdlib/contracts/test.cdc
  runtime/stdlib/test_emulatorbackend.go
  runtime/stdlib/test_test.go
Labels: Improvement

#2717 Give `CompositeTypeHandler` higher precedence over `getUserCompositeType`
  runtime/interpreter/interpreter.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Improvement

#2731 Improve REPL
  runtime/cmd/check/main.go
  runtime/cmd/cmd.go
  runtime/cmd/compile/main.go
  runtime/environment.go
  runtime/format/function.go
  runtime/interpreter/value_function.go
  runtime/repl.go
  runtime/stdlib/log.go
  values.go
  values_test.go
Labels: Improvement

#2737 Introduce `map` in Fixed/Variable sized Array types
  runtime/interpreter/value.go
  runtime/sema/type.go
  runtime/tests/checker/arrays_dictionaries_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Feature

#2742 Add `cadence-tools/test` as a dependency to the language server
  tools/update/config.yaml
Labels: Technical Debt

#2740 Add meeting notes for 2023-08-15
  meetings/2023-08-15.md
Labels: Documentation

#2736 add suggestions for missing entitlements in access errors
  runtime/sema/check_member_expression.go
  runtime/sema/errors.go
  runtime/tests/checker/attachments_test.go
  runtime/tests/checker/entitlements_test.go
Labels: Improvement

#2743 Composition of entitlement mappings
  runtime/ast/entitlement_declaration.go
  runtime/ast/entitlement_declaration_test.go
  runtime/ast/type.go
  runtime/entitlements_test.go
  runtime/parser/declaration.go
  runtime/parser/declaration_test.go
  runtime/parser/keyword.go
  runtime/sema/access.go
  runtime/sema/check_interface_declaration.go
  runtime/sema/errors.go
  runtime/sema/type.go
  runtime/tests/checker/entitlements_test.go
  runtime/tests/interpreter/entitlements_test.go
Labels: Feature

#2738 Improve error message for overloaded declaration
  runtime/sema/check_composite_declaration.go
  runtime/tests/checker/overloading_test.go
Labels: Improvement

#2751 Improve composite and interface static types
  encoding/json/encode.go
  runtime/convertTypes.go
  runtime/convertValues_test.go
  runtime/interpreter/decode.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/statictype.go
  runtime/interpreter/statictype_test.go
  runtime/interpreter/value.go
  runtime/sema/type.go
  runtime/stdlib/bls.go
  runtime/stdlib/hashalgorithm.go
  runtime/stdlib/rlp.go
  runtime/stdlib/signaturealgorithm.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/runtimetype_test.go
  types.go
Labels: Improvement

#2754 sort entitlement sets alphabetically when generating strings
  runtime/common/orderedmap/orderedmap.go
  runtime/sema/access.go
  runtime/tests/checker/entitlements_test.go
  runtime/tests/interpreter/entitlements_test.go
Labels: Improvement

#2750 Avoid unnecessary static to sema type conversions for `Type`
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/primitivestatictype.go
  runtime/interpreter/statictype.go
  runtime/interpreter/statictype_test.go
  runtime/interpreter/value.go
  runtime/sema/runtime_type_constructors.go
  runtime/sema/type.go
  runtime/tests/interpreter/metatype_test.go
Labels: Improvement

#2755 Sync Stable Cadence feature branch
  encoding/json/decode.go
  encoding/json/encode.go
  encoding/json/encoding_test.go
  meetings/2023-08-15.md
  runtime/capabilitycontrollers_test.go
  runtime/cmd/cmd.go
  runtime/convertTypes.go
  runtime/convertValues_test.go
  runtime/environment.go
  runtime/interface.go
  runtime/interpreter/decode.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/primitivestatictype.go
  runtime/interpreter/statictype.go
  runtime/interpreter/statictype_test.go
  runtime/interpreter/value.go
  runtime/interpreter/value_accountcapabilitycontroller.go
  runtime/interpreter/value_storagecapabilitycontroller.go
  runtime/runtime_test.go
  runtime/sema/account_capability_controller.cdc
  runtime/sema/account_capability_controller.gen.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/runtime_type_constructors.go
  runtime/sema/storage_capability_controller.cdc
  runtime/sema/storage_capability_controller.gen.go
  runtime/sema/type.go
  runtime/stdlib/account.go
  runtime/stdlib/bls.go
  runtime/stdlib/contracts/test.cdc
  runtime/stdlib/hashalgorithm.go
  runtime/stdlib/random.go
  runtime/stdlib/rlp.go
  runtime/stdlib/signaturealgorithm.go
  runtime/stdlib/test-framework.go
  runtime/stdlib/test_contract.go
  runtime/stdlib/test_emulatorbackend.go
  runtime/stdlib/test_test.go
  runtime/tests/checker/arrays_dictionaries_test.go
  runtime/tests/checker/capability_controller_test.go
  runtime/tests/checker/overloading_test.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/attachments_test.go
  runtime/tests/interpreter/container_mutation_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/metatype_test.go
  runtime/tests/interpreter/runtimetype_test.go
  tools/update/config.yaml
  types.go
Labels: Chore

#2746 Make CodesAndPrograms public
  runtime/context.go
  runtime/contract_function_executor.go
  runtime/environment.go
  runtime/errors.go
  runtime/runtime.go
  runtime/script_executor.go
  runtime/transaction_executor.go
Labels: Improvement

#2757 Clean up intersection types
  encoding/ccf/decode.go
  encoding/ccf/decode_type.go
  runtime/sema/checker.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Technical Debt
