Repository onflow/cadence, pull requests merged in 2023-10, with the labels that each got.

#2835 Check `before` statements in `view` contexts
  runtime/sema/check_function.go
  runtime/tests/checker/conditions_test.go
  runtime/tests/checker/resources_test.go
Labels: Bugfix

#2838 Skip adding malformed entitlement relations to maps
  runtime/sema/check_interface_declaration.go
  runtime/tests/checker/entitlements_test.go
Labels: Bugfix

#2841 [v0.39] Port internal 141: Fix swapping in resource array
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/value.go
  runtime/interpreter/value_placeholder.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Bugfix

#2840 Require full codomain of map when assigning to mapped field
  runtime/sema/check_member_expression.go
  runtime/tests/checker/entitlements_test.go
Labels: Bugfix

#2844 Port internal 141: Fix swapping in resource array
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/value.go
  runtime/interpreter/value_placeholder.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Bugfix

#2846 Port internal fix 145: Prevent re-deploy in same transaction
  runtime/contract_test.go
  runtime/contract_update_test.go
  runtime/environment.go
  runtime/stdlib/account.go
  runtime/storage.go
Labels: Bugfix

#2847 Properly set base on loaded attachments during attachment iteration
  runtime/interpreter/interpreter_statement.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/attachments_test.go
Labels: Bugfix

#2842 [v0.39] Port internal 144: Fix swap statement evaluation
  runtime/interpreter/interpreter_statement.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Bugfix

#2843 [v0.39] Port internal fix 145: Prevent re-deploy in same transaction
  runtime/contract_test.go
  runtime/contract_update_test.go
  runtime/environment.go
  runtime/stdlib/account.go
  runtime/storage.go
Labels: Bugfix

#2509 Fix memory metering for loading stored values
  runtime/common/metering.go
  runtime/interpreter/storage.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Bugfix

#2854 Sync Stable Cadence
  runtime/cmd/cmd.go
  runtime/contract_test.go
  runtime/contract_update_test.go
  runtime/environment.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_statement.go
  runtime/interpreter/value.go
  runtime/interpreter/value_placeholder.go
  runtime/sema/check_function.go
  runtime/sema/errors.go
  runtime/sema/type.go
  runtime/stdlib/account.go
  runtime/stdlib/contracts/test.cdc
  runtime/stdlib/test-framework.go
  runtime/stdlib/test.go
  runtime/stdlib/test_contract.go
  runtime/stdlib/test_emulatorbackend.go
  runtime/stdlib/test_test.go
  runtime/storage.go
  runtime/tests/checker/function_test.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Chore

#2851 mjs build for cadence-parser
  npm-packages/cadence-parser/package-lock.json
  npm-packages/cadence-parser/package.json
Labels: Improvement

#2850 Allow native functions to have type parameters
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_function.go
  runtime/sema/checker.go
  runtime/sema/errors.go
  runtime/tests/checker/genericfunction_test.go
Labels: Feature

#2868 [stable-cadence] Fix field assignment via references
  runtime/sema/check_assignment.go
  runtime/sema/check_expression.go
  runtime/sema/check_invocation_expression.go
  runtime/sema/check_member_expression.go
  runtime/tests/checker/account_test.go
  runtime/tests/checker/reference_test.go
Labels: Bugfix

#2814 Introduce `String.replaceAll` instance function
  runtime/interpreter/value.go
  runtime/sema/string_type.go
  runtime/tests/checker/string_test.go
  runtime/tests/interpreter/string_test.go
Labels: Feature

#2880 Add computation metering to the new stdlib functions
  runtime/common/computationkind.go
  runtime/common/computationkind_string.go
  runtime/interpreter/value.go
  runtime/interpreter/value_string.go
  runtime/tests/interpreter/metering_test.go
Labels: Technical Debt

#2877 Entitlement mapping escape fixes
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/sema/check_function.go
  runtime/sema/check_member_expression.go
  runtime/sema/checker.go
  runtime/tests/checker/entitlements_test.go
  runtime/tests/interpreter/entitlements_test.go
Labels: Bugfix

#2891 Use `ComputationKindLoop` for internal array-value iterations
  runtime/common/computationkind.go
  runtime/common/computationkind_string.go
  runtime/interpreter/value.go
  runtime/interpreter/value_string.go
  runtime/tests/interpreter/metering_test.go
Labels: Technical Debt

#2859 Allow specifying a mapping with source paths for locations in coverage reports
  runtime/coverage.go
  runtime/coverage_test.go
Labels: Feature

#2887 Allow different base activations per location in checker and interpreter
  runtime/cmd/cmd.go
  runtime/environment.go
  runtime/interpreter/config.go
  runtime/interpreter/interpreter.go
  runtime/predeclaredvalues_test.go
  runtime/repl.go
  runtime/sema/checker.go
  runtime/sema/config.go
  runtime/stdlib/builtin_test.go
  runtime/stdlib/test_contract.go
  runtime/stdlib/test_test.go
  runtime/tests/checker/account_test.go
  runtime/tests/checker/assert_test.go
  runtime/tests/checker/capability_controller_test.go
  runtime/tests/checker/crypto_test.go
  runtime/tests/checker/genericfunction_test.go
  runtime/tests/checker/interface_test.go
  runtime/tests/checker/invocation_test.go
  runtime/tests/checker/nesting_test.go
  runtime/tests/checker/nft_test.go
  runtime/tests/checker/predeclaredvalues_test.go
  runtime/tests/checker/return_test.go
  runtime/tests/checker/rlp_test.go
  runtime/tests/checker/storable_test.go
  runtime/tests/checker/utils_test.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/attachments_test.go
  runtime/tests/interpreter/composite_value_test.go
  runtime/tests/interpreter/condition_test.go
  runtime/tests/interpreter/container_mutation_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/equality_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/invocation_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/metatype_test.go
  runtime/tests/interpreter/transfer_test.go
  tools/analysis/programs.go
Labels: Feature, Go API Breaking Change

#2894 Improve test runtime interface
  runtime/tests/runtime_utils/testinterface.go
Labels: Improvement

#2883 Add required `mapping` keyword to entitlement mapping usages
  runtime/ast/access.go
  runtime/ast/access_test.go
  runtime/ast/type.go
  runtime/ast/type_test.go
  runtime/entitlements_test.go
  runtime/parser/declaration.go
  runtime/parser/declaration_test.go
  runtime/parser/type.go
  runtime/parser/type_test.go
  runtime/sema/checker.go
  runtime/sema/errors.go
  runtime/tests/checker/attachments_test.go
  runtime/tests/checker/entitlements_test.go
  runtime/tests/checker/member_test.go
  runtime/tests/interpreter/attachments_test.go
  runtime/tests/interpreter/entitlements_test.go
  runtime/tests/interpreter/member_test.go
Labels: Language Breaking Change

#2782 Restrict `capabilities.publish` to account's own capabilities
  runtime/capabilitycontrollers_test.go
  runtime/interpreter/errors.go
  runtime/stdlib/account.go
Labels: Language Breaking Change, Improvement

#2895 Fix string atree value comparison: handle storage as slab
  runtime/inbox_test.go
  runtime/interpreter/stringatreevalue.go
  runtime/interpreter/stringatreevalue_test.go
Labels: Bugfix

#2890 Removing an attachment is an impure operation
  runtime/sema/check_remove_statement.go
  runtime/tests/checker/attachments_test.go
Labels: Bugfix

#2876 Add support iterating references to iterables
  runtime/interpreter/interpreter_statement.go
  runtime/interpreter/value.go
  runtime/sema/check_assignment.go
  runtime/sema/check_for.go
  runtime/sema/check_member_expression.go
  runtime/sema/check_variable_declaration.go
  runtime/sema/elaboration.go
  runtime/tests/checker/for_test.go
  runtime/tests/interpreter/for_test.go
Labels: Feature

#2878 Allow injection of functions into composite values, refactor PublicKey based on it
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/environment.go
  runtime/interpreter/config.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/interpreter/value_publickey.go
  runtime/interpreter/value_test.go
  runtime/predeclaredvalues_test.go
  runtime/stdlib/account.go
  runtime/stdlib/bls.go
  runtime/stdlib/builtin.go
  runtime/stdlib/publickey.go
  runtime/stdlib/test_emulatorbackend.go
  runtime/tests/interpreter/attachments_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Feature, Improvement

#2901 [v0.39] Prevent nested contract deployments
  runtime/contract_update_test.go
  runtime/environment.go
  runtime/stdlib/account.go
Labels: Bugfix

#2904 [v0.42] Prevent nested contract deployments
  runtime/contract_update_test.go
  runtime/environment.go
  runtime/stdlib/account.go
Labels: Bugfix

#2902 Prevent nested contract deployments
  runtime/contract_update_test.go
  runtime/environment.go
  runtime/stdlib/account.go
Labels: Bugfix

#2896 add new `revertibleRandom` function
  runtime/common/computationkind.go
  runtime/common/computationkind_string.go
  runtime/environment.go
  runtime/runtime_test.go
  runtime/stdlib/builtin.go
  runtime/stdlib/random.go
Labels: Feature

#2872 Introduce `HashableStruct` type to represent Dictionary keys
  encoding/ccf/ccf_test.go
  encoding/ccf/decode_type.go
  encoding/ccf/simple_type_utils.go
  encoding/json/decode.go
  encoding/json/encode.go
  encoding/json/encoding_test.go
  runtime/convertTypes.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/primitivestatictype.go
  runtime/interpreter/primitivestatictype_string.go
  runtime/sema/check_dictionary_expression.go
  runtime/sema/checker.go
  runtime/sema/hashable_struct.cdc
  runtime/sema/hashable_struct.gen.go
  runtime/sema/hashable_struct.go
  runtime/sema/path_type.go
  runtime/sema/simple_type.go
  runtime/sema/storable_type.go
  runtime/sema/type.go
  runtime/sema/type_tags.go
  runtime/sema/type_test.go
  runtime/tests/checker/arrays_dictionaries_test.go
  runtime/tests/checker/conditional_test.go
  runtime/tests/checker/events_test.go
  runtime/tests/checker/hashable_struct_test.go
  runtime/tests/checker/storable_test.go
  runtime/tests/checker/type_inference_test.go
  types.go
Labels: Feature

#2789 Remove support for custom destructors
  encoding/ccf/ccf_test.go
  encoding/json/encoding_test.go
  runtime/ast/memberindices.go
  runtime/ast/memberindices_test.go
  runtime/ast/members.go
  runtime/common/declarationkind.go
  runtime/common/declarationkind_string.go
  runtime/convertValues_test.go
  runtime/ft_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/nft_test.go
  runtime/parser/declaration.go
  runtime/parser/declaration_test.go
  runtime/parser/errors.go
  runtime/resource_duplicate_test.go
  runtime/resourcedictionary_test.go
  runtime/runtime_test.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_interface_declaration.go
  runtime/sema/errors.go
  runtime/storage_test.go
  runtime/tests/checker/access_test.go
  runtime/tests/checker/attachments_test.go
  runtime/tests/checker/composite_test.go
  runtime/tests/checker/conditions_test.go
  runtime/tests/checker/initialization_test.go
  runtime/tests/checker/nft_test.go
  runtime/tests/checker/overloading_test.go
  runtime/tests/checker/reference_test.go
  runtime/tests/checker/resources_test.go
  runtime/tests/checker/storable_test.go
  runtime/tests/checker/swap_test.go
  runtime/tests/interpreter/attachments_test.go
  runtime/tests/interpreter/condition_test.go
  runtime/tests/interpreter/entitlements_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/member_test.go
  runtime/tests/interpreter/reference_test.go
  runtime/tests/interpreter/resources_test.go
Labels: Language Breaking Change

#2799 Support for parsing default destroy events
  runtime/ast/composite.go
  runtime/ast/expression_test.go
  runtime/ast/function_declaration_test.go
  runtime/ast/parameter.go
  runtime/ast/parameterlist.go
  runtime/parser/declaration.go
  runtime/parser/declaration_test.go
  runtime/parser/function.go
  runtime/parser/transaction.go
Labels: Language Breaking Change, Feature

#2812 Type checking for default events
  runtime/ast/composite.go
  runtime/parser/declaration.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_emit_statement.go
  runtime/sema/check_interface_declaration.go
  runtime/sema/errors.go
  runtime/sema/type.go
  runtime/tests/checker/events_test.go
Labels: Language Breaking Change, Feature

#2910 [v0.42] Port adding new `revertibleRandom` function
  runtime/common/computationkind.go
  runtime/common/computationkind_string.go
  runtime/environment.go
  runtime/runtime_test.go
  runtime/stdlib/builtin.go
  runtime/stdlib/random.go
Labels: Chore

#2916 Refactor resource-reference tracking
  runtime/environment.go
  runtime/interpreter/config.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/value.go
  runtime/stdlib/account.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/attachments_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/uuid_test.go
Labels: Improvement
