Repository onflow/cadence, pull requests merged in 2023-02, with the labels that each got.

#2286 add unwrap to ExternalError
  go.cap
  runtime/environment.go
  runtime/errors/errors.go
  runtime/errors/wrappanic.go
  runtime/events.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/sema/errors.go
  runtime/stdlib/account.go
  runtime/stdlib/block.go
  runtime/stdlib/bls.go
  runtime/stdlib/hashalgorithm.go
  runtime/stdlib/log.go
  runtime/stdlib/publickey.go
  runtime/stdlib/random.go
  runtime/storage.go
  runtime/transaction_executor.go
Labels: Improvement

#2225 Refactor external types to instantiate only once whenever possible
  encoding/json/decode.go
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/convertTypes.go
  runtime/convertTypes_test.go
  runtime/runtime_memory_metering_test.go
  types.go
  values.go
  values_test.go
Labels: Improvement

#2281 add Config() method to runtime.Runtime interface
  runtime/runtime.go
  runtime/runtime_test.go
Labels: Improvement

#2288 Make compatibility checker workflow work with old tags
  .github/workflows/compatibility-check-template.yml
  .github/workflows/compatibility-check.yml
  .github/workflows/release.yml
  docs/releasing.md
  tools/compatibility-check/go.mod
  tools/compatibility-check/go.sum
Labels: Technical Debt

#2291 Improve compatibility diff checker
  .github/workflows/compatibility-check-template.yml
  docs/releasing.md
  tools/compatibility-check/contracts_checker.go
Labels: Improvement, Chore

#2284 Transaction role prepare blocks take one signer each
  runtime/interpreter/interpreter_transaction.go
  runtime/sema/check_transaction_declaration.go
  runtime/sema/errors.go
  runtime/tests/checker/transactions_test.go
  runtime/tests/interpreter/transactions_test.go
Labels: Improvement

#2287 Add support for type parameters to Cadence to Go type translator
  runtime/sema/gen/main.go
  runtime/sema/gen/testdata/fields.golden.go
  runtime/sema/gen/testdata/functions.cdc
  runtime/sema/gen/testdata/functions.golden.go
  runtime/sema/type.go
Labels: Improvement

#2297 Fix: typos
  docs/tutorial/03-resources.mdx
  docs/tutorial/08-marketplace-compose.mdx
Labels: Documentation

#2308 Reject cyclic imports during contract deployment
  runtime/environment.go
  runtime/import_test.go
Labels: Breaking Change, Improvement

#2307 Handle cyclic imports in analyzer tool
  tools/analysis/analysis_test.go
  tools/analysis/programs.go
  tools/compatibility-check/contracts_checker.go
  tools/compatibility-check/contracts_checker_test.go
  tools/compatibility-check/go.mod
  tools/compatibility-check/go.sum
Labels: Bugfix

#2302 Fix docstring parsing for functions
  runtime/parser/declaration_test.go
  runtime/parser/function.go
Labels: Bugfix

#2295 Optimize keyword testing
  go.mod
  go.sum
  runtime/parser/expression_test.go
  runtime/parser/keyword.go
  runtime/parser/parser.go
  runtime/parser/statement_test.go
Labels: Performance

#2313 Re-merge #2302, Fix docstring parsing for functions
  runtime/parser/declaration_test.go
  runtime/parser/function.go
Labels: Bugfix

#2298 Simplify lookaheads
  runtime/parser/declaration.go
  runtime/parser/expression.go
  runtime/parser/type.go
Labels: Improvement, Performance

#2306 Clear the test runtime program cache automatically after contract update
  runtime/runtime.go
  runtime/runtime_test.go
Labels: Improvement

#2303 Retain docstrings for special function declarations, remove unnecessary return type annotations
  runtime/parser/declaration.go
  runtime/parser/declaration_test.go
  runtime/parser/expression_test.go
  runtime/parser/function.go
  runtime/parser/statement_test.go
  runtime/parser/transaction.go
  runtime/sema/checker.go
  runtime/sema/gen/main.go
  runtime/sema/void_type.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Bugfix, Technical Debt, Performance

#2315 Handle cyclic imports in analyzer tool
  tools/analysis/analysis_test.go
  tools/analysis/programs.go
  tools/compatibility-check/contracts_checker.go
  tools/compatibility-check/contracts_checker_test.go
  tools/compatibility-check/go.mod
  tools/compatibility-check/go.sum
Labels: Bugfix

#2316 Bypass go-proxy to always pick the latest commit
  .github/workflows/compatibility-check-template.yml
Labels: Technical Debt

#2289 Minor clarification for release docs
  docs/releasing.md
Labels: Documentation

#2296 Improve code coverage functionality
  runtime/coverage.go
  runtime/coverage_test.go
  runtime/environment.go
Labels: Improvement

#2323 swap arguments of NewHostFunctionValue to put the fn type first
  runtime/interpreter/deployedcontract.go
  runtime/interpreter/function.go
  runtime/interpreter/function_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/string.go
  runtime/interpreter/value.go
  runtime/stdlib/account.go
  runtime/stdlib/bls.go
  runtime/stdlib/functions.go
  runtime/stdlib/hashalgorithm.go
  runtime/stdlib/publickey.go
  runtime/stdlib/rlp.go
  runtime/stdlib/test.go
  runtime/tests/interpreter/condition_test.go
  runtime/tests/interpreter/import_test.go
  runtime/tests/interpreter/interpreter_test.go
  semgrep.yaml
Labels: Improvement

#2318 Run compatibility checker for PRs
  .github/workflows/compatibility-check-template.yml
  .github/workflows/compatibility-check.yml
Labels: Chore

#2329 backport #2302 to stable cadence (fix docstring parsing after functions)
  runtime/parser/declaration.go
  runtime/parser/declaration_test.go
  runtime/parser/function.go
  runtime/parser/transaction.go
Labels: Chore

#2330 Handle backticks in docstrings when generating code, add surrounding newlines to docstrings
  runtime/sema/block.gen.go
  runtime/sema/gen/main.go
  runtime/sema/gen/testdata/docstrings.cdc
  runtime/sema/gen/testdata/docstrings.golden.go
  runtime/sema/gen/testdata/fields.golden.go
  runtime/sema/gen/testdata/functions.golden.go
Labels: Bugfix, Improvement

#2333 Sync Stable Cadence
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/workflows/compatibility-check-template.yml
  .github/workflows/compatibility-check.yml
  .github/workflows/release.yml
  CODEOWNERS
  bump-version.sh
  docs/images/release_action.png
  docs/releasing.md
  docs/tutorial/03-resources.mdx
  docs/tutorial/08-marketplace-compose.mdx
  npm-packages/cadence-parser/package.json
  runtime/coverage.go
  runtime/coverage_test.go
  runtime/environment.go
  runtime/interpreter/deployedcontract.go
  runtime/interpreter/function.go
  runtime/interpreter/function_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/string.go
  runtime/interpreter/value.go
  runtime/parser/declaration.go
  runtime/parser/declaration_test.go
  runtime/parser/expression.go
  runtime/parser/expression_test.go
  runtime/parser/function.go
  runtime/parser/statement_test.go
  runtime/parser/type.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/sema/block.gen.go
  runtime/sema/checker.go
  runtime/sema/gen/main.go
  runtime/sema/gen/testdata/docstrings.cdc
  runtime/sema/gen/testdata/docstrings.golden.go
  runtime/sema/gen/testdata/fields.golden.go
  runtime/sema/gen/testdata/functions.cdc
  runtime/sema/gen/testdata/functions.golden.go
  runtime/sema/type.go
  runtime/stdlib/account.go
  runtime/stdlib/bls.go
  runtime/stdlib/functions.go
  runtime/stdlib/hashalgorithm.go
  runtime/stdlib/publickey.go
  runtime/stdlib/rlp.go
  runtime/stdlib/test.go
  runtime/tests/interpreter/condition_test.go
  runtime/tests/interpreter/import_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  semgrep.yaml
  tools/analysis/analysis_test.go
  tools/analysis/programs.go
  tools/compatibility-check/contracts_checker.go
  tools/compatibility-check/contracts_checker_test.go
  tools/compatibility-check/go.mod
  tools/compatibility-check/go.sum
  version.go
Labels: Chore

#2332 lift getLinkTargetFunction into parent scope to cache it
  runtime/interpreter/account.go
Labels: Bugfix

#2326 Cache external Cadence type IDs
  encoding/json/encoding_test.go
  runtime/account_test.go
  runtime/convertValues_test.go
  types.go
  types_test.go
  values.go
Labels: Performance

#2336 Use pointer receivers for external types with cached typeIDs
  encoding/json/encode.go
  encoding/json/encoding_test.go
  runtime/account_test.go
  runtime/convertTypes.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/crypto_test.go
  runtime/imported_values_memory_metering_test.go
  runtime/rlp_test.go
  runtime/runtime_test.go
  runtime/storage_test.go
  types.go
  types_test.go
  values.go
  values_test.go
Labels: Improvement

#2335 Update docstrings of borrow functions to reflect current behaviour
  runtime/sema/authaccount_type.go
  runtime/sema/type.go
Labels: Documentation

#2338 Merge stable cadence feature branch into capcon feature branch
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/workflows/compatibility-check-template.yml
  .github/workflows/compatibility-check.yml
  .github/workflows/release.yml
  CODEOWNERS
  bump-version.sh
  docs/images/release_action.png
  docs/releasing.md
  docs/tutorial/03-resources.mdx
  docs/tutorial/08-marketplace-compose.mdx
  npm-packages/cadence-parser/package.json
  runtime/coverage.go
  runtime/coverage_test.go
  runtime/environment.go
  runtime/interpreter/deployedcontract.go
  runtime/interpreter/function.go
  runtime/interpreter/function_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/string.go
  runtime/interpreter/value.go
  runtime/parser/declaration.go
  runtime/parser/declaration_test.go
  runtime/parser/expression.go
  runtime/parser/expression_test.go
  runtime/parser/function.go
  runtime/parser/statement_test.go
  runtime/parser/transaction.go
  runtime/parser/type.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/sema/block.gen.go
  runtime/sema/checker.go
  runtime/sema/gen/main.go
  runtime/sema/gen/testdata/docstrings.cdc
  runtime/sema/gen/testdata/docstrings.golden.go
  runtime/sema/gen/testdata/fields.golden.go
  runtime/sema/gen/testdata/functions.cdc
  runtime/sema/gen/testdata/functions.golden.go
  runtime/sema/type.go
  runtime/stdlib/account.go
  runtime/stdlib/bls.go
  runtime/stdlib/functions.go
  runtime/stdlib/hashalgorithm.go
  runtime/stdlib/publickey.go
  runtime/stdlib/rlp.go
  runtime/stdlib/test.go
  runtime/tests/interpreter/condition_test.go
  runtime/tests/interpreter/import_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  semgrep.yaml
  tools/analysis/analysis_test.go
  tools/analysis/programs.go
  tools/compatibility-check/contracts_checker.go
  tools/compatibility-check/contracts_checker_test.go
  tools/compatibility-check/go.mod
  tools/compatibility-check/go.sum
  version.go
Labels: Chore

#2340 If extended elaboration is enabled, record all expression types
  runtime/sema/checker.go
  runtime/sema/elaboration.go
Labels: Feature

#2341 Convert reference values
  npm-packages/cadence-parser/package.json
  runtime/interpreter/interpreter.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/metatype_test.go
  version.go
Labels: Bugfix

#2342 Convert reference values
  runtime/interpreter/interpreter.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/metatype_test.go
Labels: Bugfix

#2345 Fix racy tests
  encoding/json/encoding_test.go
  runtime/convertValues_test.go
  runtime/program_params_validation_test.go
Labels: Bugfix

#2347 Add meeting notes for Jan + Feb 2023
  meetings/2023-01-10.md
  meetings/2023-02-23.md
Labels: Documentation

#2349 fixed formating of codeblocks in lists and remove outdated callout
  docs/language/accounts.mdx
  docs/language/built-in-functions.mdx
  docs/language/capability-based-access-control.md
  docs/language/contracts.mdx
  docs/language/crypto.mdx
  docs/language/environment-information.md
  docs/language/interfaces.mdx
  docs/language/values-and-types.mdx
Labels: Documentation

#2352 Merge master into feature/attachments
  .github/workflows/compatibility-check-template.yml
  .github/workflows/compatibility-check.yml
  encoding/json/encode.go
  encoding/json/encoding_test.go
  meetings/2023-01-10.md
  meetings/2023-02-23.md
  npm-packages/cadence-parser/package.json
  runtime/account_test.go
  runtime/convertTypes.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/coverage.go
  runtime/coverage_test.go
  runtime/crypto_test.go
  runtime/environment.go
  runtime/imported_values_memory_metering_test.go
  runtime/interpreter/account.go
  runtime/interpreter/deployedcontract.go
  runtime/interpreter/function.go
  runtime/interpreter/function_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/string.go
  runtime/interpreter/value.go
  runtime/program_params_validation_test.go
  runtime/rlp_test.go
  runtime/runtime_test.go
  runtime/sema/authaccount_type.go
  runtime/sema/block.gen.go
  runtime/sema/checker.go
  runtime/sema/elaboration.go
  runtime/sema/gen/main.go
  runtime/sema/gen/testdata/docstrings.cdc
  runtime/sema/gen/testdata/docstrings.golden.go
  runtime/sema/gen/testdata/fields.golden.go
  runtime/sema/gen/testdata/functions.golden.go
  runtime/sema/type.go
  runtime/stdlib/account.go
  runtime/stdlib/bls.go
  runtime/stdlib/functions.go
  runtime/stdlib/hashalgorithm.go
  runtime/stdlib/publickey.go
  runtime/stdlib/rlp.go
  runtime/stdlib/test.go
  runtime/storage_test.go
  runtime/tests/interpreter/condition_test.go
  runtime/tests/interpreter/import_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/metatype_test.go
  semgrep.yaml
  types.go
  types_test.go
  values.go
  values_test.go
  version.go
Labels: Chore

#2355 Require #allowAccountLinking pragma to allow use of account linking function
  runtime/account_test.go
  runtime/common/declarationkind.go
  runtime/runtime.go
  runtime/sema/check_pragma.go
  runtime/sema/checker.go
  runtime/sema/errors.go
  runtime/tests/checker/account_test.go
  runtime/tests/checker/declaration_test.go
  runtime/tests/checker/pragma_test.go
  runtime/tests/interpreter/capability_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Feature

#2356 Improve errors
  go.mod
  go.sum
  runtime/interpreter/errors.go
  runtime/parser/errors.go
  runtime/sema/errors.go
Labels: Improvement

#2359 [v0.31] Require #allowAccountLinking pragma to allow use of account linking function
  runtime/account_test.go
  runtime/common/declarationkind.go
  runtime/runtime.go
  runtime/sema/check_pragma.go
  runtime/sema/checker.go
  runtime/sema/errors.go
  runtime/tests/checker/account_test.go
  runtime/tests/checker/declaration_test.go
  runtime/tests/checker/pragma_test.go
  runtime/tests/interpreter/capability_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Chore
