Repository onflow/cadence, pull requests merged in 2023-09, with the labels that each got.

#2758 Add tests for invalidation of references created with index/field-access
  runtime/tests/checker/reference_test.go
  runtime/tests/interpreter/reference_test.go
Labels: Testing

#2761 update account type mappings to include identity
  runtime/sema/account.cdc
  runtime/sema/account.gen.go
  runtime/sema/gen/main.go
  runtime/sema/gen/testdata/entitlement.cdc
  runtime/sema/gen/testdata/entitlement.golden.go
Labels: Improvement

#2756 Improve and fix static types and their ID and string functions
  encoding/ccf/ccf_test.go
  encoding/ccf/decode_typedef.go
  encoding/json/encoding_test.go
  runtime/account_test.go
  runtime/common/metering.go
  runtime/common/orderedmap/orderedmap.go
  runtime/convertTypes.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/interpreter/conversion_test.go
  runtime/interpreter/decode.go
  runtime/interpreter/deepcopyremove_test.go
  runtime/interpreter/encode.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/inspect_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_test.go
  runtime/interpreter/interpreter_tracing_test.go
  runtime/interpreter/statictype.go
  runtime/interpreter/statictype_test.go
  runtime/interpreter/storage.go
  runtime/interpreter/storage_test.go
  runtime/interpreter/value.go
  runtime/interpreter/value_accountcapabilitycontroller.go
  runtime/interpreter/value_storagecapabilitycontroller.go
  runtime/interpreter/value_test.go
  runtime/runtime_test.go
  runtime/sema/access.go
  runtime/sema/access_test.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_member_expression.go
  runtime/sema/errors.go
  runtime/sema/type.go
  runtime/sema/type_test.go
  runtime/stdlib/account.go
  runtime/stdlib/block.go
  runtime/stdlib/test_test.go
  runtime/storage_test.go
  runtime/tests/checker/account_test.go
  runtime/tests/checker/capability_test.go
  runtime/tests/checker/entitlements_test.go
  runtime/tests/checker/reference_test.go
  runtime/tests/interpreter/builtinfunctions_test.go
  runtime/tests/interpreter/character_test.go
  runtime/tests/interpreter/container_mutation_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/enum_test.go
  runtime/tests/interpreter/for_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/metatype_test.go
  runtime/tests/interpreter/reference_test.go
  runtime/tests/interpreter/runtimetype_test.go
  runtime/tests/interpreter/string_test.go
  runtime/tests/interpreter/values_test.go
  types.go
  types_test.go
  values.go
Labels: Improvement, Testing, Technical Debt

#2753 Allow use of type code generator in any package, refactor RLP and BLS contracts
  runtime/sema/account.gen.go
  runtime/sema/crypto_algorithm_types.go
  runtime/sema/gen/main.go
  runtime/sema/gen/main_test.go
  runtime/sema/gen/testdata/fields.cdc
  runtime/sema/gen/testdata/fields.golden.go
  runtime/sema/gen/testdata/nested.golden.go
  runtime/sema/type.go
  runtime/stdlib/bls.cdc
  runtime/stdlib/bls.gen.go
  runtime/stdlib/bls.go
  runtime/stdlib/builtin.go
  runtime/stdlib/flow.go
  runtime/stdlib/publickey.go
  runtime/stdlib/rlp.cdc
  runtime/stdlib/rlp.gen.go
  runtime/stdlib/rlp.go
Labels: Feature, Improvement

#2763 Add functions on testing framework's blockchain to create/load snapshots
  runtime/stdlib/contracts/test.cdc
  runtime/stdlib/test-framework.go
  runtime/stdlib/test_emulatorbackend.go
  runtime/stdlib/test_test.go
Labels: Feature

#2765 Add entitlement CopyValue and require it for Account.Storage.copyValue
  encoding/ccf/ccf_test.go
  encoding/ccf/simpletype.go
  encoding/ccf/simpletype_string.go
  runtime/convertTypes.go
  runtime/interpreter/primitivestatictype.go
  runtime/interpreter/primitivestatictype_string.go
  runtime/interpreter/statictype_test.go
  runtime/sema/account.cdc
  runtime/sema/account.gen.go
  runtime/tests/checker/account_test.go
  types.go
Labels: Improvement

#2764 Better error messages for use of old restricted types
  runtime/parser/type.go
  runtime/parser/type_test.go
Labels: Improvement

#2767 Suggested fixes for `pub` and `priv` parser errors
  runtime/ast/ast.go
  runtime/errors/errors.go
  runtime/parser/declaration.go
  runtime/parser/declaration_test.go
  runtime/parser/errors.go
  runtime/parser/parser.go
  runtime/sema/errors.go
  runtime/tests/utils/utils.go
  tools/analysis/diagnostic.go
Labels: Improvement

#2770 Merge `master` into Stable Cadence
  runtime/context.go
  runtime/contract_function_executor.go
  runtime/environment.go
  runtime/errors.go
  runtime/runtime.go
  runtime/script_executor.go
  runtime/stdlib/contracts/test.cdc
  runtime/stdlib/test-framework.go
  runtime/stdlib/test_emulatorbackend.go
  runtime/stdlib/test_test.go
  runtime/transaction_executor.go
Labels: Chore

#2772 Improve capability API
  runtime/sema/account.cdc
  runtime/sema/account.gen.go
  runtime/sema/account_capability_controller.cdc
  runtime/sema/storage_capability_controller.cdc
  runtime/sema/type.go
Labels: Improvement

#2771 Add view annotations to newly added array functions
  runtime/sema/type.go
  runtime/tests/checker/arrays_dictionaries_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Language Breaking Change, Feature

#2774 Fix doc (pretty printing) for function declaration without function block
  runtime/ast/expression.go
  runtime/ast/expression_test.go
  runtime/ast/function_declaration_test.go
  runtime/ast/transaction_declaration_test.go
Labels: Bugfix

#2769 Add `tryUpdate` method to `Account.Contracts`
  runtime/contract_test.go
  runtime/convertValues_test.go
  runtime/interpreter/value_account_contracts.go
  runtime/interpreter/value_deployment_result.go
  runtime/sema/account.cdc
  runtime/sema/account.gen.go
  runtime/sema/deployment_result.cdc
  runtime/sema/deployment_result.gen.go
  runtime/sema/deployment_result.go
  runtime/sema/gen/main.go
  runtime/sema/gen/testdata/composite-type-pragma.cdc
  runtime/sema/gen/testdata/composite-type-pragma.golden.go
  runtime/sema/type.go
  runtime/stdlib/account.go
  runtime/tests/checker/account_test.go
  runtime/tests/checker/type_inference_test.go
Labels: Feature

#2775 Replace `simpleTypeIDByType` with a bimap
  encoding/ccf/simpletype.go
  runtime/common/bimap/bimap.go
  runtime/common/bimap/bimap_test.go
Labels: Improvement

#2779 Use bimaps in the elaboration
  runtime/sema/check_interface_declaration.go
  runtime/sema/elaboration.go
Labels: Improvement

#2780 Add notes for 2023-09-12 meeting
  meetings/2023-09-12.md
Labels: Documentation

#2781 Eagerly normalize String and Character values at construction time
  runtime/interpreter/decode.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Improvement, Storage Breaking Change

#2778 Add an exists function, allows checking if capability exists/is published
  runtime/capabilities_test.go
  runtime/capabilitycontrollers_test.go
  runtime/interpreter/value_account_capabilities.go
  runtime/sema/account.cdc
  runtime/sema/account.gen.go
  runtime/stdlib/account.go
Labels: Feature

#2762 Introduce `String.join` function
  runtime/interpreter/value.go
  runtime/interpreter/value_string.go
  runtime/sema/string_type.go
  runtime/tests/checker/string_test.go
  runtime/tests/interpreter/string_test.go
Labels: Feature

#2793 Port internal #143
  runtime/interpreter/simplecompositevalue.go
  runtime/interpreter/value.go
  runtime/program_params_validation_test.go
  runtime/runtime_test.go
  runtime/tests/interpreter/values_test.go
Labels: Bugfix

#2796 Sync Stable Cadence
  .github/release.yml
  meetings/2023-09-12.md
  npm-packages/cadence-parser/package.json
  runtime/ast/expression.go
  runtime/ast/expression_test.go
  runtime/ast/function_declaration_test.go
  runtime/ast/transaction_declaration_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/simplecompositevalue.go
  runtime/interpreter/value.go
  runtime/interpreter/value_string.go
  runtime/program_params_validation_test.go
  runtime/runtime_test.go
  runtime/sema/string_type.go
  runtime/tests/checker/string_test.go
  runtime/tests/interpreter/string_test.go
  runtime/tests/interpreter/values_test.go
  version.go
Labels: Chore

#2797 Assign issues to group
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/feature-request.yaml
Labels: Chore

#2798 Properly check removed expression for resource loss
  runtime/sema/check_remove_statement.go
  runtime/tests/checker/attachments_test.go
Labels: Bugfix

#2802 Fix Test framework's TestAccount's type name
  npm-packages/cadence-parser/package.json
  runtime/stdlib/test.go
  runtime/stdlib/test_test.go
  version.go
Labels: Bugfix

#2800 Refactor runtime test helpers into separate, reusable package
  runtime/account_test.go
  runtime/attachments_test.go
  runtime/capabilities_test.go
  runtime/capabilitycontrollers_test.go
  runtime/contract_test.go
  runtime/contract_update_test.go
  runtime/contract_update_validation_test.go
  runtime/convertTypes_test.go
  runtime/convertValues_test.go
  runtime/coverage_test.go
  runtime/crypto_test.go
  runtime/debugger_test.go
  runtime/deployedcontract_test.go
  runtime/deployment_test.go
  runtime/entitlements_test.go
  runtime/environment.go
  runtime/error_test.go
  runtime/ft_test.go
  runtime/import_test.go
  runtime/imported_values_memory_metering_test.go
  runtime/inbox_test.go
  runtime/literal_test.go
  runtime/nft_test.go
  runtime/predeclaredvalues_test.go
  runtime/program_params_validation_test.go
  runtime/resource_duplicate_test.go
  runtime/resourcedictionary_test.go
  runtime/rlp_test.go
  runtime/runtime.go
  runtime/runtime_memory_metering_test.go
  runtime/runtime_test.go
  runtime/sharedstate_test.go
  runtime/storage.go
  runtime/storage_test.go
  runtime/tests/runtime_utils/interpreter.go
  runtime/tests/runtime_utils/location.go
  runtime/tests/runtime_utils/testinterface.go
  runtime/tests/runtime_utils/testledger.go
  runtime/tests/runtime_utils/testruntime.go
  runtime/type_test.go
  runtime/validation_test.go
Labels: Improvement

#2788 Fix capability controller deletion
  runtime/capabilitycontrollers_test.go
  runtime/interpreter/value_accountcapabilitycontroller.go
  runtime/interpreter/value_storagecapabilitycontroller.go
  runtime/stdlib/account.go
Labels: Bugfix

#2805 Add helpers to get constructor and initializer function type for composite type
  runtime/interpreter/interpreter.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/type.go
Labels: Improvement

#2804 Remove unused composite type to interface type conversion function
  runtime/sema/type.go
Labels: Technical Debt

#2810 meter and deduplicate included entitlement relations
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/entitlements_test.go
  runtime/sema/check_interface_declaration.go
  runtime/sema/type.go
Labels: Bugfix

#2808 Replace panic with nil return in `newInjectedCompositeFieldsHandler`
  runtime/environment.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Improvement

#2791 Introduce `String.split` function
  runtime/interpreter/value.go
  runtime/sema/string_type.go
  runtime/tests/checker/string_test.go
  runtime/tests/interpreter/string_test.go
Labels: Feature

#2811 Add support for injecting types into the environment
  runtime/environment.go
  runtime/interpreter/interpreter.go
  runtime/predeclaredvalues_test.go
  runtime/sema/type.go
Labels: Feature, Go API Breaking Change

#2819 Use kr/pretty instead of go-test/deep to prevent empty diffs, remove gocap
  .github/workflows/ci.yml
  Makefile
  go.cap
  go.mod
  go.sum
  runtime/tests/checker/utils.go
  runtime/tests/utils/utils.go
  tools/compare-parsing/main.go
Labels: Bugfix, Testing

#2820 Sync Stable Cadence
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/feature-request.yaml
  .github/workflows/ci.yml
  Makefile
  go.cap
  go.mod
  go.sum
  runtime/capabilitycontrollers_test.go
  runtime/environment.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value_accountcapabilitycontroller.go
  runtime/interpreter/value_storagecapabilitycontroller.go
  runtime/predeclaredvalues_test.go
  runtime/sema/check_remove_statement.go
  runtime/sema/type.go
  runtime/stdlib/account.go
  runtime/tests/checker/attachments_test.go
  runtime/tests/checker/utils.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/utils/utils.go
  tools/compare-parsing/main.go
Labels: Chore

#2783 Refine API of the testing framework
  runtime/sema/type.go
  runtime/stdlib/contracts/test.cdc
  runtime/stdlib/test-framework.go
  runtime/stdlib/test.go
  runtime/stdlib/test_contract.go
  runtime/stdlib/test_emulatorbackend.go
  runtime/stdlib/test_test.go
Labels: Improvement, Technical Debt

#2821 Check native function declarations
  runtime/sema/check_function.go
  runtime/sema/errors.go
  runtime/tests/checker/function_test.go
Labels: Feature

#2825 properly access-check optional chaining with entitlements
  runtime/sema/check_member_expression.go
  runtime/tests/checker/entitlements_test.go
Labels: Bugfix
