Repository onflow/cadence, pull requests merged in 2023-03, with the labels that each got.

#2357 Add defensive check for adding and removing attachments
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_statement.go
  runtime/tests/interpreter/attachments_test.go
Labels: Improvement

#2358 Attachments Feature Flag
  runtime/attachments_test.go
  runtime/config.go
  runtime/environment.go
  runtime/sema/check_attach_expression.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_expression.go
  runtime/sema/check_remove_statement.go
  runtime/sema/config.go
  runtime/sema/errors.go
  runtime/tests/checker/access_test.go
  runtime/tests/checker/attachments_test.go
  runtime/tests/checker/storable_test.go
  runtime/tests/checker/utils.go
  runtime/tests/interpreter/attachments_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Improvement

#2366 Enforce account links to be private
  docs/language/accounts.mdx
  runtime/account_test.go
  runtime/sema/authaccount_type.go
  runtime/tests/checker/account_test.go
  runtime/tests/interpreter/capability_test.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Improvement

#2368 Emit an event when an account is linked
  docs/language/run-time-types.md
  runtime/account_test.go
  runtime/environment.go
  runtime/interpreter/config.go
  runtime/interpreter/interpreter.go
  runtime/sema/authaccount_type.go
  runtime/stdlib/flow.go
  runtime/value.go
  types.go
Labels: Improvement

#2369 [v0.31] Enforce account links to be private
  docs/language/accounts.mdx
  runtime/account_test.go
  runtime/sema/authaccount_type.go
  runtime/tests/checker/account_test.go
  runtime/tests/interpreter/capability_test.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Improvement

#2370 [v0.31] Emit an event when an account is linked
  docs/language/run-time-types.md
  runtime/account_test.go
  runtime/environment.go
  runtime/interpreter/config.go
  runtime/interpreter/interpreter.go
  runtime/sema/authaccount_type.go
  runtime/stdlib/flow.go
  runtime/value.go
  types.go
Labels: Improvement

#2371 Code coverage support for pre/post conditions inside functions
  runtime/coverage.go
  runtime/coverage_test.go
Labels: Bugfix

#2339 Add metering for encoded values
  go.mod
  go.sum
  runtime/common/computationkind.go
  runtime/common/computationkind_string.go
  runtime/runtime_memory_metering_test.go
  runtime/runtime_test.go
  runtime/storage.go
Labels: Improvement

#2373 Add position information to rewritten post condition before statement
  runtime/sema/checker.go
  runtime/tests/checker/conditions_test.go
Labels: Bugfix

#2375 Document how to create a GitHub release
  docs/images/create_release.png
  docs/images/release_action.png
  docs/images/release_tag.png
  docs/releasing.md
Labels: Documentation

#2378 test: simplify TestCrashers
  runtime/tests/fuzz/crashers_test.go
Labels: Improvement

#2376 Update golangci-lint to latest release, which allows use of Go 1.20
  .github/workflows/benchmark.yml
  .github/workflows/ci.yml
  Makefile
  runtime/parser/comment.go
  tools/constructorcheck/Makefile
  tools/constructorcheck/go.mod
  tools/constructorcheck/go.sum
  tools/golangci-lint/Makefile
  tools/golangci-lint/go.mod
  tools/golangci-lint/go.sum
  tools/maprange/Makefile
  tools/maprange/go.mod
  tools/maprange/go.sum
  tools/unkeyed/Makefile
  tools/unkeyed/go.mod
  tools/unkeyed/go.sum
Labels: Chore

#2380 Change account linking pragma to run-time configuration of execution
  runtime/account_test.go
  runtime/interpreter/config.go
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/runtime.go
  runtime/script_executor.go
  runtime/sema/checker.go
  runtime/tests/checker/account_test.go
  runtime/tests/checker/pragma_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/pragma_test.go
  runtime/transaction_executor.go
Labels: Improvement

#2381 Revert "Remove support for importing/exporting and JSON encoding/deco…
  encoding/json/decode.go
  encoding/json/encode.go
  encoding/json/encoding_test.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  values.go
  values_test.go
Labels: Bugfix

#2383 [v0.31] Change account linking pragma to run-time configuration of execution
  runtime/account_test.go
  runtime/interpreter/config.go
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/script_executor.go
  runtime/sema/checker.go
  runtime/tests/checker/account_test.go
  runtime/tests/checker/pragma_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/pragma_test.go
  runtime/transaction_executor.go
Labels: Improvement

#2382 Use AddressLocation in Interface
  runtime/account_test.go
  runtime/attachments_test.go
  runtime/contract_test.go
  runtime/contract_update_test.go
  runtime/contract_update_validation_test.go
  runtime/deployedcontract_test.go
  runtime/deployment_test.go
  runtime/environment.go
  runtime/error_test.go
  runtime/ft_test.go
  runtime/interface.go
  runtime/missingmember_test.go
  runtime/predeclaredvalues_test.go
  runtime/program_params_validation_test.go
  runtime/resource_duplicate_test.go
  runtime/resourcedictionary_test.go
  runtime/runtime_memory_metering_test.go
  runtime/runtime_test.go
  runtime/sharedstate_test.go
  runtime/stdlib/account.go
  runtime/storage.go
  runtime/storage_test.go
  runtime/validation_test.go
Labels: Breaking Change, Improvement

#2384 Fix broken account tests
  runtime/account_test.go
Labels: Bug, Testing

#2372 Improve contract address for code coverage report
  runtime/common/addresslocation.go
  runtime/common/addresslocation_test.go
  runtime/common/identifierlocation.go
  runtime/common/identifierlocation_test.go
  runtime/common/location.go
  runtime/common/repllocation.go
  runtime/common/repllocation_test.go
  runtime/common/scriptlocation.go
  runtime/common/scriptlocation_test.go
  runtime/common/stringlocation.go
  runtime/common/stringlocation_test.go
  runtime/common/transactionlocation.go
  runtime/common/transactionlocation_test.go
  runtime/coverage.go
  runtime/coverage_test.go
  runtime/stdlib/flow.go
  runtime/stdlib/flow_test.go
Labels: Bugfix

#2386 Add a Reset method on CoverageReport type
  runtime/coverage.go
  runtime/coverage_test.go
Labels: Feature

#2395 Fix and run interpreter smoke tests on CI
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Makefile
  runtime/interpreter/storage.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/values_test.go
Labels: Bugfix, Chore

#2388 Fix Value.Type() returning Type referencing nil ptr for eight external values
  runtime/format/capability.go
  values.go
  values_test.go
Labels: Bug, Improvement

#2399 Revised and extended documentation of `unsafeRandom`
  docs/language/built-in-functions.mdx
Labels: Documentation

#2396 Allow empty qualified identifier when decoding type IDs
  encoding/json/encoding_test.go
  runtime/common/addresslocation.go
  runtime/common/addresslocation_test.go
  runtime/common/identifierlocation.go
  runtime/common/identifierlocation_test.go
  runtime/common/repllocation.go
  runtime/common/repllocation_test.go
  runtime/common/scriptlocation_test.go
  runtime/common/stringlocation.go
  runtime/common/stringlocation_test.go
  runtime/common/transactionlocation_test.go
  runtime/stdlib/flow.go
  runtime/stdlib/flow_test.go
Labels: Improvement

#2400 Generate labels and identifiers for function parameters in Go code generator
  runtime/sema/gen/main.go
  runtime/sema/gen/testdata/docstrings.golden.go
  runtime/sema/gen/testdata/functions.golden.go
Labels: Bugfix

#2391 Improvements to `CoverageReport` public API
  runtime/coverage.go
  runtime/coverage_test.go
  runtime/environment.go
Labels: Feature

#2408 [v0.31] Check cyclic storage references during export
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/interpreter/value.go
Labels: Bugfix

#2409 [master] Check cyclic storage references during export
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/interpreter/value.go
Labels: Bugfix

#2401 Improve external types and JSON codec
  encoding/json/decode.go
  encoding/json/encode.go
  encoding/json/encoding_test.go
  runtime/ast/expression.go
  runtime/cmd/minifier/minifier.go
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/convertTypes.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/interpreter/value_test.go
  runtime/runtime_test.go
  runtime/sema/resources.go
  runtime/sema/type.go
  runtime/tests/checker/fixedpoint_test.go
  types.go
  types_test.go
  values.go
  values_test.go
Labels: Improvement
