Repository onflow/cadence, pull requests merged in 2023-04, with the labels that each got.

#2416 Introduce a `CoverageReport` field on `runtime.Config` type
  runtime/config.go
  runtime/coverage_test.go
  runtime/environment.go
Labels: Breaking Change, Improvement

#2407 Update dependencies
  go.mod
  go.sum
  runtime/cmd/execute/colors.go
  runtime/cmd/json-cdc/main.go
  runtime/pretty/print.go
  vm/vm.go
Labels: Chore

#2417 Add support for generating code of nested types
  runtime/sema/authaccount_contracts.go
  runtime/sema/authaccount_type.go
  runtime/sema/block.gen.go
  runtime/sema/crypto_algorithm_types.go
  runtime/sema/gen/main.go
  runtime/sema/gen/testdata/docstrings.golden.go
  runtime/sema/gen/testdata/fields.golden.go
  runtime/sema/gen/testdata/functions.golden.go
  runtime/sema/gen/testdata/nested.cdc
  runtime/sema/gen/testdata/nested.golden.go
  runtime/sema/public_account_contracts.go
  runtime/sema/publicaccount_type.go
  runtime/sema/type.go
  runtime/stdlib/bls.go
  runtime/stdlib/crypto.go
  runtime/stdlib/rlp.go
  runtime/stdlib/test.go
Labels: Improvement

#2418 Refactor AuthAccount and PublicAccount types to Cadence
  docs/language/accounts.mdx
  runtime/contract_update_validation_test.go
  runtime/interpreter/account.go
  runtime/interpreter/accountcontracts.go
  runtime/interpreter/accountinbox.go
  runtime/interpreter/accountkeys.go
  runtime/interpreter/interpreter.go
  runtime/sema/account_contracts.go
  runtime/sema/authaccount.cdc
  runtime/sema/authaccount.gen.go
  runtime/sema/authaccount.go
  runtime/sema/authaccount_contracts.go
  runtime/sema/authaccount_type.go
  runtime/sema/public_account_contracts.go
  runtime/sema/publicaccount.cdc
  runtime/sema/publicaccount.cdc.go
  runtime/sema/publicaccount.gen.go
  runtime/sema/publicaccount_type.go
  runtime/stdlib/account.go
  runtime/stdlib/flow.go
Labels: Improvement

#2426 Update handling of user errors returned by atree
  go.mod
  go.sum
  runtime/interpreter/storagemap.go
  runtime/interpreter/value.go
Labels: Improvement

#2406 Remove parameter name from API documentation when argument label is given
  docs/language/accounts.mdx
  docs/language/environment-information.md
  docs/language/run-time-types.md
  docs/language/values-and-types.mdx
Labels: Documentation

#2413 Add capability controller types and values
  runtime/common/metering.go
  runtime/format/capability.go
  runtime/interpreter/primitivestatictype.go
  runtime/interpreter/primitivestatictype_string.go
  runtime/interpreter/statictype_test.go
  runtime/interpreter/value_accountcapabilitycontroller.go
  runtime/interpreter/value_accountcapabilitycontroller_test.go
  runtime/interpreter/value_storagecapabilitycontroller.go
  runtime/interpreter/value_storagecapabilitycontroller_test.go
  runtime/sema/account_capability_controller.cdc
  runtime/sema/account_capability_controller.gen.go
  runtime/sema/account_capability_controller.go
  runtime/sema/storage_capability_controller.cdc
  runtime/sema/storage_capability_controller.gen.go
  runtime/sema/storage_capability_controller.go
  runtime/sema/type.go
  runtime/sema/type_tags.go
  runtime/tests/checker/capability_controller_test.go
Labels: Feature

#2427 Improve cadence.Path
  encoding/json/decode.go
  encoding/json/encode.go
  encoding/json/encoding_test.go
  runtime/account_test.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/deployment_test.go
  runtime/imported_values_memory_metering_test.go
  runtime/literal.go
  runtime/literal_test.go
  runtime/runtime_test.go
  runtime/storage_test.go
  values.go
  values_test.go
Labels: Bugfix, Improvement, Go API Breaking Chance

#2422 Add Auth/PublicAccount.Storage/AccountCapabilities
  docs/language/accounts.mdx
  runtime/common/metering.go
  runtime/interpreter/primitivestatictype.go
  runtime/interpreter/primitivestatictype_string.go
  runtime/interpreter/statictype_test.go
  runtime/interpreter/value.go
  runtime/interpreter/value_account.go
  runtime/interpreter/value_account_accountcapabilities.go
  runtime/interpreter/value_account_contracts.go
  runtime/interpreter/value_account_storagecapabilities.go
  runtime/interpreter/value_accountkey.go
  runtime/interpreter/value_authaccount_inbox.go
  runtime/interpreter/value_authaccount_keys.go
  runtime/interpreter/value_block.go
  runtime/interpreter/value_deployedcontract.go
  runtime/interpreter/value_function.go
  runtime/interpreter/value_function_test.go
  runtime/interpreter/value_string.go
  runtime/sema/account_capability_controller.gen.go
  runtime/sema/authaccount.cdc
  runtime/sema/authaccount.gen.go
  runtime/sema/publicaccount.cdc
  runtime/sema/publicaccount.gen.go
  runtime/sema/storage_capability_controller.gen.go
  runtime/stdlib/account.go
  runtime/tests/checker/account_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Feature

#2424 Add ID field to Capability type and value
  encoding/json/decode.go
  encoding/json/encode.go
  encoding/json/encoding_test.go
  runtime/common/metering.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/format/capability.go
  runtime/interpreter/decode.go
  runtime/interpreter/encode.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/runtime_test.go
  runtime/sema/type.go
  runtime/storage_test.go
  runtime/tests/checker/capability_test.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/equality_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/values_test.go
  values.go
  values_test.go
Labels: Feature, Storage Breaking Change

#2420 Add more built-in matchers to the Cadence Testing Framework
  runtime/stdlib/contracts/test.cdc
  runtime/stdlib/test.go
  runtime/stdlib/test_test.go
Labels: Improvement

#2435 Fix release notes configuration
  .github/release.yml
Labels: Chore

#2434 Add basic support for multiline input to REPL
  runtime/parser/parser.go
  runtime/repl.go
Labels: Feature

#2436 [v0.31] Check for potential resource loss in reference expression
  runtime/sema/check_reference_expression.go
  runtime/tests/checker/reference_test.go
  runtime/tests/checker/resources_test.go
  runtime/tests/interpreter/resources_test.go
Labels: Bugfix

#2437 Check for potential resource loss in reference expression
  runtime/sema/check_reference_expression.go
  runtime/tests/checker/reference_test.go
  runtime/tests/checker/resources_test.go
  runtime/tests/interpreter/resources_test.go
Labels: Bugfix

#2438 [v0.38] Check for potential resource loss in reference expression
  runtime/sema/check_reference_expression.go
  runtime/tests/checker/reference_test.go
  runtime/tests/checker/resources_test.go
  runtime/tests/interpreter/resources_test.go
Labels: Bugfix

#2439 Update crypto doc
  docs/language/crypto.mdx
Labels: Documentation

#2364 Add CCF codec implementing CCF Specification (RC1)
  encoding/ccf/bench_test.go
  encoding/ccf/ccf.go
  encoding/ccf/ccf_test.go
  encoding/ccf/ccf_type_id.go
  encoding/ccf/ccf_type_id_test.go
  encoding/ccf/consts.go
  encoding/ccf/decode.go
  encoding/ccf/decode_type.go
  encoding/ccf/decode_typedef.go
  encoding/ccf/encode.go
  encoding/ccf/encode_type.go
  encoding/ccf/encode_typedef.go
  encoding/ccf/simple_type_utils.go
  encoding/ccf/sort.go
  encoding/ccf/traverse_value.go
  go.mod
  go.sum
  types.go
  types_test.go
  values.go
Labels: Feature, E&V Team

#2444 Fix built-in `result` variable for optional resource typed returns
  runtime/interpreter/interpreter.go
  runtime/sema/check_function.go
  runtime/tests/checker/function_test.go
  runtime/tests/interpreter/function_test.go
Labels: Bugfix

#2453 Add validation for exporting references to destroyed resources
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/interpreter/value.go
Labels: Bugfix

#2447 Add reference tracking for the result variable
  runtime/attachments_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/value.go
  runtime/stdlib/account.go
  runtime/tests/interpreter/attachments_test.go
  runtime/tests/interpreter/function_test.go
Labels: Improvement, Technical Debt

#2451 Various improvements
  runtime/attachments_test.go
  runtime/inbox_test.go
  runtime/interpreter/interpreter.go
  runtime/sema/type.go
  runtime/sema/type_tags.go
  runtime/sema/type_test.go
  runtime/stdlib/account.go
Labels: Improvement

#2456 Improve documentation sidebar
  docs/flow-docs.json
Labels: Documentation

#2442 Add history support to REPL
  runtime/cmd/execute/repl.go
Labels: Feature

#2450 Refactor console REPL into type, add type command and command completion
  runtime/cmd/execute/colors.go
  runtime/cmd/execute/debugger.go
  runtime/cmd/execute/repl.go
  runtime/cmd/main/main.go
  runtime/parser/parser.go
  runtime/repl.go
Labels: Improvement

#2465 Fix and test sema to static type conversion
  runtime/interpreter/primitivestatictype.go
  runtime/interpreter/statictype.go
  runtime/interpreter/statictype_test.go
  runtime/runtime_test.go
Labels: Bugfix, Testing, Technical Debt

#2467 Fix race conditions in CCF tests caused by shared usage of types
  encoding/ccf/ccf_test.go
Labels: Bugfix, Testing

#2469 Properly wrap nil in optionals depending on the nested optional type
  runtime/literal.go
  runtime/literal_test.go
Labels: Bugfix

#2452 Add Address.fromBytes to create Address from [UInt8]
  docs/language/values-and-types.mdx
  runtime/common/address.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/sema/type.go
  runtime/tests/checker/builtinfunctions_test.go
  runtime/tests/interpreter/builtinfunctions_test.go
Labels: Feature

#2470 Extend ordering comparison (<, <=, >, >=) to String
  docs/language/operators.md
  runtime/interpreter/value.go
  runtime/sema/string_type.go
  runtime/tests/checker/operations_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Feature
