Repository onflow/cadence, pull requests merged in 2024-01, with the labels that each got.

#2991 Port `tryUpdate` to v0.42
  runtime/contract_test.go
  runtime/convertValues_test.go
  runtime/interpreter/value_account_contracts.go
  runtime/interpreter/value_deployment_result.go
  runtime/sema/authaccount.cdc
  runtime/sema/authaccount.gen.go
  runtime/sema/deployment_result.cdc
  runtime/sema/deployment_result.gen.go
  runtime/sema/deployment_result.go
  runtime/sema/gen/main.go
  runtime/sema/type.go
  runtime/stdlib/account.go
  runtime/tests/checker/account_test.go
  runtime/tests/checker/type_inference_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Feature

#2993 Extend pragma expressions
  runtime/sema/check_pragma.go
  runtime/tests/checker/pragma_test.go
Labels: Improvement

#2996 Statically prevent referenced-typed subexpressions in default arguments to destroy events
  runtime/sema/check_composite_declaration.go
  runtime/sema/errors.go
  runtime/tests/checker/events_test.go
  runtime/tests/interpreter/resources_test.go
Labels: Bugfix

#3002 Add getter for field count to composite value
  runtime/interpreter/value.go
Labels: Feature

#3003 [v0.42] Port #3002
  runtime/interpreter/value.go
Labels: Feature

#3001 Improve error handling in migrations
  migrations/account_type/migration.go
  migrations/account_type/migration_test.go
  migrations/capcons/capabilitymigration.go
  migrations/capcons/linkmigration.go
  migrations/capcons/migration_test.go
  migrations/migration.go
  migrations/migration_reporter.go
  migrations/migration_test.go
  migrations/string_normalization/migration.go
  migrations/string_normalization/migration_test.go
  migrations/type_value/migration.go
  migrations/type_value/migration_test.go
Labels: Improvement

#2999 Prevent use of `base` variable in default destroy event arguments outside attachments
  runtime/sema/check_composite_declaration.go
  runtime/tests/checker/events_test.go
  runtime/tests/interpreter/resources_test.go
Labels: Bugfix

#3000 Prevent use of non-attachment type names in default arguments
  runtime/sema/check_composite_declaration.go
  runtime/tests/checker/events_test.go
  runtime/tests/interpreter/resources_test.go
Labels: Bugfix

#3004 Improve type inference
  runtime/sema/check_invocation_expression.go
  runtime/sema/checker.go
  runtime/sema/simple_type.go
  runtime/sema/type.go
  runtime/stdlib/test_test.go
  runtime/tests/checker/account_test.go
  runtime/tests/checker/builtinfunctions_test.go
  runtime/tests/checker/genericfunction_test.go
  runtime/tests/checker/range_value_test.go
  runtime/tests/checker/type_inference_test.go
Labels: Improvement

#2982 Introduce dereference operator for references
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/value.go
  runtime/parser/expression.go
  runtime/parser/expression_test.go
  runtime/sema/check_unary_expression.go
  runtime/sema/errors.go
  runtime/sema/type.go
  runtime/tests/checker/reference_test.go
  runtime/tests/interpreter/reference_test.go
Labels: Feature

#3008 Add support for dereferencing optional references
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/value.go
  runtime/sema/check_unary_expression.go
  runtime/tests/checker/reference_test.go
  runtime/tests/interpreter/reference_test.go
Labels: Feature

#3009 Merge range type feature
  encoding/ccf/ccf_test.go
  encoding/ccf/consts.go
  encoding/ccf/decode.go
  encoding/ccf/decode_type.go
  encoding/ccf/encode.go
  encoding/ccf/encode_type.go
  encoding/ccf/traverse_value.go
  encoding/json/decode.go
  encoding/json/encode.go
  encoding/json/encoding_test.go
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/convertTypes.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/imported_values_memory_metering_test.go
  runtime/interpreter/decode.go
  runtime/interpreter/encode.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/errors.go
  runtime/interpreter/integer.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/statictype.go
  runtime/interpreter/statictype_test.go
  runtime/interpreter/storage_test.go
  runtime/interpreter/value.go
  runtime/interpreter/value_range.go
  runtime/program_params_validation_test.go
  runtime/runtime_test.go
  runtime/sema/check_for.go
  runtime/sema/check_invocation_expression.go
  runtime/sema/checker.go
  runtime/sema/errors.go
  runtime/sema/runtime_type_constructors.go
  runtime/sema/simple_type.go
  runtime/sema/type.go
  runtime/sema/type_tags.go
  runtime/stdlib/builtin.go
  runtime/stdlib/range.go
  runtime/stdlib/test_test.go
  runtime/tests/checker/account_test.go
  runtime/tests/checker/builtinfunctions_test.go
  runtime/tests/checker/for_test.go
  runtime/tests/checker/genericfunction_test.go
  runtime/tests/checker/operations_test.go
  runtime/tests/checker/range_value_test.go
  runtime/tests/checker/runtimetype_test.go
  runtime/tests/checker/storable_test.go
  runtime/tests/checker/type_inference_test.go
  runtime/tests/checker/typeargument_test.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/for_test.go
  runtime/tests/interpreter/interface_test.go
  runtime/tests/interpreter/range_value_test.go
  runtime/tests/interpreter/runtimetype_test.go
  types.go
  values.go
  values_test.go
Labels: Feature

#3014 Add type assertion on values passed to `Test.assertEqual`
  runtime/stdlib/test_contract.go
  runtime/stdlib/test_test.go
Labels: Improvement

#3017 Improve code related to new InclusiveRange type
  encoding/ccf/ccf_test.go
  encoding/ccf/decode_type.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/interpreter/encoding_test.go
  runtime/sema/check_invocation_expression.go
  runtime/sema/type.go
  runtime/stdlib/range.go
  runtime/tests/checker/for_test.go
Labels: Improvement

#3010 Defensively check the dereferenced value is not a resource
  runtime/interpreter/errors.go
  runtime/interpreter/value.go
  runtime/tests/interpreter/reference_test.go
Labels: Improvement

#3016 Introduce `toVariableSized` to ConstantSizedArray type
  runtime/interpreter/value.go
  runtime/sema/type.go
  runtime/tests/checker/arrays_dictionaries_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Feature

#2986 Implement modulo argument of `revertibleRandom`
  go.mod
  go.sum
  runtime/runtime_test.go
  runtime/sema/type.go
  runtime/stdlib/random.go
  runtime/stdlib/random_test.go
Labels: Language Breaking Change, Feature

#3018 Allow issuing capability controllers using type values
  runtime/capabilitycontrollers_test.go
  runtime/interpreter/errors.go
  runtime/interpreter/value_account_accountcapabilities.go
  runtime/interpreter/value_account_storagecapabilities.go
  runtime/sema/account.cdc
  runtime/sema/account.gen.go
  runtime/stdlib/account.go
Labels: Feature

#2951 Entitlements Migration
  migrations/entitlements/migration.go
  migrations/entitlements/migration_test.go
  migrations/migration.go
Labels: Feature

#3026 Fix the entitlements migration
  encoding/ccf/simpletype_test.go
  encoding/json/decode.go
  encoding/json/encoding_test.go
  migrations/capcons/migration_test.go
  migrations/entitlements/migration.go
  migrations/entitlements/migration_test.go
  runtime/interpreter/primitivestatictype.go
  runtime/interpreter/primitivestatictype_test.go
  runtime/interpreter/statictype.go
  runtime/interpreter/statictype_test.go
  runtime/tests/checker/member_test.go
  runtime/tests/interpreter/member_test.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Bugfix, Improvement

#3019 Reserve more keywords for future proofing
  runtime/parser/declaration.go
  runtime/parser/expression.go
  runtime/parser/keyword.go
  runtime/parser/parser.go
  runtime/parser/statement.go
  runtime/parser/statement_test.go
  runtime/tests/interpreter/resources_test.go
Labels: Language Breaking Change, Improvement

#3013 Use legacy hashing function for key removal
  migrations/account_type/migration_test.go
  migrations/entitlements/migration.go
  migrations/entitlements/migration_test.go
  migrations/legacy_character_value.go
  migrations/legacy_intersection_type.go
  migrations/legacy_primitivestatic_type.go
  migrations/legacy_reference_type.go
  migrations/legacy_string_value.go
  migrations/migration.go
  migrations/string_normalization/migration.go
  migrations/string_normalization/migration_test.go
  migrations/type_value/migration_test.go
  runtime/convertValues.go
  runtime/interpreter/decode.go
  runtime/interpreter/encode.go
  runtime/interpreter/statictype.go
  runtime/interpreter/value.go
  runtime/interpreter/value_string.go
Labels: Improvement

#3031 Remove Insert-entitled access for toVariableSized
  runtime/sema/check_assignment.go
  runtime/sema/type.go
Labels: Bugfix

#3028 Introduce `toConstantSized` to `VariableSizedArray` type
  runtime/interpreter/value.go
  runtime/sema/type.go
  runtime/tests/checker/arrays_dictionaries_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Feature

#3034 Allow dereferencing references to containers of non-resources
  runtime/sema/check_unary_expression.go
  runtime/sema/type.go
  runtime/tests/checker/reference_test.go
  runtime/tests/interpreter/reference_test.go
Labels: Improvement

#3023 Require explicit type annotation for arguments passed to authorized reference parameters
  runtime/convertValues_test.go
  runtime/runtime_test.go
  runtime/sema/check_assignment.go
  runtime/sema/check_invocation_expression.go
  runtime/sema/checker.go
  runtime/sema/simple_type.go
  runtime/sema/type.go
  runtime/sema/type_test.go
  runtime/tests/checker/entitlements_test.go
  runtime/tests/checker/events_test.go
  runtime/tests/checker/invocation_test.go
  runtime/tests/checker/reference_test.go
  runtime/tests/interpreter/entitlements_test.go
Labels: Language Breaking Change, Improvement

#3033 Generalize static type migrations
  migrations/entitlements/migration_test.go
  migrations/statictypes/account_type_migration_test.go
  migrations/statictypes/composite_type_migration_test.go
  migrations/statictypes/dummy_statictype.go
  migrations/statictypes/intersection_type_migration_test.go
  migrations/statictypes/statictype_migration.go
  migrations/type_value/migration.go
Labels: Improvement

#3039 Add v0.42 parser package under old_parser
  runtime/ast/access.go
  runtime/ast/primitiveaccess_string.go
  runtime/ast/type.go
  runtime/ast/type_test.go
  runtime/common/declarationkind.go
  runtime/common/declarationkind_string.go
  runtime/old_parser/benchmark_test.go
  runtime/old_parser/comment.go
  runtime/old_parser/declaration.go
  runtime/old_parser/declaration_test.go
  runtime/old_parser/docstring.go
  runtime/old_parser/docstring_test.go
  runtime/old_parser/errors.go
  runtime/old_parser/expression.go
  runtime/old_parser/expression_test.go
  runtime/old_parser/function.go
  runtime/old_parser/invalidnumberliteralkind.go
  runtime/old_parser/invalidnumberliteralkind_string.go
  runtime/old_parser/keyword.go
  runtime/old_parser/lexer/lexer.go
  runtime/old_parser/lexer/lexer_test.go
  runtime/old_parser/lexer/state.go
  runtime/old_parser/lexer/token.go
  runtime/old_parser/lexer/tokenstream.go
  runtime/old_parser/lexer/tokentype.go
  runtime/old_parser/parser.go
  runtime/old_parser/parser_test.go
  runtime/old_parser/statement.go
  runtime/old_parser/statement_test.go
  runtime/old_parser/transaction.go
  runtime/old_parser/type.go
  runtime/old_parser/type_test.go
Labels: Feature

#3036 Fix gaps in migrations
  migrations/account_storage.go
  migrations/capcons/capabilitymigration.go
  migrations/capcons/linkmigration.go
  migrations/capcons/migration_test.go
  migrations/capcons/privatemigration.go
  migrations/entitlements/migration.go
  migrations/entitlements/migration_test.go
  migrations/migration.go
  migrations/migration_reporter.go
  migrations/migration_test.go
  migrations/statictypes/account_type_migration_test.go
  migrations/statictypes/composite_type_migration_test.go
  migrations/statictypes/intersection_type_migration_test.go
  migrations/statictypes/statictype_migration.go
  migrations/string_normalization/migration.go
  runtime/tests/runtime_utils/testinterface.go
Labels: Bugfix

#2882 Integrate with atree inlining and data deduplication
  go.mod
  go.sum
  runtime/cmd/decode-state-values/main.go
  runtime/convertValues.go
  runtime/interpreter/decode.go
  runtime/interpreter/deepcopyremove_test.go
  runtime/interpreter/encode.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_invocation.go
  runtime/interpreter/interpreter_statement.go
  runtime/interpreter/interpreter_tracing_test.go
  runtime/interpreter/simplecompositevalue.go
  runtime/interpreter/statictype.go
  runtime/interpreter/storage.go
  runtime/interpreter/storage_test.go
  runtime/interpreter/storagemap.go
  runtime/interpreter/storagemapkey.go
  runtime/interpreter/stringatreevalue.go
  runtime/interpreter/value.go
  runtime/interpreter/value_accountcapabilitycontroller.go
  runtime/interpreter/value_accountreference.go
  runtime/interpreter/value_function.go
  runtime/interpreter/value_placeholder.go
  runtime/interpreter/value_publickey.go
  runtime/interpreter/value_storagecapabilitycontroller.go
  runtime/interpreter/value_test.go
  runtime/interpreter/walk.go
  runtime/runtime_memory_metering_test.go
  runtime/runtime_test.go
  runtime/stdlib/account.go
  runtime/storage.go
  runtime/storage_test.go
  runtime/tests/interpreter/array_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/reference_test.go
  runtime/tests/interpreter/resources_test.go
  runtime/tests/interpreter/values_test.go
Labels: Feature, Performance, Storage Breaking Change

#3044 [v0.42-based atree inlining] Update to latest atree
  go.mod
  go.sum
  runtime/interpreter/storagemap.go
  runtime/interpreter/value.go
Labels: Chore

#3030 Test usage of potentially broken types
  runtime/tests/interpreter/metatype_test.go
Labels: Testing

#3046 Remove backticks around suggested fixes for parser errors
  runtime/parser/declaration.go
  runtime/parser/declaration_test.go
Labels: Bugfix

#3051 Allow reding from CSV and querying AST using (Go) JQ
  go.mod
  go.sum
  runtime/cmd/parse/main.go
Labels: Feature

#3052 Add Unwrap method for ParentErrors
  runtime/old_parser/errors.go
  runtime/parser/errors.go
  runtime/sema/errors.go
  runtime/sema/errors_test.go
  runtime/stdlib/contract_update_validation.go
Labels: Improvement

#3053 Add Unwrap method for ParentErrors - v0.42 backport
  runtime/parser/errors.go
  runtime/sema/errors.go
  runtime/sema/errors_test.go
  runtime/stdlib/contract_update_validation.go
Labels: Improvement

#3057 Add tests for using keywords as field names
  runtime/parser/declaration_test.go
  runtime/parser/keyword.go
  runtime/tests/checker/composite_test.go
Labels: Testing

#3060 Minor improvement in a `revertibleRandom` test
  runtime/runtime_test.go
Labels: Testing

#3056 Don't skip invalid entitlements when creating errors
  runtime/sema/checker.go
  runtime/sema/type.go
  runtime/tests/checker/errors_test.go
Labels: Improvement

#3061 Handle optional storage references when checking member access
  runtime/interpreter/interpreter_expression.go
  runtime/storage_test.go
Labels: Bugfix

#3064 Handle optional storage references
  runtime/interpreter/interpreter_expression.go
  runtime/storage_test.go
Labels: Bugfix
