Repository onflow/cadence, pull requests merged in 2024-11, with the labels that each got.

#3664 Combine domain payloads and provide on-the-fly migration
  cmd/decode-state-values/main.go
  go.mod
  go.sum
  interpreter/account_storagemap.go
  interpreter/account_storagemap_test.go
  interpreter/domain_storagemap.go
  interpreter/domain_storagemap_test.go
  interpreter/interpreter.go
  interpreter/interpreter_tracing.go
  interpreter/misc_test.go
  interpreter/storage.go
  interpreter/storage_test.go
  interpreter/stringatreevalue_test.go
  interpreter/value_test.go
  runtime/capabilitycontrollers_test.go
  runtime/contract_test.go
  runtime/environment.go
  runtime/ft_test.go
  runtime/migrate_domain_registers.go
  runtime/migrate_domain_registers_test.go
  runtime/runtime_memory_metering_test.go
  runtime/runtime_test.go
  runtime/sharedstate_test.go
  runtime/storage.go
  runtime/storage_test.go
  stdlib/account.go
  test_utils/interpreter_utils/interpreter.go
  test_utils/runtime_utils/storage.go
  test_utils/runtime_utils/testledger.go
  tools/compatibility-check/go.mod
  tools/compatibility-check/go.sum
Labels: Feature, Improvement

#3675 Remove unused Identifier() function from structs implementing atree.TypeInfo
  interpreter/encode.go
  interpreter/statictype.go
Labels: Technical Debt

#3673 Refactor storage domains to prevent import cycles and simplify maintenance
  cmd/decode-state-values/main.go
  common/pathdomain.go
  common/storagedomain.go
  interpreter/account_test.go
  interpreter/interpreter.go
  interpreter/misc_test.go
  interpreter/storage.go
  interpreter/storage_test.go
  interpreter/stringatreevalue_test.go
  interpreter/value_composite.go
  interpreter/value_storage_reference.go
  interpreter/value_test.go
  runtime/capabilitycontrollers_test.go
  runtime/contract_test.go
  runtime/environment.go
  runtime/ft_test.go
  runtime/runtime.go
  runtime/runtime_memory_metering_test.go
  runtime/sharedstate_test.go
  runtime/storage.go
  runtime/storage_test.go
  stdlib/account.go
  stdlib/account_test.go
Labels: Technical Debt

#3676 Sync `feature/combine-domain-payloads` branch with master
  cmd/decode-state-values/main.go
  common/pathdomain.go
  common/storagedomain.go
  interpreter/account_storagemap.go
  interpreter/account_storagemap_test.go
  interpreter/account_test.go
  interpreter/encode.go
  interpreter/interpreter.go
  interpreter/misc_test.go
  interpreter/statictype.go
  interpreter/storage.go
  interpreter/storage_test.go
  interpreter/stringatreevalue_test.go
  interpreter/value_composite.go
  interpreter/value_storage_reference.go
  interpreter/value_test.go
  runtime/capabilitycontrollers_test.go
  runtime/contract_test.go
  runtime/environment.go
  runtime/ft_test.go
  runtime/migrate_domain_registers.go
  runtime/migrate_domain_registers_test.go
  runtime/runtime.go
  runtime/runtime_memory_metering_test.go
  runtime/sharedstate_test.go
  runtime/storage.go
  runtime/storage_test.go
  stdlib/account.go
  stdlib/account_test.go
Labels: Chore

#3677 Replace domain string with enum for AccountStorageMap key
  common/storagedomain.go
  interpreter/account_storagemap.go
  interpreter/account_storagemap_test.go
  runtime/runtime_memory_metering_test.go
  runtime/runtime_test.go
Labels: Performance

#3682 Source Compatibility Suite: Switch to main Green Goo Dao repo
  compat/suite/green-goo-dao-flow-utils.yaml
Labels: Technical Debt

#3678 [Account Storage Maps] Refactor storage into V1 and V2
  cmd/decode-state-values/main.go
  common/address.go
  interpreter/account_storagemap.go
  interpreter/account_storagemap_test.go
  interpreter/account_test.go
  interpreter/domain_storagemap.go
  interpreter/domain_storagemap_test.go
  interpreter/interpreter.go
  interpreter/misc_test.go
  interpreter/storage.go
  interpreter/storage_test.go
  interpreter/stringatreevalue_test.go
  interpreter/value_test.go
  runtime/account_storage_v1.go
  runtime/account_storage_v2.go
  runtime/capabilitycontrollers_test.go
  runtime/config.go
  runtime/contract_function_executor.go
  runtime/contract_test.go
  runtime/environment.go
  runtime/ft_test.go
  runtime/migrate_domain_registers.go
  runtime/migrate_domain_registers_test.go
  runtime/runtime.go
  runtime/runtime_memory_metering_test.go
  runtime/runtime_test.go
  runtime/script_executor.go
  runtime/sharedstate_test.go
  runtime/slabindex.go
  runtime/storage.go
  runtime/storage_test.go
  runtime/transaction_executor.go
  stdlib/account.go
  tools/storage-explorer/main.go
Labels: Improvement

#3694 [Account Storage Maps] Add more tests for register reads for GetDomainStorageMap()
  runtime/storage.go
  runtime/storage_test.go
Labels: Testing

#3683 [Account Storage Maps] Reduce storage register reads when using `StorageFormatV2Enabled`
  runtime/sharedstate_test.go
  runtime/storage.go
  runtime/storage_test.go
Labels: Improvement, Performance

#3699 [Account Storage Maps] Bump atree version to v0.8.1
  go.mod
  go.sum
  tools/compatibility-check/go.mod
  tools/compatibility-check/go.sum
Labels: Chore

#3701 Add `Storage.AccountStorageFormat()`
  runtime/storage.go
  runtime/storage_test.go
Labels: Improvement

#3704 Optimize function calls
  bbq/compiler/compiler.go
  bbq/vm/callframe.go
  bbq/vm/linker.go
  bbq/vm/reference_tracking.go
  bbq/vm/test/ft_test.go
  bbq/vm/test/vm_bench_test.go
  bbq/vm/test/vm_test.go
  bbq/vm/vm.go
Labels: Performance

#3700 Merge feature branch `feature/combine-domain-payloads-and-domain-storage-maps` to `master` branch
  cmd/decode-state-values/main.go
  common/address.go
  common/storagedomain.go
  go.mod
  go.sum
  interpreter/account_storagemap.go
  interpreter/account_storagemap_test.go
  interpreter/account_test.go
  interpreter/domain_storagemap.go
  interpreter/domain_storagemap_test.go
  interpreter/interpreter.go
  interpreter/interpreter_tracing.go
  interpreter/misc_test.go
  interpreter/storage.go
  interpreter/storage_test.go
  interpreter/stringatreevalue_test.go
  interpreter/value_test.go
  runtime/account_storage_v1.go
  runtime/account_storage_v2.go
  runtime/capabilitycontrollers_test.go
  runtime/config.go
  runtime/contract_function_executor.go
  runtime/contract_test.go
  runtime/environment.go
  runtime/ft_test.go
  runtime/migrate_domain_registers.go
  runtime/migrate_domain_registers_test.go
  runtime/runtime.go
  runtime/runtime_memory_metering_test.go
  runtime/runtime_test.go
  runtime/script_executor.go
  runtime/sharedstate_test.go
  runtime/slabindex.go
  runtime/storage.go
  runtime/storage_test.go
  runtime/transaction_executor.go
  stdlib/account.go
  test_utils/interpreter_utils/interpreter.go
  test_utils/runtime_utils/storage.go
  test_utils/runtime_utils/testledger.go
  tools/compatibility-check/go.mod
  tools/compatibility-check/go.sum
  tools/storage-explorer/main.go
Labels: Improvement

#3705 Remove the old compiler and VM PoC
  cmd/compile/main.go
  compiler/codegen.go
  compiler/codegen_test.go
  compiler/compiler.go
  compiler/compiler_test.go
  compiler/ir/binop.go
  compiler/ir/binop_string.go
  compiler/ir/constant.go
  compiler/ir/expr.go
  compiler/ir/func.go
  compiler/ir/local.go
  compiler/ir/stmt.go
  compiler/ir/unop.go
  compiler/ir/unop_string.go
  compiler/ir/valtype.go
  compiler/ir/valtype_string.go
  compiler/ir/visitor.go
  compiler/local.go
  compiler/wasm/block.go
  compiler/wasm/blocktype.go
  compiler/wasm/buf.go
  compiler/wasm/data.go
  compiler/wasm/errors.go
  compiler/wasm/export.go
  compiler/wasm/function.go
  compiler/wasm/functiontype.go
  compiler/wasm/gen/main.go
  compiler/wasm/import.go
  compiler/wasm/instruction.go
  compiler/wasm/instructions.go
  compiler/wasm/leb128.go
  compiler/wasm/leb128_test.go
  compiler/wasm/magic.go
  compiler/wasm/memory.go
  compiler/wasm/module.go
  compiler/wasm/modulebuilder.go
  compiler/wasm/opcode.go
  compiler/wasm/reader.go
  compiler/wasm/reader_test.go
  compiler/wasm/section.go
  compiler/wasm/valuetype.go
  compiler/wasm/wasm.go
  compiler/wasm/wasm2wat.go
  compiler/wasm/writer.go
  compiler/wasm/writer_test.go
  go.mod
  go.sum
  vm/vm.go
Labels: Technical Debt
