Repository onflow/cadence, pull requests merged in 2024-05, with the labels that each got.

#3301 Update atree inlining v1.0 feature branch
  encoding/ccf/ccf_test.go
  encoding/ccf/encode.go
  encoding/ccf/service_events_test.go
  encoding/ccf/traverse_value.go
  encoding/json/encode.go
  encoding/json/encoding_test.go
  helpers.go
  migrations/broken_dictionary.go
  migrations/migration_test.go
  migrations/testdata/missing-slabs-payloads.csv
  runtime/account_test.go
  runtime/attachments_test.go
  runtime/contract_test.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/crypto_test.go
  runtime/deployment_test.go
  runtime/interpreter/simplecompositevalue.go
  runtime/interpreter/value.go
  runtime/predeclaredvalues_test.go
  runtime/program_params_validation_test.go
  runtime/resourcedictionary_test.go
  runtime/runtime_test.go
  runtime/tests/runtime_utils/testledger.go
  tools/storage-explorer/go.mod
  tools/storage-explorer/go.sum
  tools/update/config.yaml
  types.go
  values.go
  values_test.go
Labels: Chore

#3304 Produce a validator error when contracts would produce unrepresentable entitlements sets in the migration
  runtime/common/orderedmap/orderedmap.go
  runtime/sema/entitlementset.go
  runtime/sema/entitlementset_test.go
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validation_test.go
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validator.go
Labels: Language Breaking Change, Improvement

#3306 Update atree inlining 1.0 branch
  go.mod
  go.sum
  npm-packages/cadence-parser/package.json
  runtime/common/orderedmap/orderedmap.go
  runtime/sema/entitlementset.go
  runtime/sema/entitlementset_test.go
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validation_test.go
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validator.go
  tools/storage-explorer/go.mod
  tools/storage-explorer/go.sum
  version.go
Labels: Chore

#3307 Add a command to generate a mermaid diagram
  tools/update/main.ts
Labels: Feature

#3315 Make static type cache an interface
  migrations/cache.go
  migrations/entitlements/migration.go
Labels: Improvement

#3317 Add test for untyped optional nested-reference creation
  runtime/tests/interpreter/reference_test.go
Labels: Testing

#3316 Fix Cadence 1.0 migration of dictionary values when using atree inlined data
  migrations/migration.go
Labels: Bugfix

#3318 Improve dictionary migration
  migrations/entitlements/migration_test.go
  migrations/migration.go
  migrations/migration_test.go
Labels: Improvement

#3314 Add reproducer as test for Cadence 1.0 migration issue #3288
  migrations/migration_test.go
  runtime/tests/runtime_utils/testledger.go
Labels: Testing

#3322 Make migration error stacktrace configurable
  migrations/migration.go
  migrations/migration_test.go
Labels: Improvement

#3325 Remove invalid ID capability error
  runtime/interpreter/interpreter.go
  runtime/interpreter/value_capability.go
  runtime/runtime_test.go
  runtime/stdlib/account.go
Labels: Bugfix

#3329 Add/improve caching in static type and entitlements migration
  migrations/cache.go
  migrations/entitlements/migration.go
  migrations/statictypes/account_type_migration_test.go
  migrations/statictypes/composite_type_migration_test.go
  migrations/statictypes/intersection_type_migration_test.go
  migrations/statictypes/statictype_migration.go
Labels: Improvement

#3319 Update flow-go related configuration
  .github/workflows/downstream.yml
  tools/update/config.yaml
Labels: Chore

#3332 Port bug fixes to v0.42
  runtime/interpreter/value.go
  runtime/sema/check_assignment.go
  runtime/tests/checker/access_test.go
  runtime/tests/checker/resources_test.go
  runtime/tests/checker/transactions_test.go
  runtime/tests/interpreter/resources_test.go
Labels: Bugfix

#3331 Port bug fixes
  runtime/sema/check_assignment.go
  runtime/tests/checker/access_test.go
  runtime/tests/checker/resources_test.go
  runtime/tests/checker/transactions_test.go
Labels: Bugfix

#3337 Handle missing interfaces in Cadence 1.0 contract update validator
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validation_test.go
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validator.go
Labels: Bugfix

#3338 Allow construction of paths with syntactically invalid identifiers
  runtime/ast/position.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/literal.go
  runtime/sema/check_path_expression.go
  runtime/sema/check_path_expression_test.go
  runtime/stdlib/account_test.go
  runtime/tests/interpreter/path_test.go
Labels: Improvement

#3346 Bump atree version to v0.8.0-rc.2 in feature/atree-register-inlining-v1.0
  go.mod
  go.sum
  version.go
Labels: Chore

#3347 Bump atree version to v0.7.0-rc.2 in master branch
  go.mod
  go.sum
Labels: Chore

#3348 Add Storage.NondeterministicCommit for faster migrations
  migrations/migration.go
  runtime/storage.go
Labels: Performance

#3339 Check dictionary keys when checking the ability for dereferencing
  runtime/sema/type.go
  runtime/tests/checker/reference_test.go
Labels: Bugfix

#3340 Use parent to determine whether an expression is target of an invocation
  runtime/repl.go
  runtime/sema/check_array_expression.go
  runtime/sema/check_assignment.go
  runtime/sema/check_attach_expression.go
  runtime/sema/check_binary_expression.go
  runtime/sema/check_casting_expression.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_conditional.go
  runtime/sema/check_conditions.go
  runtime/sema/check_create_expression.go
  runtime/sema/check_destroy_expression.go
  runtime/sema/check_dictionary_expression.go
  runtime/sema/check_expression.go
  runtime/sema/check_for.go
  runtime/sema/check_force_expression.go
  runtime/sema/check_invocation_expression.go
  runtime/sema/check_member_expression.go
  runtime/sema/check_reference_expression.go
  runtime/sema/check_remove_statement.go
  runtime/sema/check_return_statement.go
  runtime/sema/check_swap.go
  runtime/sema/check_switch.go
  runtime/sema/check_unary_expression.go
  runtime/sema/check_variable_declaration.go
  runtime/sema/check_while.go
  runtime/sema/checker.go
  runtime/tests/checker/resources_test.go
Labels: Bugfix, Language Breaking Change

#3345 Add back transaction `execute` tests
  runtime/tests/checker/resources_test.go
  runtime/tests/interpreter/transactions_test.go
Labels: Testing

#3341 Improve static validation of contract/transaction moves
  runtime/resource_duplicate_test.go
  runtime/runtime_test.go
  runtime/sema/check_array_expression.go
  runtime/sema/check_assignment.go
  runtime/sema/check_attach_expression.go
  runtime/sema/check_dictionary_expression.go
  runtime/sema/check_expression.go
  runtime/sema/check_invocation_expression.go
  runtime/sema/check_return_statement.go
  runtime/sema/check_variable_declaration.go
  runtime/sema/checker.go
  runtime/tests/checker/attachments_test.go
  runtime/tests/checker/composite_test.go
  runtime/tests/checker/contract_test.go
  runtime/tests/checker/events_test.go
  runtime/tests/checker/move_test.go
  runtime/tests/checker/nesting_test.go
  runtime/tests/checker/operations_test.go
  runtime/tests/checker/optional_test.go
  runtime/tests/checker/resources_test.go
  runtime/tests/checker/transactions_test.go
  runtime/tests/interpreter/composite_value_test.go
  runtime/tests/interpreter/condition_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Bugfix, Language Breaking Change

#3342 Wrap host-function typed member-values with a bound-function
  runtime/contract_function_executor.go
  runtime/environment.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_transaction.go
  runtime/interpreter/invocation.go
  runtime/interpreter/value.go
  runtime/interpreter/value_account_accountcapabilities.go
  runtime/interpreter/value_account_capabilities.go
  runtime/interpreter/value_account_contracts.go
  runtime/interpreter/value_account_inbox.go
  runtime/interpreter/value_account_storage.go
  runtime/interpreter/value_account_storagecapabilities.go
  runtime/interpreter/value_accountcapabilitycontroller.go
  runtime/interpreter/value_authaccount_keys.go
  runtime/interpreter/value_capability.go
  runtime/interpreter/value_deployedcontract.go
  runtime/interpreter/value_function.go
  runtime/interpreter/value_function_test.go
  runtime/interpreter/value_range.go
  runtime/interpreter/value_storagecapabilitycontroller.go
  runtime/interpreter/value_string.go
  runtime/predeclaredvalues_test.go
  runtime/stdlib/account.go
  runtime/stdlib/assert.go
  runtime/stdlib/block.go
  runtime/stdlib/bls.go
  runtime/stdlib/builtin.go
  runtime/stdlib/functions.go
  runtime/stdlib/hashalgorithm.go
  runtime/stdlib/log.go
  runtime/stdlib/panic.go
  runtime/stdlib/publickey.go
  runtime/stdlib/random.go
  runtime/stdlib/range.go
  runtime/stdlib/rlp.go
  runtime/stdlib/test.go
  runtime/stdlib/test_contract.go
  runtime/stdlib/test_emulatorbackend.go
  runtime/tests/checker/invocation_test.go
  runtime/tests/checker/predeclaredvalues_test.go
  runtime/tests/checker/resources_test.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/condition_test.go
  runtime/tests/interpreter/container_mutation_test.go
  runtime/tests/interpreter/import_test.go
  runtime/tests/interpreter/interface_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/invocation_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/reference_test.go
  runtime/tests/interpreter/transactions_test.go
  runtime/transaction_executor.go
Labels: Bugfix

#3357 Return a copy for enum-typed members, during member-access via references
  runtime/sema/type.go
  runtime/tests/checker/entitlements_test.go
  runtime/tests/checker/for_test.go
  runtime/tests/checker/member_test.go
Labels: Language Breaking Change, Improvement

#3364 Bump atree version to v0.8.0-rc.3 in feature/atree-register-inlining-v0.42
  go.mod
  go.sum
Labels: Chore

#3365 Bump atree version to v0.8.0-rc.3 in feature/atree-register-inlining-v1.0
  go.mod
  go.sum
  version.go
Labels: Chore

#3370 Fix string formatting for values
  runtime/common/metering.go
  runtime/format/capability.go
  runtime/interpreter/value_capability.go
  runtime/interpreter/value_pathcapability.go
  runtime/interpreter/value_storagecapabilitycontroller.go
  runtime/interpreter/value_test.go
Labels: Improvement

#3374 Update the storage explorer to the latest version of flow-go
  tools/storage-explorer/addresses.go
  tools/storage-explorer/go.mod
  tools/storage-explorer/go.sum
  tools/storage-explorer/main.go
Labels: Improvement

#3373 Add deprecated path Capability into backwards compability
  encoding/json/decode.go
  encoding/json/encoding_test.go
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/format/capability.go
  values.go
  values_test.go
Labels: Bugfix

#3375 Remove incorrect caching from migrations
  migrations/cache.go
  migrations/entitlements/migration.go
  migrations/statictypes/statictype_migration.go
Labels: Bugfix

#3376 Allow types to be removed in contract updates
  runtime/ast/memberindices.go
  runtime/ast/members.go
  runtime/contract_update_validation_test.go
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validator.go
  runtime/stdlib/contract_update_validation.go
Labels: Improvement

#3378 Update atree register inlining v1.0
  encoding/json/decode.go
  encoding/json/encoding_test.go
  migrations/cache.go
  migrations/entitlements/migration.go
  migrations/statictypes/statictype_migration.go
  migrations_data/staged-contracts-report-2024-05-15T10-00-00Z-testnet.json
  migrations_data/staged-contracts-report-2024-05-15T10-00-00Z-testnet.md
  migrations_data/staged-contracts-report-2024-05-22T10-00-00Z-testnet.json
  migrations_data/staged-contracts-report-2024-05-22T10-00-00Z-testnet.md
  runtime/ast/memberindices.go
  runtime/ast/members.go
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  runtime/contract_update_validation_test.go
  runtime/format/capability.go
  runtime/interpreter/value_capability.go
  runtime/interpreter/value_pathcapability.go
  runtime/interpreter/value_storagecapabilitycontroller.go
  runtime/interpreter/value_test.go
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validator.go
  runtime/stdlib/contract_update_validation.go
  tools/storage-explorer/addresses.go
  tools/storage-explorer/go.mod
  tools/storage-explorer/go.sum
  tools/storage-explorer/main.go
  values.go
  values_test.go
Labels: Chore

#3379 Fix error message
  runtime/stdlib/contract_update_validation.go
Labels: Bugfix

#3380 Forbid interface removals
  runtime/contract_update_validation_test.go
  runtime/stdlib/contract_update_validation.go
Labels: Improvement

#3381 Improve dictionary value migration
  migrations/entitlements/migration_test.go
  migrations/migration.go
  migrations/migration_test.go
Labels: Improvement

#3384 Add report from May 29
  migrations_data/staged-contracts-report-2024-05-29T10-00-00Z-testnet.json
  migrations_data/staged-contracts-report-2024-05-29T10-00-00Z-testnet.md
Labels: Chore

#3383 Update atree register inlining feature branch to v1.0.0-preview.30
  migrations/entitlements/migration_test.go
  migrations/migration.go
  migrations/migration_test.go
  npm-packages/cadence-parser/package.json
  runtime/contract_update_validation_test.go
  runtime/stdlib/contract_update_validation.go
Labels: Chore

#3368 Decrease move operator precedence relative to cast operators
  runtime/parser/expression.go
  runtime/parser/expression_test.go
  runtime/tests/checker/move_test.go
Labels: Improvement
