Repository onflow/cadence, pull requests merged in 2024-03, with the labels that each got.

#3138 Fix migrating values with empty intersection type
  migrations/entitlements/migration_test.go
  migrations/migration_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/statictype.go
  runtime/interpreter/statictype_test.go
  runtime/interpreter/value_pathcapability.go
  runtime/parser/declaration_test.go
  runtime/parser/type.go
  runtime/sema/check_casting_expression.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/checker.go
  runtime/sema/type.go
  runtime/sema/type_test.go
  runtime/tests/checker/resources_test.go
Labels: Improvement

#3151 Fix location ranges
  runtime/interpreter/value.go
Labels: Bugfix

#3150 Produce a better error message when failing to reference type-erased references
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter_expression.go
  runtime/tests/interpreter/member_test.go
Labels: Bugfix

#3152 Make SupportedEntitlements thread safe
  runtime/sema/type.go
Labels: Bugfix

#3144 Improve migrations
  migrations/capcons/migration_test.go
  migrations/entitlements/migration.go
  migrations/entitlements/migration_test.go
  migrations/migration.go
  migrations/migration_test.go
  migrations/statictypes/account_type_migration_test.go
  migrations/statictypes/composite_type_migration_test.go
  migrations/statictypes/intersection_type_migration_test.go
  migrations/statictypes/statictype_migration.go
  migrations/statictypes/statictype_migration_test.go
  migrations/string_normalization/migration_test.go
  runtime/interpreter/value.go
  runtime/interpreter/value_link.go
  runtime/interpreter/value_test.go
Labels: Bugfix, Improvement

#3154 Improve errors in state migration
  migrations/capcons/migration_test.go
  migrations/entitlements/migration_test.go
  migrations/migration.go
  migrations/migration_reporter.go
  migrations/migration_test.go
  migrations/statictypes/account_type_migration_test.go
Labels: Improvement

#3158 Improve static type and entitlements migrations: Update array/dictionary type directly
  go.mod
  go.sum
  migrations/entitlements/migration.go
  migrations/migration_test.go
  migrations/statictypes/statictype_migration.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
Labels: Improvement

#3157 Optimize storage migration: Allow skipping of values
  migrations/capcons/capabilitymigration.go
  migrations/capcons/linkmigration.go
  migrations/capcons/migration_test.go
  migrations/entitlements/migration.go
  migrations/entitlements/migration_test.go
  migrations/migration.go
  migrations/migration_test.go
  migrations/statictypes/statictype_migration.go
  migrations/statictypes/statictype_migration_test.go
  migrations/string_normalization/migration.go
  migrations/string_normalization/migration_test.go
Labels: Improvement

#3161 Update version
  npm-packages/cadence-parser/package.json
  version.go
Labels: Technical Debt

#3160 Check invalidation of the looped reference
  runtime/interpreter/value.go
  runtime/tests/interpreter/resources_test.go
Labels: Bugfix

#3164 Handle legacy type getting converted to intersection type
  migrations/statictypes/statictype_migration.go
  migrations/statictypes/statictype_migration_test.go
Labels: Improvement

#3166 Fix intersection type's legacy type getting converted to intersection type
  migrations/entitlements/migration_test.go
  migrations/statictypes/statictype_migration.go
  migrations/statictypes/statictype_migration_test.go
  runtime/interpreter/config.go
  runtime/interpreter/interpreter.go
Labels: Bugfix

#3163 Improve update tool
  tools/update/config.yaml
  tools/update/main.ts
Labels: Improvement

#3169 Improve migration
  migrations/account_storage.go
  migrations/address_iterator.go
  migrations/capcons/capabilitymigration.go
  migrations/capcons/linkmigration.go
  migrations/capcons/migration_test.go
  migrations/entitlements/migration.go
  migrations/entitlements/migration_test.go
  migrations/migration.go
  migrations/migration_test.go
  migrations/statictypes/account_type_migration_test.go
  migrations/statictypes/composite_type_migration_test.go
  migrations/statictypes/intersection_type_migration_test.go
  migrations/statictypes/statictype_migration.go
  migrations/statictypes/statictype_migration_test.go
  migrations/string_normalization/migration.go
  migrations/string_normalization/migration_test.go
Labels: Improvement

#3132 Allow creating references to nested optionals
  runtime/interpreter/interpreter_expression.go
  runtime/sema/check_reference_expression.go
  runtime/sema/errors.go
  runtime/tests/checker/reference_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/reference_test.go
Labels: Language Breaking Change, Improvement

#3168 Implicitly track composite reference in attachment iteration
  runtime/interpreter/value.go
  runtime/tests/interpreter/resources_test.go
Labels: Bugfix

#3172 Meter computation for standard-library functions
  runtime/interpreter/value.go
  runtime/tests/interpreter/metering_test.go
Labels: Improvement

#3173 Optimize string migration: only return new value if needed
  migrations/string_normalization/migration.go
  runtime/interpreter/value.go
Labels: Improvement

#3175 Improve update tool
  tools/update/config.yaml
Labels: Improvement

#3184 Relax interface conformance changes in contract update validator
  runtime/stdlib/account.go
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validation_test.go
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validator.go
  runtime/stdlib/contract_update_validation.go
Labels: Improvement

#3147 Storage Explorer
  encoding/json/decode.go
  encoding/json/encode.go
  encoding/json/encoding_test.go
  tools/ast-explorer/.eslintrc
  tools/ast-explorer/.gitignore
  tools/ast-explorer/README.md
  tools/ast-explorer/main.go
  tools/ast-explorer/package-lock.json
  tools/ast-explorer/package.json
  tools/ast-explorer/src/cadence.ts
  tools/ast-explorer/src/index.html
  tools/ast-explorer/src/index.tsx
  tools/ast-explorer/src/tree.tsx
  tools/ast-explorer/tsconfig.json
  tools/ast-explorer/webpack.config.js
  tools/storage-explorer/.gitignore
  tools/storage-explorer/README.md
  tools/storage-explorer/addresses.go
  tools/storage-explorer/go.mod
  tools/storage-explorer/go.sum
  tools/storage-explorer/index.html
  tools/storage-explorer/main.go
  tools/storage-explorer/package-lock.json
  tools/storage-explorer/package.json
  tools/storage-explorer/src/array.tsx
  tools/storage-explorer/src/composite.tsx
  tools/storage-explorer/src/dictionary.tsx
  tools/storage-explorer/src/fallback.tsx
  tools/storage-explorer/src/index.css
  tools/storage-explorer/src/index.ts
  tools/storage-explorer/src/primitive.tsx
  tools/storage-explorer/src/type.module.css
  tools/storage-explorer/src/type.tsx
  tools/storage-explorer/src/value.ts
  tools/storage-explorer/src/vite-env.d.ts
  tools/storage-explorer/storagemaps.go
  tools/storage-explorer/tsconfig.json
  tools/storage-explorer/type.go
  tools/storage-explorer/value.go
Labels: Feature

#3189 Improve development documentation
  docs/FAQ.md
  docs/README.md
  docs/development.md
  docs/syntax-highlighting.md
Labels: Documentation

#3190 Update CODEOWNERS
  CODEOWNERS
Labels: Chore

#3196 Handle unparameterized Capability static types
  migrations/statictypes/statictype_migration.go
  migrations/statictypes/statictype_migration_test.go
Labels: Bugfix

#3195 Fix address conversion
  runtime/interpreter/value.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Bugfix

#3197 Allow removal of enum declarations from contract interfaces for C1.0 upgrade
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validation_test.go
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validator.go
  runtime/stdlib/contract_update_validation.go
Labels: Improvement

#3198 Name storage migration, include in error
  migrations/capcons/migration_test.go
  migrations/entitlements/migration_test.go
  migrations/migration.go
  migrations/migration_test.go
  migrations/statictypes/account_type_migration_test.go
  migrations/statictypes/composite_type_migration_test.go
  migrations/statictypes/intersection_type_migration_test.go
  migrations/statictypes/statictype_migration_test.go
  migrations/string_normalization/migration_test.go
Labels: Improvement

#3199 Only encode reference static type in legacy format if it was decoded as such
  migrations/entitlements/migration_test.go
  migrations/legacy_reference_type.go
  migrations/migration_test.go
  runtime/interpreter/decode.go
  runtime/interpreter/statictype.go
Labels: Bugfix

#3191 Fix conformance checking for enums in contract update validator
  runtime/contract_update_validation_test.go
  runtime/stdlib/account.go
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validation_test.go
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validator.go
Labels: Bugfix

#3178 Bump atree version in Cadence v1.0 for new features (e.g. deduplication of Cadence dictionary type info)
  go.mod
  go.sum
Labels: Performance, E&V Team

#3177 Bump atree version in Cadence 0.42 for new features (e.g. deduplication of Cadence dictionary type info)
  go.mod
  go.sum
Labels: Performance, E&V Team
