Repository onflow/cadence, pull requests merged in 2024-10, with the labels that each got.

#3600 Port bug fixes from internal repo
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/value.go
  runtime/interpreter/value_accountcapabilitycontroller.go
  runtime/interpreter/value_deployedcontract.go
  runtime/interpreter/value_function.go
  runtime/interpreter/value_pathcapability.go
  runtime/interpreter/value_range.go
  runtime/interpreter/value_storagecapabilitycontroller.go
  runtime/sema/check_assignment.go
  runtime/sema/check_expression.go
  runtime/sema/check_member_expression.go
  runtime/sema/check_reference_expression.go
  runtime/stdlib/account.go
  runtime/stdlib/publickey.go
  runtime/tests/checker/reference_test.go
  runtime/tests/checker/resources_test.go
  runtime/tests/interpreter/function_test.go
  runtime/tests/interpreter/interface_test.go
  runtime/tests/interpreter/reference_test.go
  runtime/tests/interpreter/transactions_test.go
Labels: Bugfix

#3602 Prevent leaving unreferenced slabs in storage while updating dictionary with enum key
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/runtime_test.go
Labels: Bugfix

#3601 Fix invocation boxing
  runtime/account_test.go
  runtime/capabilitycontrollers_test.go
  runtime/environment.go
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_invocation.go
  runtime/interpreter/value.go
  runtime/sema/type.go
  runtime/stdlib/account.go
  runtime/stdlib/crypto.go
  runtime/stdlib/test_contract.go
  runtime/storage_test.go
  runtime/tests/interpreter/attachments_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/invocation_test.go
Labels: Bugfix

#3609 Split `value.go` into multiple files
  runtime/interpreter/inclusive_range_iterator.go
  runtime/interpreter/value.go
  runtime/interpreter/value_address.go
  runtime/interpreter/value_array.go
  runtime/interpreter/value_bool.go
  runtime/interpreter/value_character.go
  runtime/interpreter/value_composite.go
  runtime/interpreter/value_dictionary.go
  runtime/interpreter/value_ephemeral_reference.go
  runtime/interpreter/value_fix64.go
  runtime/interpreter/value_int.go
  runtime/interpreter/value_int128.go
  runtime/interpreter/value_int16.go
  runtime/interpreter/value_int256.go
  runtime/interpreter/value_int32.go
  runtime/interpreter/value_int64.go
  runtime/interpreter/value_int8.go
  runtime/interpreter/value_nil.go
  runtime/interpreter/value_number.go
  runtime/interpreter/value_optional.go
  runtime/interpreter/value_path.go
  runtime/interpreter/value_published.go
  runtime/interpreter/value_reference.go
  runtime/interpreter/value_some.go
  runtime/interpreter/value_storage_reference.go
  runtime/interpreter/value_string.go
  runtime/interpreter/value_type.go
  runtime/interpreter/value_ufix64.go
  runtime/interpreter/value_uint.go
  runtime/interpreter/value_uint128.go
  runtime/interpreter/value_uint16.go
  runtime/interpreter/value_uint256.go
  runtime/interpreter/value_uint32.go
  runtime/interpreter/value_uint64.go
  runtime/interpreter/value_uint8.go
  runtime/interpreter/value_void.go
  runtime/interpreter/value_word128.go
  runtime/interpreter/value_word16.go
  runtime/interpreter/value_word256.go
  runtime/interpreter/value_word32.go
  runtime/interpreter/value_word64.go
  runtime/interpreter/value_word8.go
Labels: Technical Debt

#3589 Improve `result` variable
  runtime/ast/block.go
  runtime/ast/block_test.go
  runtime/ast/expression_test.go
  runtime/ast/transaction_declaration_test.go
  runtime/coverage.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_transaction.go
  runtime/interpreter/value_function.go
  runtime/old_parser/declaration_test.go
  runtime/old_parser/statement.go
  runtime/old_parser/transaction.go
  runtime/parser/declaration_test.go
  runtime/parser/statement.go
  runtime/parser/transaction.go
  runtime/runtime_test.go
  runtime/sema/check_conditions.go
  runtime/sema/check_function.go
  runtime/sema/check_transaction_declaration.go
  runtime/sema/errors.go
  runtime/sema/post_conditions_rewrite.go
  runtime/tests/checker/conditions_test.go
  runtime/tests/checker/function_test.go
Labels: Improvement

#3614 Explain the reason for support parsing legacy restricted types
  runtime/parser/type.go
Labels: Technical Debt

#3570 Add Type.address and Type.contractName
  runtime/interpreter/value_type.go
  runtime/sema/meta_type.go
  runtime/tests/checker/metatype_test.go
  runtime/tests/interpreter/metatype_test.go
Labels: Feature

#3616 Update source compatibility suite for latest cadence v1.0.1
  compat/main.py
  compat/requirements.txt
  compat/suite/flow-core-contracts.yaml
  compat/suite/flow-ft.yaml
  compat/suite/flow-nft.yaml
  compat/suite/nba-smart-contracts.yaml
Labels: Chore

#3627 Fix storage explorer
  tools/storage-explorer/addresses.go
  tools/storage-explorer/go.mod
  tools/storage-explorer/go.sum
  tools/storage-explorer/main.go
  tools/storage-explorer/storagemaps.go
  tools/storage-explorer/type.go
  tools/storage-explorer/value.go
Labels: Technical Debt

#3619 Move Crypto contract on-chain
  .github/workflows/ci.yml
  cmd/cmd.go
  runtime/environment.go
  stdlib/contracts/crypto.cdc
  stdlib/contracts/crypto.go
  stdlib/contracts/crypto_test.cdc
  stdlib/crypto.go
  stdlib/crypto_test.go
  stdlib/test.go
  tests/crypto_test.go
  tests/runtime_test.go
  tools/analysis/analysis.go
  tools/analysis/analysis_test.go
  tools/analysis/config.go
  tools/analysis/programs.go
Labels: Technical Debt

#3630 Cleanup outdated FT/NFT related contract codes and tests
  ast/inspector_test.go
  tests/checker/interface_test.go
  tests/checker/nft_test.go
  tests/examples/examples.go
  tests/interpreter/interpreter_test.go
Labels: Technical Debt

#3632 Re-enable and update the Source Compatiblity Suite GitHub action
  .github/workflows/compat.yaml
  .github/workflows/compat.yaml.disabled
  compat/main.py
  compat/requirements.txt
  compat/suite/flow-core-contracts.yaml
  compat/suite/flow-ft.yaml
  compat/suite/flow-nft.yaml
  compat/suite/nba-smart-contracts.yaml
Labels: Chore

#3629 Update release docs with a section for versioning strategy
  docs/releasing.md
Labels: Documentation

#3634 Resolve location of imported values
  runtime/contract_function_executor.go
  runtime/convertValues.go
  runtime/environment.go
  runtime/runtime.go
  tests/convertValues_test.go
  tests/deployment_test.go
  tests/runtime_utils/location.go
  tests/runtime_utils/testinterface.go
Labels: Improvement

#3635 Move meeting notes
  meetings/2022-07-22.md
  meetings/2022-08-30.md
  meetings/2022-09-13.md
  meetings/2022-09-20-Extensions.md
  meetings/2022-09-26 Capabilities.md
  meetings/2022-09-27.md
  meetings/2022-10-11.md
  meetings/2022-11-02.md
  meetings/2022-11-16-Interface-Inheritance.md
  meetings/2023-01-10.md
  meetings/2023-02-23.md
  meetings/2023-04-13.md
  meetings/2023-05-04.md
  meetings/2023-06-15.md
  meetings/2023-08-15.md
  meetings/2023-09-12.md
  meetings/2023-10-24.md
  meetings/2023-11-15.md
  meetings/README.md
Labels: Chore

#3631 Update contracts-compatibility-checker
  .github/workflows/compatibility-check-template.yml
  Makefile
  tools/analysis/programs.go
  tools/compatibility-check/cmd/check_contracts/main.go
  tools/compatibility-check/contracts_checker.go
  tools/compatibility-check/contracts_checker_test.go
  tools/compatibility-check/go.mod
  tools/compatibility-check/go.sum
Labels: Technical Debt

#3640 Update CCF CDDL for IntersectionType to match CCF codec
  encoding/ccf/decode_type.go
  encoding/ccf/encode.go
  encoding/ccf/encode_type.go
Labels: Documentation

#3641 Update the config of the update tool
  tools/update/config.yaml
Labels: Chore

#3642 Remove attachments enabling flag
  cmd/cmd.go
  runtime/config.go
  runtime/environment.go
  sema/check_attach_expression.go
  sema/check_composite_declaration.go
  sema/check_expression.go
  sema/check_remove_statement.go
  sema/config.go
  sema/errors.go
  stdlib/cadence_v0.42_to_v1_contract_upgrade_validation_test.go
  tests/attachments_test.go
  tests/checker/access_test.go
  tests/checker/attachments_test.go
  tests/checker/storable_test.go
  tests/checker/utils.go
  tests/convertValues_test.go
  tests/entitlements_test.go
  tests/interpreter/attachments_test.go
  tests/interpreter/entitlements_test.go
  tests/interpreter/interpreter_test.go
  tests/interpreter/resources_test.go
  tests/runtime_test.go
  tests/runtime_utils/testruntime.go
  tests/storage_test.go
Labels: Technical Debt

#3646 Misc minor C1.0 updates
  npm-packages/cadence-parser/README.md
  tools/ast-explorer/src/index.tsx
Labels: Improvement

#3650 Move architecture diagram to contributor documentation directory
  docs/architecture.monopic
  docs/architecture.png
  docs/architecture.svg
Labels: Technical Debt

#3649 Document Go patterns used in the codebase
  docs/go.md
Labels: Documentation

#3653 [v1.0] Port security fixes
  go.mod
  go.sum
  runtime/ast/expression.go
  runtime/contract_update_validation_test.go
  runtime/empty.go
  runtime/environment.go
  runtime/interface.go
  runtime/runtime_test.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/errors.go
  runtime/stdlib/account.go
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validator.go
  runtime/stdlib/contract_update_validation.go
  runtime/tests/checker/attachments_test.go
  runtime/tests/checker/composite_test.go
  runtime/tests/checker/contract_test.go
  runtime/tests/checker/entitlements_test.go
  runtime/tests/checker/nesting_test.go
  runtime/tests/runtime_utils/testinterface.go
Labels: Bugfix

#3647 Update old uses of pub and priv
  docs/cadence.ebnf
  docs/development.md
Labels: Technical Debt

#3644 Source Compatibility Suite: Run Cadence tests
  compat/main.py
  compat/suite/flow-core-contracts.yaml
  compat/suite/green-goo-dao-flow-utils.yaml
Labels: Feature

#3658 Enable type removal during contract updates
  interpreter/config.go
  runtime/config.go
  runtime/contract_update_validation_test.go
  runtime/environment.go
  stdlib/account.go
  stdlib/cadence_v0.42_to_v1_contract_upgrade_validator.go
  stdlib/contract_update_validation.go
Labels: Feature

#3661 Refactor and update struct stringer tests
  ast/expression.go
  go.mod
  go.sum
  interpreter/config.go
  interpreter/struct_stringer_test.go
  npm-packages/cadence-parser/package.json
  runtime/config.go
  runtime/contract_update_validation_test.go
  runtime/empty.go
  runtime/environment.go
  runtime/interface.go
  runtime/runtime_test.go
  sema/attachments_test.go
  sema/check_composite_declaration.go
  sema/composite_test.go
  sema/contract_test.go
  sema/entitlements_test.go
  sema/errors.go
  sema/nesting_test.go
  sema/struct_stringer_test.go
  stdlib/account.go
  stdlib/cadence_v0.42_to_v1_contract_upgrade_validator.go
  stdlib/contract_update_validation.go
  test_utils/runtime_utils/testinterface.go
  tools/compatibility-check/go.mod
  tools/compatibility-check/go.sum
  version.go
Labels: Technical Debt

#3663 Add a GitHub Action to get all contracts
  .github/workflows/compatibility-check-template.yml
  .github/workflows/get-contracts.yml
Labels: Chore
