Repository onflow/cadence, pull requests merged in 2024-06, with the labels that each got.

#3387 Don't short circuit references on member access when entitlements are involved
  runtime/interpreter/interpreter_expression.go
  runtime/runtime_test.go
  runtime/tests/interpreter/member_test.go
Labels: Bugfix

#3386 Improve dictionary key migration
  migrations/capcons/capabilitymigration.go
  migrations/capcons/linkmigration.go
  migrations/entitlements/migration.go
  migrations/entitlements/migration_test.go
  migrations/migration.go
  migrations/migration_test.go
  migrations/statictypes/statictype_migration.go
  migrations/string_normalization/migration.go
  migrations/type_keys/migration.go
  migrations/type_keys/migration_test.go
Labels: Improvement

#3390 Update atree inlining branch
  migrations/capcons/capabilitymigration.go
  migrations/capcons/linkmigration.go
  migrations/entitlements/migration.go
  migrations/entitlements/migration_test.go
  migrations/migration.go
  migrations/migration_test.go
  migrations/statictypes/statictype_migration.go
  migrations/string_normalization/migration.go
  migrations/type_keys/migration.go
  migrations/type_keys/migration_test.go
  migrations_data/staged-contracts-report-2024-05-29T10-00-00Z-testnet.json
  migrations_data/staged-contracts-report-2024-05-29T10-00-00Z-testnet.md
  npm-packages/cadence-parser/package.json
  runtime/interpreter/interpreter_expression.go
  runtime/parser/expression.go
  runtime/parser/expression_test.go
  runtime/runtime_test.go
  runtime/tests/checker/move_test.go
  runtime/tests/interpreter/member_test.go
Labels: Chore

#3392 Remove stacktrace from errors
  runtime/errors/errors.go
Labels: Improvement

#3394 Port predicate func from PR 3300 to feature/atree-register-inlining-v0.42
  migrations/broken_dictionary.go
  migrations/broken_dictionary_test.go
  migrations/testdata/missing-slabs-payloads.csv
  runtime/tests/runtime_utils/testledger.go
Labels: Improvement

#3393 Update to Go 1.22
  .github/workflows/benchmark.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/compatibility-check-template.yml
  .github/workflows/compatibility-check.yml
  .github/workflows/downstream.yml
  .github/workflows/release.yml
  go.mod
  go.sum
  tools/compatibility-check/go.mod
  tools/constructorcheck/Makefile
  tools/constructorcheck/go.mod
  tools/constructorcheck/go.sum
  tools/constructorcheck/main.go
  tools/get-contracts/go.mod
  tools/golangci-lint/go.mod
  tools/golangci-lint/go.sum
  tools/maprange/Makefile
  tools/maprange/go.mod
  tools/maprange/go.sum
  tools/maprange/main.go
  tools/storage-explorer/go.mod
  tools/unkeyed/Makefile
  tools/unkeyed/go.mod
  tools/unkeyed/go.sum
  tools/unkeyed/main.go
Labels: Chore

#3396 Cache results of static types migration and entitlements migration
  migrations/cache.go
  migrations/entitlements/migration.go
  migrations/statictypes/statictype_migration.go
Labels: Improvement, Performance

#3404 Prevent storage reference to another reference
  runtime/interpreter/value.go
  runtime/runtime_test.go
Labels: Bugfix

#3406 Add access top type to model inaccessible access for identity maps
  runtime/ast/access.go
  runtime/ast/primitiveaccess_string.go
  runtime/interpreter/decode.go
  runtime/interpreter/encode.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/statictype.go
  runtime/sema/access.go
  runtime/sema/check_member_expression.go
  runtime/sema/type.go
  runtime/tests/checker/entitlements_test.go
  runtime/tests/interpreter/entitlements_test.go
Labels: Bugfix

#3410 Put feature that allows type removals in contract updates behind a feature flag, disabled by default
  runtime/config.go
  runtime/contract_update_validation_test.go
  runtime/environment.go
  runtime/interpreter/config.go
  runtime/stdlib/account.go
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validator.go
  runtime/stdlib/contract_update_validation.go
  runtime/tests/runtime_utils/testruntime.go
Labels: Improvement

#3416 Merge v1.0.0-preview.34 into feature/atree-register-inlining-v1.0
  npm-packages/cadence-parser/package.json
Labels: Chore

#3413 Fix JSON output
  runtime/cmd/parse/main.go
Labels: Bugfix

#3412 [v0.42] Fix JSON output
  runtime/cmd/parse/main.go
Labels: Bugfix

#3418 Improve parsing of commit from Go's pseudo-version in update tool
  tools/update/main.ts
Labels: Bugfix

#3420 adding report from June 12 TN state migration
  migrations_data/staged-contracts-report-2024-06-12T13-03-00Z-testnet.json
  migrations_data/staged-contracts-report-2024-06-12T13-03-00Z-testnet.md
Labels: Chore

#3421 Ensure contracts cannot be borrowed with an authorization
  runtime/account_test.go
  runtime/stdlib/account.go
Labels: Improvement, Testing

#3422 [v0.42] Simplify nil-coalescing checking
  runtime/sema/check_binary_expression.go
  runtime/tests/checker/nil_coalescing_test.go
  runtime/tests/checker/resources_test.go
Labels: Bugfix

#3423 Simplify nil-coalescing checking
  runtime/sema/check_binary_expression.go
  runtime/tests/checker/nil_coalescing_test.go
  runtime/tests/checker/resources_test.go
Labels: Bugfix

#3425 Improve dump-builtin-types command: Handle parameterized types
  runtime/cmd/info/main.go
Labels: Improvement

#3426 Improve InclusiveRange type
  runtime/interpreter/interpreter.go
  runtime/sema/runtime_type_constructors.go
  runtime/sema/type.go
  runtime/stdlib/range.go
Labels: Improvement

#3427 Update update tool config
  tools/update/config.yaml
Labels: Chore

#3429 Update staged-contracts-report-2024-06-12T13-03-00Z-testnet.md
  migrations_data/staged-contracts-report-2024-06-12T13-03-00Z-testnet.md
Labels: Documentation

#3430 Update feature/atree-register-inlining-v0.42 to latest v0.42
  npm-packages/cadence-parser/package.json
  runtime/cmd/parse/main.go
  runtime/interpreter/value.go
  runtime/sema/check_assignment.go
  runtime/sema/check_binary_expression.go
  runtime/tests/checker/access_test.go
  runtime/tests/checker/nil_coalescing_test.go
  runtime/tests/checker/resources_test.go
  runtime/tests/checker/transactions_test.go
  runtime/tests/interpreter/resources_test.go
  version.go
Labels: Chore

#3431 Add command to dump all hard keywords
  runtime/cmd/info/main.go
  runtime/parser/declaration_test.go
  runtime/parser/expression_test.go
  runtime/parser/keyword.go
  runtime/parser/statement_test.go
Labels: Feature

#3435 Update update tool config
  .github/workflows/ci.yml
  tools/update/config.yaml
Labels: Chore

#3417 Import contracts as references
  runtime/coverage_test.go
  runtime/import_test.go
  runtime/interpreter/interpreter_import.go
  runtime/program_params_validation_test.go
  runtime/resource_duplicate_test.go
  runtime/runtime_test.go
  runtime/sema/check_import_declaration.go
  runtime/tests/checker/import_test.go
  runtime/tests/checker/member_test.go
  runtime/tests/checker/reference_test.go
Labels: Language Breaking Change, Improvement

#3432 Remove access to field slices from composite and interface types
  encoding/ccf/ccf_test.go
  encoding/ccf/ccf_type_id_test.go
  encoding/ccf/decode.go
  encoding/ccf/decode_typedef.go
  encoding/ccf/encode.go
  encoding/ccf/encode_typedef.go
  encoding/ccf/service_events_test.go
  encoding/ccf/traverse_value.go
  encoding/json/decode.go
  encoding/json/encode.go
  encoding/json/encoding_test.go
  runtime/convertTypes.go
  runtime/convertTypes_test.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/crypto_test.go
  runtime/program_params_validation_test.go
  runtime/runtime_test.go
  types.go
  types_test.go
  values.go
  values_test.go
Labels: Improvement, Go API Breaking Change

#3440 Improve the commit-based version handling in the update tool
  tools/update/main.ts
Labels: Improvement

#3441 Improve update tool
  tools/update/config.yaml
  tools/update/main.ts
Labels: Improvement

#3442 Improve handling of releases in update tool
  tools/update/main.ts
Labels: Improvement
