Repository onflow/cadence, pull requests merged in 2024-02, with the labels that each got.

#3065 Fix entitlements migration
  migrations/entitlements/migration.go
  migrations/migration.go
  runtime/interpreter/value.go
Labels: Bugfix

#3066 Gracefully handle runtime panics in migration
  migrations/migration.go
  migrations/migration_test.go
Labels: Improvement

#3072 Improve migrations
  migrations/capcons/migration_test.go
  migrations/capcons/privatemigration.go
  migrations/entitlements/migration.go
  migrations/entitlements/migration_test.go
  migrations/statictypes/account_type_migration_test.go
  migrations/statictypes/statictype_migration.go
  runtime/interpreter/value_link.go
Labels: Improvement

#3070 Improve update script
  tools/update/config.schema.json
  tools/update/config.schema.ts
  tools/update/config.yaml
  tools/update/main.ts
Labels: Improvement

#3073 Add support for migrating path capability values in entitlements and static type migrations
  migrations/entitlements/migration.go
  migrations/entitlements/migration_test.go
  migrations/statictypes/account_type_migration_test.go
  migrations/statictypes/statictype_migration.go
  runtime/interpreter/value_pathcapability.go
Labels: Improvement

#3074 Remove reference to `destroy` from sema.UnknownSpecialFunctionError
  runtime/sema/errors.go
Labels: Bugfix

#3075 Fixes links to new docs site
  README.md
  docs/README.md
  docs/anti-patterns.mdx
  docs/contract-upgrades.mdx
  docs/design-patterns.mdx
  docs/index.mdx
  docs/json-cadence-spec.md
  docs/language/access-control.md
  docs/language/accounts.mdx
  docs/language/attachments.md
  docs/language/built-in-functions.mdx
  docs/language/capability-based-access-control.md
  docs/language/composite-types.mdx
  docs/language/constants-and-variables.md
  docs/language/contract-updatability.md
  docs/language/contracts.mdx
  docs/language/control-flow.md
  docs/language/core-events.md
  docs/language/crypto.mdx
  docs/language/enumerations.md
  docs/language/environment-information.md
  docs/language/events.md
  docs/language/functions.mdx
  docs/language/glossary.md
  docs/language/imports.mdx
  docs/language/index.md
  docs/language/interfaces.mdx
  docs/language/operators.md
  docs/language/references.mdx
  docs/language/resources.mdx
  docs/language/restricted-types.md
  docs/language/run-time-types.md
  docs/language/scope.md
  docs/language/syntax.md
  docs/language/transactions.md
  docs/language/type-annotations.md
  docs/language/type-hierarchy.md
  docs/language/type-inference.md
  docs/language/type-safety.md
  docs/language/values-and-types.mdx
  docs/measuring-time.mdx
  docs/security-best-practices.mdx
  docs/solidity-to-cadence.mdx
  docs/testing-framework.mdx
  docs/tutorial/01-first-steps.mdx
  docs/tutorial/02-hello-world.mdx
  docs/tutorial/03-resources.mdx
  docs/tutorial/04-capabilities.mdx
  docs/tutorial/05-non-fungible-tokens-1.mdx
  docs/tutorial/05-non-fungible-tokens-2.mdx
  docs/tutorial/06-fungible-tokens.mdx
  docs/tutorial/07-marketplace-setup.mdx
  docs/tutorial/08-marketplace-compose.mdx
  docs/tutorial/09-voting.mdx
  docs/tutorial/10-resources-compose.mdx
  docs/why.md
Labels: Documentation

#3076 [v0.42] Port fixes of v0.42.8-patch.4
  runtime/contract_update_validation_test.go
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_statement.go
  runtime/interpreter/value.go
  runtime/runtime_test.go
  runtime/sema/check_invocation_expression.go
  runtime/sema/check_swap.go
  runtime/sema/check_switch.go
  runtime/stdlib/account.go
  runtime/stdlib/contract_update_validation.go
  runtime/stdlib/type-comparator.go
  runtime/storage_test.go
  runtime/tests/checker/attachments_test.go
  runtime/tests/checker/events_test.go
  runtime/tests/checker/swap_test.go
  runtime/tests/checker/switch_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/resources_test.go
Labels: Bugfix

#3078 Port Validator fix to master
  runtime/contract_update_validation_test.go
  runtime/stdlib/account.go
  runtime/stdlib/contract_update_validation.go
  runtime/stdlib/type-comparator.go
Labels: Bugfix

#3084 Fix intersection type migration: also migrate interface types
  migrations/statictypes/intersection_type_migration_test.go
  migrations/statictypes/statictype_migration.go
Labels: Bugfix

#3085 Make capability ID mapping thread-safe
  migrations/capcons/capabilitymigration.go
  migrations/capcons/linkmigration.go
  migrations/capcons/mapping.go
  migrations/capcons/migration_test.go
Labels: Bugfix

#3058 Replace existing tool to fetch network contracts with Flowdiver-based one
  .github/workflows/compatibility-check-template.yml
  .github/workflows/compatibility-check.yml
  Makefile
  docs/releasing.md
  tools/batch-script/.gitignore
  tools/batch-script/README.md
  tools/batch-script/address_provider.go
  tools/batch-script/batch.go
  tools/batch-script/cmd/get_contracts/main.go
  tools/batch-script/get_contracts.cdc
  tools/batch-script/go.mod
  tools/batch-script/go.sum
  tools/batch-script/use_cases.go
  tools/get-contracts/go.mod
  tools/get-contracts/go.sum
  tools/get-contracts/main.go
Labels: Improvement

#3092 Improve member resolvers
  runtime/sema/check_member_expression.go
  runtime/sema/type.go
  runtime/sema/type_test.go
  runtime/tests/interpreter/memory_metering_test.go
Labels: Improvement

#3089 Allow contract interface types in intersection types
  runtime/sema/checker.go
  runtime/sema/errors.go
  runtime/tests/checker/intersection_test.go
Labels: Bugfix

#3094 [v0.42] Handle optional storage references
  runtime/interpreter/interpreter_expression.go
  runtime/storage_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
Labels: Bugfix

#3093 Consider inherited interfaces when checking for member clashes in intersection types
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_interface_declaration.go
  runtime/sema/checker.go
  runtime/tests/checker/intersection_test.go
Labels: Bugfix

#3082 Add more information to analysis.Diagnostic
  tools/analysis/diagnostic.go
Labels: Improvement

#3101 Report a proper error for swapping a resource to itself
  runtime/interpreter/interpreter_statement.go
  runtime/tests/interpreter/resources_test.go
Labels: Bugfix, Improvement

#3103 Bring back support for decoding published path capabilities
  migrations/capcons/linkmigration.go
  migrations/capcons/migration_test.go
  migrations/entitlements/migration.go
  migrations/entitlements/migration_test.go
  migrations/migration.go
  migrations/migration_test.go
  migrations/statictypes/statictype_migration.go
  runtime/convertValues.go
  runtime/interpreter/decode.go
  runtime/interpreter/encode.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/interpreter/value_accountcapabilitycontroller.go
  runtime/interpreter/value_capability.go
  runtime/interpreter/value_pathcapability.go
  runtime/interpreter/value_storagecapabilitycontroller.go
  runtime/interpreter/visitor.go
  runtime/stdlib/account.go
  runtime/tests/interpreter/dynamic_casting_test.go
Labels: Improvement

#3090 Unify the requirement for all interface types to have to occur in intersection types
  migrations/statictypes/account_type_migration_test.go
  migrations/statictypes/composite_type_migration_test.go
  migrations/statictypes/intersection_type_migration_test.go
  migrations/statictypes/statictype_migration.go
  runtime/account_test.go
  runtime/interpreter/interpreter.go
  runtime/sema/runtime_type_constructors.go
  runtime/sema/type.go
  runtime/tests/checker/access_test.go
  runtime/tests/checker/arrays_dictionaries_test.go
  runtime/tests/checker/attachments_test.go
  runtime/tests/checker/composite_test.go
  runtime/tests/checker/interface_test.go
  runtime/tests/checker/resources_test.go
  runtime/tests/checker/runtimetype_test.go
  runtime/tests/interpreter/condition_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/runtimetype_test.go
  runtime/tests/utils/utils.go
Labels: Language Breaking Change, Improvement, Storage Breaking Change

#3083 Allow analysis.Load to continue with parsing/checking errors
  tools/analysis/analysis_test.go
  tools/analysis/config.go
  tools/analysis/program.go
  tools/analysis/programs.go
Labels: Improvement

#3110 Improve migration
  migrations/capcons/capabilitymigration.go
  migrations/capcons/linkmigration.go
  migrations/entitlements/migration_test.go
  migrations/legacy_primitivestatic_type.go
  migrations/migration.go
  migrations/statictypes/account_type_migration_test.go
  migrations/statictypes/composite_type_migration_test.go
  migrations/statictypes/intersection_type_migration_test.go
  migrations/statictypes/statictype_migration.go
  migrations/statictypes/statictype_migration_test.go
Labels: Improvement

#3124 Improve update tool: Allow releasing a particular branch
  tools/update/main.ts
Labels: Improvement

#3069 Contract Update Validator
  runtime/contract_update_test.go
  runtime/contract_update_validation_test.go
  runtime/interpreter/interpreter.go
  runtime/stdlib/account.go
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validation_test.go
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validator.go
  runtime/stdlib/contract_update_validation.go
Labels: Feature

#3111 Improve Cadence-1.0 contract update checker
  runtime/contract_update_validation_test.go
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validation_test.go
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validator.go
  runtime/stdlib/contract_update_validation.go
Labels: Improvement

#3117 Fix location collection in contract update validator
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validation_test.go
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validator.go
  runtime/stdlib/contract_update_validation.go
Labels: Improvement

#3120 Allow registering custom type updating rules in contract update validator
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validation_test.go
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validator.go
Labels: Improvement

#3118 Rewrite owned intersection types in migration
  migrations/entitlements/migration.go
  migrations/entitlements/migration_test.go
  migrations/migration.go
  migrations/migration_test.go
  migrations/statictypes/account_type_migration_test.go
  migrations/statictypes/intersection_type_migration_test.go
  migrations/statictypes/statictype_migration.go
  migrations/statictypes/statictype_migration_test.go
  runtime/interpreter/value.go
Labels: Improvement

#3130 Improve update tool: Fix config, improve documentation
  tools/update/README.md
  tools/update/config.yaml
Labels: Documentation, Improvement

#3137 Fix EntitlementSetAuthorization.Equal() by making it ignore order of elements
  encoding/json/encode.go
  encoding/json/encoding_test.go
  runtime/convertTypes.go
  runtime/convertValues_test.go
  types.go
  types_test.go
Labels: Bugfix

#3134 Require added entitlements to be equal to migrated entitlements rather than supertypes
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validation_test.go
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validator.go
Labels: Improvement

#3140 Pass location-range to value-interface methods
  runtime/cmd/decode-state-values/main.go
  runtime/interpreter/inspect.go
  runtime/interpreter/inspect_test.go
  runtime/interpreter/simplecompositevalue.go
  runtime/interpreter/value.go
  runtime/interpreter/value_accountcapabilitycontroller.go
  runtime/interpreter/value_capability.go
  runtime/interpreter/value_function.go
  runtime/interpreter/value_link.go
  runtime/interpreter/value_pathcapability.go
  runtime/interpreter/value_placeholder.go
  runtime/interpreter/value_storagecapabilitycontroller.go
  runtime/interpreter/value_test.go
  runtime/interpreter/walk.go
  runtime/runtime.go
Labels: Technical Debt

#3107 Add support for `FunctionType.Purity` in CCF codec
  encoding/ccf/ccf_test.go
  encoding/ccf/decode.go
  encoding/ccf/encode.go
  types.go
Labels: Feature

#3131 Add support for Attachment and AttachmentType in CCF codec
  encoding/ccf/ccf_test.go
  encoding/ccf/ccf_type_id.go
  encoding/ccf/consts.go
  encoding/ccf/decode.go
  encoding/ccf/decode_typedef.go
  encoding/ccf/encode.go
  encoding/ccf/encode_typedef.go
  encoding/ccf/traverse_value.go
Labels: Feature

#3139 Add more support for entitlements (`ReferenceType.Authorization`) to CCF codec
  encoding/ccf/ccf_test.go
  encoding/ccf/consts.go
  encoding/ccf/decode.go
  encoding/ccf/decode_type.go
  encoding/ccf/encode.go
  encoding/ccf/encode_type.go
  encoding/ccf/sort.go
Labels: Feature

#3141 Migrate static types of arrays and dictionaries
  migrations/statictypes/account_type_migration_test.go
  migrations/statictypes/statictype_migration.go
Labels: Bugfix

#3142 Add test for nested container value migration
  migrations/migration.go
  migrations/statictypes/statictype_migration.go
  migrations/statictypes/statictype_migration_test.go
Labels: Testing
