Repository onflow/cadence, pull requests merged in 2024-08, with the labels that each got.

#3506 adding migration report from Testnet migration on 31st July
  migrations_data/staged-contracts-report-2024-07-31T10-00-00Z-testnet.json
  migrations_data/staged-contracts-report-2024-07-31T10-00-00Z-testnet.md
Labels: Chore

#3511 Fix migration of storage path capabilities
  migrations/capcons/capabilities.go
  migrations/capcons/capabilitymigration.go
  migrations/capcons/migration_test.go
  migrations/capcons/storagecapmigration.go
Labels: Bugfix

#3514 Report and skip storage caps with missing borrow type
  migrations/capcons/migration_test.go
  migrations/capcons/storagecapmigration.go
  runtime/stdlib/account.go
Labels: Bugfix

#3516 Improve storage capability migration
  migrations/capcons/capabilitymigration.go
  migrations/capcons/linkmigration.go
  migrations/capcons/mapping.go
  migrations/capcons/migration_test.go
  migrations/capcons/storagecapmigration.go
Labels: Bugfix, Improvement

#3517 Avoid conversion from sema-type to StaticType in storage cap migration
  migrations/capcons/capabilitymigration.go
  migrations/capcons/linkmigration.go
  migrations/capcons/mapping.go
  migrations/capcons/storagecapmigration.go
  runtime/stdlib/account.go
Labels: Bugfix

#3519 Infer missing borrow type for storage capabilities
  migrations/capcons/capabilitymigration.go
  migrations/capcons/migration_test.go
  migrations/capcons/storagecapmigration.go
Labels: Improvement

#3520 Improve borrow type inferrence for storage path capabilities
  migrations/capcons/migration_test.go
  migrations/capcons/storagecapmigration.go
Labels: Improvement

#3522 Improve storage path capability migration reporting
  migrations/capcons/capabilities.go
  migrations/capcons/migration_test.go
  migrations/capcons/storagecapmigration.go
Labels: Improvement

#3524 Add capability stored path info to the report
  migrations/capcons/capabilitymigration.go
  migrations/capcons/migration_test.go
  migrations/capcons/storagecapmigration.go
Labels: Improvement

#3525 add staged report for aug 12
  migrations_data/staged-contracts-report-2024-08-12T10-00-00Z-testnet.json
  migrations_data/staged-contracts-report-2024-08-12T10-00-00Z-testnet.md
Labels: Chore

#3530 Fix contract update validation: Check updated contract name
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validation_test.go
  runtime/stdlib/contract_update_validation.go
Labels: Improvement

#3505 Add `Type.isRecovered` field
  runtime/environment.go
  runtime/ft_test.go
  runtime/interpreter/value.go
  runtime/repl.go
  runtime/sema/elaboration.go
  runtime/sema/meta_type.go
  runtime/tests/checker/metatype_test.go
  runtime/tests/interpreter/metatype_test.go
Labels: Feature

#3538 Add support for exporting unmigrated path capabilities
  encoding/json/encode.go
  encoding/json/encoding_test.go
  runtime/convertValues.go
  runtime/convertValues_test.go
Labels: Bugfix

#3532 Check if CBOR tag number is reserved by atree before using it to encode Cadence values
  go.mod
  go.sum
  runtime/cmd/decode-state-values/main.go
  runtime/interpreter/encode.go
Labels: Improvement

#3539 Handle invalid index-expressions in view assignment
  runtime/interpreter/interpreter_expression.go
  runtime/sema/check_assignment.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_swap.go
  runtime/sema/elaboration.go
  runtime/tests/checker/function_test.go
Labels: Bugfix

#3542 Make capabilities iteration ordered
  migrations/capcons/capabilities.go
  migrations/capcons/capabilities_test.go
  migrations/capcons/storagecapmigration.go
Labels: Bugfix

#3547 Add mainnet migration report for Aug 21
  migrations_data/staged-contracts-report-2024-08-21T15-00-00Z-mainnet.json
  migrations_data/staged-contracts-report-2024-08-21T15-00-00Z-mainnet.md
Labels: Documentation

#3548 Fix program recovery
  runtime/empty.go
  runtime/environment.go
  runtime/ft_test.go
  runtime/interface.go
  runtime/tests/runtime_utils/testinterface.go
Labels: Bugfix

#3551 Fix Cadence Parser NPM Package
  npm-packages/cadence-parser/src/go.js
  npm-packages/cadence-parser/tests/index.test.ts
Labels: Bugfix

#3553 Add regression tests for nil-coalescing bug
  runtime/tests/checker/resources_test.go
  runtime/tests/interpreter/resources_test.go
Labels: Testing

#3554 Fix contract update error when old program has errors
  runtime/contract_update_test.go
  runtime/stdlib/account.go
Labels: Bugfix

#3557 Staged contracts report Aug 27
  migrations_data/staged-contracts-report-2024-08-27T15-00-00Z-mainnet.json
  migrations_data/staged-contracts-report-2024-08-27T15-00-00Z-mainnet.md
Labels: Documentation

#3556 Smoke test update of enum key in dictionary
  runtime/tests/interpreter/values_test.go
Labels: Testing

#3552 Add sema.Access.QualifiedKeyword
  runtime/sema/access.go
  runtime/sema/access_test.go
Labels: Feature

#3559 Add contract-update test for removing a field from nested resource
  runtime/contract_update_validation_test.go
Labels: Testing

#3561 Add test for modifying events during contract updates
  runtime/contract_update_validation_test.go
Labels: Testing

#3560 Improve address decoding error
  encoding/json/decode.go
  encoding/json/encoding_test.go
Labels: Improvement

#3562 Handle unmigrated path capabilities and path links in Account.capabilities functions
  migrations/capcons/capabilitymigration.go
  migrations/capcons/linkmigration.go
  migrations/capcons/migration_test.go
  migrations/entitlements/migration.go
  migrations/entitlements/migration_test.go
  migrations/migration_test.go
  migrations/statictypes/account_type_migration_test.go
  migrations/statictypes/statictype_migration.go
  migrations/statictypes/statictype_migration_test.go
  runtime/capabilitycontrollers_test.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/interpreter/decode.go
  runtime/interpreter/encode.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value_capability.go
  runtime/interpreter/value_pathcapability.go
  runtime/interpreter/value_test.go
  runtime/stdlib/account.go
  runtime/tests/interpreter/pathcapability_test.go
Labels: Bugfix
