Repository onflow/cadence, pull requests merged in 2024-09, with the labels that each got.

#3564 add staged contracts report 2024-09-02
  migrations_data/staged-contracts-report-2024-09-02T10-00-00Z-mainnet.json
  migrations_data/staged-contracts-report-2024-09-02T10-00-00Z-mainnet.md
Labels: Chore

#3567 Clean up roadmap
  ROADMAP.md
Labels: Chore

#3568 Bring changelog up-to-date
  CHANGELOG.md
Labels: Chore

#3573 Fix CI: Flow CLI is 1.0 now
  .github/workflows/ci.yml
Labels: Bugfix

#3571 Add Crescendo migration report for mainnet24
  migrations_data/staged-contracts-report-2024-09-04T00-00-00Z-mainnet24.json
  migrations_data/staged-contracts-report-2024-09-04T00-00-00Z-mainnet24.md
Labels: Chore

#3575 Change index expression's start position
  runtime/parser/expression.go
  runtime/parser/expression_test.go
  runtime/parser/statement_test.go
  runtime/tests/checker/purity_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Bugfix

#3576 Add tests for exporting interface type
  runtime/convertValues_test.go
Labels: Testing

#3555 Fix cadence-parser npm package
  npm-packages/cadence-parser/package-lock.json
  npm-packages/cadence-parser/tests/setup.js
Labels: Bugfix

#3566 Fix storage explorer: Update dependencies, update API usage
  tools/storage-explorer/go.mod
  tools/storage-explorer/go.sum
  tools/storage-explorer/value.go
Labels: Chore

#3583 Bump atree from v0.8.0-rc.6 to v0.8.0
  go.mod
  go.sum
Labels: Chore

#3580 Unwrap optionals with dynamic cast
  runtime/interpreter/interpreter_expression.go
  runtime/tests/interpreter/dynamic_casting_test.go
Labels: Improvement

#3582 Always report errors against the new program during contract update validation
  runtime/contract_update_validation_test.go
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validator.go
  runtime/stdlib/contract_update_validation.go
Labels: Bugfix

#3581 Add tests for enum usage as transaction parameters
  runtime/program_params_validation_test.go
  runtime/tests/interpreter/transactions_test.go
Labels: Testing

#3586 Add test for circular resources
  runtime/tests/interpreter/reference_test.go
Labels: Testing

#3578 Always return parser errors gracefully
  runtime/environment.go
  runtime/error_test.go
  runtime/old_parser/parser.go
  runtime/old_parser/parser_test.go
  runtime/parser/expression_test.go
  runtime/parser/lexer/lexer.go
  runtime/parser/lexer/lexer_test.go
  runtime/parser/parser.go
  runtime/parser/parser_test.go
  runtime/repl.go
  runtime/runtime_test.go
Labels: Improvement

#3590 Allow validation of `Account.capabilities.get/borrow/publish`
  .github/workflows/compatibility-check-template.yml
  runtime/empty.go
  runtime/environment.go
  runtime/interface.go
  runtime/interpreter/config.go
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/runtime_test.go
  runtime/stdlib/account.go
  runtime/tests/runtime_utils/testinterface.go
Labels: Feature

#3592 Fix runtime type of Account_Inbox_claim() function
  runtime/stdlib/account.go
Labels: Bugfix

#3591 Fix interpreting default functions
  runtime/interpreter/interpreter.go
  runtime/tests/interpreter/interface_test.go
Labels: Bugfix
