Repository onflow/cadence, pull requests merged in 2024-07, with the labels that each got.

#3450 add 2024-07-03 staged contracts report
  migrations_data/staged-contracts-report-2024-06-26T10-00-00Z-testnet.md
  migrations_data/staged-contracts-report-2024-07-03T10-00-00Z-testnet.json
  migrations_data/staged-contracts-report-2024-07-03T10-00-00Z-testnet.md
Labels: Documentation

#3446 Fix toConstantSized
  runtime/interpreter/value.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Bugfix

#3449 Allow borrowing of capability with subtype
  runtime/capabilities_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/stdlib/account.go
  runtime/stdlib/account_test.go
Labels: Improvement

#3447 Simplify subtyping
  runtime/interpreter/interpreter.go
Labels: Improvement

#3453 Add some more tests for string functions
  runtime/tests/interpreter/interpreter_test.go
Labels: Testing

#3455 Add a String.contains function
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/sema/string_type.go
  runtime/tests/checker/string_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/string_test.go
Labels: Feature

#3456 Add String.index and String.count, fix grapheme boundary functions
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/sema/string_type.go
  runtime/tests/checker/string_test.go
  runtime/tests/interpreter/string_test.go
Labels: Feature

#3457 Fix String.split
  runtime/interpreter/value.go
  runtime/tests/interpreter/metering_test.go
  runtime/tests/interpreter/string_test.go
Labels: Bugfix

#3462 add staged contracts report 07-10
  migrations_data/staged-contracts-report-2024-07-10T10-00-00Z-testnet.json
  migrations_data/staged-contracts-report-2024-07-10T10-00-00Z-testnet.md
Labels: Documentation

#3463 add root block for migration 07-10
  migrations_data/staged-contracts-report-2024-07-10T10-00-00Z-testnet.md
Labels: Documentation

#3460 Emit events when capability controllers are issued
  migrations/capcons/linkmigration.go
  migrations/capcons/migration_test.go
  migrations/migration_test.go
  runtime/capabilitycontrollers_test.go
  runtime/convertValues_test.go
  runtime/environment.go
  runtime/events.go
  runtime/inbox_test.go
  runtime/runtime_test.go
  runtime/stdlib/account.go
  runtime/stdlib/flow.go
  runtime/storage_test.go
  runtime/value.go
Labels: Feature

#3461 Fix account link migration
  migrations/capcons/capabilitymigration.go
  migrations/capcons/linkmigration.go
  migrations/capcons/migration_test.go
Labels: Bugfix

#3464 Emit events for more Capability Controller and capability operations
  migrations/capcons/linkmigration.go
  migrations/capcons/migration_test.go
  runtime/capabilitycontrollers_test.go
  runtime/cmd/cmd.go
  runtime/environment.go
  runtime/stdlib/account.go
  runtime/stdlib/flow.go
  runtime/tests/interpreter/account_test.go
Labels: Feature

#3467 Update atree inlining cadence v1.0
  migrations/capcons/capabilitymigration.go
  migrations/capcons/linkmigration.go
  migrations/capcons/migration_test.go
  migrations/migration_test.go
  migrations_data/staged-contracts-report-2024-07-10T10-00-00Z-testnet.json
  migrations_data/staged-contracts-report-2024-07-10T10-00-00Z-testnet.md
  npm-packages/cadence-parser/package.json
  runtime/capabilitycontrollers_test.go
  runtime/cmd/cmd.go
  runtime/convertValues_test.go
  runtime/environment.go
  runtime/events.go
  runtime/inbox_test.go
  runtime/interpreter/value.go
  runtime/interpreter/value_test.go
  runtime/runtime_test.go
  runtime/sema/string_type.go
  runtime/stdlib/account.go
  runtime/stdlib/flow.go
  runtime/storage_test.go
  runtime/tests/checker/string_test.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/metering_test.go
  runtime/tests/interpreter/string_test.go
  runtime/value.go
  version.go
Labels: Chore

#3468 Speed up update tool
  tools/update/main.ts
Labels: Improvement

#3465 Changed data type of account key index to uin32
  runtime/account_test.go
  runtime/cmd/cmd.go
  runtime/environment.go
  runtime/interface.go
  runtime/interpreter/value.go
  runtime/runtime_test.go
  runtime/stdlib/account.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/runtime_utils/testinterface.go
Labels: Improvement

#3469 Improve Cadence composite to Go struct decoding
  types.go
  types_test.go
Labels: Improvement

#3472 Update atree inlining branch
  npm-packages/cadence-parser/package.json
  runtime/account_test.go
  runtime/cmd/cmd.go
  runtime/environment.go
  runtime/interface.go
  runtime/interpreter/value.go
  runtime/runtime_test.go
  runtime/stdlib/account.go
  runtime/tests/interpreter/account_test.go
  runtime/tests/runtime_utils/testinterface.go
  tools/update/main.ts
  types.go
  types_test.go
  version.go
Labels: Chore

#3471 Update Fungible token transfer benchmark
  runtime/ft_test.go
  runtime/resource_duplicate_test.go
Labels: Testing

#3474 Update feature/atree-register-inlining-v1.0
  runtime/ft_test.go
  runtime/resource_duplicate_test.go
  version.go
Labels: Chore

#3475 Update feature/atree-register-inlining-v0.42
  runtime/ft_test.go
Labels: Chore

#3479 Cleanup `ConvertSemaAccessToStaticAuthorization` method
  runtime/interpreter/statictype.go
Labels: Technical Debt

#3481 Fix data races caused by empty string singleton
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/value.go
Labels: Bugfix

#3483 Improve intersected type error message
  runtime/sema/errors.go
Labels: Improvement

#3485 Add an empty implementation of `runtime.Interface`
  runtime/empty.go
Labels: Feature

#3486 Bring back members of path capability value
  runtime/interpreter/value_pathcapability.go
  runtime/tests/interpreter/pathcapability_test.go
Labels: Improvement

#3493 Fix supertype inference
  runtime/sema/check_array_expression.go
  runtime/sema/check_binary_expression.go
  runtime/sema/check_conditional.go
  runtime/sema/check_dictionary_expression.go
  runtime/sema/checker.go
  runtime/sema/type_tags.go
  runtime/tests/checker/conditional_test.go
  runtime/tests/interpreter/interpreter_test.go
Labels: Bugfix

#3494 Return user error when CCF encodes attachment field
  encoding/ccf/ccf_test.go
  encoding/ccf/encode.go
Labels: Bugfix

#3492 Add stack traces back to unexpected errors
  runtime/errors/errors.go
Labels: Feature

#3495 Add checker tests for nil-coalesce type inference
  runtime/sema/checker.go
  runtime/tests/checker/type_inference_test.go
Labels: Testing

#3498 Fix EntitlementDeclaration EndPos
  runtime/parser/declaration.go
  runtime/parser/declaration_test.go
Labels: Bugfix

#3482 Handle broken contracts
  runtime/empty.go
  runtime/environment.go
  runtime/ft_test.go
  runtime/interface.go
  runtime/tests/runtime_utils/testinterface.go
Labels: Feature

#3500 Update feature/atree-register-inlining-v1.0 to use atree v0.8.0-rc.5
  go.mod
  go.sum
Labels: Chore

#3502 Merge atree register inlining v1.0
  go.mod
  go.sum
  migrations/entitlements/migration_test.go
  migrations/legacy_character_value.go
  migrations/legacy_string_value.go
  migrations/migration.go
  migrations/migration_test.go
  migrations/statictypes/account_type_migration_test.go
  migrations/statictypes/intersection_type_migration_test.go
  migrations/statictypes/statictype_migration_test.go
  migrations/string_normalization/migration_test.go
  migrations/type_keys/migration_test.go
  runtime/account_test.go
  runtime/cmd/decode-state-values/main.go
  runtime/convertValues.go
  runtime/empty.go
  runtime/interface.go
  runtime/interpreter/decode.go
  runtime/interpreter/deepcopyremove_test.go
  runtime/interpreter/encode.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_invocation.go
  runtime/interpreter/interpreter_tracing_test.go
  runtime/interpreter/sharedstate.go
  runtime/interpreter/simplecompositevalue.go
  runtime/interpreter/statictype.go
  runtime/interpreter/storage.go
  runtime/interpreter/storage_test.go
  runtime/interpreter/storagemap.go
  runtime/interpreter/storagemapkey.go
  runtime/interpreter/stringatreevalue.go
  runtime/interpreter/value.go
  runtime/interpreter/value_accountcapabilitycontroller.go
  runtime/interpreter/value_capability.go
  runtime/interpreter/value_function.go
  runtime/interpreter/value_link.go
  runtime/interpreter/value_pathcapability.go
  runtime/interpreter/value_placeholder.go
  runtime/interpreter/value_storagecapabilitycontroller.go
  runtime/interpreter/value_test.go
  runtime/runtime_memory_metering_test.go
  runtime/runtime_test.go
  runtime/stdlib/account.go
  runtime/storage.go
  runtime/storage_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/values_test.go
  runtime/tests/runtime_utils/testinterface.go
  runtime/tests/runtime_utils/testledger.go
  runtime/tests/utils/utils.go
  tools/storage-explorer/go.mod
  tools/storage-explorer/go.sum
  version.go
Labels: Feature

#3503 Migrate capability values targeting storage paths
  migrations/capcons/capabilitymigration.go
  migrations/capcons/migration_test.go
Labels: Improvement
