Repository onflow/cadence, pull requests merged in 2024-04, with the labels that each got.

#3203 Properly handle `Never` type argument to `Capabilities.get`
  runtime/capabilities_test.go
  runtime/stdlib/account.go
Labels: Bugfix

#3208 Add `TypeArgumentsCheck`s to certain builtin functions
  runtime/capabilities_test.go
  runtime/sema/account.go
  runtime/stdlib/random.go
  runtime/tests/checker/account_test.go
  runtime/tests/checker/builtinfunctions_test.go
Labels: Bugfix

#3211 Improve Cadence 1.0 state migration
  migrations/entitlements/migration_test.go
  migrations/legacy_character_value.go
  migrations/legacy_intersection_type.go
  migrations/legacy_primitivestatic_type.go
  migrations/legacy_reference_type.go
  migrations/legacy_string_value.go
  migrations/legacy_test.go
  migrations/migration.go
  migrations/migration_test.go
  migrations/statictypes/account_type_migration_test.go
  migrations/statictypes/intersection_type_migration_test.go
  migrations/statictypes/statictype_migration_test.go
  migrations/string_normalization/migration_test.go
Labels: Bugfix, Improvement

#3176 Proper type checking for resource use after validation on two-value transfers
  runtime/sema/check_variable_declaration.go
  runtime/sema/checker.go
  runtime/tests/checker/access_test.go
  runtime/tests/checker/resources_test.go
  runtime/tests/interpreter/resources_test.go
Labels: Bugfix

#3213 Convert references based on borrow type
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
  runtime/runtime_test.go
  runtime/tests/interpreter/attachments_test.go
Labels: Bugfix

#3205 Fix migration of built-in types
  migrations/statictypes/statictype_migration.go
  migrations/statictypes/statictype_migration_test.go
  runtime/interpreter/primitivestatictype.go
Labels: Bugfix

#3181 Resource Reference Invalidation Improvements
  migrations/statictypes/account_type_migration_test.go
  runtime/convertValues.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/simplecompositevalue.go
  runtime/interpreter/value.go
  runtime/interpreter/value_account.go
  runtime/interpreter/value_account_accountcapabilities.go
  runtime/interpreter/value_account_capabilities.go
  runtime/interpreter/value_account_contracts.go
  runtime/interpreter/value_account_inbox.go
  runtime/interpreter/value_account_storage.go
  runtime/interpreter/value_account_storagecapabilities.go
  runtime/interpreter/value_accountcapabilitycontroller.go
  runtime/interpreter/value_authaccount_keys.go
  runtime/interpreter/value_capability.go
  runtime/interpreter/value_function.go
  runtime/interpreter/value_link.go
  runtime/interpreter/value_pathcapability.go
  runtime/interpreter/value_placeholder.go
  runtime/interpreter/value_storagecapabilitycontroller.go
  runtime/stdlib/log.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/resources_test.go
  runtime/tests/interpreter/values_test.go
  runtime/tests/utils/utils.go
Labels: Bugfix

#3212 Fix built-in type import
  runtime/convertTypes.go
  runtime/convertValues_test.go
Labels: Bugfix

#3216 Fix dereferencing non-reference type
  runtime/sema/check_unary_expression.go
  runtime/tests/checker/reference_test.go
Labels: Bugfix

#3170 Use atree readonly iterators when mutation of values is not needed
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
Labels: Improvement, Performance, E&V Team

#3221 remove ability to dereference arrays or dicts of structs
  runtime/sema/check_unary_expression.go
  runtime/sema/type.go
  runtime/tests/checker/reference_test.go
  runtime/tests/interpreter/reference_test.go
Labels: Bugfix, Language Breaking Change

#3224 Check resource loss in `CompositeValue.RemoveField`
  runtime/interpreter/value.go
Labels: Improvement

#3048 Atree register inlining for v1.0
  go.mod
  go.sum
  migrations/entitlements/migration.go
  migrations/entitlements/migration_test.go
  migrations/legacy_character_value.go
  migrations/legacy_intersection_type.go
  migrations/legacy_primitivestatic_type.go
  migrations/legacy_reference_type.go
  migrations/legacy_string_value.go
  migrations/migration.go
  migrations/migration_test.go
  migrations/statictypes/account_type_migration_test.go
  migrations/statictypes/intersection_type_migration_test.go
  migrations/string_normalization/migration_test.go
  runtime/account_test.go
  runtime/cmd/decode-state-values/main.go
  runtime/convertValues.go
  runtime/interface.go
  runtime/interpreter/decode.go
  runtime/interpreter/deepcopyremove_test.go
  runtime/interpreter/encode.go
  runtime/interpreter/encoding_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_invocation.go
  runtime/interpreter/interpreter_statement.go
  runtime/interpreter/interpreter_tracing_test.go
  runtime/interpreter/sharedstate.go
  runtime/interpreter/simplecompositevalue.go
  runtime/interpreter/statictype.go
  runtime/interpreter/storage.go
  runtime/interpreter/storage_test.go
  runtime/interpreter/storagemap.go
  runtime/interpreter/storagemapkey.go
  runtime/interpreter/stringatreevalue.go
  runtime/interpreter/value.go
  runtime/interpreter/value_accountcapabilitycontroller.go
  runtime/interpreter/value_capability.go
  runtime/interpreter/value_function.go
  runtime/interpreter/value_link.go
  runtime/interpreter/value_pathcapability.go
  runtime/interpreter/value_placeholder.go
  runtime/interpreter/value_storagecapabilitycontroller.go
  runtime/interpreter/value_test.go
  runtime/interpreter/walk.go
  runtime/runtime_memory_metering_test.go
  runtime/runtime_test.go
  runtime/stdlib/account.go
  runtime/storage.go
  runtime/storage_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/values_test.go
  runtime/tests/runtime_utils/testinterface.go
  runtime/tests/runtime_utils/testledger.go
  runtime/tests/utils/utils.go
Labels: Improvement

#3226 Check resource loss in all variable assignments
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/variable.go
Labels: Improvement

#3231 Introduce a dedicated error for unreferenced slabs and expose the IDs
  migrations/migration_test.go
  runtime/storage.go
Labels: Improvement

#3230 Improve atree register inlining v1.0
  migrations/migration.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value.go
Labels: Improvement

#3228 Merge v0.42 into v0.42 atree register inlining feature branch
  go.mod
  go.sum
  npm-packages/cadence-parser/package.json
  runtime/cmd/parse/main.go
  runtime/contract_update_validation_test.go
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_statement.go
  runtime/interpreter/value.go
  runtime/parser/errors.go
  runtime/runtime_test.go
  runtime/sema/check_invocation_expression.go
  runtime/sema/check_swap.go
  runtime/sema/check_switch.go
  runtime/sema/errors.go
  runtime/sema/errors_test.go
  runtime/stdlib/account.go
  runtime/stdlib/contract_update_validation.go
  runtime/stdlib/type-comparator.go
  runtime/storage_test.go
  runtime/tests/checker/attachments_test.go
  runtime/tests/checker/events_test.go
  runtime/tests/checker/swap_test.go
  runtime/tests/checker/switch_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/resources_test.go
  version.go
Labels: Chore

#3234 Handle missing type arguments in type argument checks
  runtime/sema/account.go
  runtime/sema/type.go
  runtime/stdlib/random.go
  runtime/stdlib/range.go
  runtime/tests/checker/account_test.go
  runtime/tests/checker/arrays_dictionaries_test.go
  runtime/tests/checker/builtinfunctions_test.go
  runtime/tests/checker/range_value_test.go
Labels: Bugfix

#3237 Port #3231 to v0.42
  runtime/storage.go
Labels: Improvement

#3236 Clear `inAssignment` when recursing into subexpressions
  runtime/sema/check_assignment.go
  runtime/sema/check_member_expression.go
  runtime/tests/checker/entitlements_test.go
Labels: Bugfix

#3227 Move conflicting dictionary key to new dictionary in unique storage path
  migrations/capcons/migration_test.go
  migrations/entitlements/migration_test.go
  migrations/migration.go
  migrations/migration_reporter.go
  migrations/migration_test.go
  migrations/statictypes/account_type_migration_test.go
  migrations/statictypes/composite_type_migration_test.go
  migrations/statictypes/intersection_type_migration_test.go
  migrations/statictypes/statictype_migration_test.go
  migrations/string_normalization/migration_test.go
Labels: Improvement

#3223 Bump onflow/atree to latest version in feature/atree-register-inlining-v1.0
  go.mod
  go.sum
Labels: Chore

#3240 Improve dictionary key conflict handling
  migrations/capcons/migration_test.go
  migrations/entitlements/migration_test.go
  migrations/migration.go
  migrations/migration_reporter.go
  migrations/migration_test.go
  migrations/statictypes/account_type_migration_test.go
  migrations/statictypes/composite_type_migration_test.go
  migrations/statictypes/intersection_type_migration_test.go
  migrations/statictypes/statictype_migration_test.go
  migrations/string_normalization/migration_test.go
  runtime/parser/lexer/lexer.go
Labels: Bugfix, Improvement

#3235 Introduce special self-variable
  runtime/cmd/execute/debugger.go
  runtime/debugger_test.go
  runtime/environment.go
  runtime/interpreter/globalvariables.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/interpreter_import.go
  runtime/interpreter/interpreter_invocation.go
  runtime/interpreter/interpreter_transaction.go
  runtime/interpreter/sharedstate.go
  runtime/interpreter/simplecompositevalue.go
  runtime/interpreter/value.go
  runtime/interpreter/value_function.go
  runtime/interpreter/value_string.go
  runtime/interpreter/variable.go
  runtime/interpreter/variable_activations.go
  runtime/repl.go
  runtime/runtime_test.go
  runtime/stdlib/builtin_test.go
  runtime/stdlib/crypto.go
  runtime/stdlib/test.go
  runtime/tests/interpreter/arithmetic_test.go
  runtime/tests/interpreter/bitwise_test.go
  runtime/tests/interpreter/builtinfunctions_test.go
  runtime/tests/interpreter/composite_value_test.go
  runtime/tests/interpreter/container_mutation_test.go
  runtime/tests/interpreter/dynamic_casting_test.go
  runtime/tests/interpreter/enum_test.go
  runtime/tests/interpreter/equality_test.go
  runtime/tests/interpreter/fixedpoint_test.go
  runtime/tests/interpreter/if_test.go
  runtime/tests/interpreter/import_test.go
  runtime/tests/interpreter/integers_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/metatype_test.go
  runtime/tests/interpreter/path_test.go
  runtime/tests/interpreter/range_value_test.go
  runtime/tests/interpreter/reference_test.go
  runtime/tests/interpreter/runtimetype_test.go
  runtime/tests/interpreter/string_test.go
  runtime/tests/interpreter/transactions_test.go
Labels: Bugfix

#3251 Improve supported entitlements
  migrations/entitlements/migration.go
  runtime/interpreter/interpreter.go
  runtime/sema/access.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_function.go
  runtime/sema/check_member_expression.go
  tools/storage-explorer/go.sum
Labels: Improvement

#3254 Bump atree version in master branch
  go.mod
  go.sum
Labels: Chore

#3255 Bump atree version in feature/atree-register-inlining-v0.42
  go.mod
  go.sum
Labels: Chore

#3256 Bump atree version in feature/atree-register-inlining-v1.0
  go.mod
  go.sum
Labels: Chore

#3258 Update atree register inlining v0.42 feature branch
  npm-packages/cadence-parser/package.json
  runtime/storage.go
  version.go
Labels: Chore

#3260 Add a test case for non-public interface members
  runtime/runtime_test.go
Labels: Testing

#3267 Fix resource-loss check in dictionary set-key
  runtime/interpreter/value.go
  runtime/tests/interpreter/resources_test.go
Labels: Bugfix

#3270 Merge master into atree register inlining v1.0 branch
  npm-packages/cadence-parser/package.json
  runtime/interpreter/value.go
  runtime/runtime_test.go
  runtime/tests/interpreter/resources_test.go
  tools/staged-contracts-report-printer/main.go
  tools/storage-explorer/go.mod
  tools/storage-explorer/go.sum
  version.go
Labels: Chore

#3274 Improve conformance mismatch error
  runtime/contract_update_validation_test.go
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validator.go
  runtime/stdlib/contract_update_validation.go
Labels: Improvement

#3277 Further improve conformance error by including location
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validator.go
  runtime/stdlib/contract_update_validation.go
Labels: Improvement

#3252 Implement FLIP 242
  migrations/entitlements/migration_test.go
  runtime/capabilities_test.go
  runtime/capabilitycontrollers_test.go
  runtime/entitlements_test.go
  runtime/interpreter/errors.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/value_capability.go
  runtime/runtime_test.go
  runtime/sema/account.cdc
  runtime/sema/account.gen.go
  runtime/stdlib/account.go
  runtime/storage_test.go
  runtime/tests/checker/account_test.go
Labels: Language Breaking Change, Feature

#3247 Implement FLIP 262
  runtime/ast/access.go
  runtime/runtime_test.go
  runtime/sema/access.go
  runtime/sema/check_composite_declaration.go
  runtime/tests/checker/conformance_test.go
  runtime/tests/checker/entitlements_test.go
  runtime/tests/interpreter/entitlements_test.go
Labels: Language Breaking Change, Improvement

#3272 Fix optional type ID ambiguity and migrate types
  migrations/entitlements/migration_test.go
  migrations/legacy_optional_type.go
  migrations/legacy_test.go
  migrations/migration.go
  migrations/migration_test.go
  migrations/statictypes/account_type_migration_test.go
  migrations/statictypes/intersection_type_migration_test.go
  migrations/statictypes/statictype_migration.go
  migrations/statictypes/statictype_migration_test.go
  migrations/string_normalization/migration_test.go
  runtime/sema/type.go
  types_test.go
Labels: Bugfix

#3278 Remove unused parameter
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validator.go
Labels: Improvement

#3232 Cache results of entitlement type conversion
  migrations/cache.go
  migrations/entitlements/migration.go
  migrations/entitlements/migration_test.go
Labels: Improvement

#3266 Improve supported entitlements and entitlements inferrence in migration
  migrations/entitlements/migration.go
  migrations/entitlements/migration_test.go
  runtime/interpreter/interpreter.go
  runtime/interpreter/interpreter_expression.go
  runtime/interpreter/value.go
  runtime/sema/access.go
  runtime/sema/check_composite_declaration.go
  runtime/sema/check_function.go
  runtime/sema/check_member_expression.go
  runtime/sema/entitlementset.go
  runtime/sema/entitlementset_test.go
  runtime/sema/errors.go
  runtime/sema/type.go
  runtime/sema/type_tags.go
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validator.go
Labels: Language Breaking Change

#3273 Adding staged contracts migration output JSON from Apr 17 to migratio…
  migrations_data/staged-contracts-report-2024-04-17T20:05:50.000Z-testnet.json
  migrations_data/staged-contracts-report-2024-04-17T20:05:50.000Z-testnet.md
Labels: Chore

#3280 Adjust branches of downstream dependency checks
  .github/workflows/downstream.yml
Labels: Chore

#3284 Handle account types in contract update validator
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validation_test.go
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validator.go
Labels: Bugfix

#3283 Fix restricted typed field updates
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validation_test.go
  runtime/stdlib/cadence_v0.42_to_v1_contract_upgrade_validator.go
Labels: Bugfix

#3285 Adding migration result for Testnet state from Apr 24
  migrations_data/staged-contracts-report-2024-04-24T07-50-00Z-testnet.json
  migrations_data/staged-contracts-report-2024-04-24T07-50-00Z-testnet.md
Labels: Chore

#3276 add backwards compatibility to old JSON decodings
  encoding/json/decode.go
  encoding/json/encoding_test.go
  runtime/common/memorykind.go
  runtime/common/memorykind_string.go
  runtime/common/metering.go
  types.go
  types_test.go
Labels: Feature

#3204 Add additional fields to account key added event
  runtime/account_test.go
  runtime/stdlib/account.go
  runtime/stdlib/flow.go
Labels: Improvement

#3292 Update update tool config
  tools/update/config.yaml
Labels: Chore

#3298 Add runtime check for transaction value moves
  runtime/interpreter/simplecompositevalue.go
  runtime/runtime_test.go
Labels: Improvement

#3294 Bump atree version in feature/atree-register-inlining-v0.42
  go.mod
  go.sum
  version.go
Labels: Chore

#3290 Unexport fields to prevent access by index
  encoding/ccf/ccf_test.go
  encoding/ccf/encode.go
  encoding/ccf/service_events_test.go
  encoding/ccf/traverse_value.go
  encoding/json/encode.go
  encoding/json/encoding_test.go
  runtime/account_test.go
  runtime/attachments_test.go
  runtime/contract_test.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/crypto_test.go
  runtime/deployment_test.go
  runtime/interpreter/value.go
  runtime/predeclaredvalues_test.go
  runtime/program_params_validation_test.go
  runtime/resourcedictionary_test.go
  runtime/runtime_test.go
  types.go
  values.go
  values_test.go
Labels: Improvement, Go API Breaking Change

#3291 Remove Value.ToGoValue and NewValue
  helpers.go
  types.go
  values.go
Labels: Go API Breaking Change

#3300 Add predicate function and test for atree's PersistentSlabStorage.FixLoadedBrokenReferences
  migrations/broken_dictionary.go
  migrations/migration_test.go
  migrations/testdata/missing-slabs-payloads.csv
  runtime/tests/runtime_utils/testledger.go
Labels: Improvement
