Repository onflow/cadence, pull requests merged in 2025-02, with the labels that each got.

#3753 Update config of update tool
  tools/update/config.yaml
Labels: Chore

#3756 [Compiler] Compile if-let
  bbq/compiler/codegen.go
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/function.go
  bbq/opcode/instructions.go
  bbq/opcode/instructions.yml
  bbq/opcode/opcode.go
  bbq/opcode/opcode_string.go
  bbq/vm/test/vm_test.go
  bbq/vm/vm.go
Labels: Feature

#3755 [Compiler] Improve compiler tests
  bbq/compiler/compiler_test.go
Labels: Improvement

#3757 [Compiler] Compile switch
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/vm/test/vm_test.go
Labels: Feature

#3741 [Compiler] Support accessing `result` variable inside post conditions
  ast/variable_declaration.go
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/desugar.go
  bbq/compiler/extended_elaboration.go
  bbq/compiler/native_functions.go
  bbq/vm/test/utils.go
  bbq/vm/test/vm_test.go
  sema/check_function.go
  sema/check_transaction_declaration.go
  sema/elaboration.go
Labels: Feature

#3754 [Compiler] Improve default functions existence with conditions
  bbq/compiler/desugar.go
  bbq/compiler/extended_elaboration.go
  bbq/vm/test/utils.go
  bbq/vm/test/vm_test.go
  sema/simple_type.go
  sema/type.go
Labels: Improvement

#3707 Machine readable syntax specification
  docs/syntax/Cadence.syntax
  docs/syntax/Syntax Notation.md
Labels: Documentation

#3759 [Compiler] Document stack effects of instructions in their description
  bbq/opcode/instructions.go
  bbq/opcode/instructions.yml
Labels: Documentation

#3749 Handle command failures in update tool
  tools/update/main.ts
Labels: Improvement

#3748 Decouple interpreter values from interpreter – Part 2
  interpreter/for_test.go
  interpreter/interpreter.go
  interpreter/value.go
  interpreter/value_array.go
  interpreter/value_composite.go
  interpreter/value_ephemeral_reference.go
  interpreter/value_storage_reference.go
  interpreter/value_string.go
Labels: Improvement, Technical Debt

#3751 Decouple interpreter values from interpreter – Part 3
  interpreter/interface.go
  interpreter/interpreter.go
  interpreter/interpreter_expression.go
  interpreter/interpreter_statement.go
  interpreter/misc_test.go
  interpreter/simplecompositevalue.go
  interpreter/value.go
  interpreter/value_accountcapabilitycontroller.go
  interpreter/value_address.go
  interpreter/value_array.go
  interpreter/value_bool.go
  interpreter/value_capability.go
  interpreter/value_character.go
  interpreter/value_composite.go
  interpreter/value_dictionary.go
  interpreter/value_ephemeral_reference.go
  interpreter/value_fix64.go
  interpreter/value_function.go
  interpreter/value_int.go
  interpreter/value_int128.go
  interpreter/value_int16.go
  interpreter/value_int256.go
  interpreter/value_int32.go
  interpreter/value_int64.go
  interpreter/value_int8.go
  interpreter/value_link.go
  interpreter/value_nil.go
  interpreter/value_number.go
  interpreter/value_path.go
  interpreter/value_pathcapability.go
  interpreter/value_placeholder.go
  interpreter/value_published.go
  interpreter/value_range.go
  interpreter/value_some.go
  interpreter/value_storage_reference.go
  interpreter/value_storagecapabilitycontroller.go
  interpreter/value_string.go
  interpreter/value_type.go
  interpreter/value_ufix64.go
  interpreter/value_uint.go
  interpreter/value_uint128.go
  interpreter/value_uint16.go
  interpreter/value_uint256.go
  interpreter/value_uint32.go
  interpreter/value_uint64.go
  interpreter/value_uint8.go
  interpreter/value_void.go
  interpreter/value_word128.go
  interpreter/value_word16.go
  interpreter/value_word256.go
  interpreter/value_word32.go
  interpreter/value_word64.go
  interpreter/value_word8.go
  interpreter/variable.go
  runtime/convertValues.go
  stdlib/account.go
  stdlib/test.go
Labels: Improvement, Go API Breaking Change

#3767 [Compiler] Support basic casting operations in VM
  bbq/compiler/compiler.go
  bbq/opcode/castkind.go
  bbq/opcode/instruction.go
  bbq/opcode/instructions.go
  bbq/opcode/instructions.yml
  bbq/opcode/opcode.go
  bbq/opcode/opcode_string.go
  bbq/opcode/print_test.go
  bbq/vm/errors.go
  bbq/vm/test/vm_test.go
  bbq/vm/types.go
  bbq/vm/value.go
  bbq/vm/value_some.go
  bbq/vm/vm.go
Labels: Feature

#3771 [Compiler] Add tests for compiling casting expressions to casting instructions
  bbq/compiler/compiler_test.go
Labels: Testing

#3775 [v1.3] Port internal fixes
  ast/visitor.go
  interpreter/interface_test.go
  interpreter/interpreter.go
  interpreter/interpreter_expression.go
  interpreter/misc_test.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/empty.go
  runtime/runtime_test.go
  sema/check_function.go
  sema/function_test.go
  sema/gen/main.go
Labels: Bugfix

#3776 Port internal fixes to master
  ast/visitor.go
  interpreter/interface_test.go
  interpreter/interpreter.go
  interpreter/interpreter_expression.go
  interpreter/misc_test.go
  npm-packages/cadence-parser/package.json
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/empty.go
  runtime/runtime_test.go
  sema/check_function.go
  sema/function_test.go
  sema/gen/main.go
  version.go
Labels: Bugfix

#3778 [v1.3] Port internal fix
  activations/activations.go
  interpreter/interpreter.go
  interpreter/interpreter_expression.go
  interpreter/misc_test.go
Labels: Bugfix

#3779 [v1.3] Port internal fix
  activations/activations.go
  interpreter/interpreter.go
  interpreter/interpreter_expression.go
  interpreter/misc_test.go
Labels: Bugfix

#3780 Fix and improve compat suite
  compat/README.md
  compat/main.py
  compat/suite/dapper-labs-nba-smart-contracts.yaml
  compat/suite/dapper-labs-nfl-smart-contracts.yaml
  compat/suite/flow-core-contracts.yaml
  compat/suite/flow-ft.yaml
  compat/suite/flow-nft.yaml
  compat/suite/green-goo-dao-flow-utils.yaml
  compat/suite/index.yaml
Labels: Bugfix, Improvement

#3763 [Compiler] Support compilation for before statements
  bbq/compiler/desugar.go
  bbq/compiler/native_functions.go
  bbq/vm/test/vm_test.go
  bbq/vm/value_int.go
Labels: Feature

#3760 address latest comments on PR
  docs/syntax/Cadence.syntax
Labels: Improvement

#3786 [Compiler] Test compilation of currently supported features
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
Labels: Bugfix, Improvement, Testing

#3788 [Compiler] Add compiler tests for default functions and function conditions
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/global.go
  bbq/compiler/native_functions.go
  bbq/vm/test/ft_test.go
Labels: Testing

#3787 [Compiler] Fix break in switch
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/control_flow.go
  bbq/vm/test/vm_test.go
Labels: Bugfix

#3789 [Compiler] Implement scoping
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/vm/test/vm_test.go
  sema/checker.go
Labels: Bugfix, Feature

#3790 Make the number interfaces in the value-package generic
  interpreter/value_int.go
  values/value_int.go
  values/value_integer.go
  values/value_number.go
Labels: Improvement

#3793 [Compiler] Compile for-loops
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/native_functions.go
  bbq/opcode/instructions.go
  bbq/opcode/instructions.yml
  bbq/opcode/opcode.go
  bbq/opcode/opcode_string.go
  bbq/vm/test/vm_test.go
  bbq/vm/value.go
  bbq/vm/value_array.go
  bbq/vm/vm.go
Labels: Feature

#3794 [Compiler] Re-enable skipped tests
  bbq/compiler/compiler_test.go
Labels: Technical Debt

#3795 [Compiler] Compile conditional expression
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/vm/test/vm_test.go
Labels: Feature

#3796 [Compiler] Compile boolean operators
  bbq/compiler/codegen.go
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/opcode/instructions.go
  bbq/opcode/instructions.yml
  bbq/opcode/opcode.go
  bbq/opcode/opcode_string.go
  bbq/vm/test/vm_test.go
  bbq/vm/value_conversions.go
  bbq/vm/vm.go
Labels: Feature

#3799 [Compiler] Compile remaining unary operators
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/opcode/instructions.go
  bbq/opcode/instructions.yml
  bbq/opcode/opcode.go
  bbq/opcode/opcode_string.go
  bbq/opcode/print_test.go
  bbq/vm/test/vm_test.go
  bbq/vm/value_int.go
  bbq/vm/value_number.go
  bbq/vm/value_ufix64.go
  bbq/vm/vm.go
Labels: Feature, Testing

#3801 [Compiler] Compile transaction pre/post conditions
  bbq/commons/constants.go
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/desugar.go
  bbq/vm/test/vm_test.go
  bbq/vm/vm.go
  sema/check_composite_declaration.go
  sema/check_transaction_declaration.go
Labels: Feature
