Repository onflow/cadence, pull requests merged in 2025-05, with the labels that each got.

#3914 [Compiler] Improve and fix event emission
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/opcode/instructions.go
  bbq/opcode/instructions.yml
  bbq/opcode/print_test.go
  bbq/vm/config.go
  bbq/vm/test/vm_test.go
  bbq/vm/vm.go
Labels: Bugfix, Improvement

#3915 [Compiler] Skip events compilation
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/test_utils/utils.go
  bbq/vm/test/utils.go
  bbq/vm/test/vm_test.go
  bbq/vm/vm.go
Labels: Technical Debt

#3918 [Compiler] Fix argument compilation: transfer to parameter type, not argument type
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/desugar.go
  interpreter/interpreter_expression.go
  sema/check_invocation_expression.go
  sema/elaboration.go
Labels: Bugfix

#3916 [Compiler] Unify emission of event value and event fields, enable event emission in VM environment
  bbq/vm/config.go
  bbq/vm/test/ft_test.go
  bbq/vm/test/interpreter_test.go
  bbq/vm/test/vm_test.go
  bbq/vm/vm.go
  cmd/cmd.go
  interpreter/attachments_test.go
  interpreter/condition_test.go
  interpreter/interface.go
  interpreter/interpreter.go
  interpreter/interpreter_statement.go
  interpreter/misc_test.go
  interpreter/resources_test.go
  interpreter/value_composite.go
  runtime/events.go
  runtime/handlers.go
  runtime/runtime_test.go
  runtime/vm_environment.go
  test_utils/test_utils.go
Labels: Feature, Technical Debt

#3917 [Compiler] Enable conditions test
  bbq/compiler/compiler.go
  bbq/compiler/desugar.go
  bbq/compiler/desugared_elaboration.go
  bbq/constant/constant.go
  bbq/constant/kind.go
  bbq/constant/kind_string.go
  bbq/contract.go
  bbq/vm/linker.go
  bbq/vm/test/ft_test.go
  bbq/vm/test/utils.go
  bbq/vm/test/vm_test.go
  bbq/vm/vm.go
  interpreter/character_test.go
  interpreter/condition_test.go
  interpreter/interpreter_test.go
  sema/type.go
  test_utils/test_utils.go
Labels: Improvement, Testing

#3921 [Compiler] Run more tests with the compiler and VM
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/vm/errors.go
  bbq/vm/vm.go
  interpreter/condition_test.go
  interpreter/container_mutation_test.go
  interpreter/contract_test.go
  interpreter/declaration_test.go
  interpreter/dynamic_casting_test.go
  interpreter/interpreter.go
  test_utils/interpreter_utils/values.go
  test_utils/test_utils.go
Labels: Technical Debt

#3923 [Compiler] Run for-statement tests with compiler
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/desugared_elaboration.go
  bbq/vm/vm.go
  interpreter/for_test.go
  interpreter/value_ephemeral_reference.go
  interpreter/value_storage_reference.go
  interpreter/value_string.go
Labels: Testing

#3924 [Compiler] Refactor test utility functions
  bbq/compiler/desugared_elaboration.go
  bbq/test_utils/utils.go
  bbq/vm/test/utils.go
  interpreter/account_test.go
  interpreter/condition_test.go
  interpreter/function_test.go
  interpreter/import_test.go
  interpreter/interpreter.go
  interpreter/interpreter_test.go
  interpreter/member_test.go
  interpreter/misc_test.go
  interpreter/reference_test.go
  test_utils/common_utils/utils.go
  test_utils/sema_utils/utils.go
  test_utils/test_utils.go
Labels: Technical Debt

#3926 [Compiler] Run `interpreter/misc_test.go` with compiler
  bbq/commons/constants.go
  bbq/commons/types.go
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/vm/errors.go
  bbq/vm/test/vm_test.go
  bbq/vm/value_array.go
  bbq/vm/value_capability.go
  bbq/vm/value_dictionary.go
  bbq/vm/value_function.go
  bbq/vm/value_optional.go
  bbq/vm/vm.go
  interpreter/interpreter_expression.go
  interpreter/misc_test.go
  interpreter/value_function.go
  interpreter/value_nil.go
  interpreter/value_optional.go
  interpreter/value_some.go
  runtime/convertValues.go
  test_utils/interpreter_utils/values.go
  test_utils/test_utils.go
Labels: Improvement, Testing

#3928 [Compiler] Enable more misc tests
  bbq/compiler/compiler.go
  interpreter/misc_test.go
  interpreter/values_test.go
  test_utils/test_utils.go
Labels: Testing

#3927 Improve error wrapping of runtime interface calls
  runtime/code.go
  runtime/events.go
  runtime/external.go
  runtime/handlers.go
  runtime/location.go
  runtime/runtime.go
  runtime/slabindex.go
  runtime/transaction_executor.go
  runtime/validation.go
  stdlib/account.go
  stdlib/block.go
  stdlib/bls.go
  stdlib/hashalgorithm.go
  stdlib/log.go
  stdlib/publickey.go
  stdlib/random.go
Labels: Technical Debt

#3929 Improve computation metering interface
  common/metering.go
  errors/errors.go
  interpreter/account_test.go
  interpreter/config.go
  interpreter/interface.go
  interpreter/interpreter.go
  interpreter/interpreter_statement.go
  interpreter/metering_test.go
  interpreter/value_array.go
  interpreter/value_composite.go
  interpreter/value_dictionary.go
  interpreter/value_string.go
  interpreter/value_test.go
  old_parser/expression.go
  old_parser/expression_test.go
  old_parser/lexer/lexer.go
  old_parser/parser_test.go
  parser/expression.go
  parser/expression_test.go
  parser/parser_test.go
  runtime/empty.go
  runtime/environment.go
  runtime/external.go
  runtime/handlers.go
  runtime/interface.go
  runtime/runtime_memory_metering_test.go
  runtime/runtime_test.go
  runtime/storage.go
  stdlib/rlp.go
  test_utils/runtime_utils/testinterface.go
Labels: Technical Debt

#3930 Port non-compiler/VM changes from feature branch to master
  interpreter/account_test.go
  interpreter/character_test.go
  interpreter/condition_test.go
  interpreter/container_mutation_test.go
  interpreter/contract_test.go
  interpreter/declaration_test.go
  interpreter/dynamic_casting_test.go
  interpreter/for_test.go
  interpreter/function_test.go
  interpreter/if_test.go
  interpreter/import_test.go
  interpreter/interface_test.go
  interpreter/interpreter.go
  interpreter/interpreter_expression.go
  interpreter/interpreter_test.go
  interpreter/member_test.go
  interpreter/misc_test.go
  interpreter/reference_test.go
  interpreter/value_ephemeral_reference.go
  interpreter/value_function.go
  interpreter/value_nil.go
  interpreter/value_optional.go
  interpreter/value_some.go
  interpreter/value_storage_reference.go
  interpreter/value_string.go
  interpreter/values_test.go
  runtime/convertValues.go
  runtime/runtime_test.go
  sema/type.go
  test_utils/common_utils/utils.go
  test_utils/interpreter_utils/values.go
  test_utils/sema_utils/utils.go
  test_utils/test_utils.go
Labels: Chore

#3933 [Compiler] Pass `vm.Context` instead of `vm.Config` to contract function handler
  bbq/vm/config.go
  bbq/vm/context.go
  bbq/vm/linker.go
  bbq/vm/test/ft_test.go
  bbq/vm/test/runtime_test.go
  bbq/vm/test/utils.go
  bbq/vm/test/vm_bench_test.go
  bbq/vm/test/vm_test.go
  bbq/vm/tracer.go
  runtime/vm_environment.go
Labels: Technical Debt

#3932 [Compiler] Fix compilation of inherited conditions with different parameters
  bbq/compiler/compiler.go
  bbq/compiler/desugar.go
  bbq/vm/test/vm_test.go
  interpreter/misc_test.go
Labels: Improvement

#3934 [Compiler] Refactor function invocation on vm
  bbq/vm/context.go
  bbq/vm/linker.go
  bbq/vm/test/ft_test.go
  bbq/vm/test/utils.go
  bbq/vm/test/vm_bench_test.go
  bbq/vm/test/vm_test.go
  bbq/vm/value_function.go
  bbq/vm/vm.go
  interpreter/interface.go
  interpreter/interpreter.go
  interpreter/misc_test.go
  interpreter/path_test.go
  runtime/contract_function_executor.go
  test_utils/test_utils.go
Labels: Improvement

#3935 [Compiler] Add receiver validation for bound functions
  bbq/vm/context.go
  bbq/vm/reference_tracking.go
  bbq/vm/value_function.go
  bbq/vm/vm.go
  interpreter/interface.go
  interpreter/interpreter.go
  interpreter/interpreter_expression.go
  interpreter/interpreter_statement.go
  interpreter/reference_test.go
  interpreter/value_array.go
  interpreter/value_composite.go
  interpreter/value_dictionary.go
  interpreter/value_function.go
  interpreter/value_reference.go
  interpreter/value_storage_reference.go
  interpreter/variable.go
Labels: Improvement

#3939 [Compiler] Compile position info as a line-number table
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/function.go
  bbq/function.go
  bbq/line_number_table.go
  bbq/vm/test/vm_test.go
  bbq/vm/vm.go
  interpreter/dynamic_casting_test.go
Labels: Improvement

#3940 Update linter, lint
  .github/workflows/ci.yml
  .golangci.yml
  Makefile
  ast/access.go
  cmd/decode-state-values/main.go
  common/address.go
  interpreter/builtinfunctions_test.go
  interpreter/interpreter.go
  interpreter/statictype.go
  interpreter/value_function.go
  runtime/capabilitycontrollers_test.go
  sema/capability_test.go
  sema/gen/golden_test.go
  sema/resourceinvalidationkind.go
  sema/type.go
  tools/constructorcheck/go.mod
  tools/constructorcheck/go.sum
  tools/golangci-lint/Makefile
  tools/golangci-lint/go.mod
  tools/golangci-lint/go.sum
  tools/golangci-lint/main.go
  tools/maprange/go.mod
  tools/maprange/go.sum
  tools/unkeyed/go.mod
  tools/unkeyed/go.sum
  types.go
  utils/version/main.go
Labels: Chore

#3942 Refactor type constructors
  interpreter/interpreter.go
Labels: Improvement, Technical Debt

#3941 [Compiler] Run most metatype tests and all interface tests with compiler/VM
  activations/activations.go
  bbq/vm/config.go
  bbq/vm/native_functions.go
  bbq/vm/test/utils.go
  bbq/vm/test/vm_test.go
  bbq/vm/vm.go
  cmd/execute/debugger.go
  interpreter/account_test.go
  interpreter/interface_test.go
  interpreter/metatype_test.go
  test_utils/test_utils.go
Labels: Improvement, Testing

#3943 Port non-compiler/VM changes from feature branch to master
  activations/activations.go
  cmd/execute/debugger.go
  interpreter/account_test.go
  interpreter/dynamic_casting_test.go
  interpreter/interface.go
  interpreter/interface_test.go
  interpreter/interpreter.go
  interpreter/interpreter_expression.go
  interpreter/interpreter_statement.go
  interpreter/metatype_test.go
  interpreter/misc_test.go
  interpreter/path_test.go
  interpreter/reference_test.go
  interpreter/string_test.go
  interpreter/value_address.go
  interpreter/value_array.go
  interpreter/value_character.go
  interpreter/value_composite.go
  interpreter/value_dictionary.go
  interpreter/value_function.go
  interpreter/value_number.go
  interpreter/value_path.go
  interpreter/value_reference.go
  interpreter/value_storage_reference.go
  interpreter/value_string.go
  interpreter/variable.go
  runtime/contract_function_executor.go
  sema/string_type.go
  sema/type.go
  test_utils/test_utils.go
Labels: Chore

#3945 [Compiler] Register type constructor functions in VM, run runtime-type tests with compiler/VM
  bbq/vm/config.go
  bbq/vm/native_functions.go
  bbq/vm/test/utils.go
  interpreter/runtimetype_test.go
  test_utils/test_utils.go
Labels: Improvement, Testing

#3947 [Compiler] Improve invocation of external functions and transactions
  bbq/vm/test/ft_test.go
  bbq/vm/test/interpreter_test.go
  bbq/vm/test/runtime_test.go
  bbq/vm/test/vm_test.go
  bbq/vm/value_function.go
  bbq/vm/vm.go
  interpreter/interpreter.go
  interpreter/transactions_test.go
  runtime/contract_function_executor.go
  runtime/transaction_executor.go
  test_utils/common_utils/utils.go
  test_utils/test_utils.go
Labels: Improvement, Testing

#3948 [Compiler] Enable arithmetic and bitwise tests to run with compiler/VM
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/constant/constant.go
  bbq/opcode/instruction.go
  bbq/vm/test/vm_test.go
  bbq/vm/vm.go
  interpreter/arithmetic_test.go
  interpreter/bitwise_test.go
  interpreter/builtinfunctions_test.go
  interpreter/interpreter.go
  interpreter/value_fix64.go
  interpreter/value_int.go
  interpreter/value_int128.go
  interpreter/value_int16.go
  interpreter/value_int256.go
  interpreter/value_int32.go
  interpreter/value_int64.go
  interpreter/value_int8.go
  interpreter/value_ufix64.go
  interpreter/value_uint.go
  interpreter/value_uint128.go
  interpreter/value_uint16.go
  interpreter/value_uint256.go
  interpreter/value_uint32.go
  interpreter/value_uint64.go
  interpreter/value_uint8.go
  interpreter/value_word128.go
  interpreter/value_word16.go
  interpreter/value_word256.go
  interpreter/value_word32.go
  interpreter/value_word64.go
  interpreter/value_word8.go
  sema/type.go
Labels: Bugfix, Improvement, Testing

#3949 [Compiler] Enable more interpreter tests to be run with the compiler / VM
  bbq/compiler/compiler.go
  bbq/constant/kind.go
  interpreter/builtinfunctions_test.go
  interpreter/equality_test.go
  interpreter/fixedpoint_test.go
  interpreter/integers_test.go
Labels: Improvement, Testing

#3953 [Compiler] Run more tests with compiler/vm
  bbq/compiler/desugar.go
  interpreter/declaration_test.go
  interpreter/dynamic_casting_test.go
  interpreter/entitlements_test.go
  interpreter/fib_test.go
  interpreter/fixedpoint_test.go
  interpreter/integers_test.go
  interpreter/invocation_test.go
  interpreter/misc_test.go
  interpreter/reference_test.go
  interpreter/struct_stringer_test.go
  interpreter/switch_test.go
  interpreter/transactions_test.go
Labels: Improvement

#3938 [Compiler] Run `resources-test` with the compiler
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/desugared_elaboration.go
  bbq/vm/vm.go
  interpreter/resources_test.go
  sema/check_unary_expression.go
  sema/elaboration.go
Labels: Improvement, Testing

#3956 [Compiler] Cache compiled programs
  runtime/checking_environment.go
  runtime/contract_update_test.go
  runtime/contract_update_validation_test.go
  runtime/empty.go
  runtime/environment.go
  runtime/external.go
  runtime/interface.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/storage_test.go
  runtime/vm_environment.go
  test_utils/runtime_utils/testinterface.go
Labels: Feature, Go API Breaking Change

#3957 [Compiler] Improve imports compilation for transitive dependencies
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
Labels: Improvement, Testing

#3958 Port non-compiler/VM changes from feature branch to master
  interpreter/declaration_test.go
  interpreter/dynamic_casting_test.go
  interpreter/entitlements_test.go
  interpreter/fib_test.go
  interpreter/fixedpoint_test.go
  interpreter/integers_test.go
  interpreter/invocation_test.go
  interpreter/misc_test.go
  interpreter/reference_test.go
  interpreter/resources_test.go
  interpreter/struct_stringer_test.go
  interpreter/switch_test.go
  interpreter/transactions_test.go
  runtime/checking_environment.go
  runtime/contract_update_test.go
  runtime/contract_update_validation_test.go
  runtime/empty.go
  runtime/environment.go
  runtime/external.go
  runtime/interface.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/storage_test.go
  sema/check_unary_expression.go
  sema/elaboration.go
  test_utils/runtime_utils/testinterface.go
Labels: Chore, Go API Breaking Change

#3961 Fix release action
  .github/workflows/release.yml
Labels: Chore

#3955 Improve value visitor: Only call checked visitor
  interpreter/visitor.go
Labels: Bugfix, Improvement

#3964 [Compiler] Remove dependency to `interpreter.Config` from VM
  bbq/vm/config.go
  bbq/vm/native_functions.go
  bbq/vm/test/ft_test.go
  bbq/vm/test/utils.go
  bbq/vm/test/vm_test.go
  bbq/vm/tracer.go
  bbq/vm/value_account_capabilities.go
  bbq/vm/value_account_storagecapabilities.go
  bbq/vm/value_composite.go
  interpreter/account_test.go
  interpreter/interface.go
  interpreter/interpreter.go
  interpreter/value_accountcapabilitycontroller.go
  interpreter/value_composite.go
  runtime/vm_environment.go
  stdlib/account.go
  test_utils/test_utils.go
Labels: Technical Debt

#3959 Error prompts
  errors/errors.go
  interpreter/errors.go
  interpreter/errors_test.go
  parser/errors.go
  parser/parser_test.go
  runtime/deployment_test.go
  runtime/error_test.go
  runtime/errors.go
  runtime/runtime_test.go
  sema/errors.go
Labels: Feedback

#3966 [v1.4] Port v1.4.1-rc.2
  ast/string_test.go
  interpreter/reference_test.go
  interpreter/value_storage_reference.go
  parser/declaration_test.go
  parser/expression.go
  parser/expression_test.go
  parser/parser_test.go
  pretty/print.go
  runtime/runtime_test.go
  version.go
Labels: Bugfix

#3969 Remove unreachable test cases
  interpreter/equality_test.go
Labels: Technical Debt

#3968 Port 1.4.1 to master
  ast/string_test.go
  interpreter/reference_test.go
  interpreter/value_storage_reference.go
  parser/declaration_test.go
  parser/expression.go
  parser/expression_test.go
  parser/parser_test.go
  pretty/print.go
  runtime/runtime_test.go
Labels: Bugfix

#3970 [v1.4] Fix version
  version.go
Labels: Chore

#3974 Ensure unbounded loops in parser eventually make progress
  cmd/lex/main.go
  parser/comment.go
  parser/comment_test.go
  parser/declaration.go
  parser/expression.go
  parser/function.go
  parser/lexer/lexer_test.go
  parser/lexer/state.go
  parser/parser.go
  parser/statement.go
  parser/transaction.go
  parser/type.go
Labels: Improvement

#3978 Add Raymond as code owner
  CODEOWNERS
Labels: Chore

#3980 Revert removal of storage format v1 support
  runtime/account_storage_v1.go
  runtime/account_storage_v2.go
  runtime/contract_function_executor.go
  runtime/contract_test.go
  runtime/runtime_memory_metering_test.go
  runtime/script_executor.go
  runtime/sharedstate_test.go
  runtime/storage.go
  runtime/storage_test.go
  runtime/transaction_executor.go
Labels: Feature, Storage Breaking Change

#3982 [Compiler] Implement `Number` types' methods and static functions
  bbq/commons/types.go
  bbq/compiler/compiler.go
  bbq/compiler/native_functions.go
  bbq/vm/native_functions.go
  bbq/vm/test/vm_test.go
  bbq/vm/value_number.go
  bbq/vm/vm.go
  interpreter/builtinfunctions_test.go
  interpreter/fixedpoint_test.go
  interpreter/integers_test.go
  interpreter/interpreter.go
  interpreter/value_fix64.go
  interpreter/value_int128.go
  interpreter/value_int16.go
  interpreter/value_int8.go
  interpreter/value_uint16.go
  interpreter/value_uint32.go
  interpreter/value_uint8.go
  interpreter/value_word8.go
  sema/string_type.go
  sema/type.go
Labels: Feature

#3983 [Compiler] Implement built-in methods and functions for `Address`
  bbq/vm/native_functions.go
  bbq/vm/test/utils.go
  bbq/vm/value_account_capabilities.go
  bbq/vm/value_account_storage.go
  bbq/vm/value_address.go
  bbq/vm/value_array.go
  bbq/vm/value_character.go
  bbq/vm/value_dictionary.go
  bbq/vm/value_number.go
  bbq/vm/value_optional.go
  bbq/vm/value_path.go
  bbq/vm/value_string.go
  bbq/vm/value_type.go
  interpreter/builtinfunctions_test.go
  interpreter/interpreter.go
  interpreter/value_address.go
Labels: Feature

#3984 [Compiler] Support optional chaining in compiler
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/vm/test/vm_test.go
  interpreter/misc_test.go
Labels: Feature

#3987 [Compiler] Compile second value assignment
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/desugared_elaboration.go
  bbq/opcode/instructions.go
  bbq/opcode/instructions.yml
  bbq/opcode/opcode.go
  bbq/opcode/opcode_string.go
  bbq/opcode/print_test.go
  bbq/vm/vm.go
  interpreter/misc_test.go
  interpreter/resources_test.go
Labels: Feature
