Repository onflow/cadence, pull requests merged in 2025-09, with the labels that each got.

#4193 [Compiler] Do not transfer and convert moved value
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  interpreter/resources_test.go
  runtime/error_test.go
Labels: Bugfix

#4194 Update to latest fixed-point version
  go.mod
  go.sum
  interpreter/value_fix128.go
  interpreter/value_ufix128.go
  tools/compatibility-check/go.mod
  tools/compatibility-check/go.sum
Labels: Technical Debt

#4196 Bump fixed-point version to `v0.1.1`
  go.mod
  go.sum
  tools/compatibility-check/go.mod
  tools/compatibility-check/go.sum
Labels: Chore

#4192 [Compiler] Split VM Typeloader into separate dedicated methods.
  bbq/vm/config.go
  bbq/vm/test/utils.go
  bbq/vm/test/vm_bench_test.go
  bbq/vm/test/vm_test.go
  runtime/vm_environment.go
  test_utils/test_utils.go
Labels: Technical Debt

#4200 Review of Sema and Parser Errors
  runtime/deployment_test.go
  runtime/error_test.go
  sema/errors.go
Labels: Documentation, Improvement

#4033 [Interpreter] Import Aliasing
  ast/import.go
  ast/import_test.go
  bbq/compiler/desugar.go
  cmd/errors/errors.go
  interpreter/import_test.go
  interpreter/interpreter_import.go
  old_parser/declaration.go
  parser/declaration.go
  parser/declaration_test.go
  parser/errors.go
  sema/check_import_declaration.go
  sema/import_test.go
Labels: Feature

#4201 Add suggested fix for duplicate conformance error
  ast/position.go
  ast/position_test.go
  sema/errors.go
  sema/interface_test.go
Labels: Feature

#4087 [Compiler] Attachments #2/3
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/desugar.go
  bbq/vm/builtin_globals.go
  bbq/vm/context.go
  bbq/vm/test/vm_test.go
  bbq/vm/value_function.go
  bbq/vm/vm.go
  interpreter/attachments_test.go
  interpreter/interpreter_expression.go
  interpreter/interpreter_statement.go
  interpreter/value_composite.go
Labels: Feature

#4205 Add additional authentication options for Cadence update tool
  tools/update/README.md
  tools/update/main.ts
Labels: Improvement

#4203 Import Aliasing
  ast/identifier.go
  ast/import.go
  ast/import_test.go
  bbq/commons/types.go
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/desugar.go
  bbq/vm/test/vm_test.go
  cmd/errors/errors.go
  cmd/errors/gen/main.go
  cmd/errors/placeholders.go
  interpreter/import_test.go
  interpreter/interpreter_import.go
  interpreter/interpreter_tracing_test.go
  old_parser/declaration.go
  old_parser/declaration_test.go
  parser/declaration.go
  parser/declaration_test.go
  parser/errors.go
  runtime/ft_test.go
  sema/check_import_declaration.go
  sema/checker.go
  sema/elaboration.go
  sema/errors.go
  sema/import_test.go
  stdlib/contract_update_validation.go
Labels: Feature

#4220 [Compiler] Simplify imported globals linking
  bbq/compiler/builtin_globals.go
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/global.go
  bbq/vm/linker.go
  bbq/vm/test/ft_test.go
  bbq/vm/test/utils.go
  bbq/vm/test/vm_test.go
  interpreter/account_test.go
  runtime/rlp_test.go
  runtime/vm_environment.go
  test_utils/test_utils.go
Labels: Improvement, Technical Debt

#4222 [Compiler] Initialize all variable of all imports
  bbq/compiler/compiler.go
  bbq/vm/linker.go
  bbq/vm/test/utils.go
  bbq/vm/test/vm_test.go
  bbq/vm/vm.go
  interpreter/import_test.go
Labels: Bugfix

#4223 [Compiler] Initialize all variables of a dynamically linked program
  bbq/compiler/compiler.go
  bbq/contract.go
  bbq/vm/linker.go
  bbq/vm/vm.go
  interpreter/import_test.go
Labels: Improvement

#4215 [Compiler] Reuse elaboration for imports when possible.
  bbq/compiler/compiler.go
Labels: Technical Debt

#4197 [Compiler] Add control flow basic block visualization to program printer.
  bbq/opcode/print.go
  bbq/opcode/print_test.go
  bbq/program_printer.go
  bbq/test_utils/utils.go
Labels: Testing

#4224 Fix tracing of function invocations
  bbq/vm/vm.go
  interpreter/interpreter_expression.go
Labels: Bugfix

#4227 [Compiler] Use global's index instead of array index during linking
  bbq/compiler/compiler.go
  bbq/vm/linker.go
Labels: Bugfix

#4228 [Compiler] Add tests for importing same program from multiple paths
  bbq/compiler/compiler.go
  bbq/vm/test/vm_test.go
Labels: Testing

#4229 [Compiler] Improve transaction program init function
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/desugar.go
Labels: Improvement, Testing

#4231 [Compiler] Trace event emission
  bbq/vm/config.go
  interpreter/interpreter_statement.go
  interpreter/interpreter_tracing.go
Labels: Improvement

#4214 [Compiler] Skip encoding-decoding of constants
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/constant.go
  bbq/constant/constant.go
  bbq/constant/kind.go
  bbq/constant/kind_string.go
  bbq/opcode/gen/main.go
  bbq/opcode/instruction.go
  bbq/opcode/instructions.go
  bbq/opcode/print.go
  bbq/opcode/print_test.go
  bbq/program.go
  bbq/program_printer.go
  bbq/vm/test/vm_test.go
  bbq/vm/vm.go
  interpreter/memory_metering_test.go
Labels: Improvement

#4236 [Compiler] Fix result variable transfer
  ast/transferoperation.go
  ast/transferoperation_string.go
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/desugar.go
  interpreter/function_test.go
Labels: Bugfix

#4241 [Compiler] Fix Account.contracts.borrow
  bbq/vm/context.go
  bbq/vm/test/vm_test.go
  bbq/vm/vm.go
Labels: Bugfix

#4243 [Compiler] Fix function types for capability value methods
  bbq/vm/value_capability.go
  interpreter/value_published.go
Labels: Bugfix

#4242 [Compiler] Ensure program is initialized whenever type-info is requested
  bbq/vm/config.go
  bbq/vm/context.go
  bbq/vm/test/vm_test.go
  interpreter/import_test.go
  interpreter/metatype_test.go
  interpreter/misc_test.go
  runtime/rlp_test.go
  runtime/vm_environment.go
Labels: Bugfix

#4208 [Compiler] Always transfer on move operator. Remove redundent transfers
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/desugared_elaboration.go
  bbq/opcode/instructions.go
  bbq/opcode/instructions.yml
  bbq/opcode/opcode.go
  bbq/opcode/opcode_string.go
  bbq/opcode/print_test.go
  bbq/vm/vm.go
  interpreter/function_test.go
  interpreter/interpreter.go
  interpreter/resources_test.go
  interpreter/transfer_test.go
  runtime/error_test.go
  sema/check_unary_expression.go
  sema/elaboration.go
Labels: Improvement
