Repository onflow/cadence, pull requests merged in 2025-06, with the labels that each got.

#3988 [Compiler] Check resource loss in assignments
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/vm/vm.go
  interpreter/interpreter.go
  interpreter/resources_test.go
  interpreter/value_array.go
  interpreter/value_composite.go
  interpreter/value_dictionary.go
  interpreter/variable.go
Labels: Feature

#3999 [Compiler] Run some more tests with the compiler/vm
  interpreter/composite_value_test.go
  interpreter/dynamic_casting_test.go
  interpreter/function_test.go
  interpreter/misc_test.go
  interpreter/nesting_test.go
  interpreter/pathcapability_test.go
  interpreter/reference_test.go
  interpreter/transfer_test.go
  test_utils/test_utils.go
Labels: Testing

#3998 [Compiler] Computation metering
  Makefile
  bbq/vm/test/vm_test.go
  bbq/vm/vm.go
  common/computationkind.go
  common/computationkind_string.go
  common/metering.go
  runtime/runtime_test.go
  runtime/vm_environment.go
Labels: Feature

#4002 [Compiler] Optimize computation metering
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/opcode/instructions.go
  bbq/opcode/instructions.yml
  bbq/opcode/opcode.go
  bbq/opcode/opcode_string.go
  bbq/opcode/print_test.go
  bbq/vm/test/vm_test.go
  bbq/vm/vm.go
  common/computationkind.go
  common/computationkind_string.go
  common/metering.go
  runtime/runtime_test.go
Labels: Performance

#4003 [Compiler] Compile swap statements
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/desugared_elaboration.go
  bbq/vm/test/vm_test.go
  bbq/vm/vm.go
  interpreter/member_test.go
  interpreter/misc_test.go
  interpreter/resources_test.go
  interpreter/value_dictionary.go
  interpreter/value_placeholder.go
Labels: Feature

#4005 [Compiler] Transfer and convert index indexing/key expression
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  interpreter/indexing_test.go
Labels: Bugfix

#4006 [Compiler] Test implicit boxing
  bbq/vm/test/vm_test.go
Labels: Testing

#4004 [Compiler] Emit default destroyed events when resources are destroyed
  bbq/commons/constants.go
  bbq/compiler/compiler.go
  bbq/compiler/desugar.go
  bbq/compiler/desugared_elaboration.go
  bbq/vm/context.go
  common/memorykind.go
  common/memorykind_string.go
  common/metering.go
  interpreter/interface.go
  interpreter/interpreter.go
  interpreter/misc_test.go
  interpreter/resources_test.go
  interpreter/value_composite.go
  sema/check_composite_declaration.go
  sema/elaboration.go
Labels: Feature

#4008 [Compiler] Meter computation for "entry point" function invocations in interpreter
  interpreter/interpreter.go
  runtime/runtime_test.go
Labels: Improvement

#4022 Port v1.6.1-rc.1
  interpreter/div_mod_test.go
  interpreter/value_ufix64.go
  parser/lexer/lexer.go
  parser/lexer/lexer_test.go
  values/value_ufix64.go
Labels: Bugfix

#4021 [v1.6] Port v1.6.1-rc.1
  interpreter/div_mod_test.go
  interpreter/value_ufix64.go
  parser/lexer/lexer.go
  parser/lexer/lexer_test.go
  values/value_ufix64.go
Labels: Bugfix

#4029 [Compiler] Run more tests with compiler
  bbq/compiler/compiler.go
  bbq/vm/vm.go
  interpreter/metatype_test.go
  interpreter/misc_test.go
  interpreter/resources_test.go
  interpreter/transactions_test.go
  interpreter/value_ephemeral_reference.go
  test_utils/test_utils.go
Labels: Improvement

#4027 [Compiler] Compile conditions in function-expressions and inner-functions
  ast/statement.go
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/desugar.go
  bbq/vm/test/vm_test.go
  common/memorykind.go
  common/memorykind_string.go
  common/metering.go
  interpreter/condition_test.go
  parser/statement.go
Labels: Improvement

#4031 [Compiler] Implement more stdlib functions
  runtime/runtime_test.go
  runtime/type_test.go
  stdlib/account.go
  stdlib/block.go
  stdlib/builtin.go
  stdlib/random.go
Labels: Feature

#4032 [Compiler] Implement Account.Keys functions for VM
  stdlib/account.go
  stdlib/builtin.go
Labels: Feature

#4035 [Compiler] Implement RLP and BLS functions for VM
  runtime/crypto_test.go
  runtime/rlp_test.go
  runtime/vm_environment.go
  stdlib/bls.go
  stdlib/builtin.go
  stdlib/rlp.go
Labels: Feature

#4036 [Compiler] Implement StorageCapabilityController and AccountCapabilityController functions for VM
  bbq/vm/value_accountcapabilitycontroller.go
  bbq/vm/value_storagecapabilitycontroller.go
  interpreter/value_accountcapabilitycontroller.go
  interpreter/value_storagecapabilitycontroller.go
  runtime/capabilitycontrollers_test.go
Labels: Feature

#4038 [Compiler] Implement PublicKey constructor for VM
  interpreter/value_publickey.go
  runtime/account_test.go
  runtime/convertValues.go
  runtime/crypto_test.go
  sema/type.go
  stdlib/builtin.go
  stdlib/publickey.go
Labels: Feature

#4039 [Compiler] Allow loading of `flow.*` types in VM environment
  runtime/runtime_test.go
  runtime/vm_environment.go
Labels: Feature

#4040 Fix race when array/dictionary entitlement set is used concurrently
  sema/type.go
Labels: Bugfix

#4042 [Compiler] Remove environment composite functions handler
  runtime/environment.go
  runtime/vm_environment.go
Labels: Improvement

#4041 [Compiler] Refactor method invocation
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/opcode/instructions.go
  bbq/opcode/instructions.yml
  bbq/opcode/opcode.go
  bbq/opcode/opcode_string.go
  bbq/opcode/print_test.go
  bbq/vm/context.go
  bbq/vm/test/vm_test.go
  bbq/vm/value_function.go
  bbq/vm/vm.go
  interpreter/misc_test.go
  interpreter/transactions_test.go
  runtime/vm_environment.go
  stdlib/stdlib.go
Labels: Improvement

#4047 [Compiler] Add member access type validation in VM
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/desugar.go
  bbq/compiler/desugared_elaboration.go
  bbq/opcode/instructions.go
  bbq/opcode/instructions.yml
  bbq/opcode/print_test.go
  bbq/vm/builtin_globals.go
  bbq/vm/config.go
  bbq/vm/executable_program.go
  bbq/vm/linker.go
  bbq/vm/test/ft_test.go
  bbq/vm/test/utils.go
  bbq/vm/test/vm_test.go
  bbq/vm/vm.go
  common/memorykind.go
  common/memorykind_string.go
  interpreter/account_test.go
  interpreter/interpreter_expression.go
  interpreter/member_test.go
  interpreter/statictype.go
  interpreter/variable.go
  runtime/runtime_test.go
  runtime/vm_environment.go
  sema/check_transaction_declaration.go
  sema/type.go
  sema/type_test.go
  test_utils/test_utils.go
Labels: Improvement

#4051 Merge master into the compiler feature branch
  common/bimap/bimap.go
  common/bimap/bimap_test.go
  interpreter/div_mod_test.go
  interpreter/value_ufix64.go
  npm-packages/cadence-parser/package.json
  parser/lexer/lexer.go
  parser/lexer/lexer_test.go
  runtime/checking_environment.go
  runtime/contract_function_executor.go
  runtime/convertValues_test.go
  runtime/coverage.go
  runtime/environment.go
  runtime/runtime.go
  runtime/runtime_memory_metering_test.go
  runtime/script_executor.go
  runtime/storage_test.go
  runtime/transaction_executor.go
  runtime/vm_environment.go
  sema/type.go
  stdlib/test-framework.go
  tools/accounts-script/README.md
  tools/accounts-script/go.mod
  tools/accounts-script/go.sum
  tools/accounts-script/iterate_storage.cdc
  tools/accounts-script/main.go
  values/value_ufix64.go
  version.go
Labels: Chore

#4054 Re-use static-type to sema-type conversion results
  bbq/vm/context.go
  bbq/vm/test/ft_test.go
  bbq/vm/value.go
  bbq/vm/value_account_storage.go
  bbq/vm/value_capability.go
  bbq/vm/vm.go
  interpreter/account_test.go
  interpreter/interface.go
  interpreter/interpreter.go
  interpreter/statictype.go
  interpreter/statictype_test.go
  interpreter/value_storage_reference.go
  runtime/contract_function_executor.go
  runtime/runtime_test.go
  sema/type.go
Labels: Improvement
