Repository onflow/cadence, pull requests merged in 2025-08, with the labels that each got.

#4108 [4062-Part 1] Update Cadence Errors with recommended fixes and links to documentation
  cmd/gen-errors/errors.go
  errors/errors.go
  parser/declaration.go
  parser/declaration_test.go
  parser/errors.go
  sema/attachments_test.go
  sema/check_invocation_expression.go
  sema/checker.go
  sema/declaration_test.go
  sema/entitlements_test.go
  sema/error_handling_test.go
  sema/errors.go
Labels: Documentation, Improvement

#4129 Improve errors and suggested fixes, add tests
  ast/ast.go
  cmd/gen-errors/errors.go
  parser/declaration.go
  parser/declaration_test.go
  parser/errors.go
  parser/expression_test.go
  sema/check_emit_statement.go
  sema/composite_test.go
  sema/declaration_test.go
  sema/errors.go
  sema/events_test.go
  sema/invocation_test.go
Labels: Improvement, Testing

#4130 Show migration note and documentation link in pretty error printer
  pretty/print.go
Labels: Improvement

#4133 [v1.6] Port v1.6.4-rc.1: Fix conformance kind mismatch error reporting
  sema/check_composite_declaration.go
  sema/conformance_test.go
Labels: Bugfix

#4132 Validate documentation links of errors
  .github/workflows/ci.yml
  Makefile
  cmd/errors/README.md
  cmd/errors/errors.go
  cmd/errors/gen/main.go
  cmd/errors/main.go
  cmd/errors/placeholders.go
Labels: Feature

#4138 [v1.6] Fix NPM version
  npm-packages/cadence-parser/package.json
Labels: Bugfix

#4154 Improve release note generation
  .github/release.yml
Labels: Chore

#4052 [Compiler] Attachments #1/3
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/desugared_elaboration.go
  bbq/opcode/instructions.go
  bbq/opcode/instructions.yml
  bbq/opcode/opcode.go
  bbq/opcode/opcode_string.go
  bbq/opcode/print_test.go
  bbq/vm/test/vm_test.go
  bbq/vm/value_function.go
  bbq/vm/vm.go
  interpreter/attachments_test.go
  interpreter/interpreter_expression.go
  sema/check_attach_expression.go
  sema/elaboration.go
Labels: Feature

#4144 Improve sema errors
  cmd/errors/errors.go
  sema/check_interface_declaration.go
  sema/checker.go
  sema/dictionary_test.go
  sema/entitlements_test.go
  sema/errors.go
  sema/type.go
Labels: Improvement

#4148 Improve statement parsing errors
  cmd/errors/errors.go
  parser/declaration.go
  parser/declaration_test.go
  parser/errors.go
  parser/statement.go
  parser/statement_test.go
  parser/transaction.go
Labels: Improvement, Testing

#4150 Improve expression parsing errors
  cmd/errors/errors.go
  parser/errors.go
  parser/expression.go
  parser/expression_test.go
Labels: Improvement, Testing

#4158 Add suggested fixes to errors
  parser/comment_test.go
  parser/declaration_test.go
  parser/errors.go
  parser/expression_test.go
  parser/statement_test.go
Labels: Feature

#4161 Improve insertion positions of suggested fixes
  ast/position.go
  ast/position_test.go
  parser/errors.go
  parser/expression_test.go
Labels: Improvement

#4147 Add `UFix128` type to Cadence
  encoding/ccf/ccf_test.go
  encoding/ccf/decode.go
  encoding/ccf/encode.go
  encoding/ccf/simpletype.go
  encoding/ccf/simpletype_string.go
  encoding/json/decode.go
  encoding/json/encode.go
  encoding/json/encoding_test.go
  fixedpoint/check.go
  fixedpoint/convert.go
  fixedpoint/parse.go
  format/fix.go
  format/fix_test.go
  go.mod
  go.sum
  integer/integer.go
  interpreter/arithmetic_test.go
  interpreter/builtinfunctions_test.go
  interpreter/decode.go
  interpreter/encode.go
  interpreter/fixedpoint_test.go
  interpreter/hashablevalue.go
  interpreter/interpreter.go
  interpreter/interpreter_expression.go
  interpreter/memory_metering_test.go
  interpreter/misc_test.go
  interpreter/primitivestatictype.go
  interpreter/primitivestatictype_string.go
  interpreter/reference_test.go
  interpreter/statictype_test.go
  interpreter/value_fix128.go
  interpreter/value_fix64.go
  interpreter/value_test.go
  interpreter/value_ufix128.go
  interpreter/visitor.go
  parser/type_test.go
  runtime/convertTypes.go
  runtime/convertValues.go
  runtime/convertValues_test.go
  runtime/imported_values_memory_metering_test.go
  sema/operations_test.go
  sema/type.go
  sema/type_names.go
  sema/type_tags.go
  sema/type_test.go
  tools/compatibility-check/go.mod
  tools/compatibility-check/go.sum
  types.go
  values.go
  values/encode.go
  values_test.go
Labels: Feature

#4155 Test least-significant decimal point truncation
  interpreter/fixedpoint_test.go
  interpreter/value_fix128.go
Labels: Testing

#4164 [Compiler] Support `Fix128` and `UFix128` types in compiler
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/constant/kind.go
  bbq/constant/kind_string.go
  bbq/vm/test/vm_test.go
  bbq/vm/vm.go
  encoding/ccf/decode.go
  interpreter/memory_metering_test.go
Labels: Feature

#4165 Add suggested fixes for sema errors
  ast/position.go
  cmd/errors/errors.go
  sema/check_create_expression.go
  sema/check_destroy_expression.go
  sema/check_member_expression.go
  sema/check_unary_expression.go
  sema/composite_test.go
  sema/declaration_test.go
  sema/error_handling_test.go
  sema/errors.go
  sema/events_test.go
  sema/interface_test.go
  sema/member_test.go
  sema/resource_test.go
  sema/return_test.go
Labels: Feature

#4169 Update dependencies
  go.mod
  go.sum
  test_utils/common_utils/utils.go
  tools/compatibility-check/go.mod
  tools/compatibility-check/go.sum
Labels: Chore

#4170 Handle external overflow/underflow errors from library
  interpreter/arithmetic_test.go
  interpreter/div_mod_test.go
  interpreter/fixedpoint_test.go
  interpreter/value_fix128.go
  interpreter/value_fix64.go
  interpreter/value_int16.go
  interpreter/value_int32.go
  interpreter/value_int64.go
  interpreter/value_int8.go
  interpreter/value_ufix64.go
Labels: Improvement

#4173 Handle partial AST nodes when pretty printing
  ast/access.go
  ast/argument.go
  ast/argument_test.go
  ast/attachment.go
  ast/block.go
  ast/block_test.go
  ast/composite.go
  ast/entitlement_declaration.go
  ast/expression.go
  ast/operation.go
  ast/parameter.go
  ast/parameter_test.go
  ast/parameterlist.go
  ast/parameterlist_test.go
  ast/pragma.go
  ast/pragma_test.go
  ast/prettier.go
  ast/program.go
  ast/program_test.go
  ast/transfer.go
  ast/transfer_test.go
  ast/type.go
  ast/type_test.go
  ast/typeparameter.go
  ast/typeparameter_test.go
  ast/typeparameterlist.go
  ast/typeparameterlist_test.go
  ast/variable_declaration.go
Labels: Improvement, Testing

#4180 Fix spacing in pretty printed AST nodes
  ast/attachment.go
  ast/attachment_test.go
  ast/block_test.go
  ast/composite_test.go
  ast/expression.go
  ast/expression_test.go
  ast/function_declaration_test.go
  ast/import_test.go
  ast/interface_test.go
  ast/members_test.go
  ast/parameter_test.go
  ast/parameterlist_test.go
  ast/statement_test.go
  ast/transaction_declaration_test.go
  ast/type.go
  ast/type_test.go
  ast/variable_declaration_test.go
Labels: Bugfix

#3891 Fix typos
  interpreter/interpreter.go
  runtime/nft_test.go
  sema/deployment_result.cdc
  sema/deployment_result.gen.go
  sema/interface_test.go
Labels: Documentation, Improvement

#4185 [Compiler] Move empty initializer and enum lookup function creation from compiler into desugaring.
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/desugar.go
Labels: Technical Debt

#4190 Add release badge to README
  README.md
Labels: Documentation, Chore

#4184 Use truncation instead of rounding for `big.Int` division
  interpreter/fixedpoint_test.go
  interpreter/integers_test.go
  interpreter/value_fix64.go
  interpreter/value_int128.go
  interpreter/value_int256.go
  interpreter/value_uint.go
  interpreter/value_uint128.go
  interpreter/value_uint256.go
  interpreter/value_word128.go
  interpreter/value_word256.go
  values/value_int.go
  values/value_ufix64.go
Labels: Bugfix
