Repository onflow/cadence, pull requests merged in 2025-04, with the labels that each got.

#3817 [Compiler] Refactor `vm.Value` and related operations to be independent of the `vm.Config`
  bbq/vm/config.go
  bbq/vm/reference_tracking.go
  bbq/vm/storage.go
  bbq/vm/types.go
  bbq/vm/value.go
  bbq/vm/value_account.go
  bbq/vm/value_address.go
  bbq/vm/value_array.go
  bbq/vm/value_bool.go
  bbq/vm/value_capability.go
  bbq/vm/value_capability_controller.go
  bbq/vm/value_composite.go
  bbq/vm/value_conversions.go
  bbq/vm/value_dictionary.go
  bbq/vm/value_ephemeral_reference.go
  bbq/vm/value_function.go
  bbq/vm/value_int.go
  bbq/vm/value_nil.go
  bbq/vm/value_path.go
  bbq/vm/value_simple_composite.go
  bbq/vm/value_some.go
  bbq/vm/value_storage_reference.go
  bbq/vm/value_string.go
  bbq/vm/value_ufix64.go
  bbq/vm/value_void.go
  bbq/vm/vm.go
  interpreter/interface.go
  test_utils/test_utils.go
Labels: Technical Debt

#3824 [Compiler] Decouple `ValueIndexableValue` interface from the interpreter
  interpreter/interface.go
  interpreter/interpreter.go
  interpreter/value.go
  interpreter/value_array.go
  interpreter/value_composite.go
  interpreter/value_dictionary.go
  interpreter/value_ephemeral_reference.go
  interpreter/value_storage_reference.go
  interpreter/value_string.go
Labels: Technical Debt

#3827 [Compiler] Re-use interpreter's account related stdlibs in vm
  bbq/vm/config.go
  bbq/vm/test/ft_test.go
  bbq/vm/test/utils.go
  bbq/vm/test/vm_bench_test.go
  bbq/vm/test/vm_test.go
  bbq/vm/value_account.go
  bbq/vm/value_account_capabilities.go
  bbq/vm/value_account_storage.go
  bbq/vm/value_account_storagecapabilities.go
  bbq/vm/value_capability.go
  bbq/vm/value_capability_controller.go
  bbq/vm/vm.go
  interpreter/interface.go
  interpreter/interpreter.go
  interpreter/interpreter_statement.go
  interpreter/value_account_storage.go
  interpreter/value_composite.go
  runtime/environment.go
  stdlib/account.go
Labels: Technical Debt

#3829 [Compiler] Add type construction and conversion standard-library functions
  bbq/compiler/native_functions.go
  bbq/vm/config.go
  bbq/vm/native_functions.go
  bbq/vm/test/vm_test.go
  bbq/vm/value_account_capabilities.go
  bbq/vm/value_account_storage.go
  bbq/vm/value_account_storagecapabilities.go
  bbq/vm/value_capability.go
  bbq/vm/value_int.go
  bbq/vm/value_string.go
  bbq/vm/vm.go
  interpreter/interpreter.go
  interpreter/value_string.go
  sema/runtime_type_constructors.go
  sema/type.go
  stdlib/log.go
  stdlib/panic.go
Labels: Feature

#3830 [Compiler] Fix FT test in vm
  bbq/vm/test/ft_test.go
  bbq/vm/value_account.go
  bbq/vm/value_account_capabilities.go
  bbq/vm/value_account_storage.go
  bbq/vm/value_simple_composite.go
  interpreter/simplecompositevalue.go
  interpreter/value_account.go
  interpreter/value_account_accountcapabilities.go
  interpreter/value_account_capabilities.go
  interpreter/value_account_storage.go
  interpreter/value_account_storagecapabilities.go
  stdlib/account.go
Labels: Technical Debt

#3831 [Compiler] Add remaining `Account.Storage` stdlib functions to the VM
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/config.go
  bbq/compiler/global.go
  bbq/compiler/native_functions.go
  bbq/vm/config.go
  bbq/vm/errors.go
  bbq/vm/test/utils.go
  bbq/vm/test/vm_test.go
  bbq/vm/value_account_storage.go
  bbq/vm/value_function.go
  bbq/vm/vm.go
  interpreter/account_test.go
  interpreter/interface.go
  interpreter/interpreter.go
  interpreter/interpreter_invocation.go
  interpreter/interpreter_transaction.go
  interpreter/value_composite.go
  interpreter/value_function.go
  test_utils/interpreter_utils/values.go
  test_utils/test_utils.go
Labels: Improvement

#3720 chore: fix some function names in comment
  sema/check_composite_declaration.go
Labels: Documentation

#3834 [Compiler] Compile simple function expressions
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/desugar.go
  bbq/opcode/instructions.go
  bbq/opcode/instructions.yml
  bbq/opcode/opcode.go
  bbq/opcode/opcode_string.go
  bbq/opcode/print_test.go
  bbq/vm/test/vm_test.go
  bbq/vm/value_function.go
  bbq/vm/vm.go
Labels: Feature

#3839 [Compiler] Compile simple inner functions
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/vm/test/vm_test.go
Labels: Feature

#3840 [Compiler] Work towards implementing closures
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/function.go
  bbq/compiler/local.go
  bbq/function.go
Labels: Improvement

#3845 Decouple remaining methods of value-related interfaces from the interpreter
  interpreter/interface.go
  interpreter/interpreter.go
  interpreter/interpreter_expression.go
  interpreter/interpreter_tracing.go
  interpreter/simplecompositevalue.go
  interpreter/value.go
  interpreter/value_accountcapabilitycontroller.go
  interpreter/value_address.go
  interpreter/value_array.go
  interpreter/value_capability.go
  interpreter/value_character.go
  interpreter/value_composite.go
  interpreter/value_dictionary.go
  interpreter/value_ephemeral_reference.go
  interpreter/value_fix64.go
  interpreter/value_function.go
  interpreter/value_int.go
  interpreter/value_int128.go
  interpreter/value_int16.go
  interpreter/value_int256.go
  interpreter/value_int32.go
  interpreter/value_int64.go
  interpreter/value_int8.go
  interpreter/value_nil.go
  interpreter/value_path.go
  interpreter/value_pathcapability.go
  interpreter/value_some.go
  interpreter/value_storage_reference.go
  interpreter/value_storagecapabilitycontroller.go
  interpreter/value_string.go
  interpreter/value_type.go
  interpreter/value_ufix64.go
  interpreter/value_uint.go
  interpreter/value_uint128.go
  interpreter/value_uint16.go
  interpreter/value_uint256.go
  interpreter/value_uint32.go
  interpreter/value_uint64.go
  interpreter/value_uint8.go
  interpreter/value_word128.go
  interpreter/value_word16.go
  interpreter/value_word256.go
  interpreter/value_word32.go
  interpreter/value_word64.go
  interpreter/value_word8.go
Labels: Technical Debt

#3814 Remove support for account storage format V1
  interpreter/account_storagemap_test.go
  runtime/account_storage.go
  runtime/account_storage_v1.go
  runtime/config.go
  runtime/contract_function_executor.go
  runtime/contract_test.go
  runtime/migrate_domain_registers.go
  runtime/migrate_domain_registers_test.go
  runtime/runtime.go
  runtime/runtime_memory_metering_test.go
  runtime/runtime_test.go
  runtime/script_executor.go
  runtime/sharedstate_test.go
  runtime/storage.go
  runtime/storage_test.go
  runtime/transaction_executor.go
Labels: Improvement

#3846 [Compiler] Implement closed upvalues in VM
  bbq/vm/callframe.go
  bbq/vm/test/vm_test.go
  bbq/vm/upvalue.go
  bbq/vm/vm.go
Labels: Feature

#3848 [Compiler] Sync `feature/compiler` with `master`
  bbq/vm/tracer.go
  bbq/vm/value_function.go
  bbq/vm/value_iterator.go
  interpreter/interface.go
  interpreter/interpreter.go
  interpreter/interpreter_expression.go
  interpreter/interpreter_tracing.go
  interpreter/simplecompositevalue.go
  interpreter/value.go
  interpreter/value_accountcapabilitycontroller.go
  interpreter/value_address.go
  interpreter/value_array.go
  interpreter/value_bool.go
  interpreter/value_capability.go
  interpreter/value_character.go
  interpreter/value_composite.go
  interpreter/value_dictionary.go
  interpreter/value_ephemeral_reference.go
  interpreter/value_fix64.go
  interpreter/value_function.go
  interpreter/value_int.go
  interpreter/value_int128.go
  interpreter/value_int16.go
  interpreter/value_int256.go
  interpreter/value_int32.go
  interpreter/value_int64.go
  interpreter/value_int8.go
  interpreter/value_link.go
  interpreter/value_nil.go
  interpreter/value_path.go
  interpreter/value_pathcapability.go
  interpreter/value_placeholder.go
  interpreter/value_published.go
  interpreter/value_some.go
  interpreter/value_storage_reference.go
  interpreter/value_storagecapabilitycontroller.go
  interpreter/value_string.go
  interpreter/value_test.go
  interpreter/value_type.go
  interpreter/value_ufix64.go
  interpreter/value_uint.go
  interpreter/value_uint128.go
  interpreter/value_uint16.go
  interpreter/value_uint256.go
  interpreter/value_uint32.go
  interpreter/value_uint64.go
  interpreter/value_uint8.go
  interpreter/value_void.go
  interpreter/value_word128.go
  interpreter/value_word16.go
  interpreter/value_word256.go
  interpreter/value_word32.go
  interpreter/value_word64.go
  interpreter/value_word8.go
  interpreter/visitor.go
Labels: Technical Debt

#3852 [v1.3] Port internal v1.3.4-rc.2
  .github/workflows/compatibility-check-template.yml
  .github/workflows/compatibility-check.yml
  .github/workflows/get-contracts.yml
  encoding/ccf/decode.go
  encoding/json/encoding_test.go
  go.mod
  go.sum
  interpreter/account_test.go
  interpreter/attachments_test.go
  interpreter/encoding_test.go
  interpreter/entitlements_test.go
  interpreter/errors.go
  interpreter/function_test.go
  interpreter/interpreter.go
  interpreter/interpreter_expression.go
  interpreter/interpreter_invocation.go
  interpreter/invocation.go
  interpreter/invocation_test.go
  interpreter/member_test.go
  interpreter/memory_metering_test.go
  interpreter/misc_test.go
  interpreter/reference_test.go
  interpreter/resources_test.go
  interpreter/sharedstate.go
  interpreter/value_composite.go
  interpreter/value_function.go
  interpreter/value_function_test.go
  parser/declaration.go
  parser/declaration_test.go
  runtime/contract_function_executor.go
  runtime/entitlements_test.go
  runtime/runtime_test.go
  sema/access.go
  sema/attachments_test.go
  sema/check_composite_declaration.go
  sema/check_expression.go
  sema/check_for.go
  sema/check_function.go
  sema/check_member_expression.go
  sema/check_reference_expression.go
  sema/checker.go
  sema/checker_test.go
  sema/entitlements_test.go
  sema/errors.go
  sema/function_test.go
  sema/runtime_type_constructors.go
  sema/simple_type.go
  sema/type.go
  sema/type_test.go
  stdlib/account.go
  test_utils/common_utils/utils.go
  test_utils/sema_utils/utils.go
  tools/compatibility-check/go.mod
  tools/compatibility-check/go.sum
  tools/get-contracts/main.go
  types.go
  types_test.go
  version.go
Labels: Bugfix, Language Breaking Change

#3850 [Compiler] Add UUID to resources
  bbq/vm/config.go
  bbq/vm/test/utils.go
  bbq/vm/test/vm_test.go
  bbq/vm/value_composite.go
  bbq/vm/vm.go
  interpreter/account_test.go
Labels: Feature

#3853 [Compiler] Clean up VM tests
  bbq/vm/test/vm_test.go
Labels: Testing, Technical Debt

#3854 Port v1.3.4 to master
  .github/workflows/compatibility-check.yml
  encoding/ccf/decode.go
  encoding/json/encoding_test.go
  go.mod
  go.sum
  interpreter/account_test.go
  interpreter/attachments_test.go
  interpreter/encoding_test.go
  interpreter/entitlements_test.go
  interpreter/errors.go
  interpreter/function_test.go
  interpreter/interface.go
  interpreter/interpreter.go
  interpreter/interpreter_expression.go
  interpreter/interpreter_invocation.go
  interpreter/invocation.go
  interpreter/invocation_test.go
  interpreter/member_test.go
  interpreter/memory_metering_test.go
  interpreter/misc_test.go
  interpreter/reference_test.go
  interpreter/resources_test.go
  interpreter/sharedstate.go
  interpreter/statictype.go
  interpreter/value_composite.go
  interpreter/value_function.go
  interpreter/value_function_test.go
  npm-packages/cadence-parser/package.json
  parser/declaration.go
  parser/declaration_test.go
  runtime/contract_function_executor.go
  runtime/entitlements_test.go
  runtime/runtime_test.go
  sema/access.go
  sema/attachments_test.go
  sema/check_composite_declaration.go
  sema/check_expression.go
  sema/check_for.go
  sema/check_function.go
  sema/check_member_expression.go
  sema/check_reference_expression.go
  sema/checker.go
  sema/checker_test.go
  sema/entitlements_test.go
  sema/errors.go
  sema/function_test.go
  sema/runtime_type_constructors.go
  sema/simple_type.go
  sema/type.go
  sema/type_test.go
  stdlib/account.go
  test_utils/common_utils/utils.go
  test_utils/sema_utils/utils.go
  tools/compatibility-check/go.mod
  tools/compatibility-check/go.sum
  tools/get-contracts/main.go
  types.go
  types_test.go
  version.go
Labels: Bugfix, Language Breaking Change

#3851 [Compiler] Complete the implementation of vm function values
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/desugar.go
  bbq/compiler/extended_elaboration.go
  bbq/compiler/function.go
  bbq/function.go
  bbq/vm/executable_program.go
  bbq/vm/linker.go
  bbq/vm/native_functions.go
  bbq/vm/value_account_capabilities.go
  bbq/vm/value_account_storage.go
  bbq/vm/value_account_storagecapabilities.go
  bbq/vm/value_capability.go
  bbq/vm/value_function.go
  bbq/vm/value_int.go
  bbq/vm/value_string.go
  bbq/vm/vm.go
Labels: Improvement

#3862 [Compiler] Improve compilation of constants
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/constantkind/constantkind.go
  bbq/constantkind/constantkind_string.go
  bbq/program_printer.go
  bbq/vm/test/utils.go
  bbq/vm/test/vm_test.go
  bbq/vm/vm.go
Labels: Improvement

#3866 [Compiler] Skip anonymous functions in linker
  bbq/function.go
  bbq/vm/config.go
  bbq/vm/linker.go
  bbq/vm/vm.go
Labels: Bugfix

#3865 [Compiler] Improve program printing
  bbq/opcode/gen/main.go
  bbq/opcode/instruction.go
  bbq/opcode/instructions.go
  bbq/opcode/print.go
  bbq/opcode/print_test.go
  bbq/program_printer.go
Labels: Improvement

#3869 [Compiler] Register common type-bound functions for all builtin types
  bbq/vm/native_functions.go
  bbq/vm/test/vm_test.go
  bbq/vm/value_account_capabilities.go
  bbq/vm/value_account_storage.go
  bbq/vm/value_account_storagecapabilities.go
  bbq/vm/value_array.go
  bbq/vm/value_capability.go
  bbq/vm/value_dictionary.go
  bbq/vm/value_function.go
  bbq/vm/value_int.go
  bbq/vm/value_string.go
  bbq/vm/value_type.go
  bbq/vm/value_ufix64.go
  bbq/vm/value_uint64.go
  interpreter/interpreter.go
  sema/type.go
Labels: Improvement

#3870 [Compiler] Rename path instruction
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/opcode/instructions.go
  bbq/opcode/instructions.yml
  bbq/opcode/opcode.go
  bbq/opcode/opcode_string.go
  bbq/opcode/print_test.go
  bbq/vm/vm.go
Labels: Technical Debt

#3872 [Compiler] Support builtin methods for user-defined structs
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/function.go
  bbq/compiler/native_functions.go
  bbq/function.go
  bbq/program_printer.go
  bbq/vm/linker.go
  bbq/vm/native_functions.go
  bbq/vm/test/vm_test.go
  bbq/vm/vm.go
Labels: Feature

#3873 [Compiler] Fix native function dynamic dispatching
  bbq/vm/test/vm_test.go
  bbq/vm/vm.go
Labels: Bugfix

#3874 [Compiler] Enable access to last instruction, test codegens
  bbq/compiler/codegen.go
  bbq/compiler/codegen_test.go
Labels: Feature, Testing

#3875 [Compiler] Optimize transfer instructions
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/constant/kind.go
Labels: Performance

#3871 [Compiler] Improve program printing
  bbq/opcode/gen/instructions.schema.json
  bbq/opcode/gen/main.go
  bbq/opcode/instruction.go
  bbq/opcode/instructions.go
  bbq/opcode/instructions.yml
  bbq/opcode/print.go
  bbq/opcode/print_test.go
Labels: Improvement

#3877 [Compiler] Fix condition compiling
  bbq/compiler/compiler.go
  bbq/compiler/desugar.go
  bbq/compiler/extended_elaboration.go
  bbq/vm/test/vm_test.go
Labels: Bugfix

#3876 [Compiler] Improve compilation of static method invocations
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/opcode/instructions.go
  bbq/opcode/instructions.yml
  bbq/opcode/opcode.go
  bbq/opcode/opcode_string.go
  bbq/opcode/print_test.go
  bbq/vm/linker.go
  bbq/vm/test/runtime_test.go
  bbq/vm/test/vm_test.go
  bbq/vm/value_account.go
  bbq/vm/value_account_capabilities.go
  bbq/vm/value_account_storage.go
  bbq/vm/value_account_storagecapabilities.go
  bbq/vm/value_capability.go
  bbq/vm/vm.go
  interpreter/metatype_test.go
Labels: Bugfix

#3860 [Compiler] Make FT transfer VM test realistic
  bbq/vm/test/contracts/Burner.cdc
  bbq/vm/test/contracts/FlowToken.cdc
  bbq/vm/test/contracts/FungibleToken.cdc
  bbq/vm/test/contracts/FungibleTokenMetadataViews.cdc
  bbq/vm/test/contracts/MetadataViews.cdc
  bbq/vm/test/contracts/NonFungibleToken.cdc
  bbq/vm/test/contracts/ViewResolver.cdc
  bbq/vm/test/ft_contracts_and_txs.go
  bbq/vm/test/ft_test.go
  bbq/vm/test/interpreter_test.go
  bbq/vm/test/scripts/flowToken/get_balance.cdc
  bbq/vm/test/transactions/flowToken/mint_tokens.cdc
  bbq/vm/test/transactions/flowToken/setup_account.cdc
  bbq/vm/test/transactions/flowToken/transfer_tokens.cdc
  bbq/vm/test/utils.go
  bbq/vm/test/vm_test.go
  bbq/vm/vm.go
Labels: Testing

#3882 Refactor interpreter environment
  runtime/checking_environment.go
  runtime/code.go
  runtime/contract.go
  runtime/contract_function_executor.go
  runtime/environment.go
  runtime/handlers.go
  runtime/location.go
  runtime/runtime.go
  runtime/script_executor.go
  runtime/storage.go
  runtime/transaction_executor.go
Labels: Technical Debt

#3883 Refactor interpreter environment – Part 2
  runtime/environment.go
  stdlib/account.go
Labels: Technical Debt

#3885 Decouple runtime code from interpreter
  interpreter/inspect.go
  interpreter/walk.go
  runtime/contract_function_executor.go
  runtime/convertValues.go
  runtime/events.go
  runtime/literal.go
  runtime/runtime.go
  runtime/script_executor.go
  runtime/transaction_executor.go
  runtime/validation.go
Labels: Technical Debt

#3888 Refactor runtime package
  runtime/authorizer.go
  runtime/contract_function_executor.go
  runtime/coverage_test.go
  runtime/environment.go
  runtime/executor.go
  runtime/recover.go
  runtime/runtime.go
  runtime/script_executor.go
  runtime/storage.go
  runtime/transaction_executor.go
  test_utils/runtime_utils/testruntime.go
Labels: Technical Debt

#3847 Remove register reads related to account storage format V1
  runtime/account_storage.go
  runtime/sharedstate_test.go
  runtime/storage.go
  runtime/storage_test.go
Labels: Technical Debt, Performance, Storage Breaking Change

#3886 [Compiler] Support use of member-functions as function-pointers
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/config.go
  bbq/compiler/desugar.go
  bbq/compiler/desugared_elaboration.go
  bbq/test-utils/utils.go
  bbq/vm/callframe.go
  bbq/vm/context.go
  bbq/vm/linker.go
  bbq/vm/test/ft_test.go
  bbq/vm/test/utils.go
  bbq/vm/test/vm_test.go
  bbq/vm/value_account_storagecapabilities.go
  bbq/vm/value_function.go
  bbq/vm/vm.go
  interpreter/interface.go
  interpreter/interpreter.go
  interpreter/member_test.go
  interpreter/simplecompositevalue.go
  interpreter/value.go
  interpreter/value_accountcapabilitycontroller.go
  interpreter/value_address.go
  interpreter/value_array.go
  interpreter/value_capability.go
  interpreter/value_character.go
  interpreter/value_composite.go
  interpreter/value_dictionary.go
  interpreter/value_ephemeral_reference.go
  interpreter/value_fix64.go
  interpreter/value_function.go
  interpreter/value_int.go
  interpreter/value_int128.go
  interpreter/value_int16.go
  interpreter/value_int256.go
  interpreter/value_int32.go
  interpreter/value_int64.go
  interpreter/value_int8.go
  interpreter/value_nil.go
  interpreter/value_number.go
  interpreter/value_path.go
  interpreter/value_pathcapability.go
  interpreter/value_some.go
  interpreter/value_storage_reference.go
  interpreter/value_storagecapabilitycontroller.go
  interpreter/value_string.go
  interpreter/value_type.go
  interpreter/value_ufix64.go
  interpreter/value_uint.go
  interpreter/value_uint128.go
  interpreter/value_uint16.go
  interpreter/value_uint256.go
  interpreter/value_uint32.go
  interpreter/value_uint64.go
  interpreter/value_uint8.go
  interpreter/value_word128.go
  interpreter/value_word16.go
  interpreter/value_word256.go
  interpreter/value_word32.go
  interpreter/value_word64.go
  interpreter/value_word8.go
Labels: Feature

#3890 [Compiler] Separate methods from fields for `SimpleCompositeValue`
  interpreter/composite_value_test.go
  interpreter/interpreter_transaction.go
  interpreter/simplecompositevalue.go
  interpreter/value_account.go
  interpreter/value_account_accountcapabilities.go
  interpreter/value_account_capabilities.go
  interpreter/value_account_contracts.go
  interpreter/value_account_inbox.go
  interpreter/value_account_storage.go
  interpreter/value_account_storagecapabilities.go
  interpreter/value_accountkey.go
  interpreter/value_authaccount_keys.go
  interpreter/value_block.go
  interpreter/value_deployedcontract.go
  interpreter/value_deployment_result.go
  interpreter/value_function.go
  interpreter/value_test.go
  runtime/predeclaredvalues_test.go
  stdlib/bls.go
  stdlib/hashalgorithm.go
  stdlib/rlp.go
  stdlib/signaturealgorithm.go
Labels: Technical Debt

#3879 [Compiler] Optimize transfers
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
Labels: Performance

#3889 Test interface function with conditions
  interpreter/interface_test.go
Labels: Testing

#3893 [Compiler] Sync compiler feature branch with master
  interpreter/interface_test.go
  runtime/account_storage.go
  runtime/authorizer.go
  runtime/contract_function_executor.go
  runtime/coverage_test.go
  runtime/environment.go
  runtime/executor.go
  runtime/recover.go
  runtime/runtime.go
  runtime/script_executor.go
  runtime/sharedstate_test.go
  runtime/storage.go
  runtime/storage_test.go
  runtime/transaction_executor.go
  test_utils/runtime_utils/testruntime.go
Labels: Chore

#3898 [Compiler] Refactor qualified name generation
  bbq/commons/constants.go
  bbq/commons/types.go
  bbq/compiler/compiler.go
  bbq/compiler/native_functions.go
  bbq/vm/context.go
  bbq/vm/native_functions.go
  bbq/vm/value_array.go
Labels: Technical Debt

#3900 Decouple NewEnumCaseValue from interpreter
  interpreter/value_composite.go
  interpreter/value_published.go
  interpreter/value_some.go
Labels: Technical Debt

#3902 Fix version of parser NPM package
  npm-packages/cadence-parser/package.json
Labels: Chore

#3905 Improve generation / tool usage
  Makefile
  ast/access.go
  ast/conditionkind.go
  ast/elementtype.go
  ast/operation.go
  ast/precedence.go
  ast/transferoperation.go
  ast/variablekind.go
  common/compositekind.go
  common/computationkind.go
  common/controlstatement.go
  common/declarationkind.go
  common/integerliteralkind.go
  common/memorykind.go
  common/operandside.go
  common/operationkind.go
  common/pathdomain.go
  encoding/ccf/simpletype.go
  interpreter/primitivestatictype.go
  old_parser/invalidnumberliteralkind.go
  parser/invalidnumberliteralkind.go
  sema/accesscheckmode.go
  sema/binaryoperationkind.go
  sema/containerkind.go
  sema/crypto_algorithm_types.go
  sema/resourceinvalidationkind.go
  sema/typeannotationstate.go
Labels: Chore

#3904 [Compiler] Sync compiler branch with master
  go.mod
  go.sum
  interpreter/value_composite.go
  interpreter/value_published.go
  interpreter/value_some.go
  npm-packages/cadence-parser/package.json
  runtime/errors_test.go
  tools/compatibility-check/go.mod
  tools/compatibility-check/go.sum
  version.go
Labels: Technical Debt

#3897 [Compiler] Derive the function type from the receiver for bound-function values
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/opcode/instructions.go
  bbq/opcode/instructions.yml
  bbq/opcode/print_test.go
  bbq/vm/native_functions.go
  bbq/vm/test/utils.go
  bbq/vm/test/vm_test.go
  bbq/vm/value_account_capabilities.go
  bbq/vm/value_account_storage.go
  bbq/vm/value_account_storagecapabilities.go
  bbq/vm/value_array.go
  bbq/vm/value_capability.go
  bbq/vm/value_dictionary.go
  bbq/vm/value_function.go
  bbq/vm/value_string.go
  bbq/vm/value_type.go
  bbq/vm/vm.go
  interpreter/array_test.go
  interpreter/interpreter.go
  interpreter/interpreter_expression.go
  interpreter/interpreter_invocation.go
  interpreter/interpreter_statement.go
  interpreter/value_array.go
  interpreter/value_composite.go
  interpreter/value_dictionary.go
  interpreter/value_function.go
  interpreter/value_some.go
  runtime/convertValues.go
  sema/type.go
  stdlib/account.go
  stdlib/test_contract.go
Labels: Technical Debt

#3907 [Compiler] Add dictionary built-in functions
  bbq/vm/context.go
  bbq/vm/value_capability.go
  bbq/vm/value_dictionary.go
  bbq/vm/vm.go
  interpreter/dictionary_test.go
  interpreter/value_dictionary.go
  sema/type.go
Labels: Improvement

#3908 [Compiler] Fix function invocation
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/vm/test/vm_test.go
  bbq/vm/vm.go
  bbq/vm/vm_test.go
  interpreter/condition_test.go
  interpreter/container_mutation_test.go
  interpreter/misc_test.go
  test_utils/test_utils.go
Labels: Bugfix, Improvement

#3909 [Compiler] Various improvements/fixes
  bbq/compiler/desugar.go
  bbq/vm/test/ft_test.go
  bbq/vm/test/interpreter_test.go
  runtime/runtime_test.go
  runtime/vm_environment.go
Labels: Improvement

#3911 [Compiler] Implement saturating arithmetic functions in VM
  bbq/vm/native_functions.go
  bbq/vm/test/vm_test.go
Labels: Feature

#3912 [Compiler] Configure account handler in VM environment
  runtime/runtime_test.go
  runtime/vm_environment.go
Labels: Improvement

#3910 [Compiler] Fix contract value use inside of contract
  bbq/vm/executable_program.go
  bbq/vm/linker.go
  bbq/vm/native_functions.go
  bbq/vm/test/runtime_test.go
  bbq/vm/test/utils.go
  bbq/vm/test/vm_test.go
  bbq/vm/vm.go
  interpreter/account_test.go
  interpreter/variable.go
  runtime/runtime_test.go
Labels: Improvement

#3913 [Compiler] Add support for resource fields in VM environment
  runtime/runtime_test.go
  runtime/vm_environment.go
Labels: Improvement
