Repository onflow/cadence, pull requests merged in 2025-10, with the labels that each got.

#4247 [Compiler] Improve error position/location info
  bbq/vm/vm.go
  interpreter/errors.go
  interpreter/interpreter.go
  runtime/capabilitycontrollers_test.go
  runtime/deployment_test.go
  stdlib/account.go
  stdlib/assert.go
  stdlib/builtin_test.go
  stdlib/rlp.go
  stdlib/test_contract.go
  stdlib/test_test.go
Labels: Improvement

#4232 [Compiler] Create unified interface for native/host functions
  bbq/vm/builtin_globals.go
  bbq/vm/unified_adapter.go
  bbq/vm/value_array.go
  bbq/vm/value_number.go
  interpreter/unified_function.go
  interpreter/value_array.go
  interpreter/value_number.go
Labels: Technical Debt

#4255 Remove per-context coverage report, use runtime config's
  runtime/context.go
  runtime/contract_function_executor.go
  runtime/coverage_test.go
  runtime/environment.go
  runtime/runtime.go
  runtime/script_executor.go
  runtime/transaction_executor.go
  runtime/vm_environment.go
Labels: Improvement

#4257 [Compiler] Fix and improve compiler/VM benchmarks and tests, fix CI
  .github/workflows/benchmark.yml
  bbq/compiler/compiler_test.go
  bbq/vm/test/vm_bench_test.go
  bbq/vm/test/vm_test.go
Labels: Bugfix, Testing

#4258 [Compiler] Fix performance regression
  bbq/vm/context.go
  bbq/vm/vm.go
Labels: Performance

#4261 Speed up benchmarks
  .github/workflows/benchmark.yml
  Makefile
  bbq/vm/test/vm_test.go
  runtime/runtime_test.go
Labels: Chore

#4249 Set error location range in interpreter like in VM
  bbq/vm/vm.go
  interpreter/interpreter.go
  interpreter/interpreter_expression.go
  interpreter/misc_test.go
  runtime/runtime_test.go
  stdlib/builtin_test.go
  stdlib/panic.go
Labels: Technical Debt
