Repository onflow/cadence, pull requests merged in 2025-01, with the labels that each got.

#3725 Update get-contracts tool to use new find.xyz API
  .github/workflows/compatibility-check-template.yml
  .github/workflows/compatibility-check.yml
  .github/workflows/get-contracts.yml
  tools/get-contracts/main.go
Labels: Chore

#3732 [Compiler] Adjust parameters to reduce run-time when race detector is enabled
  bbq/vm/test/vm_test.go
Labels: Testing

#3736 Update to Go 1.23
  .github/workflows/benchmark.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/compatibility-check-template.yml
  .github/workflows/compatibility-check.yml
  .github/workflows/downstream.yml
  .github/workflows/get-contracts.yml
  .github/workflows/release.yml
  go.mod
  interpreter/dynamic_casting_test.go
  old_parser/declaration.go
  old_parser/parser.go
  parser/declaration.go
  parser/parser.go
  sema/type.go
  stdlib/test_contract.go
  stdlib/test_test.go
  tools/compatibility-check/go.mod
  tools/constructorcheck/go.mod
  tools/constructorcheck/go.sum
  tools/get-contracts/go.mod
  tools/golangci-lint/go.mod
  tools/golangci-lint/go.sum
  tools/maprange/go.mod
  tools/maprange/go.sum
  tools/storage-explorer/go.mod
  tools/unkeyed/go.mod
  tools/unkeyed/go.sum
Labels: Chore

#3737 [v1.0] Port internal fixes
  go.mod
  go.sum
  runtime/interpreter/errors.go
  runtime/interpreter/value.go
  runtime/interpreter/value_some_test.go
  runtime/runtime_test.go
  runtime/tests/interpreter/bitwise_test.go
  runtime/tests/interpreter/interpreter_test.go
  runtime/tests/interpreter/memory_metering_test.go
  runtime/tests/interpreter/resources_test.go
  runtime/tests/interpreter/values_test.go
  tools/storage-explorer/go.mod
  tools/storage-explorer/go.sum
  values.go
  values_test.go
  version.go
Labels: Bugfix

#3740 Port internal fixes
  go.mod
  go.sum
  interpreter/bitwise_test.go
  interpreter/errors.go
  interpreter/memory_metering_test.go
  interpreter/misc_test.go
  interpreter/resources_test.go
  interpreter/value.go
  interpreter/value_array.go
  interpreter/value_composite.go
  interpreter/value_dictionary.go
  interpreter/value_int.go
  interpreter/value_int128.go
  interpreter/value_int16.go
  interpreter/value_int256.go
  interpreter/value_int32.go
  interpreter/value_int64.go
  interpreter/value_int8.go
  interpreter/value_some.go
  interpreter/value_some_test.go
  interpreter/value_uint.go
  interpreter/value_uint128.go
  interpreter/value_uint256.go
  interpreter/value_word128.go
  interpreter/value_word256.go
  interpreter/values_test.go
  runtime/runtime_test.go
  tools/compatibility-check/go.mod
  tools/compatibility-check/go.sum
  tools/storage-explorer/go.mod
  tools/storage-explorer/go.sum
  values.go
  values_test.go
Labels: Bugfix

#3734 [Compiler] Support inherited functions and conditions through delegation
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/config.go
  bbq/compiler/desugar.go
  bbq/compiler/extended_elaboration.go
  bbq/opcode/instructions.go
  bbq/opcode/instructions.yml
  bbq/opcode/opcode.go
  bbq/opcode/opcode_string.go
  bbq/vm/config.go
  bbq/vm/linker.go
  bbq/vm/native_functions.go
  bbq/vm/test/ft_test.go
  bbq/vm/test/runtime_test.go
  bbq/vm/test/utils.go
  bbq/vm/test/vm_bench_test.go
  bbq/vm/test/vm_test.go
  bbq/vm/value_int.go
  bbq/vm/vm.go
  sema/type.go
Labels: Feature

#3745 [Compiler] Improve VM stack operations
  bbq/vm/vm.go
  bbq/vm/vm_test.go
Labels: Improvement

#3746 [Compiler] Fix operand order for SetField and SetIndex instructions, check resource invalidation
  bbq/compiler/compiler.go
  bbq/opcode/instructions.yml
  bbq/vm/vm.go
  bbq/vm/vm_test.go
Labels: Bugfix, Improvement

#3747 [Compiler] Compile dictionary expressions, implement NewDictionary instruction
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/extended_elaboration.go
  bbq/opcode/instructions.go
  bbq/opcode/instructions.yml
  bbq/vm/test/vm_test.go
  bbq/vm/value_dictionary.go
  bbq/vm/vm.go
Labels: Bugfix, Improvement

#3750 Fix backward compatibility job
  .github/workflows/compatibility-check-template.yml
  .github/workflows/get-contracts.yml
Labels: Chore

#3752 Update readme to add reference to Cadence working group
  README.md
Labels: Documentation
