Repository onflow/cadence, pull requests merged in 2025-07, with the labels that each got.

#4056 [Compiler] Fix compilation of dynamic method invocation via optional chaining
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/vm/test/vm_test.go
Labels: Bugfix

#4060 [Compiler] Implement contract deployment and update in VM environment
  bbq/vm/test/vm_test.go
  runtime/account_test.go
  runtime/capabilities_test.go
  runtime/capabilitycontrollers_test.go
  runtime/contract_test.go
  runtime/contract_update_test.go
  runtime/contract_update_validation_test.go
  runtime/convertValues_test.go
  runtime/deployedcontract_test.go
  runtime/deployment_test.go
  runtime/entitlements_test.go
  runtime/ft_test.go
  runtime/import_test.go
  runtime/program_params_validation_test.go
  runtime/resource_duplicate_test.go
  runtime/resourcedictionary_test.go
  runtime/runtime_test.go
  runtime/sharedstate_test.go
  runtime/storage_test.go
  runtime/vm_environment.go
  stdlib/account.go
  stdlib/builtin.go
Labels: Feature

#4061 [Compiler] Implement contract removal and recoverable contract update for VM environment
  runtime/contract_test.go
  runtime/contract_update_validation_test.go
  runtime/runtime_test.go
  stdlib/account.go
  stdlib/builtin.go
Labels: Feature

#4066 [Compiler] Improve VM config
  bbq/vm/context.go
  bbq/vm/test/vm_bench_test.go
  bbq/vm/test/vm_test.go
  bbq/vm/vm.go
  bbq/vm/vm_test.go
  interpreter/account_test.go
  runtime/vm_environment.go
  test_utils/test_utils.go
Labels: Improvement

#4067 [Compiler] Add call stack depth limit to VM
  bbq/vm/config.go
  bbq/vm/test/vm_test.go
  bbq/vm/vm.go
  interpreter/errors.go
  runtime/errors.go
  runtime/runtime_test.go
  runtime/stackdepth.go
  runtime/vm_environment.go
Labels: Feature

#4070 [Compiler] Various improvements
  bbq/compiler/compiler.go
  interpreter/container_mutation_test.go
  interpreter/if_test.go
  interpreter/switch_test.go
  runtime/convertValues_test.go
  runtime/import_test.go
  runtime/predeclaredvalues_test.go
  runtime/storage_test.go
  semgrep-compiler-vm.yaml
Labels: Improvement, Testing

#4074 [Compiler] Fix nested loops
  bbq/compiler/compiler_test.go
  bbq/vm/test/vm_test.go
  bbq/vm/value_iterator.go
  runtime/crypto_test.go
Labels: Bugfix

#4073 [Compiler] Support meta-type `isRecovered` field in VM
  bbq/vm/config.go
  bbq/vm/context.go
  bbq/vm/test/utils.go
  interpreter/function_test.go
  interpreter/member_test.go
  interpreter/metatype_test.go
  runtime/ft_test.go
  runtime/vm_environment.go
  test_utils/test_utils.go
Labels: Improvement

#4075 [Compiler] Use the correct environment for runtime tests
  bbq/vm/test/interpreter_test.go
  runtime/contract_function_executor.go
  runtime/ft_test.go
  runtime/import_test.go
  runtime/predeclaredvalues_test.go
  runtime/runtime_test.go
  runtime/script_executor.go
  runtime/sharedstate_test.go
  runtime/transaction_executor.go
Labels: Bugfix

#4072 [Compiler] Register common built-in type bound functions for values injected into VM environment
  bbq/compiler/builtin_globals.go
  bbq/compiler/compiler.go
  bbq/vm/builtin_globals.go
  bbq/vm/value_account_contracts.go
  bbq/vm/value_account_storage.go
  bbq/vm/value_accountcapabilitycontroller.go
  bbq/vm/value_address.go
  bbq/vm/value_array.go
  bbq/vm/value_capability.go
  bbq/vm/value_character.go
  bbq/vm/value_deployedcontract.go
  bbq/vm/value_dictionary.go
  bbq/vm/value_number.go
  bbq/vm/value_optional.go
  bbq/vm/value_path.go
  bbq/vm/value_storagecapabilitycontroller.go
  bbq/vm/value_string.go
  bbq/vm/value_type.go
  runtime/crypto_test.go
  runtime/rlp_test.go
  runtime/vm_environment.go
Labels: Improvement

#4077 [Compiler] Produce ConditionError for pre/post condition failures in VM
  bbq/commons/constants.go
  bbq/compiler/builtin_globals.go
  bbq/compiler/compiler_test.go
  bbq/compiler/desugar.go
  bbq/vm/builtin_globals.go
  bbq/vm/test/ft_test.go
  bbq/vm/test/utils.go
  bbq/vm/test/vm_test.go
  interpreter/condition_test.go
  interpreter/entitlements_test.go
  runtime/runtime_test.go
Labels: Improvement

#4076 [Compiler] Enable more tests to be run with with compiler/VM
  interpreter/function_test.go
  interpreter/metatype_test.go
  interpreter/misc_test.go
  runtime/predeclaredvalues_test.go
  runtime/sharedstate_test.go
  semgrep-compiler-vm.yaml
  test_utils/test_utils.go
Labels: Testing

#4078 Remove interpreter shared state feature
  runtime/empty.go
  runtime/environment.go
  runtime/external.go
  runtime/interface.go
  runtime/sharedstate_test.go
  test_utils/runtime_utils/testinterface.go
Labels: Bugfix, Go API Breaking Change

#4079 [Compiler] Support iterating storage with broken types in VM
  bbq/vm/config.go
  bbq/vm/test/utils.go
  bbq/vm/test/vm_bench_test.go
  bbq/vm/test/vm_test.go
  runtime/storage_test.go
  runtime/vm_environment.go
  test_utils/test_utils.go
Labels: Improvement

#4081 [Compiler] Implement InclusiveRange
  bbq/commons/constants.go
  bbq/commons/types.go
  bbq/vm/test/utils.go
  bbq/vm/test/vm_test.go
  bbq/vm/value_inclusiverange.go
  interpreter/account_test.go
  interpreter/dynamic_casting_test.go
  interpreter/for_test.go
  interpreter/inclusive_range_iterator.go
  interpreter/range_value_test.go
  interpreter/value_range.go
  runtime/runtime_test.go
  stdlib/builtin.go
  stdlib/range.go
  test_utils/test_utils.go
Labels: Feature

#4082 [Compiler] Fix inherited default destroy event compilation
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/desugar.go
  bbq/compiler/desugared_elaboration.go
  bbq/vm/test/vm_test.go
  runtime/runtime_test.go
Labels: Bugfix

#4083 [Compiler] Enable more tests for VM or add TODO
  runtime/convertValues_test.go
  runtime/runtime_test.go
Labels: Testing

#4088 [Compiler] Fix second-value assignment for index-expressions
  bbq/vm/vm.go
  interpreter/resources_test.go
  interpreter/transactions_test.go
Labels: Bugfix

#4094 [Compiler] Transaction pre/post conditions are already executed
  bbq/vm/vm.go
Labels: Chore

#4095 [Compiler] Enable computation metering / limiting tests to be run with compiler/VM
  runtime/runtime_test.go
Labels: Testing

#4092 [Compiler] Fix contract deployment / initialization
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/opcode/instructions.go
  bbq/opcode/instructions.yml
  bbq/opcode/opcode.go
  bbq/opcode/opcode_string.go
  bbq/opcode/print_test.go
  bbq/vm/vm.go
  runtime/runtime_test.go
  runtime/vm_environment.go
Labels: Bugfix, Testing

#4089 Interpreter: Evaluate and transfer invocation, array, and dictionary arguments immediately
  interpreter/interpreter_expression.go
  interpreter/interpreter_invocation.go
  interpreter/misc_test.go
  runtime/convertValues_test.go
  runtime/test-export-json-deterministic.json
Labels: Improvement, Performance, Execution result breaking change

#4098 [Compiler] Enable contract update program caching test for VM
  runtime/contract_update_validation_test.go
Labels: Testing

#4099 [Compiler] Test construction of InclusiveRange with VM, resolve TODO
  bbq/vm/test/vm_test.go
  bbq/vm/vm.go
Labels: Testing

#4097 [Compiler] Create an implicit reference for self variable
  bbq/vm/builtin_globals.go
  bbq/vm/context.go
  bbq/vm/test/vm_test.go
  bbq/vm/value.go
  bbq/vm/value_account_storage.go
  bbq/vm/value_accountcapabilitycontroller.go
  bbq/vm/value_address.go
  bbq/vm/value_array.go
  bbq/vm/value_capability.go
  bbq/vm/value_character.go
  bbq/vm/value_deployedcontract.go
  bbq/vm/value_dictionary.go
  bbq/vm/value_function.go
  bbq/vm/value_implicit_reference.go
  bbq/vm/value_inclusiverange.go
  bbq/vm/value_number.go
  bbq/vm/value_optional.go
  bbq/vm/value_path.go
  bbq/vm/value_storagecapabilitycontroller.go
  bbq/vm/value_string.go
  bbq/vm/value_type.go
  bbq/vm/vm.go
  common/memorykind.go
  common/memorykind_string.go
  interpreter/interface.go
  interpreter/interpreter.go
  interpreter/misc_test.go
  interpreter/value_storage_reference.go
  runtime/contract_update_validation_test.go
  runtime/predeclaredvalues_test.go
  runtime/runtime_test.go
  stdlib/account.go
  stdlib/bls.go
  stdlib/hashalgorithm.go
  stdlib/publickey.go
  stdlib/rlp.go
Labels: Bugfix, Improvement

#4103 [Compiler] Refactor function invocation
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/opcode/instructions.go
  bbq/opcode/instructions.yml
  bbq/opcode/opcode.go
  bbq/opcode/opcode_string.go
  bbq/opcode/print_test.go
  bbq/vm/context.go
  bbq/vm/vm.go
Labels: Technical Debt

#4105 [Compiler] Fix external invocations of bound functions
  bbq/vm/value_function.go
  bbq/vm/vm.go
  interpreter/function_test.go
  interpreter/resources_test.go
Labels: Bugfix

#4106 [Compiler] Add corresponding VM tests for missing interpreter test
  bbq/commons/handlers.go
  bbq/test_utils/utils.go
  bbq/vm/test/ft_test.go
  bbq/vm/test/vm_test.go
  interpreter/memory_metering_test.go
  interpreter/misc_test.go
Labels: Testing

#4110 [Compiler] Fix optional binding expression evaluation order
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  interpreter/misc_test.go
Labels: Bugfix

#4112 Remove unused error
  cmd/gen-errors/errors.go
  sema/errors.go
Labels: Technical Debt

#4113 [Compiler] Remove outdated todo's in VM
  bbq/vm/vm.go
Labels: Technical Debt

#4114 [Compiler] Fix compilation of for loops over non-reference array with reference values
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  interpreter/for_test.go
  sema/check_for.go
  sema/elaboration.go
Labels: Bugfix

#4115 Fix Array.map and Array.filter
  interpreter/value_array.go
Labels: Bugfix

#4116 [Compiler] Create `SimpleCompositeValue`s for transactions
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/compiler/desugar.go
  bbq/opcode/instructions.go
  bbq/opcode/instructions.yml
  bbq/opcode/opcode.go
  bbq/opcode/opcode_string.go
  bbq/opcode/print_test.go
  bbq/vm/test/vm_test.go
  bbq/vm/vm.go
  interpreter/simplecompositevalue.go
  interpreter/transactions_test.go
  parser/declaration_test.go
  runtime/runtime_test.go
Labels: Technical Debt

#4117 Improve event emission
  interpreter/interpreter_statement.go
  interpreter/misc_test.go
Labels: Performance, Execution result breaking change

#4118 [Compiler] Fix optional chaining in compiler
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/opcode/instructions.go
  bbq/opcode/instructions.yml
  bbq/opcode/opcode.go
  bbq/opcode/opcode_string.go
  bbq/opcode/print_test.go
  bbq/vm/vm.go
  interpreter/member_test.go
Labels: Technical Debt

#4119 Add a new tool to decode a single slab
  cmd/decode-slab/main.go
Labels: Feature

#4120 [Compiler] Improve naming and meter UUID field and value creation in VM
  bbq/vm/value_composite.go
  bbq/vm/vm.go
Labels: Improvement
