Repository onflow/cadence, pull requests merged in 2025-03, with the labels that each got.

#3803 [Compiler] Compile force expression
  bbq/compiler/compiler.go
  bbq/compiler/compiler_test.go
  bbq/opcode/instructions.go
  bbq/opcode/instructions.yml
  bbq/vm/errors.go
  bbq/vm/test/vm_test.go
  bbq/vm/vm.go
  interpreter/misc_test.go
Labels: Feature

#3807 Fix TestHashable
  interpreter/value_test.go
Labels: Bugfix, Testing

#3809 Fix get-contracts workflow
  .github/workflows/get-contracts.yml
Labels: Chore

#3810 fix syntax specification for import declaration
  docs/syntax/Cadence.syntax
Labels: Bugfix
